/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_entrada;
import controlador.ctrl_material;
import controlador.ctrl_salida;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;
import model.class_entrada;
import model.class_material;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import model.class_salida;
import static view.frm_transferenciamaterialubicacion.spin_cantidadtrans;

/**
 *
 * @author ruben
 */
public class frm_transferenciamaterialproyecto extends javax.swing.JFrame {

    /**
     * Creates new form frm_transferenciamaterialubicacion
     */
    public frm_transferenciamaterialproyecto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - TRANSFERENCIA ENTRE MATERIALES");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_desde = new javax.swing.JPanel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_grupomaterial = new javax.swing.JLabel();
        lbl_codmatalternativo = new javax.swing.JLabel();
        lbl_umb = new javax.swing.JLabel();
        lbl_stockdisponible = new javax.swing.JLabel();
        lbl_clasematerial = new javax.swing.JLabel();
        lbl_materialdesde2 = new javax.swing.JLabel();
        lbl_desdescripcion = new javax.swing.JLabel();
        lbl_desmarca = new javax.swing.JLabel();
        lbl_desmodelo = new javax.swing.JLabel();
        lbl_desclasematerial = new javax.swing.JLabel();
        lbl_desgrupomaterial = new javax.swing.JLabel();
        lbl_desumb = new javax.swing.JLabel();
        lbl_desstockdisponible = new javax.swing.JLabel();
        lbl_descodmaterial = new javax.swing.JLabel();
        txt_nromaterial = new javax.swing.JTextField();
        bot_buscardesde = new javax.swing.JButton();
        lbl_nromaterialdesde1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmb_proyectodestino = new javax.swing.JComboBox<>();
        lbl_proyectodestino = new javax.swing.JLabel();
        bot_actualizarmaterial = new javax.swing.JButton();
        lbl_proyectoactual = new javax.swing.JLabel();
        lbl_almacen4 = new javax.swing.JLabel();
        spin_cantidadtrans = new javax.swing.JSpinner();
        lbl_unidad = new javax.swing.JLabel();
        cmb_proyectoactual = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_desde.setBackground(new java.awt.Color(255, 255, 255));
        panel_desde.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_desde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        panel_desde.add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lbl_marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_marca.setText("MARCA");
        panel_desde.add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lbl_modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_modelo.setText("MODELO");
        panel_desde.add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lbl_grupomaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_grupomaterial.setText("GRUPO DE MATERIAL");
        panel_desde.add(lbl_grupomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        lbl_codmatalternativo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_codmatalternativo.setText("CÓDIGO DE MATERIAL ");
        panel_desde.add(lbl_codmatalternativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lbl_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb.setText("UMB");
        panel_desde.add(lbl_umb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbl_stockdisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_stockdisponible.setText("STOCK DISPONIBLE");
        panel_desde.add(lbl_stockdisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lbl_clasematerial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_clasematerial.setText("CLASE DE MATERIAL");
        panel_desde.add(lbl_clasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lbl_materialdesde2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_materialdesde2.setForeground(new java.awt.Color(0, 138, 218));
        lbl_materialdesde2.setText("DETALLE DE MATERIAL");
        panel_desde.add(lbl_materialdesde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
        panel_desde.add(lbl_desdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 450, 20));
        panel_desde.add(lbl_desmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 190, 20));
        panel_desde.add(lbl_desmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 260, 20));
        panel_desde.add(lbl_desclasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 320, 20));
        panel_desde.add(lbl_desgrupomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 340, 20));
        panel_desde.add(lbl_desumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 260, 20));
        panel_desde.add(lbl_desstockdisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 270, 20));
        panel_desde.add(lbl_descodmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 290, 20));

        getContentPane().add(panel_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 700, 300));

        txt_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        bot_buscardesde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscardesde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscardesde.setText("Buscar");
        bot_buscardesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscardesdeActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscardesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));
        complemento.DisableBorderButton(bot_buscardesde);

        lbl_nromaterialdesde1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nromaterialdesde1.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nromaterialdesde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_proyectodestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_proyectodestino.setEnabled(false);
        cmb_proyectodestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proyectodestinoActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_proyectodestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 390, -1));

        lbl_proyectodestino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyectodestino.setText("PROYECTO DESTINO");
        jPanel1.add(lbl_proyectodestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        bot_actualizarmaterial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bot_actualizarmaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        bot_actualizarmaterial.setText("ACTUALIZAR");
        bot_actualizarmaterial.setEnabled(false);
        bot_actualizarmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarmaterialActionPerformed(evt);
            }
        });
        jPanel1.add(bot_actualizarmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        lbl_proyectoactual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyectoactual.setText("PROYECTO ACTUAL");
        jPanel1.add(lbl_proyectoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_almacen4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_almacen4.setText("CANTIDAD");
        jPanel1.add(lbl_almacen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        spin_cantidadtrans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidadtrans.setEnabled(false);
        jPanel1.add(spin_cantidadtrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 70, -1));

        lbl_unidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 70, 20));

        cmb_proyectoactual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_proyectoactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proyectoactualActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_proyectoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1120, 90));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("TRANSFERENCIA ENTRE PROYECTOS");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(270, 20, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 240, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 100, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(770, 10, 330, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(772, 30, 330, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_buscardesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscardesdeActionPerformed
        frm_buscarmaterial frm = new frm_buscarmaterial(8);
        frm.setVisible(true);

       
    }//GEN-LAST:event_bot_buscardesdeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        /*ctrl_comun control = new ctrl_comun(1);
        cmb_almacendestino =  control.cargar_combo(cmb_almacendestino,"Seleccione...");*/
        
        txt_nromaterial.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void bot_actualizarmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarmaterialActionPerformed
        frm_progress frm = new frm_progress(3,Integer.parseInt(spin_cantidadtrans.getValue().toString())*2);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_actualizarmaterialActionPerformed

    private void cmb_proyectodestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proyectodestinoActionPerformed

    }//GEN-LAST:event_cmb_proyectodestinoActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_transferenciamaterialproyecto frm = new frm_transferenciamaterialproyecto();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void txt_nromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialKeyReleased
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            ctrl_material material = null;
            class_material modelo_material = null;
        
            material = new ctrl_material(
                    0,
                    Integer.parseInt(txt_nromaterial.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    lbl_descodmaterial.setText(modelo_material.getCodigo_mat_alter());
                    lbl_desdescripcion.setText(modelo_material.getDescripcion());
                    lbl_desmarca.setText(modelo_material.getMarca());
                    lbl_desmodelo.setText(modelo_material.getModelo());
                    lbl_desclasematerial.setText(modelo_material.getDescripcionclasearticulo());
                    lbl_desgrupomaterial.setText(modelo_material.getDescripciongrupoarticulo());
                    lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    lbl_desstockdisponible.setText(String.valueOf(modelo_material.getStock_disponible()));
                   
                    spin_cantidadtrans.setValue(modelo_material.getStock_disponible());
            
                }
            
                ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(txt_nromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                cmb_proyectoactual =  entrada.cargarmaterial_proyecto(cmb_proyectoactual,"Seleccione...",1);

        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nromaterial.setText("");
                
             }   
        }     
        

    }//GEN-LAST:event_txt_nromaterialKeyReleased

    private void cmb_proyectoactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proyectoactualActionPerformed
        try{

            if (evt.getModifiers() != 0){

                if (!cmb_proyectoactual.getSelectedItem().equals("Seleccione...")){
                    ctrl_entrada entrada  = new ctrl_entrada(
                        0, //id_entrada,
                        0,
                        Integer.parseInt(txt_nromaterial.getText().trim()), //id_material,
                        "", //descripcionmaterial
                        0, //idvaloracion
                        "", //descripcionvaloracion
                        1,  //moneda
                        "", // descripcion_moneda,
                        0, //id_almacen,
                        "", //descripcion_almacen,
                        0,
                        "", //ubicacion
                        0, //id_procedencia
                        "", //descripcion_procedencia
                        0, //id_clasedemovimiento
                        "", //descripcion_clasedemovimiento
                        Integer.parseInt(cmb_proyectoactual.getSelectedItem().toString().substring(0,3).trim()), //id_proyecto
                        "", //descripcion_proyecto
                        0,
                        "", // codigo alterno
                        0, //iddocumento
                        0,//idcompra
                        0, //nrofactura
                        "", //fecha_entrada,
                        0, //cantidad_ingresada,
                        0.0, //precio_unitario,
                        0.0, //monto,
                        0.0, //flete
                        0.0, //monto
                        "", //observacion
                        true //status
                    );

                    cmb_proyectodestino =  entrada.cargarmaterial_proyecto(cmb_proyectodestino,"Seleccione...",2);
                    cmb_proyectodestino.setEnabled(true);
                    spin_cantidadtrans.setEnabled(true);

                    lbl_desstockdisponible.setText(entrada.consultarmaterial_cantidadproyecto().toString());
                    spin_cantidadtrans.setValue(entrada.consultarmaterial_cantidadproyecto());

                    bot_actualizarmaterial.setEnabled(true);
                }
                else{
                    spin_cantidadtrans.setEnabled(false);
                    bot_actualizarmaterial.setEnabled(false);
                }
            }
        }catch(NullPointerException ex){}
    }//GEN-LAST:event_cmb_proyectoactualActionPerformed

    public static void actualizar_material_proyecto(){
        Boolean resp;
        class_entrada modelo_entrada;
        class_salida modelo_salida;
        String fecha_contabilizacion;
        
        fecha_contabilizacion = funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2);
        
        if (!cmb_proyectodestino.getSelectedItem().equals("Seleccione...") &&
            !cmb_proyectoactual.getSelectedItem().equals("Seleccione...") ){ 
           
           if(Integer.parseInt(spin_cantidadtrans.getValue().toString()) <= Integer.parseInt(lbl_desstockdisponible.getText())){ 
            
            //DATOS DE ENTRADA -SALIENTE
            ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(txt_nromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0, //id_ubicacion
                    "", //ubicacion
                    0, //procedencia
                    "",//descripcion_procedencia
                    0, //clasedemovimiento
                    "",//descripcion_clasedemovimiento
                    Integer.parseInt(cmb_proyectoactual.getSelectedItem().toString().substring(0,3).trim()), //id_proyecto
                    "",//descripcion_proyecto
                    0,
                    "", //codigo_alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
            ); 

            
            modelo_entrada = entrada.consultar_material_proyecto();
            
            ctrl_salida salida  = new ctrl_salida(
                    0, 
                    0, 
                    Integer.parseInt(lbl_descodmaterial.getText().trim()),
                    "", //descripcion material
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText()), 
                    frm_principalM1.lbl_nombres.getText(), 
                    modelo_entrada.getId_almacen(),
                    "",
                    modelo_entrada.getUbicacion(),
                    "",
                    fecha_contabilizacion,
                    modelo_entrada.getId_proyecto(),
                    9,
                    0,    
                    Integer.parseInt(spin_cantidadtrans.getValue().toString()),
                    "", 
                    "", 
                    true
                           
            ); 
            
            //REALIZAR SALIDA DEL MATERIAL(PROYECTO DESDE) A TRANSFERIR CODIGO MOVIMIENTO 301
            txt_nromaterial.setEnabled(false);
            bot_buscardesde.setEnabled(false);
            bot_actualizarmaterial.setEnabled(false);
            
            modelo_salida = salida.crear_salida_express_proyecto();
            
            //DATOS DE ENTRADA -ALMACEN ENTRANTE
            ctrl_entrada entrada_2  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(lbl_descodmaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    modelo_entrada.getId_valoracion(), //idvaloracion
                    modelo_entrada.getDescripcion_valoracion(), //descripcionvaloracion
                    modelo_entrada.getId_moneda(),  //moneda
                    "", // descripcion_moneda,  
                    modelo_entrada.getId_almacen(), //id_almacen,
                    "", //descripcion_almacen,
                    modelo_entrada.getUbicacion(),//id_ubicacion
                    "", //ubicacion
                    modelo_entrada.getProcedencia(),//id_procedencia
                    "", //procedencia
                    9,//id_clasedemovimiento
                    "ENTRADA MATERIAL POR TRANSFERENCIA DE PROYECTOS", //descripcion_clasedemovimiento
                    Integer.parseInt(cmb_proyectodestino.getSelectedItem().toString().substring(0,3).trim()),//id_proyecto
                    cmb_proyectodestino.getSelectedItem().toString().substring(4,cmb_proyectodestino.getSelectedItem().toString().length()).trim(), //descripcion_proyecto
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                    "",//codigo_alterno
                    0, //iddocumento
                    modelo_entrada.getId_ordendecompra(),//idcompra
                    modelo_entrada.getNro_factura(), //nrofactura
                    fecha_contabilizacion, //fecha_entrada,
                    Integer.parseInt(spin_cantidadtrans.getValue().toString()), //cantidad_ingresada,
                    modelo_entrada.getPrecio_unitario(), //precio_unitario,
                    modelo_entrada.getMonto(), //monto,
                    modelo_entrada.getFlete(), //flete
                    modelo_entrada.getMonto(), //monto
                    modelo_entrada.getObservaciones(), //observacion
                    true //status
                           
            ); 
            
            modelo_entrada = entrada_2.crear_entrada_express_proyecto();
            
            if (modelo_entrada.isStatus()){
                
               JOptionPane.showMessageDialog(null, "ACTUALIZADO REGISTRO");
               bot_reiniciar.doClick();
            }
          }
          else{
            JOptionPane.showMessageDialog(null, "LA CANTIDAD A TRANSFERIR ES SUPERIOR A LA CANTIDAD DISPONIBLE EN EL ALMACÉN");
             bot_actualizarmaterial.setEnabled(false);
          } 
        }
        else{
             JOptionPane.showMessageDialog(null, "FALTAN DATOS POR COMPLETAR PARA REALIZAR LA TRANSFERENCIA DEL MATERIAL");
             bot_actualizarmaterial.setEnabled(false);
        }
        
    }
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_transferenciamaterialproyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton bot_actualizarmaterial;
    protected static javax.swing.JButton bot_buscardesde;
    private javax.swing.JButton bot_cerrar;
    protected static javax.swing.JButton bot_reiniciar;
    protected static javax.swing.JComboBox<String> cmb_proyectoactual;
    protected static javax.swing.JComboBox<String> cmb_proyectodestino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_almacen4;
    private javax.swing.JLabel lbl_clasematerial;
    private javax.swing.JLabel lbl_codmatalternativo;
    protected static javax.swing.JLabel lbl_desclasematerial;
    protected static javax.swing.JLabel lbl_descodmaterial;
    private javax.swing.JLabel lbl_descripcionmaterial;
    protected static javax.swing.JLabel lbl_desdescripcion;
    protected static javax.swing.JLabel lbl_desgrupomaterial;
    protected static javax.swing.JLabel lbl_desmarca;
    protected static javax.swing.JLabel lbl_desmodelo;
    protected static javax.swing.JLabel lbl_desstockdisponible;
    protected static javax.swing.JLabel lbl_desumb;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_grupomaterial;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_materialdesde2;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nromaterialdesde1;
    private javax.swing.JLabel lbl_proyectoactual;
    private javax.swing.JLabel lbl_proyectodestino;
    private javax.swing.JLabel lbl_stockdisponible;
    private javax.swing.JLabel lbl_umb;
    protected static javax.swing.JLabel lbl_unidad;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_desde;
    protected static javax.swing.JSpinner spin_cantidadtrans;
    protected static javax.swing.JTextField txt_nromaterial;
    // End of variables declaration//GEN-END:variables
}
