/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ruben
 */
public class frm_detalle_oc extends javax.swing.JFrame {

    /**
     * Creates new form frm_detalle_cotizacion
     */
    Integer opcion;
    
    private String destinoArchivo1;
    private File archivo;
    
    public frm_detalle_oc(Integer opcion) {
        initComponents();
        this.opcion = opcion;
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - DETALLE COTIZACIÓN");
        this.getContentPane().setBackground(new Color(240,240,240));
                
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_alternativa1 = new javax.swing.JPanel();
        txt_descripcionprov1 = new javax.swing.JTextField();
        lbl_proveedor1 = new javax.swing.JLabel();
        lbl_preciounitario1 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        lbl_total1 = new javax.swing.JLabel();
        lbl_cantidad1 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_rif1 = new javax.swing.JTextField();
        lbl_cantidaddias1 = new javax.swing.JLabel();
        chk_recomendacion = new javax.swing.JCheckBox();
        lbl_diasflete1 = new javax.swing.JLabel();
        lbl_undmonto = new javax.swing.JLabel();
        lbl_fechacotizacion1 = new javax.swing.JLabel();
        lbl_adjuntar1 = new javax.swing.JLabel();
        txt_diasplazo = new javax.swing.JTextField();
        lbl_plazoentrega1 = new javax.swing.JLabel();
        lbl_monedaflete = new javax.swing.JLabel();
        lbl_condicionpago1 = new javax.swing.JLabel();
        txt_tipotransporte = new javax.swing.JTextField();
        lbl_diasplazoentrega1 = new javax.swing.JLabel();
        lbl_tipotransporte1 = new javax.swing.JLabel();
        lbl_costoflete1 = new javax.swing.JLabel();
        txt_costoflete = new javax.swing.JTextField();
        bot_verarchivo = new javax.swing.JButton();
        lbl_undcantidad = new javax.swing.JLabel();
        txt_diasflete = new javax.swing.JTextField();
        txt_plazoentrega = new javax.swing.JTextField();
        txt_condicionpago = new javax.swing.JTextField();
        txt_preciounitario = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        lbl_monedatotal = new javax.swing.JLabel();
        lbl_nrosolicitud = new javax.swing.JLabel();
        lbl_idmaterial = new javax.swing.JLabel();
        lbl_desidmaterial = new javax.swing.JLabel();
        lbl_idsolicitud = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_desmaterial = new javax.swing.JLabel();
        lbl_descantidad = new javax.swing.JLabel();
        lbl_cantidadautorizada = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_nroordencompra = new javax.swing.JLabel();
        lbl_documentocompra = new javax.swing.JLabel();
        lbl_fechaordencompra = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_fechaprocura = new javax.swing.JLabel();
        lbl_autorizaciongerencia = new javax.swing.JLabel();
        lbl_aprobacionprocura = new javax.swing.JLabel();
        lbl_fechaautorizacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_alternativa1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_alternativa1.setEnabled(false);
        panel_alternativa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_descripcionprov1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionprov1.setEnabled(false);
        panel_alternativa1.add(txt_descripcionprov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, -1));

        lbl_proveedor1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proveedor1.setText("PROVEEDOR");
        panel_alternativa1.add(lbl_proveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lbl_preciounitario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_preciounitario1.setText("PRECIO UNITARIO");
        panel_alternativa1.add(lbl_preciounitario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txt_fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_fecha.setEnabled(false);
        panel_alternativa1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, -1));

        lbl_total1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total1.setText("TOTAL");
        panel_alternativa1.add(lbl_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lbl_cantidad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad1.setText("CANTIDAD A COTIZAR");
        panel_alternativa1.add(lbl_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_cantidad.setEnabled(false);
        panel_alternativa1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, -1));

        txt_rif1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_rif1.setEnabled(false);
        panel_alternativa1.add(txt_rif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        lbl_cantidaddias1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidaddias1.setText("CANTIDAD DE DÍAS");
        panel_alternativa1.add(lbl_cantidaddias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        chk_recomendacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_recomendacion.setText("RECOMENDACIÓN COMPRADOR");
        chk_recomendacion.setEnabled(false);
        panel_alternativa1.add(chk_recomendacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        lbl_diasflete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasflete1.setText("DÍAS");
        panel_alternativa1.add(lbl_diasflete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 20));

        lbl_undmonto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_undmonto.setText("jLabel13");
        panel_alternativa1.add(lbl_undmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        lbl_fechacotizacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechacotizacion1.setText("FECHA COTIZACIÓN");
        panel_alternativa1.add(lbl_fechacotizacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lbl_adjuntar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_adjuntar1.setText("VER COTIZACIÓN");
        panel_alternativa1.add(lbl_adjuntar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txt_diasplazo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_diasplazo.setEnabled(false);
        panel_alternativa1.add(txt_diasplazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 60, -1));

        lbl_plazoentrega1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_plazoentrega1.setText("PLAZO DE ENTREGA");
        panel_alternativa1.add(lbl_plazoentrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        lbl_monedaflete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_alternativa1.add(lbl_monedaflete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 90, 20));

        lbl_condicionpago1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_condicionpago1.setText("CONDICIÓN DE PAGO");
        panel_alternativa1.add(lbl_condicionpago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txt_tipotransporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tipotransporte.setEnabled(false);
        panel_alternativa1.add(txt_tipotransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 230, -1));

        lbl_diasplazoentrega1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasplazoentrega1.setText("DÍAS");
        panel_alternativa1.add(lbl_diasplazoentrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        lbl_tipotransporte1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_tipotransporte1.setText("TIPO DE TRANSPORTE");
        panel_alternativa1.add(lbl_tipotransporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        lbl_costoflete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_costoflete1.setText("COSTO FLETE");
        panel_alternativa1.add(lbl_costoflete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        txt_costoflete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_costoflete.setEnabled(false);
        panel_alternativa1.add(txt_costoflete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 70, -1));

        bot_verarchivo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bot_verarchivo.setText("Ver Documento");
        bot_verarchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verarchivoActionPerformed(evt);
            }
        });
        panel_alternativa1.add(bot_verarchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        lbl_undcantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_undcantidad.setText("jLabel13");
        panel_alternativa1.add(lbl_undcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        txt_diasflete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_diasflete.setEnabled(false);
        panel_alternativa1.add(txt_diasflete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 70, -1));

        txt_plazoentrega.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_plazoentrega.setEnabled(false);
        panel_alternativa1.add(txt_plazoentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 230, -1));

        txt_condicionpago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_condicionpago.setEnabled(false);
        panel_alternativa1.add(txt_condicionpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, -1));

        txt_preciounitario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_preciounitario.setEnabled(false);
        panel_alternativa1.add(txt_preciounitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 230, -1));

        txt_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_total.setEnabled(false);
        panel_alternativa1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, -1));

        lbl_monedatotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_monedatotal.setText("jLabel13");
        panel_alternativa1.add(lbl_monedatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        getContentPane().add(panel_alternativa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 480, 480));

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("DOCUMENTO SOLICITUD");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_idmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idmaterial.setText("ID MATERIAL");
        getContentPane().add(lbl_idmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_desidmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desidmaterial.setText("jLabel1");
        getContentPane().add(lbl_desidmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        lbl_idsolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idsolicitud.setText("jLabel1");
        getContentPane().add(lbl_idsolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcion.setText("DESCRIPCIÓN MATERIAL");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        lbl_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desmaterial.setText("jLabel1");
        getContentPane().add(lbl_desmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        lbl_descantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descantidad.setText("jLabel1");
        getContentPane().add(lbl_descantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        lbl_cantidadautorizada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadautorizada.setText("CANTIDAD AUTORIZADA");
        getContentPane().add(lbl_cantidadautorizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("DETALLE ORDEN DE COMPRA");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(260, 10, 240, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.setToolTipText("");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(810, 10, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1270, 10, 0, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ESTATUS DE ORDEN DE COMPRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("GENERADO DOCUMENTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("FECHA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("NRO ORDEN DE COMPRA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_nroordencompra.setText("jLabel5");
        jPanel1.add(lbl_nroordencompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        lbl_documentocompra.setText("jLabel5");
        jPanel1.add(lbl_documentocompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        lbl_fechaordencompra.setText("jLabel5");
        jPanel1.add(lbl_fechaordencompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 410, 170));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ESTATUS DE APROBACIÓN");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("APROBACIÓN DE JEFE DE PROCURA");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("FECHA DE APROBACIÓN");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("AUTORIZACIÓN DE  GERENCIA");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("FECHA DE AUTORIZACIÓN");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("ESTATUS DE APROBACIÓN");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel17.setText("jLabel2");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel18.setText("jLabel3");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel19.setText("jLabel4");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel20.setText("jLabel5");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 320, 170));

        lbl_fechaprocura.setText("jLabel5");
        jPanel4.add(lbl_fechaprocura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        lbl_autorizaciongerencia.setText("jLabel5");
        jPanel4.add(lbl_autorizaciongerencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        lbl_aprobacionprocura.setText("jLabel5");
        jPanel4.add(lbl_aprobacionprocura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        lbl_fechaautorizacion.setText("jLabel5");
        jPanel4.add(lbl_fechaautorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 410, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_verarchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verarchivoActionPerformed
     String referencia;
       
       URI url;
       
       referencia = destinoArchivo1;
       
       try{
            File archivo = new File(referencia);
            Desktop.getDesktop().open(archivo);
       }
       catch(IOException | IllegalArgumentException e){
            Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
            if ( desktop != null && desktop.isSupported(Desktop.Action.BROWSE) ) {
                try {
                    url = new URI(referencia);
                    desktop.browse(url);
                } catch ( IOException | URISyntaxException ex ) {
                    JOptionPane.showMessageDialog(null, "ERROR ABRIR COTIZACIÓN. " + ex.getMessage());
                }
            }    
            
       }        

    }//GEN-LAST:event_bot_verarchivoActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Integer posicion;
        
        
        switch (this.opcion){

            case 0:
                posicion = frm_ordendecompra.table_posicioncompra.getSelectedRow();

                lbl_idsolicitud.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,1).toString());
                lbl_desidmaterial.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,3).toString());
                lbl_desmaterial.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,4).toString());
                lbl_descantidad.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,6).toString());
                txt_rif1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,16).toString());
                txt_descripcionprov1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,5).toString());
                txt_preciounitario.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,8).toString());
                lbl_undmonto.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,9).toString());        
                txt_cantidad.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,6).toString());  
                lbl_undcantidad.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,7).toString());        
                txt_total.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,10).toString());
                lbl_monedatotal.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,9).toString());
                txt_fecha.setText(funciones.fecha_bd_usuario(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,19).toString(),1));
                txt_plazoentrega.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,20).toString());
                txt_diasplazo.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,11).toString());
                txt_condicionpago.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,12).toString());

                if(!frm_ordendecompra.table_posicioncompra.getValueAt(posicion,21).toString().equals("Seleccione...")){
                    txt_tipotransporte.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,21).toString());
                    txt_diasflete.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,22).toString());
                    txt_costoflete.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,23).toString());   
                    lbl_monedaflete.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,24).toString());        
                }



                if (frm_ordendecompra.table_posicioncompra.getValueAt(posicion,25).toString().equals("true")){
                    lbl_aprobacionprocura.setText("SI");
                    lbl_fechaprocura.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,26).toString());
                }
                else{
                    lbl_aprobacionprocura.setText("NO");
                    lbl_fechaprocura.setText("-"); 
                }

                if (frm_ordendecompra.table_posicioncompra.getValueAt(posicion,27).toString().equals("true")){
                    lbl_autorizaciongerencia.setText("SI");
                    lbl_fechaautorizacion.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,28).toString());
                }
                else{
                    lbl_autorizaciongerencia.setText("NO");
                    lbl_fechaautorizacion.setText("-"); 
                }

                if (frm_ordendecompra.table_posicioncompra.getValueAt(posicion,30).toString().equals("true")){
                    lbl_nroordencompra.setText("SI");
                    lbl_fechaordencompra.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,32).toString());
                    lbl_documentocompra.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,31).toString());
                }
                else{
                    lbl_nroordencompra.setText("NO");
                    lbl_fechaordencompra.setText("-"); 
                    lbl_documentocompra.setText("-");
                }

                 if (frm_ordendecompra.table_posicioncompra.getValueAt(posicion,29).toString().equals("true")){
                    chk_recomendacion.setSelected(true);
                 }
                 else{
                   chk_recomendacion.setSelected(false);
                 }
        
                 if(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,13).toString().trim().equals("")){
                    destinoArchivo1 = "";
                }
                else{
                    destinoArchivo1 = frm_ordendecompra.table_posicioncompra.getValueAt(posicion,13).toString().trim();
                }
                 
                 /*txt_preciounitario.setText(txt_preciounitario.getText().trim().replace(".", ","));
                 txt_preciounitario.setText(funciones.separadormilesflotante(txt_preciounitario.getText().trim(),true));
 
                 txt_total.setText(txt_total.getText().trim().replace(".", ","));
                 txt_total.setText(funciones.separadormilesflotante(txt_total.getText().trim(),true));
 
                 txt_costoflete.setText(txt_costoflete.getText().trim().replace(".", ","));
                 txt_costoflete.setText(funciones.separadormilesflotante(txt_costoflete.getText().trim(),true));*/
                 
                 
                  break;  


            
            case 1:
                posicion = frm_consultarordendecompra.table_posicioncompra.getSelectedRow();

                lbl_idsolicitud.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,1).toString());
                lbl_desidmaterial.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,3).toString());
                lbl_desmaterial.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,4).toString());
                lbl_descantidad.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,6).toString());
                txt_rif1.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,16).toString());
                txt_descripcionprov1.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,5).toString());
                txt_preciounitario.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,8).toString());
                lbl_undmonto.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,9).toString());        
                txt_cantidad.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,6).toString());  
                lbl_undcantidad.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,7).toString());        
                txt_total.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,10).toString());
                lbl_monedatotal.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,9).toString());
                txt_fecha.setText(funciones.fecha_bd_usuario(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,19).toString(),1));
                txt_plazoentrega.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,20).toString());
                txt_diasplazo.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,11).toString());
                txt_condicionpago.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,12).toString());

                if(!frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,21).toString().equals("Seleccione...")){
                    txt_tipotransporte.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,21).toString());
                    txt_diasflete.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,22).toString());
                    txt_costoflete.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,23).toString());   
                    lbl_monedaflete.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,24).toString());        
                }



                if (frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,25).toString().equals("true")){
                    lbl_aprobacionprocura.setText("SI");
                    lbl_fechaprocura.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,26).toString());
                }
                else{
                    lbl_aprobacionprocura.setText("NO");
                    lbl_fechaprocura.setText("-"); 
                }

                if (frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,27).toString().equals("true")){
                    lbl_autorizaciongerencia.setText("SI");
                    lbl_fechaautorizacion.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,28).toString());
                }
                else{
                    lbl_autorizaciongerencia.setText("NO");
                    lbl_fechaautorizacion.setText("-"); 
                }

                if (frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,30).toString().equals("true")){
                    lbl_nroordencompra.setText("SI");
                    lbl_fechaordencompra.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,32).toString());
                    lbl_documentocompra.setText(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,31).toString());
                }
                else{
                    lbl_nroordencompra.setText("NO");
                    lbl_fechaordencompra.setText("-"); 
                    lbl_documentocompra.setText("-");
                }

                 if (frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,29).toString().equals("true")){
                    chk_recomendacion.setSelected(true);
                 }
                 else{
                   chk_recomendacion.setSelected(false);
                 
                 }
      
                if(frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,13).toString().trim().equals("")){
                    destinoArchivo1 = "";
                }
                else{
                    destinoArchivo1 = frm_consultarordendecompra.table_posicioncompra.getValueAt(posicion,13).toString().trim();
                }
                 
                  break;  
        }
        
              
        
              
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_detalle_oc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_detalle_oc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_detalle_oc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_detalle_oc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_detalle_oc(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_verarchivo;
    private javax.swing.JCheckBox chk_recomendacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_adjuntar1;
    private javax.swing.JLabel lbl_aprobacionprocura;
    private javax.swing.JLabel lbl_autorizaciongerencia;
    private javax.swing.JLabel lbl_cantidad1;
    private javax.swing.JLabel lbl_cantidadautorizada;
    private javax.swing.JLabel lbl_cantidaddias1;
    private javax.swing.JLabel lbl_condicionpago1;
    private javax.swing.JLabel lbl_costoflete1;
    private javax.swing.JLabel lbl_descantidad;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_desidmaterial;
    private javax.swing.JLabel lbl_desmaterial;
    private javax.swing.JLabel lbl_diasflete1;
    private javax.swing.JLabel lbl_diasplazoentrega1;
    private javax.swing.JLabel lbl_documentocompra;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_fechaautorizacion;
    private javax.swing.JLabel lbl_fechacotizacion1;
    private javax.swing.JLabel lbl_fechaordencompra;
    private javax.swing.JLabel lbl_fechaprocura;
    private javax.swing.JLabel lbl_idmaterial;
    private javax.swing.JLabel lbl_idsolicitud;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_monedaflete;
    private javax.swing.JLabel lbl_monedatotal;
    private javax.swing.JLabel lbl_nroordencompra;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_plazoentrega1;
    private javax.swing.JLabel lbl_preciounitario1;
    private javax.swing.JLabel lbl_proveedor1;
    private javax.swing.JLabel lbl_tipotransporte1;
    private javax.swing.JLabel lbl_total1;
    private javax.swing.JLabel lbl_undcantidad;
    private javax.swing.JLabel lbl_undmonto;
    private javax.swing.JPanel panel_alternativa1;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_condicionpago;
    private javax.swing.JTextField txt_costoflete;
    protected static javax.swing.JTextField txt_descripcionprov1;
    private javax.swing.JTextField txt_diasflete;
    private javax.swing.JTextField txt_diasplazo;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_plazoentrega;
    private javax.swing.JTextField txt_preciounitario;
    protected static javax.swing.JTextField txt_rif1;
    private javax.swing.JTextField txt_tipotransporte;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
