/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_entrada;
import controlador.ctrl_material;
import controlador.ctrl_ubicacion;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;
import model.class_material;
import javax.swing.UIManager;
import javax.swing.ImageIcon;

/**
 *
 * @author ruben
 */
public class frm_transferenciamaterial extends javax.swing.JFrame {

    /**
     * Creates new form frm_transferenciamaterial
     */
    public frm_transferenciamaterial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - TRANSFERENCIA ENTRE MATERIALES");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){}
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_descantidadentrante = new javax.swing.JLabel();
        lbl_descantidadsaliente = new javax.swing.JLabel();
        lbl_descantidadentrantehasta = new javax.swing.JLabel();
        lbl_descantidadsalientehasta = new javax.swing.JLabel();
        txt_idubicacion = new javax.swing.JTextField();
        panel_desde = new javax.swing.JPanel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_grupomaterial = new javax.swing.JLabel();
        lbl_codmatalternativo = new javax.swing.JLabel();
        lbl_umb = new javax.swing.JLabel();
        lbl_stockdisponible = new javax.swing.JLabel();
        lbl_clasematerial = new javax.swing.JLabel();
        lbl_materialdesde2 = new javax.swing.JLabel();
        lbl_desdescripcion = new javax.swing.JLabel();
        lbl_desmarca = new javax.swing.JLabel();
        lbl_desmodelo = new javax.swing.JLabel();
        lbl_desclasematerial = new javax.swing.JLabel();
        lbl_desgrupomaterial = new javax.swing.JLabel();
        lbl_desumb = new javax.swing.JLabel();
        lbl_descodmatalternativo = new javax.swing.JLabel();
        lbl_desstockdisponible = new javax.swing.JLabel();
        panel_pre = new javax.swing.JPanel();
        lbl_materialpre = new javax.swing.JLabel();
        lbl_modelopre = new javax.swing.JLabel();
        lbl_marcapre = new javax.swing.JLabel();
        lbl_codmatalternativopre = new javax.swing.JLabel();
        lbl_descripcionmaterialpre = new javax.swing.JLabel();
        lbl_clasematerialpre = new javax.swing.JLabel();
        lbl_stockdisponiblepre = new javax.swing.JLabel();
        lbl_umbpre = new javax.swing.JLabel();
        lbl_grupomaterialpre = new javax.swing.JLabel();
        lbl_desmodelopre = new javax.swing.JLabel();
        lbl_desumbpre = new javax.swing.JLabel();
        lbl_desclasematerialpre = new javax.swing.JLabel();
        lbl_desmarcapre = new javax.swing.JLabel();
        lbl_desgrupomaterialpre = new javax.swing.JLabel();
        lbl_desdescripcionpre = new javax.swing.JLabel();
        lbl_descodmatalternativopre = new javax.swing.JLabel();
        lbl_desstockdisponiblepre = new javax.swing.JLabel();
        txt_nromaterialdesde = new javax.swing.JTextField();
        lbl_nromaterialdesde = new javax.swing.JLabel();
        lbl_nromaterialhasta = new javax.swing.JLabel();
        txt_nromaterialhasta = new javax.swing.JTextField();
        panel_hasta = new javax.swing.JPanel();
        lbl_materialhasta = new javax.swing.JLabel();
        lbl_modelohasta = new javax.swing.JLabel();
        lbl_marcahasta = new javax.swing.JLabel();
        lbl_codmatalternativohasta = new javax.swing.JLabel();
        lbl_descripcionmaterialhasta = new javax.swing.JLabel();
        lbl_clasematerialhasta = new javax.swing.JLabel();
        lbl_stockdisponiblehasta = new javax.swing.JLabel();
        lbl_umbhasta = new javax.swing.JLabel();
        lbl_grupomaterialhasta = new javax.swing.JLabel();
        lbl_desstockdisponiblehasta = new javax.swing.JLabel();
        lbl_desdescripcionhasta = new javax.swing.JLabel();
        lbl_descodmatalternativohasta = new javax.swing.JLabel();
        lbl_desmarcahasta = new javax.swing.JLabel();
        lbl_desmodelohasta = new javax.swing.JLabel();
        lbl_desgrupomaterialhasta = new javax.swing.JLabel();
        lbl_desumbhasta = new javax.swing.JLabel();
        lbl_desclasematerialhasta = new javax.swing.JLabel();
        bot_actualizarmaterial = new javax.swing.JButton();
        bot_buscarhasta = new javax.swing.JButton();
        bot_buscardesde = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_usuario1 = new javax.swing.JLabel();
        lbl_nombres1 = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_cantidadentrantepre = new javax.swing.JLabel();
        lbl_cantidadsalientepre = new javax.swing.JLabel();
        lbl_descantidadentrantepre = new javax.swing.JLabel();
        lbl_descantidadsalientepre = new javax.swing.JLabel();
        lbl_cantidadstocksaliente = new javax.swing.JLabel();
        spin_cantidadsaliente = new javax.swing.JSpinner();
        lbl_almacen = new javax.swing.JLabel();
        lbl_almacen1 = new javax.swing.JLabel();
        cmb_ubicacionactual = new javax.swing.JComboBox<>();
        cmb_almacenactual = new javax.swing.JComboBox<>();
        lbl_almacen2 = new javax.swing.JLabel();
        cmb_almacendestino = new javax.swing.JComboBox<>();
        lbl_almacen3 = new javax.swing.JLabel();
        cmb_ubicacionhasta = new javax.swing.JComboBox<>();

        lbl_descantidadentrante.setText("jLabel1");

        lbl_descantidadsaliente.setText("jLabel1");

        lbl_descantidadentrantehasta.setText("jLabel1");

        lbl_descantidadsalientehasta.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_desde.setBackground(new java.awt.Color(255, 255, 255));
        panel_desde.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_desde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCION DE MATERIAL");
        panel_desde.add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lbl_marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_marca.setText("MARCA");
        panel_desde.add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lbl_modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_modelo.setText("MODELO");
        panel_desde.add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lbl_grupomaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_grupomaterial.setText("GRUPO DE MATERIAL");
        panel_desde.add(lbl_grupomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        lbl_codmatalternativo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_codmatalternativo.setText("CODIGO DE MATERIAL");
        panel_desde.add(lbl_codmatalternativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb.setText("UMB");
        panel_desde.add(lbl_umb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        lbl_stockdisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_stockdisponible.setText("STOCK DISPONIBLE");
        panel_desde.add(lbl_stockdisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        lbl_clasematerial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_clasematerial.setText("CLASE DE MATERIAL");
        panel_desde.add(lbl_clasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lbl_materialdesde2.setBackground(new java.awt.Color(0, 138, 218));
        lbl_materialdesde2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_materialdesde2.setForeground(new java.awt.Color(0, 138, 218));
        lbl_materialdesde2.setText("DESDE");
        panel_desde.add(lbl_materialdesde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
        panel_desde.add(lbl_desdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, 10));
        panel_desde.add(lbl_desmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 330, 10));
        panel_desde.add(lbl_desmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 330, 10));
        panel_desde.add(lbl_desclasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, 10));
        panel_desde.add(lbl_desgrupomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 330, 10));
        panel_desde.add(lbl_desumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 330, 10));
        panel_desde.add(lbl_descodmatalternativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, 10));
        panel_desde.add(lbl_desstockdisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 320, 10));

        getContentPane().add(panel_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 350, 380));

        panel_pre.setBackground(new java.awt.Color(255, 255, 255));
        panel_pre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_pre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_materialpre.setBackground(new java.awt.Color(0, 138, 218));
        lbl_materialpre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_materialpre.setForeground(new java.awt.Color(0, 138, 218));
        lbl_materialpre.setText("RESULTADO PRELIMINAR");
        panel_pre.add(lbl_materialpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lbl_modelopre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_modelopre.setText("MODELO");
        panel_pre.add(lbl_modelopre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lbl_marcapre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_marcapre.setText("MARCA");
        panel_pre.add(lbl_marcapre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lbl_codmatalternativopre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_codmatalternativopre.setText("CODIGO DE MATERIAL");
        panel_pre.add(lbl_codmatalternativopre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_descripcionmaterialpre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterialpre.setText("DESCRIPCION DE MATERIAL");
        panel_pre.add(lbl_descripcionmaterialpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lbl_clasematerialpre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_clasematerialpre.setText("CLASE DE MATERIAL");
        panel_pre.add(lbl_clasematerialpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lbl_stockdisponiblepre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_stockdisponiblepre.setText("STOCK DISPONIBLE");
        panel_pre.add(lbl_stockdisponiblepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        lbl_umbpre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umbpre.setText("UMB");
        panel_pre.add(lbl_umbpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        lbl_grupomaterialpre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_grupomaterialpre.setText("GRUPO DE MATERIAL");
        panel_pre.add(lbl_grupomaterialpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        panel_pre.add(lbl_desmodelopre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 340, 20));
        panel_pre.add(lbl_desumbpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 340, 20));
        panel_pre.add(lbl_desclasematerialpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 340, 20));
        panel_pre.add(lbl_desmarcapre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 340, 20));
        panel_pre.add(lbl_desgrupomaterialpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 340, 20));
        panel_pre.add(lbl_desdescripcionpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, 20));
        panel_pre.add(lbl_descodmatalternativopre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 20));
        panel_pre.add(lbl_desstockdisponiblepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 20));

        getContentPane().add(panel_pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 360, 380));

        txt_nromaterialdesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nromaterialdesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nromaterialdesdeActionPerformed(evt);
            }
        });
        txt_nromaterialdesde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialdesdeKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterialdesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        lbl_nromaterialdesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nromaterialdesde.setText("NRO DE MATERIAL ");
        getContentPane().add(lbl_nromaterialdesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        lbl_nromaterialhasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nromaterialhasta.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nromaterialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        txt_nromaterialhasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nromaterialhasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialhastaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, 30));

        panel_hasta.setBackground(new java.awt.Color(255, 255, 255));
        panel_hasta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_hasta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_materialhasta.setBackground(new java.awt.Color(0, 138, 218));
        lbl_materialhasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_materialhasta.setForeground(new java.awt.Color(0, 138, 218));
        lbl_materialhasta.setText("HASTA");
        panel_hasta.add(lbl_materialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        lbl_modelohasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_modelohasta.setText("MODELO");
        panel_hasta.add(lbl_modelohasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lbl_marcahasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_marcahasta.setText("MARCA");
        panel_hasta.add(lbl_marcahasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lbl_codmatalternativohasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_codmatalternativohasta.setText("CODIGO DE MATERIAL");
        panel_hasta.add(lbl_codmatalternativohasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_descripcionmaterialhasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterialhasta.setText("DESCRIPCION DE MATERIAL");
        panel_hasta.add(lbl_descripcionmaterialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lbl_clasematerialhasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_clasematerialhasta.setText("CLASE DE MATERIAL");
        panel_hasta.add(lbl_clasematerialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lbl_stockdisponiblehasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_stockdisponiblehasta.setText("STOCK DISPONIBLE");
        panel_hasta.add(lbl_stockdisponiblehasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        lbl_umbhasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umbhasta.setText("UMB");
        panel_hasta.add(lbl_umbhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        lbl_grupomaterialhasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_grupomaterialhasta.setText("GRUPO DE MATERIAL");
        panel_hasta.add(lbl_grupomaterialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        panel_hasta.add(lbl_desstockdisponiblehasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 330, 10));
        panel_hasta.add(lbl_desdescripcionhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 340, 20));
        panel_hasta.add(lbl_descodmatalternativohasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 10));
        panel_hasta.add(lbl_desmarcahasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 340, 10));
        panel_hasta.add(lbl_desmodelohasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 340, 10));
        panel_hasta.add(lbl_desgrupomaterialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 340, 20));
        panel_hasta.add(lbl_desumbhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 340, 20));
        panel_hasta.add(lbl_desclasematerialhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, 20));

        getContentPane().add(panel_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 360, 380));

        bot_actualizarmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_actualizarmaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        bot_actualizarmaterial.setText("ACTUALIZAR MATERIAL");
        bot_actualizarmaterial.setEnabled(false);
        bot_actualizarmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarmaterialActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizarmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, -1, -1));
        complemento.DisableBorderButton(bot_actualizarmaterial);

        bot_buscarhasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_buscarhasta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscarhasta.setText("Buscar");
        bot_buscarhasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarhastaActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscarhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));
        complemento.DisableBorderButton(bot_buscarhasta);

        bot_buscardesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_buscardesde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscardesde.setText("Buscar");
        bot_buscardesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscardesdeActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscardesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));
        complemento.DisableBorderButton(bot_buscardesde);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("TRANSFERENCIA ENTRE MATERIALES");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1113, 20, 130, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel4);
        jPanel4.setBounds(1100, 10, 1, 40);

        lbl_usuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario1.setText("USUARIO");
        jPanel7.add(lbl_usuario1);
        lbl_usuario1.setBounds(760, 10, 330, 17);

        lbl_nombres1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres1.setText("NOMBRES");
        lbl_nombres1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres1);
        lbl_nombres1.setBounds(760, 30, 330, 17);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        lbl_usuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_usuario.setText("USUARIO");
        getContentPane().add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbl_nombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbl_cantidadentrantepre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadentrantepre.setText("CANTIDAD ENTRANTE");
        getContentPane().add(lbl_cantidadentrantepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 670, -1, -1));

        lbl_cantidadsalientepre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadsalientepre.setText("CANTIDAD SALIENTE");
        getContentPane().add(lbl_cantidadsalientepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 710, -1, -1));

        lbl_descantidadentrantepre.setText("jLabel1");
        getContentPane().add(lbl_descantidadentrantepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, -1, -1));

        lbl_descantidadsalientepre.setText("jLabel1");
        getContentPane().add(lbl_descantidadsalientepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 730, -1, -1));

        lbl_cantidadstocksaliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadstocksaliente.setText("STOCK SALIENTE");
        getContentPane().add(lbl_cantidadstocksaliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        spin_cantidadsaliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidadsaliente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_cantidadsalienteStateChanged(evt);
            }
        });
        getContentPane().add(spin_cantidadsaliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 50, -1));

        lbl_almacen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_almacen.setText("ALMACÉN ACTUAL");
        getContentPane().add(lbl_almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lbl_almacen1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_almacen1.setText("UBICACIÓN ACTUAL");
        getContentPane().add(lbl_almacen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cmb_ubicacionactual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_ubicacionactual.setEnabled(false);
        cmb_ubicacionactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ubicacionactualActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_ubicacionactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, -1));

        cmb_almacenactual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_almacenactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_almacenactualActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_almacenactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, -1));

        lbl_almacen2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_almacen2.setText("ALMACÉN DESTINO");
        getContentPane().add(lbl_almacen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        cmb_almacendestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_almacendestino.setEnabled(false);
        cmb_almacendestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_almacendestinoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_almacendestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 210, -1));

        lbl_almacen3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_almacen3.setText("UBICACIÓN DESTINO");
        getContentPane().add(lbl_almacen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        cmb_ubicacionhasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_ubicacionhasta.setEnabled(false);
        cmb_ubicacionhasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ubicacionhastaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_ubicacionhasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_buscarhastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarhastaActionPerformed
        frm_buscarmaterial frm = new frm_buscarmaterial(14);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_buscarhastaActionPerformed

    private void bot_buscardesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscardesdeActionPerformed
        frm_buscarmaterial frm = new frm_buscarmaterial(13);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_buscardesdeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txt_nromaterialdesde.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void bot_actualizarmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarmaterialActionPerformed
        class_material modelo_material;
        ctrl_comun control;
        String image_string = null;

        
        if(Integer.parseInt(lbl_desstockdisponible.getText())>= Integer.parseInt(spin_cantidadsaliente.getValue().toString())){
        
            if(!spin_cantidadsaliente.getValue().equals(0)){
        
                ctrl_material material = new ctrl_material(
                        0,
                        Integer.parseInt(txt_nromaterialdesde.getText().trim().toUpperCase()),
                        "",
                        "",
                        "",
                        "",
                        "",
                         0,
                        "",
                        0,
                        Integer.parseInt(lbl_desstockdisponiblepre.getText()),//STOCKDISPONIBLE
                        0,
                        0,
                        0,
                        0,
                        0.0,
                        0.0,
                        "",
                        0,
                        "",
                        Integer.parseInt(lbl_descantidadentrantepre.getText()),//CANTIDAD ENTRANTE
                        Integer.parseInt(lbl_descantidadsalientepre.getText()),//CANTIDAD SALIENTE
                        "",
                        "",
                        0,
                        "",
                        0,
                        "",
                        0,
                        "",
                        "",
                        0,
                        "",
                        0,
                        "",
                        0,
                        "",
                        true

                    );

                    modelo_material = material.actualizar_nromaterial(Integer.parseInt(txt_nromaterialdesde.getText().trim().toUpperCase()),Integer.parseInt(txt_nromaterialhasta.getText().trim().toUpperCase()),Integer.parseInt(cmb_almacendestino.getSelectedItem().toString().substring(0,3)),Integer.parseInt(cmb_ubicacionhasta.getSelectedItem().toString().substring(0,3).trim()),Integer.parseInt(spin_cantidadsaliente.getValue().toString()));

                    if (modelo_material.isStatus()){

                        JOptionPane.showMessageDialog(null, "ACTUALIZADO REGISTRO");

                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "SELECCIONE UN VALOR MAYOR A CERO EN EL STOCK SALIENTE");
            }
        
        }
        else{
            JOptionPane.showMessageDialog(null, "EL STOCK SALIENTE ES MAYOR AL STOCK DISPONIBLE");

        }
    }//GEN-LAST:event_bot_actualizarmaterialActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_transferenciamaterial frm = new frm_transferenciamaterial();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void txt_nromaterialdesdeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialdesdeKeyReleased
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            ctrl_material material = null;
            class_material modelo_material = null;
        
                            
                material = new ctrl_material(
                    0,
                    Integer.parseInt(txt_nromaterialdesde.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    lbl_descodmatalternativo.setText(modelo_material.getCodigo_mat_alter());
                    lbl_desdescripcion.setText(modelo_material.getDescripcion());
                    lbl_desmarca.setText(modelo_material.getMarca());
                    lbl_desmodelo.setText(modelo_material.getModelo());
                    lbl_desclasematerial.setText(modelo_material.getDescripcionclasearticulo());
                    lbl_desgrupomaterial.setText(modelo_material.getDescripciongrupoarticulo());
                    lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    lbl_desstockdisponible.setText(String.valueOf(modelo_material.getStock_disponible()));
                    lbl_descantidadentrante.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    lbl_descantidadsaliente.setText(String.valueOf(modelo_material.getCantidad_saliente()));
                    lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    spin_cantidadsaliente.setValue(modelo_material.getStock_disponible());
            
                }
            
                ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(txt_nromaterialdesde.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                cmb_almacenactual =  entrada.cargarmaterial_almacen(cmb_almacenactual,"Seleccione...",1);

        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nromaterialdesde.setText("");
             }   
        }           
    }//GEN-LAST:event_txt_nromaterialdesdeKeyReleased

    private void txt_nromaterialhastaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialhastaKeyReleased
        class_material modelo_material;
        
        
        
        if(!txt_nromaterialhasta.getText().equals("")  ) {

            ctrl_material material = new ctrl_material(
                0,
                Integer.parseInt(txt_nromaterialhasta.getText().trim().toUpperCase()),
                "",
                "",
                "",
                "",
                "",
                 0,
                "",
                0,
                0,
                0,
                0,
                0,
                0,
                0.0,
                0.0,
                "",
                0,
                "",
                0,
                0,
                "",
                "",
                0,
                "",
                0,
                "",
                0,
                "",
                "",
                0,
                "",
                0,
                "",
                0,
                "",
                true

            );

            modelo_material = material.consultar_material();

            

                
            if (modelo_material.isStatus()){
                
                lbl_descodmatalternativohasta.setText(modelo_material.getCodigo_mat_alter());
                lbl_desdescripcionhasta.setText(modelo_material.getDescripcion());
                lbl_desmarcahasta.setText(modelo_material.getMarca());
                lbl_desmodelohasta.setText(modelo_material.getModelo());
                lbl_desclasematerialhasta.setText(modelo_material.getDescripcionclasearticulo());
                lbl_desgrupomaterialhasta.setText(modelo_material.getDescripciongrupoarticulo());
                lbl_desumbhasta.setText(modelo_material.getDescripcion_medida());
                lbl_desstockdisponiblehasta.setText(String.valueOf(modelo_material.getStock_disponible()));
                lbl_descantidadentrantehasta.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                lbl_descantidadsalientehasta.setText(String.valueOf(modelo_material.getCantidad_saliente()));

                ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(txt_nromaterialhasta.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                cmb_almacendestino =  entrada.cargarmaterial_almacen(cmb_almacendestino,"Seleccione...",1);
         
                cmb_almacendestino.setEnabled(true);
                            
            }

        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS");
        }
    }//GEN-LAST:event_txt_nromaterialhastaKeyReleased

    private void spin_cantidadsalienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_cantidadsalienteStateChanged
        if(!lbl_desstockdisponiblehasta.getText().trim().equals("")){
                           
                ctrl_material material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialhasta.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

            class_material modelo_material = material.consultar_material();

            
            //stockdesde
            Integer stockdisponibledesde =0;
            try{
                 
                    stockdisponibledesde = Integer.parseInt(frm_transferenciamaterial.spin_cantidadsaliente.getValue().toString());
                 
            }
            catch(NullPointerException ex){
                 stockdisponibledesde = 0;
            }
            
            
                Integer stockdisponiblehasta = 0;
                Integer stockdisponiblepre = 0;
                //stockhasta
                try{
                    stockdisponiblehasta = modelo_material.getStock_disponible();
                    stockdisponiblepre = stockdisponibledesde + stockdisponiblehasta;

                }
                catch(NullPointerException ex){
                    stockdisponiblepre = 0;
                }

                Integer stockcantidadentrantedesde = 0;
                //cantidad entrante
                try{

                    stockcantidadentrantedesde = Integer.parseInt(frm_transferenciamaterial.lbl_descantidadentrante.getText());

                }
                catch(NullPointerException ex){
                    stockcantidadentrantedesde = 0;
                }


                Integer stockcantidadentrantepre = 0;
                Integer stockcantidadentrantehasta = modelo_material.getCantidad_entrante();
                stockcantidadentrantepre = stockcantidadentrantedesde + stockcantidadentrantehasta;


                //cantidad saliente
                Integer stockcantidadsalientedesde = 0;
                try{

                    stockcantidadsalientedesde = Integer.parseInt(frm_transferenciamaterial.lbl_descantidadsaliente.getText());

                }
                catch(NullPointerException ex){
                    stockcantidadsalientedesde = 0;
                }

                Integer stockcantidadsalientepre = 0;
                Integer stockcantidadsalientehasta = modelo_material.getCantidad_saliente();
                stockcantidadsalientepre = stockcantidadsalientedesde + stockcantidadsalientehasta;

                if (modelo_material.isStatus()){

                    frm_transferenciamaterial.lbl_descodmatalternativohasta.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcionhasta.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarcahasta.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelohasta.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerialhasta.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterialhasta.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumbhasta.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterial.lbl_desstockdisponiblehasta.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterial.lbl_descantidadentrantehasta.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterial.lbl_descantidadsalientehasta.setText(String.valueOf(modelo_material.getCantidad_saliente()));

                    frm_transferenciamaterial.lbl_descodmatalternativopre.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcionpre.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarcapre.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelopre.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerialpre.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterialpre.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumbpre.setText(modelo_material.getDescripcion_medida());

                    if (stockdisponiblepre > 0) {
                        frm_transferenciamaterial.lbl_desstockdisponiblepre.setText(String.valueOf(stockdisponiblepre));
                        frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }   

                    if(stockcantidadentrantepre  > 0){
                       frm_transferenciamaterial.lbl_descantidadentrantepre.setText(String.valueOf(stockcantidadentrantepre));
                       frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }

                    if(stockcantidadentrantepre  > 0){
                       frm_transferenciamaterial.lbl_descantidadsalientepre.setText(String.valueOf(stockcantidadsalientepre));
                       frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }

                }

            
        }
    }//GEN-LAST:event_spin_cantidadsalienteStateChanged

    private void txt_nromaterialdesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nromaterialdesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nromaterialdesdeActionPerformed

    private void cmb_almacenactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_almacenactualActionPerformed
        try{

            if (evt.getModifiers() != 0){

                if (!cmb_almacenactual.getSelectedItem().equals("Seleccione...")){
                    ctrl_entrada entrada  = new ctrl_entrada(
                        0, //id_entrada,
                        0,
                        Integer.parseInt(txt_nromaterialdesde.getText().trim()), //id_material,
                        "", //descripcionmaterial
                        0, //idvaloracion
                        "", //descripcionvaloracion
                        1,  //moneda
                        "", // descripcion_moneda,
                        Integer.parseInt(cmb_almacenactual.getSelectedItem().toString().substring(0,3).trim()), //id_almacen,
                        "", //descripcion_almacen,
                        0,
                        "", //ubicacion
                        0, //id_procedencia
                        "", //descripcion_procedencia
                        0, //id_clasedemovimiento
                        "", //descripcion_clasedemovimiento
                        0, //id_proyecto
                        "", //descripcion_proyecto
                        0,
                        "", // codigo alterno
                        0, //iddocumento
                        0,//idcompra
                        0, //nrofactura
                        "", //fecha_entrada,
                        0, //cantidad_ingresada,
                        0.0, //precio_unitario,
                        0.0, //monto,
                        0.0, //flete
                        0.0, //monto
                        "", //observacion
                        true //status
                    );

                    cmb_ubicacionactual =  entrada.cargarmaterial_almacen(cmb_ubicacionactual,"Seleccione...",2);
                    cmb_ubicacionactual.setEnabled(true);

                   
                }
                else{
                    cmb_ubicacionactual.setEnabled(false);
                }
            }
        }catch(NullPointerException ex){}
    }//GEN-LAST:event_cmb_almacenactualActionPerformed

    private void cmb_ubicacionactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ubicacionactualActionPerformed
        try{
            if(evt.getModifiers() != 0 ){
                if(!cmb_ubicacionactual.getSelectedItem().equals("Seleccione...")){
                    

                    ctrl_entrada entrada  = new ctrl_entrada(
                        0, //id_entrada,
                        0,
                        Integer.parseInt(txt_nromaterialdesde.getText().trim()), //id_material,
                        "", //descripcionmaterial
                        0, //idvaloracion
                        "", //descripcionvaloracion
                        1,  //moneda
                        "", // descripcion_moneda,
                        Integer.parseInt(cmb_almacenactual.getSelectedItem().toString().substring(0,3).trim()), //id_almacen,
                        "", //descripcion_almacen,
                        Integer.parseInt(cmb_ubicacionactual.getSelectedItem().toString().substring(0,3).trim()),
                        "", //ubicacion
                        0, //id_procedencia
                        "", //descripcion_procedencia
                        0, //id_clasedemovimiento
                        "", //descripcion_clasedemovimiento
                        0, //id_proyecto
                        "", //descripcion_proyecto
                        0,
                        "", // codigo alterno
                        0, //iddocumento
                        0,//idcompra
                        0, //nrofactura
                        "", //fecha_entrada,
                        0, //cantidad_ingresada,
                        0.0, //precio_unitario,
                        0.0, //monto,
                        0.0, //flete
                        0.0, //monto
                        "", //observacion
                        true //status
                    );

                    lbl_desstockdisponible.setText(entrada.consultarmaterial_cantidadubicacion().toString());

                    spin_cantidadsaliente.setValue(Integer.parseInt(lbl_desstockdisponible.getText()));
                }
                else{
                   

                }
            }
        }catch(NullPointerException ex){ }

    }//GEN-LAST:event_cmb_ubicacionactualActionPerformed

    private void cmb_almacendestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_almacendestinoActionPerformed
        try{

            if (evt.getModifiers() != 0){

                if (!cmb_almacendestino.getSelectedItem().equals("Seleccione...")){
                    ctrl_entrada entrada  = new ctrl_entrada(
                        0, //id_entrada,
                        0,
                        Integer.parseInt(txt_nromaterialhasta.getText().trim()), //id_material,
                        "", //descripcionmaterial
                        0, //idvaloracion
                        "", //descripcionvaloracion
                        1,  //moneda
                        "", // descripcion_moneda,
                        Integer.parseInt(cmb_almacendestino.getSelectedItem().toString().substring(0,3).trim()), //id_almacen,
                        "", //descripcion_almacen,
                        0,
                        "", //ubicacion
                        0, //id_procedencia
                        "", //descripcion_procedencia
                        0, //id_clasedemovimiento
                        "", //descripcion_clasedemovimiento
                        0, //id_proyecto
                        "", //descripcion_proyecto
                        0,
                        "", // codigo alterno
                        0, //iddocumento
                        0,//idcompra
                        0, //nrofactura
                        "", //fecha_entrada,
                        0, //cantidad_ingresada,
                        0.0, //precio_unitario,
                        0.0, //monto,
                        0.0, //flete
                        0.0, //monto
                        "", //observacion
                        true //status
                    );

                    cmb_ubicacionhasta =  entrada.cargarmaterial_almacen(cmb_ubicacionhasta,"Seleccione...",2);
                    cmb_ubicacionhasta.setEnabled(true);

                   
                }
                else{
                    cmb_ubicacionhasta.setEnabled(false);
                }
            }    
        }
        catch(NullPointerException ex){}
    }//GEN-LAST:event_cmb_almacendestinoActionPerformed

    private void cmb_ubicacionhastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ubicacionhastaActionPerformed
         cmb_ubicacionhasta.setEnabled(true);  
        if(!cmb_ubicacionhasta.getSelectedItem().equals("Seleccione...")){
                    

                    ctrl_entrada entrada  = new ctrl_entrada(
                        0, //id_entrada,
                        0,
                        Integer.parseInt(txt_nromaterialhasta.getText().trim()), //id_material,
                        "", //descripcionmaterial
                        0, //idvaloracion
                        "", //descripcionvaloracion
                        1,  //moneda
                        "", // descripcion_moneda,
                        Integer.parseInt(cmb_almacendestino.getSelectedItem().toString().substring(0,3).trim()), //id_almacen,
                        "", //descripcion_almacen,
                        Integer.parseInt(cmb_ubicacionhasta.getSelectedItem().toString().substring(0,3).trim()),
                        "", //ubicacion
                        0, //id_procedencia
                        "", //descripcion_procedencia
                        0, //id_clasedemovimiento
                        "", //descripcion_clasedemovimiento
                        0, //id_proyecto
                        "", //descripcion_proyecto
                        0,
                        "", // codigo alterno
                        0, //iddocumento
                        0,//idcompra
                        0, //nrofactura
                        "", //fecha_entrada,
                        0, //cantidad_ingresada,
                        0.0, //precio_unitario,
                        0.0, //monto,
                        0.0, //flete
                        0.0, //monto
                        "", //observacion
                        true //status
                    );

                    lbl_desstockdisponiblehasta.setText(entrada.consultarmaterial_cantidadubicacion().toString());   
                   
          }
        
        ctrl_material material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialhasta.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

            class_material modelo_material = material.consultar_material();

            
            //stockdesde
            Integer stockdisponibledesde =0;
            try{
                 
                    stockdisponibledesde = Integer.parseInt(frm_transferenciamaterial.spin_cantidadsaliente.getValue().toString());
                 
            }
            catch(NullPointerException ex){
                 stockdisponibledesde = 0;
            }
            
            
                Integer stockdisponiblehasta = 0;
                Integer stockdisponiblepre = 0;
                //stockhasta
                try{
                    stockdisponiblehasta = Integer.parseInt(lbl_desstockdisponiblehasta.getText());
                    stockdisponiblepre = stockdisponibledesde + stockdisponiblehasta;

                }
                catch(NullPointerException ex){
                    stockdisponiblepre = 0;
                }

                Integer stockcantidadentrantedesde = 0;
                //cantidad entrante
                try{

                    stockcantidadentrantedesde = Integer.parseInt(frm_transferenciamaterial.lbl_descantidadentrante.getText());

                }
                catch(NullPointerException ex){
                    stockcantidadentrantedesde = 0;
                }


                Integer stockcantidadentrantepre = 0;
                Integer stockcantidadentrantehasta = modelo_material.getCantidad_entrante();
                stockcantidadentrantepre = stockcantidadentrantedesde + stockcantidadentrantehasta;


                //cantidad saliente
                Integer stockcantidadsalientedesde = 0;
                try{

                    stockcantidadsalientedesde = Integer.parseInt(frm_transferenciamaterial.lbl_descantidadsaliente.getText());

                }
                catch(NullPointerException ex){
                    stockcantidadsalientedesde = 0;
                }

                Integer stockcantidadsalientepre = 0;
                Integer stockcantidadsalientehasta = modelo_material.getCantidad_saliente();
                stockcantidadsalientepre = stockcantidadsalientedesde + stockcantidadsalientehasta;

                if (modelo_material.isStatus()){

                    frm_transferenciamaterial.lbl_descodmatalternativohasta.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcionhasta.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarcahasta.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelohasta.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerialhasta.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterialhasta.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumbhasta.setText(modelo_material.getDescripcion_medida());
                    //frm_transferenciamaterial.lbl_desstockdisponiblehasta.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterial.lbl_descantidadentrantehasta.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterial.lbl_descantidadsalientehasta.setText(String.valueOf(modelo_material.getCantidad_saliente()));

                    frm_transferenciamaterial.lbl_descodmatalternativopre.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcionpre.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarcapre.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelopre.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerialpre.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterialpre.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumbpre.setText(modelo_material.getDescripcion_medida());

                    if (stockdisponiblepre > 0) {
                        frm_transferenciamaterial.lbl_desstockdisponiblepre.setText(String.valueOf(stockdisponiblepre));
                        frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }   

                    if(stockcantidadentrantepre  > 0){
                       frm_transferenciamaterial.lbl_descantidadentrantepre.setText(String.valueOf(stockcantidadentrantepre));
                       frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }

                    if(stockcantidadentrantepre  > 0){
                       frm_transferenciamaterial.lbl_descantidadsalientepre.setText(String.valueOf(stockcantidadsalientepre));
                       frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }

                }
    }//GEN-LAST:event_cmb_ubicacionhastaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_transferenciamaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton bot_actualizarmaterial;
    private javax.swing.JButton bot_buscardesde;
    private javax.swing.JButton bot_buscarhasta;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    protected static javax.swing.JComboBox<String> cmb_almacenactual;
    protected static javax.swing.JComboBox<String> cmb_almacendestino;
    protected static javax.swing.JComboBox<String> cmb_ubicacionactual;
    protected static javax.swing.JComboBox<String> cmb_ubicacionhasta;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_almacen;
    private javax.swing.JLabel lbl_almacen1;
    private javax.swing.JLabel lbl_almacen2;
    private javax.swing.JLabel lbl_almacen3;
    private javax.swing.JLabel lbl_cantidadentrantepre;
    private javax.swing.JLabel lbl_cantidadsalientepre;
    private javax.swing.JLabel lbl_cantidadstocksaliente;
    private javax.swing.JLabel lbl_clasematerial;
    private javax.swing.JLabel lbl_clasematerialhasta;
    private javax.swing.JLabel lbl_clasematerialpre;
    private javax.swing.JLabel lbl_codmatalternativo;
    private javax.swing.JLabel lbl_codmatalternativohasta;
    private javax.swing.JLabel lbl_codmatalternativopre;
    protected static javax.swing.JLabel lbl_descantidadentrante;
    protected static javax.swing.JLabel lbl_descantidadentrantehasta;
    protected static javax.swing.JLabel lbl_descantidadentrantepre;
    protected static javax.swing.JLabel lbl_descantidadsaliente;
    protected static javax.swing.JLabel lbl_descantidadsalientehasta;
    protected static javax.swing.JLabel lbl_descantidadsalientepre;
    protected static javax.swing.JLabel lbl_desclasematerial;
    protected static javax.swing.JLabel lbl_desclasematerialhasta;
    protected static javax.swing.JLabel lbl_desclasematerialpre;
    protected static javax.swing.JLabel lbl_descodmatalternativo;
    protected static javax.swing.JLabel lbl_descodmatalternativohasta;
    protected static javax.swing.JLabel lbl_descodmatalternativopre;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_descripcionmaterialhasta;
    private javax.swing.JLabel lbl_descripcionmaterialpre;
    protected static javax.swing.JLabel lbl_desdescripcion;
    protected static javax.swing.JLabel lbl_desdescripcionhasta;
    protected static javax.swing.JLabel lbl_desdescripcionpre;
    protected static javax.swing.JLabel lbl_desgrupomaterial;
    protected static javax.swing.JLabel lbl_desgrupomaterialhasta;
    protected static javax.swing.JLabel lbl_desgrupomaterialpre;
    protected static javax.swing.JLabel lbl_desmarca;
    protected static javax.swing.JLabel lbl_desmarcahasta;
    protected static javax.swing.JLabel lbl_desmarcapre;
    protected static javax.swing.JLabel lbl_desmodelo;
    protected static javax.swing.JLabel lbl_desmodelohasta;
    protected static javax.swing.JLabel lbl_desmodelopre;
    protected static javax.swing.JLabel lbl_desstockdisponible;
    protected static javax.swing.JLabel lbl_desstockdisponiblehasta;
    protected static javax.swing.JLabel lbl_desstockdisponiblepre;
    protected static javax.swing.JLabel lbl_desumb;
    protected static javax.swing.JLabel lbl_desumbhasta;
    protected static javax.swing.JLabel lbl_desumbpre;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_grupomaterial;
    private javax.swing.JLabel lbl_grupomaterialhasta;
    private javax.swing.JLabel lbl_grupomaterialpre;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_marcahasta;
    private javax.swing.JLabel lbl_marcapre;
    private javax.swing.JLabel lbl_materialdesde2;
    private javax.swing.JLabel lbl_materialhasta;
    private javax.swing.JLabel lbl_materialpre;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_modelohasta;
    private javax.swing.JLabel lbl_modelopre;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nombres1;
    private javax.swing.JLabel lbl_nromaterialdesde;
    private javax.swing.JLabel lbl_nromaterialhasta;
    private javax.swing.JLabel lbl_stockdisponible;
    private javax.swing.JLabel lbl_stockdisponiblehasta;
    private javax.swing.JLabel lbl_stockdisponiblepre;
    private javax.swing.JLabel lbl_umb;
    private javax.swing.JLabel lbl_umbhasta;
    private javax.swing.JLabel lbl_umbpre;
    protected static javax.swing.JLabel lbl_usuario;
    protected static javax.swing.JLabel lbl_usuario1;
    private javax.swing.JPanel panel_desde;
    private javax.swing.JPanel panel_hasta;
    private javax.swing.JPanel panel_pre;
    protected static javax.swing.JSpinner spin_cantidadsaliente;
    protected static javax.swing.JTextField txt_idubicacion;
    protected static javax.swing.JTextField txt_nromaterialdesde;
    protected static javax.swing.JTextField txt_nromaterialhasta;
    // End of variables declaration//GEN-END:variables
}
