/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_prestamo;
import controlador.ctrl_solicitud;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static view.frm_prestamo.txt_numeromaterial;
import static view.frm_solicitud.lbl_usuario;

/**
 *
 * @author ruben
 */
public class frm_consultarprestamo extends javax.swing.JFrame {

    /**
     * Creates new form frm_consultarsolicitud
     */
    public frm_consultarprestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - CONSULTAR PRÉSTAMOS DE MATERIAL");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());  
        
        DefaultTableModel modelotabla = (DefaultTableModel) table_prestamo.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        table_prestamo.setRowSorter(elQueOrdena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_solicitud = new javax.swing.ButtonGroup();
        lbl_nrosolicitud = new javax.swing.JLabel();
        txt_nromaterial = new javax.swing.JTextField();
        lbl_proyecto = new javax.swing.JLabel();
        cmb_proyecto = new javax.swing.JComboBox<>();
        lbl_area = new javax.swing.JLabel();
        cmb_area = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoaprobarsolicitud = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        date_desde = new com.toedter.calendar.JDateChooser();
        lbl_fechadesde = new javax.swing.JLabel();
        radio_todas = new javax.swing.JRadioButton();
        radio_activa = new javax.swing.JRadioButton();
        radio_devueltas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prestamo = new javax.swing.JTable();
        radio_anulada = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txt_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 90, -1));

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        getContentPane().add(lbl_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        cmb_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proyectoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 270, -1));

        lbl_area.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_area.setText("ÁREA");
        getContentPane().add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, -1, -1));

        cmb_area.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_areaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 240, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoaprobarsolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoaprobarsolicitud.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoaprobarsolicitud.setText("CONSULTAR PRÉSTAMO DE MATERIAL");
        jPanel7.add(lbl_encabezadoaprobarsolicitud);
        lbl_encabezadoaprobarsolicitud.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FECHA HASTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        date_hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_hastaPropertyChange(evt);
            }
        });
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 110, -1));

        date_desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_desdePropertyChange(evt);
            }
        });
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, -1));

        lbl_fechadesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechadesde.setText("FECHA DESDE");
        getContentPane().add(lbl_fechadesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        group_solicitud.add(radio_todas);
        radio_todas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_todas.setText("TODAS");
        radio_todas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_todasActionPerformed(evt);
            }
        });
        getContentPane().add(radio_todas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        group_solicitud.add(radio_activa);
        radio_activa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_activa.setSelected(true);
        radio_activa.setText("ACTIVAS");
        radio_activa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_activaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_activa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        group_solicitud.add(radio_devueltas);
        radio_devueltas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_devueltas.setText("DEVUELTAS");
        radio_devueltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_devueltasActionPerformed(evt);
            }
        });
        getContentPane().add(radio_devueltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, -1, -1));

        table_prestamo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_prestamo", "id_entrada", "NRO DOCUMENTO", "NRO MATERIAL", "DESCRIPCIÓN", "POSICIÓN", "CANTIDAD PRESTADA", "UMB", "PROYECTO", "ÁREA", "NOMBRE SOLICITANTE", "FECHA DESDE", "FECHA HASTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_prestamo);
        if (table_prestamo.getColumnModel().getColumnCount() > 0) {
            table_prestamo.getColumnModel().getColumn(0).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(2).setMinWidth(100);
            table_prestamo.getColumnModel().getColumn(2).setPreferredWidth(100);
            table_prestamo.getColumnModel().getColumn(2).setMaxWidth(100);
            table_prestamo.getColumnModel().getColumn(3).setMinWidth(100);
            table_prestamo.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_prestamo.getColumnModel().getColumn(3).setMaxWidth(100);
            table_prestamo.getColumnModel().getColumn(4).setMinWidth(300);
            table_prestamo.getColumnModel().getColumn(4).setPreferredWidth(300);
            table_prestamo.getColumnModel().getColumn(4).setMaxWidth(300);
            table_prestamo.getColumnModel().getColumn(7).setMinWidth(50);
            table_prestamo.getColumnModel().getColumn(7).setPreferredWidth(50);
            table_prestamo.getColumnModel().getColumn(7).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1390, 480));

        group_solicitud.add(radio_anulada);
        radio_anulada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_anulada.setText("ANULADAS");
        radio_anulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_anuladaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_anulada, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_consultarprestamo frm = new frm_consultarprestamo();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_comun control = new ctrl_comun(7);
        cmb_proyecto =  control.cargar_combo(cmb_proyecto,"Seleccione...");
        control = new ctrl_comun(16);
        cmb_area =  control.cargar_combo(cmb_area,"Seleccione...");
        
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    0, //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

        prestamo.consultar_prestamos(table_prestamo,"","",1);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_nromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialKeyReleased
        Integer opcion = 1;
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    Integer.parseInt(txt_nromaterial.getText().trim()), //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );
        
            if(radio_todas.isSelected()){
                opcion = 0;
            }

            if(radio_activa.isSelected()){
                opcion = 1;
            }

            if(radio_devueltas.isSelected()){
                opcion = 2;
            } 
            
            if(radio_devueltas.isSelected()){
                opcion = 3;
            } 
            
            prestamo.consultar_prestamos(table_prestamo,"","",opcion);

        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nromaterial.setText("");
                
             }   
        }     
    }//GEN-LAST:event_txt_nromaterialKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
           Integer opcion = 1;
           
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    0, //id_material, 
                    txt_descripcionmaterial.getText().trim(), // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );
        
            if(radio_todas.isSelected()){
                opcion = 0;
            }

            if(radio_activa.isSelected()){
                opcion = 1;
            }

            if(radio_devueltas.isSelected()){
                opcion = 2;
            } 
            
            if(radio_devueltas.isSelected()){
                opcion = 3;
            } 
            
            prestamo.consultar_prestamos(table_prestamo,"","",opcion);

         
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void cmb_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proyectoActionPerformed
        
        Integer opcion = 1;
        
        if(evt.getModifiers() != 0){
            
            if(!cmb_proyecto.getSelectedItem().equals("Seleccione...")){

                ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            0, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            0, // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0, 3).trim()), // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                    );

                    if(radio_todas.isSelected()){
                        opcion = 0;
                    }

                    if(radio_activa.isSelected()){
                        opcion = 1;
                    }

                    if(radio_devueltas.isSelected()){
                        opcion = 2;
                    } 

                    if(radio_devueltas.isSelected()){
                        opcion = 3;
                    } 

                    prestamo.consultar_prestamos(table_prestamo,"","",opcion);  
            }    
        }
            
    }//GEN-LAST:event_cmb_proyectoActionPerformed

    private void date_hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_hastaPropertyChange
        String fechadesde;
        String fechahasta;
        Integer opcion = 1;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
                ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            0, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            0, // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            0, // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                    );

                    if(radio_todas.isSelected()){
                        opcion = 0;
                    }

                    if(radio_activa.isSelected()){
                        opcion = 1;
                    }

                    if(radio_devueltas.isSelected()){
                        opcion = 2;
                    } 

                    if(radio_devueltas.isSelected()){
                        opcion = 3;
                    } 

                    prestamo.consultar_prestamos(table_prestamo,fechadesde,fechahasta,opcion);  
   
            }
        
    }//GEN-LAST:event_date_hastaPropertyChange

    private void date_desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_desdePropertyChange
        String fechadesde;
        String fechahasta;
        Integer opcion = 1;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
               ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            0, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            0, // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            0, // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                    );

                    if(radio_todas.isSelected()){
                        opcion = 0;
                    }

                    if(radio_activa.isSelected()){
                        opcion = 1;
                    }

                    if(radio_devueltas.isSelected()){
                        opcion = 2;
                    } 

                    if(radio_devueltas.isSelected()){
                        opcion = 3;
                    } 

                    prestamo.consultar_prestamos(table_prestamo,fechadesde,fechahasta,opcion); 
                    
            }
    }//GEN-LAST:event_date_desdePropertyChange

    private void radio_todasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_todasActionPerformed
    String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer area;
    Integer nromaterial;
    
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
    if(!cmb_proyecto.getSelectedItem().equals("Seleccione...")){
        proyecto = Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        proyecto = 0;
    }
    
    if(!cmb_area.getSelectedItem().equals("Seleccione...")){
        area = Integer.parseInt(cmb_area.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        area = 0;
    }

    if (!txt_nromaterial.getText().trim().equals("")){
        nromaterial = Integer.parseInt(txt_nromaterial.getText().trim());
    }
    else{
        nromaterial = 0;
    }    
    
               ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            nromaterial, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            area, // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            proyecto, // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                    );
               
               prestamo.consultar_prestamos(table_prestamo,fechadesde,fechahasta,0); 
                    
    }//GEN-LAST:event_radio_todasActionPerformed

    private void radio_activaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_activaActionPerformed
     String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer area;
    Integer nromaterial;
    
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
    if(!cmb_proyecto.getSelectedItem().equals("Seleccione...")){
        proyecto = Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        proyecto = 0;
    }
    
    if(!cmb_area.getSelectedItem().equals("Seleccione...")){
        area = Integer.parseInt(cmb_area.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        area = 0;
    }

    if (!txt_nromaterial.getText().trim().equals("")){
        nromaterial = Integer.parseInt(txt_nromaterial.getText().trim());
    }
    else{
        nromaterial = 0;
    }    
    
               ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            nromaterial, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            area, // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            proyecto, // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                    );
               
               prestamo.consultar_prestamos(table_prestamo,fechadesde,fechahasta,1); 
    }//GEN-LAST:event_radio_activaActionPerformed

    private void radio_devueltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_devueltasActionPerformed
    String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer area;
    Integer nromaterial;
    
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
    if(!cmb_proyecto.getSelectedItem().equals("Seleccione...")){
        proyecto = Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        proyecto = 0;
    }
    
    if(!cmb_area.getSelectedItem().equals("Seleccione...")){
        area = Integer.parseInt(cmb_area.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        area = 0;
    }

    if (!txt_nromaterial.getText().trim().equals("")){
        nromaterial = Integer.parseInt(txt_nromaterial.getText().trim());
    }
    else{
        nromaterial = 0;
    }    
    
               ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            nromaterial, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            area, // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            proyecto, // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                    );
               
               prestamo.consultar_prestamos(table_prestamo,fechadesde,fechahasta,3); 
    }//GEN-LAST:event_radio_devueltasActionPerformed

    private void cmb_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_areaActionPerformed
        Integer opcion = 1;

        if(evt.getModifiers() != 0){

            if(!cmb_area.getSelectedItem().equals("Seleccione...")){

                ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            0, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            Integer.parseInt(cmb_area.getSelectedItem().toString().substring(0, 3).trim()), // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            0, // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                );

                if(radio_todas.isSelected()){
                    opcion = 0;
                }

                if(radio_activa.isSelected()){
                    opcion = 1;
                }

                if(radio_devueltas.isSelected()){
                    opcion = 2;
                }
                prestamo.consultar_prestamos(table_prestamo,"","",opcion); 
            }
        }
    }//GEN-LAST:event_cmb_areaActionPerformed

    private void radio_anuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_anuladaActionPerformed
    String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer area;
    Integer nromaterial;
    
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
    if(!cmb_proyecto.getSelectedItem().equals("Seleccione...")){
        proyecto = Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        proyecto = 0;
    }
    
    if(!cmb_area.getSelectedItem().equals("Seleccione...")){
        area = Integer.parseInt(cmb_area.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        area = 0;
    }

    if (!txt_nromaterial.getText().trim().equals("")){
        nromaterial = Integer.parseInt(txt_nromaterial.getText().trim());
    }
    else{
        nromaterial = 0;
    }    
    
               ctrl_prestamo prestamo = new ctrl_prestamo(
                            0, //id_prestamo 
                            nromaterial, //id_material, 
                            "", // descripcionmaterial, 
                            0, // id_empresa, 
                            "", // descripcion_empresa, 
                            area, // id_area, 
                            "", //descripcion_area
                            "", // nombre_usuario, 
                            0, // id_almacen, 
                            "",// descripcionalmacen, 
                            0, // id_ubicaciom, 
                            "",// descripcionubicacion, 
                            proyecto, // id_proyecto, 
                            "",// descripcionproyecto,
                            0, // posicion,
                            0, // cantidad_prestada,
                            0, //nrodocumento
                            "", //fecha_solicitud, 
                            "", //fecha_desde, 
                            "", //fecha_hasta, 
                            "", // justificacion, 
                            "", //fecha_recepcion, 
                            false, //dano, 
                            "", //foto, 
                            "", //descripciondano)
                            0, //id_entrada
                            true
                    );
               
               prestamo.consultar_prestamos(table_prestamo,fechadesde,fechahasta,2); 
    }//GEN-LAST:event_radio_anuladaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_consultarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_consultarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_consultarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_consultarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_consultarprestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox<String> cmb_area;
    private javax.swing.JComboBox<String> cmb_proyecto;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.ButtonGroup group_solicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_encabezadoaprobarsolicitud;
    private javax.swing.JLabel lbl_fechadesde;
    private javax.swing.JLabel lbl_imagentimaca2;
    protected static javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_proyecto;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JRadioButton radio_activa;
    private javax.swing.JRadioButton radio_anulada;
    private javax.swing.JRadioButton radio_devueltas;
    private javax.swing.JRadioButton radio_todas;
    private javax.swing.JTable table_prestamo;
    private javax.swing.JTextField txt_descripcionmaterial;
    private javax.swing.JTextField txt_nromaterial;
    // End of variables declaration//GEN-END:variables
}
