/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import com.sun.org.apache.xpath.internal.operations.And;
import controlador.ctrl_entrada;
import controlador.ctrl_material;
import controlador.ctrl_prestamo;
import controlador.ctrl_reserva;
import controlador.ctrl_solicitud;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.class_material;

/**
 *
 * @author ruben
 */
public class frm_buscarmaterial extends javax.swing.JFrame {

    /**
     * Creates new form frm_buscarmaterial
     */
    private final Integer  id_frame;
    public frm_buscarmaterial(Integer id_frame) {
        initComponents();
        this.setTitle("SISTIMACA - BUSCAR MATERIAL");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setLocationRelativeTo(null);
        this.id_frame = id_frame;
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_material = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_material = new javax.swing.JTable();
        radio_numeromaterial = new javax.swing.JRadioButton();
        radio_descripcion = new javax.swing.JRadioButton();
        txt_descripcionmaterial = new javax.swing.JTextField();
        txt_numeromaterial = new javax.swing.JTextField();
        bot_seleccionar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_material.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_material.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO MATERIAL", "DESCRIPCIÓN", "UMB", "MARCA", "MODELO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_materialMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_material);
        if (table_material.getColumnModel().getColumnCount() > 0) {
            table_material.getColumnModel().getColumn(0).setMinWidth(120);
            table_material.getColumnModel().getColumn(0).setPreferredWidth(120);
            table_material.getColumnModel().getColumn(0).setMaxWidth(120);
            table_material.getColumnModel().getColumn(2).setMinWidth(50);
            table_material.getColumnModel().getColumn(2).setPreferredWidth(50);
            table_material.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 650, 210));

        group_material.add(radio_numeromaterial);
        radio_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_numeromaterial.setSelected(true);
        radio_numeromaterial.setText("NÚMERO DE MATERIAL");
        radio_numeromaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_numeromaterialActionPerformed(evt);
            }
        });
        getContentPane().add(radio_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        group_material.add(radio_descripcion);
        radio_descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_descripcion.setText("DESCRIPCIÓN");
        radio_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(radio_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 30));

        txt_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numeromaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numeromaterialActionPerformed(evt);
            }
        });
        txt_numeromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 30));

        bot_seleccionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_seleccionar.setText("SELECCIONAR");
        bot_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_seleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));
        complemento.DisableBorderButton(bot_seleccionar);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("BÚSQUEDA DE MATERIALES");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 210, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(611, 20, 100, 29);
        complemento.DisableBorderButton(bot_cerrar);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txt_numeromaterial.requestFocusInWindow();
        txt_descripcionmaterial.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void txt_numeromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeromaterialKeyReleased
      
        ctrl_solicitud solicitud;
       DefaultTableModel modelotabla = (DefaultTableModel) table_material.getModel();
       
        if (radio_numeromaterial.isSelected() && !txt_numeromaterial.getText().trim().equals("")){
            
        
            solicitud = new ctrl_solicitud(
                
                0,
                0,
                0,
                "",
                0,
                "",
                0,
                Integer.parseInt(txt_numeromaterial.getText().trim()), //numero de material
                "",                                  // descripcion de material     
                0,
                "",
                0,
                "",
                0,    
                0,
                0,
                0,
                0,    
                "",
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  
            solicitud.buscar_material(table_material);
        
        }
        else{
                modelotabla.setRowCount(0);
        }
       
        

        
       
        
    }//GEN-LAST:event_txt_numeromaterialKeyReleased

    private void radio_numeromaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_numeromaterialActionPerformed
        DefaultTableModel modelotabla = (DefaultTableModel) table_material.getModel();
        modelotabla.setRowCount(0);
        txt_numeromaterial.setEnabled(true);
        txt_numeromaterial.setText("");
        txt_descripcionmaterial.setText("");
        txt_descripcionmaterial.setEnabled(false);
        txt_numeromaterial.requestFocusInWindow();
    }//GEN-LAST:event_radio_numeromaterialActionPerformed

    private void radio_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_descripcionActionPerformed
        DefaultTableModel modelotabla = (DefaultTableModel) table_material.getModel();
        modelotabla.setRowCount(0);
        txt_descripcionmaterial.setEnabled(true);
        txt_numeromaterial.setText("");
        txt_descripcionmaterial.setText("");
        txt_numeromaterial.setEnabled(false);
        txt_descripcionmaterial.requestFocusInWindow();
    }//GEN-LAST:event_radio_descripcionActionPerformed

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
     
        ctrl_solicitud solicitud;
       DefaultTableModel modelotabla = (DefaultTableModel) table_material.getModel();
        
        if (radio_descripcion.isSelected() && !txt_descripcionmaterial.getText().trim().equals("")){
                solicitud = new ctrl_solicitud(
                
                   0,
                    0,
                    0,
                    "",
                    0,
                    "",
                    0,
                    -1, //numero de material
                    txt_descripcionmaterial.getText().trim(),                                  // descripcion de material     
                    0,
                    "",
                    0,
                    "",
                    0,    
                    0,
                    0,
                    0,
                    0,    
                    "",
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""   
                ); 
               
                solicitud.buscar_material(table_material);
        }
        else{
                modelotabla.setRowCount(0);
        } 
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void bot_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_seleccionarActionPerformed
         DefaultTableModel modelotabla = (DefaultTableModel) table_material.getModel();
         Integer fila;
         fila = table_material.getSelectedRow();
      
         BufferedImage img;
         
         switch (this.id_frame){
             case 1: frm_solicitud.txt_numeromaterial.setText(table_material.getValueAt(fila,0).toString());
                     frm_solicitud.txt_descripcionmaterial.setText(table_material.getValueAt(fila,1).toString());
                     frm_solicitud.lbl_unidad.setText(table_material.getValueAt(fila,2).toString());
                                         
                     frm_solicitud.bot_agregarposicion.setEnabled(true);
                     ctrl_solicitud solicitud = new ctrl_solicitud(
                
                        0,
                        0,
                        0,
                        "",
                        0,
                        "",
                        0,
                        Integer.parseInt(frm_solicitud.txt_numeromaterial.getText().trim()), //numero de material
                        "",             // descripcion de material     
                        0,
                        "",
                        0,
                        "",
                        0,    
                        0,
                        0,
                        0,
                        0,     
                        "", //fecha solicitud
                        "",
                        "",
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""     
                );  
                     
                   try{  
                     img = funciones.decodeToImage(solicitud.consultar_foto());
                     frm_solicitud.lbl_foto.setIcon(null);
                     ImageIcon icon = new ImageIcon(img);
                     Icon icono = new ImageIcon(icon.getImage().getScaledInstance(frm_solicitud.lbl_foto.getWidth(), frm_solicitud.lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                     
                     frm_solicitud.lbl_foto.setIcon(icono);
                    
                   }  
                   catch(NullPointerException ex){  }
                     
                     break;
                     
             case 2: frm_reserva.txt_numeromaterial.setText(table_material.getValueAt(fila,0).toString());
                     frm_reserva.txt_descripcionmaterial.setText(table_material.getValueAt(fila,1).toString());
                     frm_reserva.bot_agregarposicion.setEnabled(true);
                     frm_reserva.lbl_umb.setText(table_material.getValueAt(fila,2).toString());
                     ctrl_reserva reserva = new ctrl_reserva(
                                0,
                                0,
                                0,
                                "",
                                0,
                                Integer.parseInt(frm_reserva.txt_numeromaterial.getText()), //numero de material
                                "",             // descripcion de material     
                                0,
                                "",
                                0,
                                "",
                                0,    
                                0,
                                0,
                                0,
                                0,
                                "", //fecha reserva
                                "",
                                "",
                                false,
                                "",
                                "",
                                "",
                                "",
                                "",
                                "",
                                "",
                                "",
                                ""
                        );  
        
                        img = funciones.decodeToImage(reserva.consultar_foto());
       
                        try{
                        frm_reserva.lbl_foto.setIcon(null);
                        ImageIcon icon2 = new ImageIcon(img);
                        Icon icono2 = new ImageIcon(icon2.getImage().getScaledInstance(frm_reserva.lbl_foto.getWidth(), frm_reserva.lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                        
                        frm_reserva.lbl_foto.setIcon(icono2);
                     
                        }
                        catch(NullPointerException ex){}
                     
                     break;        
                     
            case 3: frm_entradaexpress.txt_numeromaterial.setText(table_material.getValueAt(fila,0).toString());
                    frm_entradaexpress.txt_descripcionmaterial.setText(table_material.getValueAt(fila,1).toString());
                    frm_entradaexpress.lbl_umb.setText(table_material.getValueAt(fila,2).toString()); 
                    //frm_entradaexpress.bot_documento.setEnabled(false);
                    ctrl_solicitud solicitud2 = new ctrl_solicitud(
                
                        0,
                        0,
                        0,
                        "",
                        0,
                        "",
                        0,
                        Integer.parseInt(frm_entradaexpress.txt_numeromaterial.getText().trim()), //numero de material
                        "",             // descripcion de material     
                        0,
                        "",
                        0,
                        "",
                        0,    
                        0,
                        0,
                        0,
                        0,    
                        "", //fecha solicitud
                        "",
                        "",
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""    
                );  
                     
                     
                     img = funciones.decodeToImage(solicitud2.consultar_foto());
       
                     try{
                     frm_entradaexpress.lbl_foto.setIcon(null);
                     ImageIcon icon3 = new ImageIcon(img);
                     Icon icono3 = new ImageIcon(icon3.getImage().getScaledInstance(frm_entradaexpress.lbl_foto.getWidth(), frm_entradaexpress.lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                     
                     frm_entradaexpress.lbl_foto.setIcon(icono3);
                     
                     }
                     catch(NullPointerException ex){ }
                     
                     break;
            
            case 4: frm_salidaexpress.txt_numeromaterial.setText(table_material.getValueAt(fila,0).toString());
                    frm_salidaexpress.txt_descripcionmaterial.setText(table_material.getValueAt(fila,1).toString());
                    frm_salidaexpress.lbl_umb.setText(table_material.getValueAt(fila,2).toString());
                     
                    ctrl_solicitud solicitud3 = new ctrl_solicitud(
                
                        0,
                        0,
                        0,
                        "",
                        0,
                        "",
                        0,
                        Integer.parseInt(frm_salidaexpress.txt_numeromaterial.getText().trim()), //numero de material
                        "",             // descripcion de material     
                        0,
                        "",
                        0,
                        "",
                        0,    
                        0,
                        0,
                        0,
                        0,    
                        "", //fecha solicitud
                        "",
                        "",
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""    
                );  
                     
                  try{   
                     img = funciones.decodeToImage(solicitud3.consultar_foto());
                     frm_salidaexpress.lbl_foto.setIcon(null);
                     ImageIcon icon4 = new ImageIcon(img);
                     Icon icono4 = new ImageIcon(icon4.getImage().getScaledInstance(frm_salidaexpress.lbl_foto.getWidth(), frm_salidaexpress.lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                     
                     frm_salidaexpress.lbl_foto.setIcon(icono4);
                  }
                  catch(NullPointerException ex){
                      
                  }
                 ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(frm_salidaexpress.txt_numeromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                    0,
                    "", //procedencia
                     0,
                    "", //clase de movimiento 
                    0,
                    "", //proyecto  
                     0, //id_usuario
                    "",
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
                    frm_salidaexpress.cmb_almacen.setEnabled(true);
                    frm_salidaexpress.cmb_almacen = entrada.cargarmaterial_almacen(frm_salidaexpress.cmb_almacen, "Seleccione...", 1);
                    frm_salidaexpress.cmb_ubicacion.removeAllItems();
                    frm_salidaexpress.cmb_ubicacion.setEnabled(false);
                    
                break;         
                     
            case 5:        
                frm_transferenciamaterial.txt_nromaterialdesde.setText(table_material.getValueAt(fila,0).toString());
                
                ctrl_material material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialdesde.getText()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true
                );

                class_material modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    frm_transferenciamaterial.lbl_descodmatalternativo.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcion.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarca.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelo.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerial.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterial.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterial.lbl_desstockdisponible.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterial.lbl_descantidadentrante.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterial.lbl_descantidadsaliente.setText(String.valueOf(modelo_material.getCantidad_saliente()));
                    frm_transferenciamaterial.spin_cantidadsaliente.setValue(modelo_material.getStock_disponible());
                }
                break;
            case 6:
                
                frm_transferenciamaterial.txt_nromaterialhasta.setText(table_material.getValueAt(fila,0).toString());
                
                material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialhasta.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

            modelo_material = material.consultar_material();

            
            //stockdesde
            Integer stockdisponibledesde =0;
            try{
                 
                    stockdisponibledesde = Integer.parseInt(frm_transferenciamaterial.spin_cantidadsaliente.getValue().toString());
                 
            }
            catch(NullPointerException ex){
                 stockdisponibledesde = 0;
            }
            
            
                Integer stockdisponiblehasta = 0;
                Integer stockdisponiblepre = 0;
                //stockhasta
                try{
                    stockdisponiblehasta = modelo_material.getStock_disponible();
                    stockdisponiblepre = stockdisponibledesde + stockdisponiblehasta;

                }
                catch(NullPointerException ex){
                    stockdisponiblepre = 0;
                }

                Integer stockcantidadentrantedesde = 0;
                //cantidad entrante
                try{

                    stockcantidadentrantedesde = Integer.parseInt(frm_transferenciamaterial.lbl_descantidadentrante.getText());

                }
                catch(NullPointerException ex){
                    stockcantidadentrantedesde = 0;
                }


                Integer stockcantidadentrantepre = 0;
                Integer stockcantidadentrantehasta = modelo_material.getCantidad_entrante();
                stockcantidadentrantepre = stockcantidadentrantedesde + stockcantidadentrantehasta;


                //cantidad saliente
                Integer stockcantidadsalientedesde = 0;
                try{

                    stockcantidadsalientedesde = Integer.parseInt(frm_transferenciamaterial.lbl_descantidadsaliente.getText());

                }
                catch(NullPointerException ex){
                    stockcantidadsalientedesde = 0;
                }

                Integer stockcantidadsalientepre = 0;
                Integer stockcantidadsalientehasta = modelo_material.getCantidad_saliente();
                stockcantidadsalientepre = stockcantidadsalientedesde + stockcantidadsalientehasta;

                if (modelo_material.isStatus()){

                    frm_transferenciamaterial.lbl_descodmatalternativohasta.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcionhasta.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarcahasta.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelohasta.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerialhasta.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterialhasta.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumbhasta.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterial.lbl_desstockdisponiblehasta.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterial.lbl_descantidadentrantehasta.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterial.lbl_descantidadsalientehasta.setText(String.valueOf(modelo_material.getCantidad_saliente()));

                    frm_transferenciamaterial.lbl_descodmatalternativopre.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcionpre.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarcapre.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelopre.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerialpre.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterialpre.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumbpre.setText(modelo_material.getDescripcion_medida());

                    if (stockdisponiblepre > 0) {
                        frm_transferenciamaterial.lbl_desstockdisponiblepre.setText(String.valueOf(stockdisponiblepre));
                        frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }   

                    if(stockcantidadentrantepre  > 0){
                       frm_transferenciamaterial.lbl_descantidadentrantepre.setText(String.valueOf(stockcantidadentrantepre));
                       frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }

                    if(stockcantidadentrantepre  > 0){
                       frm_transferenciamaterial.lbl_descantidadsalientepre.setText(String.valueOf(stockcantidadsalientepre));
                       frm_transferenciamaterial.bot_actualizarmaterial.setEnabled(true);
                    }

                }
                        
            break;
            
            case 7:
                frm_transferenciamaterialubicacion.txt_nromaterial.setText(table_material.getValueAt(fila,0).toString());
                
                material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterialubicacion.txt_nromaterial.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    frm_transferenciamaterialubicacion.lbl_descodmaterial.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterialubicacion.lbl_desdescripcion.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterialubicacion.lbl_desmarca.setText(modelo_material.getMarca());
                    frm_transferenciamaterialubicacion.lbl_desmodelo.setText(modelo_material.getModelo());
                    frm_transferenciamaterialubicacion.lbl_desclasematerial.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterialubicacion.lbl_desgrupomaterial.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterialubicacion.lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterialubicacion.lbl_desstockdisponible.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterialubicacion.lbl_descantidadentrante.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterialubicacion.lbl_descantidadsaliente.setText(String.valueOf(modelo_material.getCantidad_saliente()));
                    frm_transferenciamaterialubicacion.lbl_cantumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterialubicacion.spin_cantidadtrans.setValue(modelo_material.getStock_disponible());
            
                }
            
                entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(frm_transferenciamaterialubicacion.txt_nromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                frm_transferenciamaterialubicacion.cmb_almacenactual =  entrada.cargarmaterial_almacen(frm_transferenciamaterialubicacion.cmb_almacenactual,"Seleccione...",1);
            
                break;

            case 8:
                frm_transferenciamaterialproyecto.txt_nromaterial.setText(table_material.getValueAt(fila,0).toString());
                frm_transferenciamaterialproyecto.lbl_unidad.setText(table_material.getValueAt(fila,2).toString());
                material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterialproyecto.txt_nromaterial.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    frm_transferenciamaterialproyecto.lbl_descodmaterial.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterialproyecto.lbl_desdescripcion.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterialproyecto.lbl_desmarca.setText(modelo_material.getMarca());
                    frm_transferenciamaterialproyecto.lbl_desmodelo.setText(modelo_material.getModelo());
                    frm_transferenciamaterialproyecto.lbl_desclasematerial.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterialproyecto.lbl_desgrupomaterial.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterialproyecto.lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterialproyecto.lbl_desstockdisponible.setText(String.valueOf(modelo_material.getStock_disponible()));
                    
                   
                }
            
                entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(frm_transferenciamaterialproyecto.txt_nromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                frm_transferenciamaterialproyecto.cmb_proyectoactual =  entrada.cargarmaterial_proyecto(frm_transferenciamaterialproyecto.cmb_proyectoactual,"Seleccione...",1);
                
                break;                
        
         
            case 9:
                frm_reporteentradamaterial2.txt_nromaterial.setText(table_material.getValueAt(fila,0).toString());
                
                material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_reporteentradamaterial2.txt_nromaterial.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    frm_reporteentradamaterial2.txt_descripcionmaterial.setText(modelo_material.getDescripcion());
                                       
                }
                      
                
                break;     
                
            case 10:
                    frm_prestamo.txt_numeromaterial.setText(table_material.getValueAt(fila,0).toString());
                    frm_prestamo.lbl_desdescripcionmaterial.setText(table_material.getValueAt(fila,1).toString());
                    frm_prestamo.lbl_desumb.setText(table_material.getValueAt(fila,2).toString());
                    frm_prestamo.lbl_marca.setText(table_material.getValueAt(fila,3).toString());
                    frm_prestamo.lbl_modelo.setText(table_material.getValueAt(fila,4).toString());
                 
                    
                    ctrl_solicitud solicitud5 = new ctrl_solicitud(
                
                        0,
                        0,
                        0,
                        "",
                        0,
                        "",
                        0,
                        Integer.parseInt(frm_prestamo.txt_numeromaterial.getText().trim()), //numero de material
                        "",             // descripcion de material     
                        0,
                        "",
                        0,
                        "",
                        0,    
                        0,
                        0,
                        0,
                        0,     
                        "", //fecha solicitud
                        "",
                        "",
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""    
                );  
                   frm_prestamo.lbl_foto.setIcon(null);  
                   try{  
                     img = funciones.decodeToImage(solicitud5.consultar_foto());
       
                     ImageIcon icon = new ImageIcon(img);
                     Icon icono = new ImageIcon(icon.getImage().getScaledInstance(frm_prestamo.lbl_foto.getWidth(), frm_prestamo.lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                    
                     frm_prestamo.lbl_foto.setIcon(icono);
                    
                   }  
                   catch(NullPointerException ex){  }
                  
                               entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(frm_prestamo.txt_numeromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                frm_prestamo.cmb_proyecto =  entrada.cargarmaterial_proyecto(frm_prestamo.cmb_proyecto,"Seleccione...",1);
                frm_prestamo.cmb_almacen.setEnabled(true);
                frm_prestamo.cmb_almacen = entrada.cargarmaterial_almacen(frm_prestamo.cmb_almacen, "Seleccione...", 1);   
                frm_prestamo.bot_borrar.setEnabled(false);   
                   
                   
                     break;
                     
        case 11:
                frm_transferenciamaterialubicacionenalmacen.txt_nromaterial.setText(table_material.getValueAt(fila,0).toString());
                
                material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterialubicacionenalmacen.txt_nromaterial.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    frm_transferenciamaterialubicacionenalmacen.lbl_descodmaterial.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterialubicacionenalmacen.lbl_desdescripcion.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterialubicacionenalmacen.lbl_desmarca.setText(modelo_material.getMarca());
                    frm_transferenciamaterialubicacionenalmacen.lbl_desmodelo.setText(modelo_material.getModelo());
                    frm_transferenciamaterialubicacionenalmacen.lbl_desclasematerial.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterialubicacionenalmacen.lbl_desgrupomaterial.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterialubicacionenalmacen.lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterialubicacionenalmacen.lbl_desstockdisponible.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterialubicacionenalmacen.lbl_descantidadentrante.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterialubicacionenalmacen.lbl_descantidadsaliente.setText(String.valueOf(modelo_material.getCantidad_saliente()));
                    frm_transferenciamaterialubicacionenalmacen.lbl_cantumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterialubicacionenalmacen.spin_cantidadtrans.setValue(modelo_material.getStock_disponible());
            
                }
            
                entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(frm_transferenciamaterialubicacionenalmacen.txt_nromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                frm_transferenciamaterialubicacionenalmacen.cmb_almacenactual =  entrada.cargarmaterial_almacen(frm_transferenciamaterialubicacionenalmacen.cmb_almacenactual,"Seleccione...",1);
            
                break;
                
        case 12:  
            
            ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    Integer.parseInt(table_material.getValueAt(fila,0).toString()), //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

            prestamo.consultar_prestamos(frm_actualizarprestamo.table_prestamo,"","",1);
            
            break;
        
        case 13:
                frm_transferenciamaterial.txt_nromaterialdesde.setText(table_material.getValueAt(fila,0).toString());
                
                material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialdesde.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    frm_transferenciamaterial.lbl_descodmatalternativo.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcion.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarca.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelo.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerial.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterial.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterial.lbl_desstockdisponible.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterial.lbl_descantidadentrante.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterial.lbl_descantidadsaliente.setText(String.valueOf(modelo_material.getCantidad_saliente()));
                    frm_transferenciamaterial.lbl_desumb.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterial.spin_cantidadsaliente.setValue(modelo_material.getStock_disponible());
            
                }
            
                entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialdesde.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
          
                frm_transferenciamaterial.cmb_almacenactual =  entrada.cargarmaterial_almacen(frm_transferenciamaterial.cmb_almacenactual,"Seleccione...",1);
            
                break;

        case 14:
                frm_transferenciamaterial.txt_nromaterialhasta.setText(table_material.getValueAt(fila,0).toString());
                
                material = new ctrl_material(
                    0,
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialhasta.getText().trim().toUpperCase()),
                    "",
                    "",
                    "",
                    "",
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.0,
                    0.0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    true

                );

                modelo_material = material.consultar_material();

                if (modelo_material.isStatus()){
                
                    frm_transferenciamaterial.lbl_descodmatalternativohasta.setText(modelo_material.getCodigo_mat_alter());
                    frm_transferenciamaterial.lbl_desdescripcionhasta.setText(modelo_material.getDescripcion());
                    frm_transferenciamaterial.lbl_desmarcahasta.setText(modelo_material.getMarca());
                    frm_transferenciamaterial.lbl_desmodelohasta.setText(modelo_material.getModelo());
                    frm_transferenciamaterial.lbl_desclasematerialhasta.setText(modelo_material.getDescripcionclasearticulo());
                    frm_transferenciamaterial.lbl_desgrupomaterialhasta.setText(modelo_material.getDescripciongrupoarticulo());
                    frm_transferenciamaterial.lbl_desumbhasta.setText(modelo_material.getDescripcion_medida());
                    frm_transferenciamaterial.lbl_desstockdisponiblehasta.setText(String.valueOf(modelo_material.getStock_disponible()));
                    frm_transferenciamaterial.lbl_descantidadentrantehasta.setText(String.valueOf(modelo_material.getCantidad_entrante()));
                    frm_transferenciamaterial.lbl_descantidadsalientehasta.setText(String.valueOf(modelo_material.getCantidad_saliente()));
                    frm_transferenciamaterial.lbl_desumbhasta.setText(modelo_material.getDescripcion_medida());
                    
                }
            
                entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(frm_transferenciamaterial.txt_nromaterialhasta.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                       0, //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
                       
                frm_transferenciamaterial.cmb_almacendestino =  entrada.cargarmaterial_almacen(frm_transferenciamaterial.cmb_almacendestino,"Seleccione...",1);
            
                frm_transferenciamaterial.cmb_almacendestino.setEnabled(true);
                break;                
                
           } 
         
        this.dispose();
        
    }//GEN-LAST:event_bot_seleccionarActionPerformed

    private void table_materialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_materialMousePressed
         //bot_seleccionar.doClick();
    }//GEN-LAST:event_table_materialMousePressed

    private void txt_numeromaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numeromaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numeromaterialActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_buscarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_buscarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_buscarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_buscarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_buscarmaterial(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_seleccionar;
    private javax.swing.ButtonGroup group_material;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JRadioButton radio_descripcion;
    private javax.swing.JRadioButton radio_numeromaterial;
    private javax.swing.JTable table_material;
    private javax.swing.JTextField txt_descripcionmaterial;
    private javax.swing.JTextField txt_numeromaterial;
    // End of variables declaration//GEN-END:variables
}
