/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_reserva;
import controlador.ctrl_solicitud;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.class_reserva;



/**
 *
 * @author ruben
 */
public class frm_actualizarreserva extends javax.swing.JFrame {

    /**
     * Creates new form frm_consultarsolicitud
     */
    public frm_actualizarreserva() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - ACTUALIZAR RESERVAS");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());  
        
        DefaultTableModel modelotabla = (DefaultTableModel) tabla_resumenreserva.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        tabla_resumenreserva.setRowSorter(elQueOrdena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        lbl_nrosolicitud = new javax.swing.JLabel();
        txt_nroreserva = new javax.swing.JTextField();
        lbl_proyecto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_resumenreserva = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoaprobarsolicitud = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        date_desde = new com.toedter.calendar.JDateChooser();
        lbl_fechadesde = new javax.swing.JLabel();
        lbl_proyectonuevo = new javax.swing.JLabel();
        cmb_proyectoactualizado = new javax.swing.JComboBox<>();
        lbl_empresaactualizar = new javax.swing.JLabel();
        cmb_empresaactualizar = new javax.swing.JComboBox<>();
        bot_actualizar = new javax.swing.JButton();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        txt_idproyecto = new javax.swing.JTextField();
        bot_buscarreporte = new javax.swing.JButton();
        txt_descripcionproyecto = new javax.swing.JTextField();
        bot_actualizarreserva = new javax.swing.JButton();

        txt_id.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("NRO RESERVA");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_nroreserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nroreserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nroreservaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        getContentPane().add(lbl_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        tabla_resumenreserva.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tabla_resumenreserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_area", "id_proyecto", "", "NRO RESERVA", "NRO DE MATERIAL", "MATERIAL SOLICITADO", "POSICIÓN", "CANTIDAD RESERVADA", "UMB", "PROYECTO", "EMPRESA", "FECHA RESERVA", "aprob_reserva", "fecha_aprobacion", "cantidad_aprobada", "autori_reserva", "fecha_autorizacion", "cantidad_autorizada", "conformacion_solicitud", "fecha_conformacion", "cantidad_conformada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_resumenreserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_resumenreservaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_resumenreserva);
        if (tabla_resumenreserva.getColumnModel().getColumnCount() > 0) {
            tabla_resumenreserva.getColumnModel().getColumn(0).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(1).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(1).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(1).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(2).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(2).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(2).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(3).setMinWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(3).setMaxWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(4).setMinWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(4).setPreferredWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(4).setMaxWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(5).setMinWidth(350);
            tabla_resumenreserva.getColumnModel().getColumn(5).setPreferredWidth(350);
            tabla_resumenreserva.getColumnModel().getColumn(5).setMaxWidth(350);
            tabla_resumenreserva.getColumnModel().getColumn(6).setMinWidth(70);
            tabla_resumenreserva.getColumnModel().getColumn(6).setPreferredWidth(70);
            tabla_resumenreserva.getColumnModel().getColumn(6).setMaxWidth(70);
            tabla_resumenreserva.getColumnModel().getColumn(7).setMinWidth(140);
            tabla_resumenreserva.getColumnModel().getColumn(7).setPreferredWidth(140);
            tabla_resumenreserva.getColumnModel().getColumn(7).setMaxWidth(140);
            tabla_resumenreserva.getColumnModel().getColumn(8).setMinWidth(50);
            tabla_resumenreserva.getColumnModel().getColumn(8).setPreferredWidth(50);
            tabla_resumenreserva.getColumnModel().getColumn(8).setMaxWidth(50);
            tabla_resumenreserva.getColumnModel().getColumn(9).setMinWidth(200);
            tabla_resumenreserva.getColumnModel().getColumn(9).setPreferredWidth(200);
            tabla_resumenreserva.getColumnModel().getColumn(9).setMaxWidth(200);
            tabla_resumenreserva.getColumnModel().getColumn(10).setMinWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(10).setPreferredWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(10).setMaxWidth(120);
            tabla_resumenreserva.getColumnModel().getColumn(11).setMinWidth(150);
            tabla_resumenreserva.getColumnModel().getColumn(11).setPreferredWidth(150);
            tabla_resumenreserva.getColumnModel().getColumn(11).setMaxWidth(150);
            tabla_resumenreserva.getColumnModel().getColumn(12).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(12).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(12).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(13).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(13).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(13).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(14).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(14).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(14).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(15).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(15).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(15).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(16).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(16).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(16).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(17).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(17).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(17).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(18).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(18).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(18).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(19).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(19).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(19).setMaxWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(20).setMinWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(20).setPreferredWidth(0);
            tabla_resumenreserva.getColumnModel().getColumn(20).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1320, 410));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoaprobarsolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoaprobarsolicitud.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoaprobarsolicitud.setText("ACTUALIZAR RESERVA");
        jPanel7.add(lbl_encabezadoaprobarsolicitud);
        lbl_encabezadoaprobarsolicitud.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FECHA HASTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        date_hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_hastaPropertyChange(evt);
            }
        });
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        date_desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_desdePropertyChange(evt);
            }
        });
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));

        lbl_fechadesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechadesde.setText("FECHA DESDE");
        getContentPane().add(lbl_fechadesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_proyectonuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyectonuevo.setText("PROYECTO A ACTUALIZAR");
        getContentPane().add(lbl_proyectonuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        cmb_proyectoactualizado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_proyectoactualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proyectoactualizadoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_proyectoactualizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 270, -1));

        lbl_empresaactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empresaactualizar.setText("EMPRESA A ACTUALIZAR");
        getContentPane().add(lbl_empresaactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        cmb_empresaactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_empresaactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_empresaactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_empresaactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 240, -1));

        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR POSICIÓN");
        bot_actualizar.setToolTipText("");
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, -1, -1));

        panel_foto.setBackground(new java.awt.Color(255, 255, 255));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        getContentPane().add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 170, 120));

        txt_idproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_idproyecto.setEnabled(false);
        getContentPane().add(txt_idproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 70, -1));

        bot_buscarreporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_buscarreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscarreporte.setText("Buscar");
        bot_buscarreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarreporteActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscarreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        txt_descripcionproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionproyecto.setEnabled(false);
        getContentPane().add(txt_descripcionproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 230, 20));

        bot_actualizarreserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_actualizarreserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        bot_actualizarreserva.setText("ACTUALIZAR RESERVA");
        bot_actualizarreserva.setEnabled(false);
        bot_actualizarreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarreservaActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizarreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_actualizarreserva frm = new frm_actualizarreserva();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               
               ctrl_reserva reserva=null;

                reserva = new ctrl_reserva(
                        0,//IDRESERVA
                        Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                        Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                        frm_principalM1.lbl_desarea.getText().trim(), 
                        0,
                        0, //numero de material
                        "",             // descripcion de material     
                        0, //IDEMPRESA
                        "",//DESCRIPCION EMPRESA
                        0,//IDPROYECTO
                        "",//DESCRIPCION PROYECTO
                        0,//POSICION
                        0,//CANTIDAD A RESERVAR
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",//fecharequerida
                        "", //justificacion
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
            );  
                                
                reserva.consultar_reserva_activa(tabla_resumenreserva,0,"","",1,0); 
        
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_nroreservaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nroreservaKeyReleased
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            
               ctrl_reserva reserva=null;

                reserva = new ctrl_reserva(
                
                        Integer.parseInt(txt_nroreserva.getText().trim()),//IDRESERVA
                        Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                        Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                        frm_principalM1.lbl_desarea.getText().trim(), 
                        0,
                        0, //numero de material
                        "",             // descripcion de material     
                        0, //IDEMPRESA
                        "",//DESCRIPCION EMPRESA
                        0,//IDPROYECTO
                        "",//DESCRIPCION PROYECTO
                        0,//POSICION
                        0,//CANTIDAD A RESERVAR
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",//fecharequerida
                        "", //justificacion
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
            );  
                                
                reserva.consultar_reserva_activa(tabla_resumenreserva,1,"","",1,0);

        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nroreserva.setText("");
                
             }   
        }     
    }//GEN-LAST:event_txt_nroreservaKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
           
             ctrl_reserva reserva=null;
             
                 reserva = new ctrl_reserva(
                
                        0,//IDRESERVA
                        Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                        Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                        frm_principalM1.lbl_desarea.getText().trim(), 
                        0,
                        0, //numero de material
                        txt_descripcionmaterial.getText().trim(),             // descripcion de material     
                        0, //IDEMPRESA
                        "",//DESCRIPCION EMPRESA
                        0,//IDPROYECTO
                        "",//DESCRIPCION PROYECTO
                        0,//POSICION
                        0,//CANTIDAD A RESERVAR
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",//fecharequerida
                        "", //justificacion
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
            );  
                                
                reserva.consultar_reserva_activa(tabla_resumenreserva,2,"","",1,0); 

         
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void date_hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_hastaPropertyChange
        String fechadesde;
        String fechahasta;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
        
    
                   ctrl_reserva reserva=null;

                reserva = new ctrl_reserva(
                
                        0,//IDRESERVA
                        Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                        Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                        frm_principalM1.lbl_desarea.getText().trim(), 
                        0,
                        0, //numero de material
                        "",             // descripcion de material     
                        0, //IDEMPRESA
                        "",//DESCRIPCION EMPRESA
                        0,//IDPROYECTO
                        "",//DESCRIPCION PROYECTO
                        0,//POSICION
                        0,//CANTIDAD A RESERVAR
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",//fecharequerida
                        "", //justificacion
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
            );  
                                
            reserva.consultar_reserva_activa(tabla_resumenreserva,5,fechadesde,fechahasta,1,0);    
            }
        
    }//GEN-LAST:event_date_hastaPropertyChange

    private void date_desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_desdePropertyChange
        String fechadesde;
        String fechahasta;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
               ctrl_reserva reserva=null;

                reserva = new ctrl_reserva(
                
                        0,//IDRESERVA
                        Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                        Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                        frm_principalM1.lbl_desarea.getText().trim(), 
                        0,
                        0, //numero de material
                        "",             // descripcion de material     
                        0, //IDEMPRESA
                        "",//DESCRIPCION EMPRESA
                        0,//IDPROYECTO
                        "",//DESCRIPCION PROYECTO
                        0,//POSICION
                        0,//CANTIDAD A RESERVAR
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",//fecharequerida
                        "", //justificacion
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
            );  
                                
                reserva.consultar_reserva_activa(tabla_resumenreserva,5,fechadesde,fechahasta,1,0);     
            }
    }//GEN-LAST:event_date_desdePropertyChange

    private void tabla_resumenreservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_resumenreservaMouseClicked
        Integer fila;
        
        fila = tabla_resumenreserva.getSelectedRow();
        
        ctrl_comun control = new ctrl_comun(7);
        cmb_proyectoactualizado =  control.cargar_combo(cmb_proyectoactualizado,tabla_resumenreserva.getValueAt(fila,9).toString().trim().toUpperCase());
        
       
        control = new ctrl_comun(4);
        cmb_empresaactualizar =  control.cargar_combo(cmb_empresaactualizar,tabla_resumenreserva.getValueAt(fila,10).toString().trim());
        
        ctrl_solicitud solicitud = new ctrl_solicitud(

            0,
            0,
            0,
            "",
            0,
            "",
            0,
            Integer.parseInt(frm_actualizarreserva.tabla_resumenreserva.getValueAt(fila,4).toString()), //numero de material
            "",             // descripcion de material
            0,
            "",
            0,
            "",
            0,
            0,
            0,
            0,
            0,
            "", //fecha solicitud
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""    
        );

        try{
            lbl_foto.setIcon(null);
            BufferedImage img = funciones.decodeToImage(solicitud.consultar_foto());

            ImageIcon icon = new ImageIcon(img);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_DEFAULT));
            
            lbl_foto.setIcon(icono);

        }
        catch(NullPointerException ex){ }
        bot_actualizar.setEnabled(true);
        bot_actualizarreserva.setEnabled(true);
    }//GEN-LAST:event_tabla_resumenreservaMouseClicked

    private void cmb_proyectoactualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proyectoactualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_proyectoactualizadoActionPerformed

    private void cmb_empresaactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_empresaactualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_empresaactualizarActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        Integer fila;
        
        fila = tabla_resumenreserva.getSelectedRow();
        if (!cmb_proyectoactualizado.getSelectedItem().equals("Seleccione...") && !cmb_empresaactualizar.getSelectedItem().equals("Seleccione...")){

                ctrl_reserva reserva=null;

                reserva = new ctrl_reserva(
                
                        Integer.parseInt(tabla_resumenreserva.getValueAt(fila, 3).toString()),//IDRESERVA
                        Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                        Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                        frm_principalM1.lbl_desarea.getText().trim(), 
                        0,
                        0, //numero de material
                        "",             // descripcion de material     
                        Integer.parseInt(cmb_empresaactualizar.getSelectedItem().toString().substring(0,3).trim()), //IDEMPRESA
                        "",//DESCRIPCION EMPRESA
                        Integer.parseInt(cmb_proyectoactualizado.getSelectedItem().toString().substring(0,3).trim()),//IDPROYECTO
                        "",//DESCRIPCION PROYECTO
                        Integer.parseInt(tabla_resumenreserva.getValueAt(fila, 6).toString()),//POSICION
                        0,//CANTIDAD A RESERVAR
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",//fecharequerida
                        "", //justificacion
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
            );              
                
                                                
            if(reserva.actualizar_reserva_posicion()){
                JOptionPane.showMessageDialog(null, "ACTUALIZACIÓN DE LA RESERVA-POSICIÓN SATISFACTORIA");
                reserva.consultar_reserva_activa(tabla_resumenreserva,0,"","",1,0);
                bot_actualizar.setEnabled(false);
            }   
            else{
                JOptionPane.showMessageDialog(null, "ERROR EN LA ACTUALIZACIÓN DE LA RESERVA-POSICIÓN");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
            
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_buscarreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarreporteActionPerformed
        frm_buscarproyecto frm = new frm_buscarproyecto(10);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_buscarreporteActionPerformed

    private void bot_actualizarreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarreservaActionPerformed
        Integer fila;
        class_reserva modelo_reserva;

        fila = tabla_resumenreserva.getSelectedRow();

        JOptionPane.showMessageDialog(null, "SE VISUALIZARÁN SOLO LAS POSICIONES QUE NO HAN SIDO APROBADAS");

        frm_reserva frm = new frm_reserva(1);
        frm.setVisible(true);

        frm_reserva.txt_reserva.setText(tabla_resumenreserva.getValueAt(fila,3).toString());

         ctrl_reserva reserva = new ctrl_reserva(
                
                Integer.parseInt(frm_reserva.txt_reserva.getText().trim()),
                0,
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha reserva
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  

        modelo_reserva = reserva.consultar_posicion_noaprob(frm_reserva.table_posicion);

        frm_reserva.txt_posicion.setText(modelo_reserva.getPosicion().toString());

    }//GEN-LAST:event_bot_actualizarreservaActionPerformed

    public static void actualizar_consultar_reserva(){
                ctrl_reserva reserva=null;

                reserva = new ctrl_reserva(
                
                        0,//IDRESERVA
                        Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                        Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                        frm_principalM1.lbl_desarea.getText().trim(), 
                        0,
                        0, //numero de material
                        "",             // descripcion de material     
                        0, //IDEMPRESA
                        "",//DESCRIPCION EMPRESA
                        Integer.parseInt(txt_id.getText().trim()),//IDPROYECTO
                        "",//DESCRIPCION PROYECTO
                        0,//POSICION
                        0,//CANTIDAD A RESERVAR
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",//fecharequerida
                        "", //justificacion
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
            );  
                                
            reserva.consultar_reserva_activa(tabla_resumenreserva,3,"","",1,0);  
           


   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarreserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarreserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarreserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarreserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_actualizarreserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_actualizarreserva;
    private javax.swing.JButton bot_buscarreporte;
    private javax.swing.JButton bot_cerrar;
    protected static javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox<String> cmb_empresaactualizar;
    private javax.swing.JComboBox<String> cmb_proyectoactualizado;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_empresaactualizar;
    private javax.swing.JLabel lbl_encabezadoaprobarsolicitud;
    private javax.swing.JLabel lbl_fechadesde;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    protected static javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_proyecto;
    private javax.swing.JLabel lbl_proyectonuevo;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    protected static javax.swing.JTable tabla_resumenreserva;
    private javax.swing.JTextField txt_descripcionmaterial;
    protected static javax.swing.JTextField txt_descripcionproyecto;
    public static javax.swing.JTextField txt_id;
    protected static javax.swing.JTextField txt_idproyecto;
    private javax.swing.JTextField txt_nroreserva;
    // End of variables declaration//GEN-END:variables
}
