/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_solicitud;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.class_solicitud;
import static view.frm_consultadetallesolicitud.lbl_foto;
import static view.frm_solicitud.lbl_usuario;

/**
 *
 * @author ruben
 */
public class frm_actualizarsolicitud extends javax.swing.JFrame {

    /**
     * Creates new form frm_consultarsolicitud
     */
    public frm_actualizarsolicitud() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - ACTUALIZAR SOLICITUDES A COMPRAS");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());  
        
        DefaultTableModel modelotabla = (DefaultTableModel) tabla_resumensolicitud.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        tabla_resumensolicitud.setRowSorter(elQueOrdena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        lbl_nrosolicitud = new javax.swing.JLabel();
        txt_nrosolicitud = new javax.swing.JTextField();
        lbl_proyecto = new javax.swing.JLabel();
        lbl_tiposolicitud = new javax.swing.JLabel();
        cmb_tiposolicitud = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoaprobarsolicitud = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        date_desde = new com.toedter.calendar.JDateChooser();
        lbl_fechadesde = new javax.swing.JLabel();
        lbl_proyectonuevo = new javax.swing.JLabel();
        cmb_proyectoactualizado = new javax.swing.JComboBox<>();
        lbl_tiposolicitudactualizar = new javax.swing.JLabel();
        cmb_tiposolicitudactualizar = new javax.swing.JComboBox<>();
        lbl_empresaactualizar = new javax.swing.JLabel();
        cmb_empresaactualizar = new javax.swing.JComboBox<>();
        bot_actualizar = new javax.swing.JButton();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        bot_actualizarsolicitud = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_resumensolicitud = new javax.swing.JTable();
        txt_idproyecto = new javax.swing.JTextField();
        bot_buscarreporte = new javax.swing.JButton();
        txt_descripcionproyecto = new javax.swing.JTextField();

        txt_id.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("NRO SOLICITUD");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nrosolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nrosolicitudKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        getContentPane().add(lbl_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        lbl_tiposolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_tiposolicitud.setText("TIPO DE SOLICITUD");
        getContentPane().add(lbl_tiposolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, -1, -1));

        cmb_tiposolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_tiposolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tiposolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tiposolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 240, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoaprobarsolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoaprobarsolicitud.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoaprobarsolicitud.setText("ACTUALIZAR SOLICITUD");
        jPanel7.add(lbl_encabezadoaprobarsolicitud);
        lbl_encabezadoaprobarsolicitud.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FECHA HASTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        date_hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_hastaPropertyChange(evt);
            }
        });
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        date_desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_desdePropertyChange(evt);
            }
        });
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));

        lbl_fechadesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechadesde.setText("FECHA DESDE");
        getContentPane().add(lbl_fechadesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_proyectonuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyectonuevo.setText("PROYECTO A ACTUALIZAR");
        getContentPane().add(lbl_proyectonuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        cmb_proyectoactualizado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_proyectoactualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proyectoactualizadoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_proyectoactualizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 270, -1));

        lbl_tiposolicitudactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_tiposolicitudactualizar.setText("TIPO DE SOLICITUD A ACTUALIZAR");
        getContentPane().add(lbl_tiposolicitudactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        cmb_tiposolicitudactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_tiposolicitudactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tiposolicitudactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tiposolicitudactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 240, -1));

        lbl_empresaactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empresaactualizar.setText("EMPRESA A ACTUALIZAR");
        getContentPane().add(lbl_empresaactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, -1, -1));

        cmb_empresaactualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_empresaactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_empresaactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_empresaactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 240, -1));

        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR POSICIÓN");
        bot_actualizar.setToolTipText("");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, 210, -1));

        panel_foto.setBackground(new java.awt.Color(255, 255, 255));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        getContentPane().add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 170, 120));

        bot_actualizarsolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_actualizarsolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        bot_actualizarsolicitud.setText("ACTUALIZAR SOLICITUD");
        bot_actualizarsolicitud.setEnabled(false);
        bot_actualizarsolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarsolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizarsolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, 210, 30));

        tabla_resumensolicitud.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tabla_resumensolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_area", "id_proyecto", "id_tiposolicitud", "", "NRO DE SOLICITUD", "POS", "NRO DE MATERIAL", "MATERIAL SOLICITADO", "UMB", "FECHA REQ", "GRUPO ART", "CANT SOLIC.", "PROYECTO", "EMPRESA", "TIPO SOLICITUD", "FECHA SOLICITUD", "aprob_solicitud", "fecha_aprobacion", "cantidad_aprobada", "autori_solicitud", "fecha_autorizacion", "cantidad_autorizada", "conformacion_solicitud", "fecha_conformacion", "cantidad_conformada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_resumensolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_resumensolicitudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_resumensolicitud);
        if (tabla_resumensolicitud.getColumnModel().getColumnCount() > 0) {
            tabla_resumensolicitud.getColumnModel().getColumn(0).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(1).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(1).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(1).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(2).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(2).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(2).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(3).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(3).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(3).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(5).setMinWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(5).setPreferredWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(5).setMaxWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(8).setMinWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(8).setPreferredWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(8).setMaxWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(16).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(16).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(16).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(17).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(17).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(17).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(18).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(18).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(18).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(19).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(19).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(19).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(20).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(20).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(20).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(21).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(21).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(21).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(22).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(22).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(22).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(23).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(23).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(23).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(24).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(24).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(24).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1360, 400));

        txt_idproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_idproyecto.setEnabled(false);
        getContentPane().add(txt_idproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 70, -1));

        bot_buscarreporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_buscarreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscarreporte.setText("Buscar");
        bot_buscarreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarreporteActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscarreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        txt_descripcionproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionproyecto.setEnabled(false);
        getContentPane().add(txt_descripcionproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 230, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_actualizarsolicitud frm = new frm_actualizarsolicitud();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        ctrl_comun control = new ctrl_comun(11);
        cmb_tiposolicitud =  control.cargar_combo(cmb_tiposolicitud,"Seleccione...");
        
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,"","",0); 
        
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_nrosolicitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nrosolicitudKeyReleased
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            
            ctrl_solicitud solicitud = new ctrl_solicitud(
                
                Integer.parseInt(txt_nrosolicitud.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  

             solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,"","",0); 

        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nrosolicitud.setText("");
                
             }   
        }     
    }//GEN-LAST:event_txt_nrosolicitudKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
           
            ctrl_solicitud solicitud = new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  

             solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,"","",0); 

         
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void cmb_tiposolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tiposolicitudActionPerformed
        if(evt.getModifiers() != 0){
            
            if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){

                ctrl_solicitud solicitud =  new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim()),
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""        
             );
              solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,"","",0); 
            }  
        }    
    }//GEN-LAST:event_cmb_tiposolicitudActionPerformed

    private void date_hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_hastaPropertyChange
        String fechadesde;
        String fechahasta;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                JOptionPane.showMessageDialog(this, "entre");
                ctrl_solicitud solicitud=null;

                solicitud = new ctrl_solicitud(
                
                    0,
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    0,
                    "",
                    0,
                    0, //numero de material
                    "",             // descripcion de material     
                    0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,    
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );  
                                
                 solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,fechadesde,fechahasta,0);   
            }
        
    }//GEN-LAST:event_date_hastaPropertyChange

    private void date_desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_desdePropertyChange
        String fechadesde;
        String fechahasta;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
                ctrl_solicitud solicitud=null;

                solicitud = new ctrl_solicitud(
                
                    0,
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    0,
                    "",
                    0,
                    0, //numero de material
                    "",             // descripcion de material     
                    0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,    
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );  
                                
                solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,fechadesde,fechahasta,0);  
            }
    }//GEN-LAST:event_date_desdePropertyChange

    private void cmb_proyectoactualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proyectoactualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_proyectoactualizadoActionPerformed

    private void cmb_tiposolicitudactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tiposolicitudactualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tiposolicitudactualizarActionPerformed

    private void cmb_empresaactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_empresaactualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_empresaactualizarActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        Integer fila;
        Boolean valido1;
        Boolean valido2;
        
        fila = tabla_resumensolicitud.getSelectedRow();
        if (!cmb_proyectoactualizado.getSelectedItem().equals("Seleccione...") && !cmb_tiposolicitudactualizar.getSelectedItem().equals("Seleccione...") && !cmb_empresaactualizar.getSelectedItem().equals("Seleccione...")){
                
                ctrl_solicitud solicitud=null;

                solicitud = new ctrl_solicitud(
                
                    Integer.parseInt(tabla_resumensolicitud.getValueAt(fila, 4).toString()),
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    Integer.parseInt(cmb_tiposolicitudactualizar.getSelectedItem().toString().substring(0,3).trim()),
                    "",
                    0,
                    0, //numero de material
                    "",// descripcion de material     
                    Integer.parseInt(cmb_empresaactualizar.getSelectedItem().toString().substring(0,3).trim()),
                    "",
                    Integer.parseInt(cmb_proyectoactualizado.getSelectedItem().toString().substring(0,3).trim()),
                    "",
                    Integer.parseInt(tabla_resumensolicitud.getValueAt(fila, 5).toString()),
                    0,
                    0,
                    0,
                    0,    
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );  
                
                try{
                    if(tabla_resumensolicitud.getValueAt(fila, 16).toString().equals("")){} 
                    
                    valido1 = false;
                }
                catch(NullPointerException ex){
                    valido1 = true;
                }
                
                try{
                    if(tabla_resumensolicitud.getValueAt(fila, 22).toString().equals("")){}
                    
                    valido2 = false;
                }
                catch(NullPointerException ex){
                    valido2 = true;
                }
  
                if(valido1 && valido2){
                    if(solicitud.actualizar_solicitud_posicion()){
                        JOptionPane.showMessageDialog(null, "ACTUALIZACIÓN DE LA SOLICITUD-POSICIÓN SATISFACTORIA");
                        bot_reiniciar.doClick();
                    }   
                    else{
                        JOptionPane.showMessageDialog(null, "ERROR EN LA ACTUALIZACIÓN DE LA SOLICITUD-POSICIÓN");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "LA SOLICITUD - POSICION ESTA APROBADA Y/O CONFORMADA. ESTA INHABILITADO PARA ACTUALIZAR");    
                }
        }
        else{
            JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
            
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_actualizarsolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarsolicitudActionPerformed
        Integer fila;
        class_solicitud modelo_solicitud;
        
        fila = tabla_resumensolicitud.getSelectedRow();
     
        JOptionPane.showMessageDialog(null, "SE VISUALIZARÁN SOLO LAS POSICIONES QUE NO HAN SIDO APROBADAS Y/O CONFORMADAS");
        
        
        frm_solicitud frm = new frm_solicitud(1);
        frm.setVisible(true);
    
        frm_solicitud.txt_solicitud.setText(tabla_resumensolicitud.getValueAt(fila,4).toString());
    
        
        ctrl_solicitud solicitud = new ctrl_solicitud(

            Integer.parseInt(frm_solicitud.txt_solicitud.getText()),
            0,
            0,
            "",
            0,
            "",
            0,
            0, //numero de material
            "",             // descripcion de material
            0,
            "",
            0,
            "",
            0,
            0,
            0,
            0,
            0,
            "", //fecha solicitud
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""    
        );
        
        
        modelo_solicitud = solicitud.consultar_posicion_noaprob_noconform(frm_solicitud.table_posicion);
    
        frm_solicitud.txt_posicion.setText(modelo_solicitud.getPosicion().toString());
        
        
    }//GEN-LAST:event_bot_actualizarsolicitudActionPerformed

    private void tabla_resumensolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_resumensolicitudMouseClicked
       Integer fila;

        fila = tabla_resumensolicitud.getSelectedRow();

        ctrl_comun control = new ctrl_comun(7);
        cmb_proyectoactualizado =  control.cargar_combo(cmb_proyectoactualizado,tabla_resumensolicitud.getValueAt(fila,12).toString().trim().toUpperCase());

        control = new ctrl_comun(11);
        if(tabla_resumensolicitud.getValueAt(fila,14).toString().trim().equals("SD")){
                cmb_tiposolicitudactualizar =  control.cargar_combo(cmb_tiposolicitudactualizar,"SOLICITUD DIRECTA (SD)");
        }        
        if(tabla_resumensolicitud.getValueAt(fila,14).toString().trim().equals("SI")){
                cmb_tiposolicitudactualizar =  control.cargar_combo(cmb_tiposolicitudactualizar,"SOLICITUD DE INVENTARIO (SI)");
        }        
        if(tabla_resumensolicitud.getValueAt(fila,14).toString().trim().equals("SS")){
                cmb_tiposolicitudactualizar =  control.cargar_combo(cmb_tiposolicitudactualizar,"SOLICITUD DE SERVICIOS (SS)");
        }        
        
        control = new ctrl_comun(4);
        cmb_empresaactualizar =  control.cargar_combo(cmb_empresaactualizar,tabla_resumensolicitud.getValueAt(fila,13).toString().trim());

        ctrl_solicitud solicitud = new ctrl_solicitud(

            0,
            0,
            0,
            "",
            0,
            "",
            0,
            Integer.parseInt(tabla_resumensolicitud.getValueAt(fila,6).toString()), //numero de material
            "",             // descripcion de material
            0,
            "",
            0,
            "",
            0,
            0,
            0,
            0,
            0,
            "", //fecha solicitud
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""    
        );

        try{
            lbl_foto.setIcon(null);
            BufferedImage img = funciones.decodeToImage(solicitud.consultar_foto());

            ImageIcon icon = new ImageIcon(img);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_DEFAULT));

            lbl_foto.setIcon(icono);

        }
        catch(NullPointerException ex){ }
        bot_actualizar.setEnabled(true);
        bot_actualizarsolicitud.setEnabled(true);
 
    }//GEN-LAST:event_tabla_resumensolicitudMouseClicked

    private void bot_buscarreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarreporteActionPerformed
        frm_buscarproyecto frm = new frm_buscarproyecto(11);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_buscarreporteActionPerformed

    public static void actualizar_consultar_solicitud(){
    
      

                ctrl_solicitud solicitud =  new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                Integer.parseInt(txt_id.getText().trim()),
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""        
             );
              solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,"","",0); 
            
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_actualizarsolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_actualizarsolicitud;
    private javax.swing.JButton bot_buscarreporte;
    private javax.swing.JButton bot_cerrar;
    protected static javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox<String> cmb_empresaactualizar;
    private javax.swing.JComboBox<String> cmb_proyectoactualizado;
    private javax.swing.JComboBox<String> cmb_tiposolicitud;
    private javax.swing.JComboBox<String> cmb_tiposolicitudactualizar;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_empresaactualizar;
    private javax.swing.JLabel lbl_encabezadoaprobarsolicitud;
    private javax.swing.JLabel lbl_fechadesde;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    protected static javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_proyecto;
    private javax.swing.JLabel lbl_proyectonuevo;
    private javax.swing.JLabel lbl_tiposolicitud;
    private javax.swing.JLabel lbl_tiposolicitudactualizar;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    public static javax.swing.JTable tabla_resumensolicitud;
    private javax.swing.JTextField txt_descripcionmaterial;
    protected static javax.swing.JTextField txt_descripcionproyecto;
    public static javax.swing.JTextField txt_id;
    protected static javax.swing.JTextField txt_idproyecto;
    private javax.swing.JTextField txt_nrosolicitud;
    // End of variables declaration//GEN-END:variables
}
