/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_cotizacion;
import controlador.ctrl_usuario;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import model.class_cotizacion;
import model.class_usuario;


/**
 *
 * @author ruben
 */
public class frm_detalleact_oc extends javax.swing.JFrame {

     private String destinoArchivo1;
     private File archivo;
     
    public frm_detalleact_oc() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - DETALLE COTIZACIÓN");
        this.getContentPane().setBackground(new Color(240,240,240));
                
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idcotizacion = new javax.swing.JTextField();
        txt_idproveedor = new javax.swing.JTextField();
        lbl_nrosolicitud = new javax.swing.JLabel();
        lbl_idmaterial = new javax.swing.JLabel();
        lbl_desidmaterial = new javax.swing.JLabel();
        lbl_idsolicitud = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_desmaterial = new javax.swing.JLabel();
        lbl_descantidad = new javax.swing.JLabel();
        lbl_cantidadautorizada = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bot_actualizar = new javax.swing.JButton();
        panel_alternativa1 = new javax.swing.JPanel();
        txt_descripcionprov1 = new javax.swing.JTextField();
        lbl_proveedor1 = new javax.swing.JLabel();
        lbl_preciounitario1 = new javax.swing.JLabel();
        txt_total1 = new javax.swing.JTextField();
        lbl_total1 = new javax.swing.JLabel();
        lbl_cantidad1 = new javax.swing.JLabel();
        txt_preciounitario1 = new javax.swing.JTextField();
        txt_rif1 = new javax.swing.JTextField();
        lbl_cantidaddias1 = new javax.swing.JLabel();
        chk_recomendacion1 = new javax.swing.JCheckBox();
        cmb_moneda1 = new javax.swing.JComboBox<>();
        lbl_diasflete1 = new javax.swing.JLabel();
        lbl_und1 = new javax.swing.JLabel();
        date_cotizar1 = new com.toedter.calendar.JDateChooser();
        lbl_fechacotizacion1 = new javax.swing.JLabel();
        cmb_condicionpago1 = new javax.swing.JComboBox<>();
        lbl_adjuntar1 = new javax.swing.JLabel();
        txt_diasplazo1 = new javax.swing.JTextField();
        lbl_plazoentrega1 = new javax.swing.JLabel();
        cmb_plazoentrega1 = new javax.swing.JComboBox<>();
        chk_flete1 = new javax.swing.JCheckBox();
        lbl_moneda1 = new javax.swing.JLabel();
        cmb_tipotransporte1 = new javax.swing.JComboBox<>();
        lbl_condicionpago1 = new javax.swing.JLabel();
        txt_diasflete1 = new javax.swing.JTextField();
        lbl_diasplazoentrega1 = new javax.swing.JLabel();
        lbl_tipotransporte1 = new javax.swing.JLabel();
        lbl_costoflete1 = new javax.swing.JLabel();
        txt_costoflete1 = new javax.swing.JTextField();
        cmb_monedacosto1 = new javax.swing.JComboBox<>();
        bot_verdocumeto = new javax.swing.JButton();
        bot_crear = new javax.swing.JButton();
        spin_cantidad1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("DOCUMENTO SOLICITUD");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_idmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idmaterial.setText("ID MATERIAL");
        getContentPane().add(lbl_idmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_desidmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desidmaterial.setText("jLabel1");
        getContentPane().add(lbl_desidmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        lbl_idsolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idsolicitud.setText("jLabel1");
        getContentPane().add(lbl_idsolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcion.setText("DESCRIPCIÓN MATERIAL");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        lbl_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desmaterial.setText("jLabel1");
        getContentPane().add(lbl_desmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        lbl_descantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descantidad.setText("jLabel1");
        getContentPane().add(lbl_descantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        lbl_cantidadautorizada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadautorizada.setText("CANTIDAD CONFORMADA");
        getContentPane().add(lbl_cantidadautorizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("ACTUALIZAR ORDEN DE COMPRA");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(260, 10, 240, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.setToolTipText("");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(720, 10, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1270, 10, 0, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 60));

        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, -1, -1));

        panel_alternativa1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_alternativa1.setEnabled(false);
        panel_alternativa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_descripcionprov1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionprov1.setEnabled(false);
        panel_alternativa1.add(txt_descripcionprov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, -1));

        lbl_proveedor1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proveedor1.setText("PROVEEDOR");
        panel_alternativa1.add(lbl_proveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_preciounitario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_preciounitario1.setText("PRECIO UNITARIO");
        panel_alternativa1.add(lbl_preciounitario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txt_total1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_total1.setEnabled(false);
        panel_alternativa1.add(txt_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, -1));

        lbl_total1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total1.setText("TOTAL");
        panel_alternativa1.add(lbl_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lbl_cantidad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad1.setText("CANTIDAD A COTIZAR");
        panel_alternativa1.add(lbl_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txt_preciounitario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_preciounitario1.setEnabled(false);
        txt_preciounitario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_preciounitario1KeyReleased(evt);
            }
        });
        panel_alternativa1.add(txt_preciounitario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        txt_rif1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_rif1.setEnabled(false);
        panel_alternativa1.add(txt_rif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, -1));

        lbl_cantidaddias1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidaddias1.setText("CANTIDAD DE DÍAS");
        panel_alternativa1.add(lbl_cantidaddias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        chk_recomendacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_recomendacion1.setText("RECOMENDACIÓN COMPRADOR");
        panel_alternativa1.add(chk_recomendacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        cmb_moneda1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_moneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_moneda1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(cmb_moneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 90, -1));

        lbl_diasflete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasflete1.setText("DÍAS");
        panel_alternativa1.add(lbl_diasflete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, 20));

        lbl_und1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_und1.setText("jLabel13");
        panel_alternativa1.add(lbl_und1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        date_cotizar1.setEnabled(false);
        panel_alternativa1.add(date_cotizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        lbl_fechacotizacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechacotizacion1.setText("FECHA COTIZACIÓN");
        panel_alternativa1.add(lbl_fechacotizacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        cmb_condicionpago1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_condicionpago1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "CRÉDITO", "CONTADO" }));
        panel_alternativa1.add(cmb_condicionpago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, -1));

        lbl_adjuntar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_adjuntar1.setText("DOCUMENTO");
        panel_alternativa1.add(lbl_adjuntar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txt_diasplazo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_diasplazo1.setText("0");
        txt_diasplazo1.setEnabled(false);
        txt_diasplazo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_diasplazo1KeyReleased(evt);
            }
        });
        panel_alternativa1.add(txt_diasplazo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 60, -1));

        lbl_plazoentrega1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_plazoentrega1.setText("PLAZO DE ENTREGA");
        panel_alternativa1.add(lbl_plazoentrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        cmb_plazoentrega1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_plazoentrega1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "ENTREGA INMEDIATA", "ENTREGA SUJETA A PLAZO(DÍAS)" }));
        cmb_plazoentrega1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_plazoentrega1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(cmb_plazoentrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 240, -1));

        chk_flete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_flete1.setText("FLETE");
        chk_flete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_flete1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(chk_flete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        lbl_moneda1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_moneda1.setText("jLabel13");
        panel_alternativa1.add(lbl_moneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        cmb_tipotransporte1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_tipotransporte1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "AÉREO", "MARÍTIMO", "TERRESTRE" }));
        cmb_tipotransporte1.setEnabled(false);
        cmb_tipotransporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipotransporte1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(cmb_tipotransporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 220, -1));

        lbl_condicionpago1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_condicionpago1.setText("CONDICIÓN DE PAGO");
        panel_alternativa1.add(lbl_condicionpago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        txt_diasflete1.setText("0");
        txt_diasflete1.setEnabled(false);
        txt_diasflete1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_diasflete1KeyReleased(evt);
            }
        });
        panel_alternativa1.add(txt_diasflete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 70, -1));

        lbl_diasplazoentrega1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasplazoentrega1.setText("DÍAS");
        panel_alternativa1.add(lbl_diasplazoentrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        lbl_tipotransporte1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_tipotransporte1.setText("TIPO DE TRANSPORTE");
        panel_alternativa1.add(lbl_tipotransporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        lbl_costoflete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_costoflete1.setText("COSTO FLETE");
        panel_alternativa1.add(lbl_costoflete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        txt_costoflete1.setText("0");
        txt_costoflete1.setEnabled(false);
        txt_costoflete1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_costoflete1KeyReleased(evt);
            }
        });
        panel_alternativa1.add(txt_costoflete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 120, -1));

        cmb_monedacosto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_monedacosto1.setEnabled(false);
        cmb_monedacosto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_monedacosto1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(cmb_monedacosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 80, 20));

        bot_verdocumeto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bot_verdocumeto.setText("Ver Cotización");
        bot_verdocumeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdocumetoActionPerformed(evt);
            }
        });
        panel_alternativa1.add(bot_verdocumeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        bot_crear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        bot_crear.setText("Asignar Proveedor");
        bot_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_crearActionPerformed(evt);
            }
        });
        panel_alternativa1.add(bot_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        spin_cantidad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidad1.setEnabled(false);
        panel_alternativa1.add(spin_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 90, -1));

        getContentPane().add(panel_alternativa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 510, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Integer posicion;
        
        posicion = frm_ordendecompra.table_posicioncompra.getSelectedRow();
        
        ctrl_comun ctrl = new ctrl_comun(6);
        ctrl.cargar_combo(cmb_moneda1, frm_ordendecompra.table_posicioncompra.getValueAt(posicion,9).toString());
        ctrl.cargar_combo(cmb_monedacosto1, frm_ordendecompra.table_posicioncompra.getValueAt(posicion,24).toString());
        
        txt_idcotizacion.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,0).toString());
        lbl_idsolicitud.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,1).toString());
        lbl_desidmaterial.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,3).toString());
        lbl_desmaterial.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,4).toString());
        lbl_descantidad.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,6).toString());
        txt_rif1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,16).toString());
        txt_descripcionprov1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,5).toString());
        txt_preciounitario1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,8).toString());
               
        spin_cantidad1.setText(lbl_descantidad.getText());  
        lbl_und1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,7).toString());        
        txt_total1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,10).toString());
        lbl_moneda1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,9).toString());
        funciones.fecha_convertir_string(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,19).toString(),date_cotizar1);
        cmb_plazoentrega1.setSelectedItem(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,20).toString());
        txt_diasplazo1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,11).toString());
        cmb_condicionpago1.setSelectedItem(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,12).toString());
        
        if(!frm_ordendecompra.table_posicioncompra.getValueAt(posicion,21).toString().equals("Seleccione...")){
            chk_flete1.setSelected(true);
            cmb_tipotransporte1.setSelectedItem(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,21).toString());
            txt_diasflete1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,22).toString());
            txt_costoflete1.setText(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,23).toString());   
        }
   
        if (frm_ordendecompra.table_posicioncompra.getValueAt(posicion,29).equals("true")){
            chk_recomendacion1.setSelected(true);
         }
         else{
           chk_recomendacion1.setSelected(false);
         }
        
        
        if(cmb_plazoentrega1.getSelectedItem().equals("ENTREGA SUJETA A PLAZO(DÍAS)")){
            txt_diasplazo1.setEnabled(true);
            txt_diasplazo1.requestFocusInWindow();
        }
         
        if (chk_flete1.isSelected()){
            cmb_tipotransporte1.setEnabled(true);
            txt_diasflete1.setEnabled(true);
            txt_costoflete1.setEnabled(true);
            cmb_monedacosto1.setEnabled(true);
        }
        
        if(frm_ordendecompra.table_posicioncompra.getValueAt(posicion,13).toString().trim().equals("")){
            destinoArchivo1 = "";
        }
        else{
            destinoArchivo1 = frm_ordendecompra.table_posicioncompra.getValueAt(posicion,13).toString().trim();
        }
         
        
        
    }//GEN-LAST:event_formWindowOpened

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
         String fecha_cotizacion;
        String fecha_carga_compras;
        ctrl_cotizacion cotizacion = null;
        class_cotizacion modelo_cotizacion = null;
        boolean validadoflete = false;
        boolean diasplazo = false;
       
        Boolean errorguardar = false;
        Integer fila;
        
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
        
        fila = frm_ordendecompra.table_resumenordendecompra.getSelectedRow();
       
        
            ctrl_usuario usuario = new ctrl_usuario(
                      Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                       "", 
                       "", 
                       "", 
                       "", 
                       0, 
                       "",
                       0,
                       "",
                       0,
                       true,
                       ""
            );

            modelo_usuario = usuario.buscar_usuario();
            
            respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR ACTUALIZAR LA ORDEN DE COMPRA, DESEA CONTINUAR?");
        
            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
            
                                if(Integer.parseInt(spin_cantidad1.getText().toString()) <= Integer.parseInt(lbl_descantidad.getText().trim())){


                                    fecha_carga_compras = funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2);



                                        /*if (destinoArchivo1.trim().equals("")) {
                                            JOptionPane.showMessageDialog(null,"INGRESAR EL DOCUMENTO DE COTIZACIÓN");
                                            errorguardar = true;
                                        }*/

                                        if (chk_flete1.isSelected()){
                                            if(!cmb_tipotransporte1.getSelectedItem().equals("Seleccione...") && 
                                               !txt_diasflete1.getText().trim().equals("") &&
                                               !cmb_monedacosto1.getSelectedItem().equals("Seleccione...") &&     
                                               !txt_costoflete1.getText().trim().equals("")){

                                                validadoflete = true;

                                            }
                                        }
                                        else{
                                            validadoflete = true;
                                            cmb_monedacosto1.setSelectedIndex(1);
                                        }

                                        if(!cmb_plazoentrega1.getSelectedItem().equals("Seleccione...")){
                                           if(cmb_plazoentrega1.getSelectedItem().equals("ENTREGA INMEDIATA")){
                                               txt_diasplazo1.setText("0");
                                               diasplazo = true;
                                           } 
                                           else{
                                               if(!txt_diasplazo1.getText().trim().equals("")){
                                                    diasplazo = true;
                                               } 
                                           }
                                        }


                                         fecha_cotizacion = funciones.fecha_convertir_date(date_cotizar1, 1);

                                        if ( !txt_rif1.getText().trim().equals("") &&
                                            !txt_preciounitario1.getText().trim().equals("") &&
                                            !cmb_condicionpago1.getSelectedItem().equals("Seleccione...") &&    
                                            !fecha_cotizacion.equals("") &&
                                            !cmb_moneda1.getSelectedItem().equals("Seleccione...") && 
                                            diasplazo &&   
                                            !errorguardar &&    
                                            validadoflete){

                                            cotizacion = new ctrl_cotizacion(
                                               Integer.parseInt(txt_idcotizacion.getText().trim()), 
                                               Integer.parseInt(txt_idproveedor.getText().trim()), 
                                               "", 
                                               "", 
                                               0, 
                                               0, 
                                               0, 
                                               Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()), 
                                               Integer.parseInt(cmb_moneda1.getSelectedItem().toString().substring(0,3).trim()), 
                                               Integer.parseInt(spin_cantidad1.getText()),
                                               Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario1.getText(),false)), 
                                               Double.parseDouble(funciones.separadormilesflotante(txt_total1.getText(),false)), 
                                               fecha_cotizacion, 
                                               cmb_plazoentrega1.getSelectedItem().toString(), //tipo plazo entrega
                                               Integer.parseInt(txt_diasplazo1.getText()), //dias plazoentrega
                                               cmb_condicionpago1.getSelectedItem().toString(), //condicion de pago
                                               cmb_tipotransporte1.getSelectedItem().toString(), //tipotransporte
                                               Integer.parseInt(txt_diasflete1.getText()), //diasflete
                                               Double.parseDouble(funciones.separadormilesflotante(txt_costoflete1.getText(),false)),  //costoflete
                                               Integer.parseInt(cmb_monedacosto1.getSelectedItem().toString().substring(0,3).trim()), //codigomonedaflete
                                               destinoArchivo1.trim(), //fotocotizacion
                                                "", //justificacion
                                                "", //observacion    
                                               chk_recomendacion1.isSelected(), 
                                               false, 
                                               "", 
                                               false, 
                                               "", 
                                               false, 
                                               Integer.parseInt(frm_ordendecompra.table_resumenordendecompra.getValueAt(fila, 0).toString()),
                                               fecha_carga_compras,     
                                               true
                                            );       


                                        //try {
                                            //if(cotizacion.consultar_posicion()){

                                                modelo_cotizacion = cotizacion.actualizar_posicion_oc();

                                                if (modelo_cotizacion.isStatus()){
                                                    JOptionPane.showMessageDialog(null,"DATOS ACTUALIZADOS SATISFACTORIAMENTE");
                                                    frm_ordendecompra.bot_reiniciar.doClick();
                                                    this.dispose();
                                                }   
                                            //}
                                            //else{
                                            //    JOptionPane.showMessageDialog(null,"LA COTIZACION ESTA BLOQUEADA, ESTA APROBADA POR PROCURA");
                                            //    frm_actualizarcotizacion.bot_reiniciar.doClick();
                                            //    this.dispose();
                                            //}
                                        //} catch (SQLException ex) {

                                        //}

                                    }
                                    else{
                                        JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS");
                                    }
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "LA CANTIDAD ES SUPERIOR A LA CANTIDAD CONFORMADA");
                                }
                        }
                        else{

                            JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        } 
                }
                else{
                    JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                }
            }         
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void txt_preciounitario1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_preciounitario1KeyReleased
        String monto = null;

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){
            monto = String.valueOf(Double.parseDouble(txt_preciounitario1.getText().trim()) * Integer.parseInt(spin_cantidad1.getText().toString()));
            txt_total1.setText(monto);
        }
        else{

            JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
            txt_preciounitario1.setText("");
            txt_total1.setText("");

        }
    }//GEN-LAST:event_txt_preciounitario1KeyReleased

    private void txt_diasplazo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diasplazo1KeyReleased

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){
        }
        else{

            JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
            txt_diasplazo1.setText("");

        }
    }//GEN-LAST:event_txt_diasplazo1KeyReleased

    private void cmb_plazoentrega1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_plazoentrega1ActionPerformed
        if (evt.getModifiers() != 0){
            if(cmb_plazoentrega1.getSelectedItem().equals("ENTREGA SUJETA A PLAZO(DÍAS)")){
                txt_diasplazo1.setEnabled(true);
                txt_diasplazo1.requestFocusInWindow();
            }
            else{
                txt_diasplazo1.setText("0");
                txt_diasplazo1.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmb_plazoentrega1ActionPerformed

    private void chk_flete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_flete1ActionPerformed
        if (chk_flete1.isSelected()){
            cmb_tipotransporte1.setEnabled(true);
            txt_diasflete1.setEnabled(true);
            txt_costoflete1.setEnabled(true);
            cmb_monedacosto1.setEnabled(true);
        }
        else{
            cmb_tipotransporte1.setEnabled(false);
            txt_diasflete1.setEnabled(false);
            txt_costoflete1.setEnabled(false);
            cmb_monedacosto1.setEnabled(false);
        }
    }//GEN-LAST:event_chk_flete1ActionPerformed

    private void cmb_tipotransporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipotransporte1ActionPerformed
        if (evt.getModifiers() != 0){
            if(!cmb_tipotransporte1.getSelectedItem().equals("Seleccione...")){
                txt_diasflete1.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_cmb_tipotransporte1ActionPerformed

    private void txt_diasflete1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diasflete1KeyReleased
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){
        }
        else{

            JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
            txt_diasflete1.setText("");

        }
    }//GEN-LAST:event_txt_diasflete1KeyReleased

    private void txt_costoflete1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_costoflete1KeyReleased
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){
        }
        else{

            JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
            txt_costoflete1.setText("");

        }
    }//GEN-LAST:event_txt_costoflete1KeyReleased

    private void cmb_monedacosto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_monedacosto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_monedacosto1ActionPerformed

    private void bot_verdocumetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdocumetoActionPerformed
       
       String referencia;
       
       URI url;
       
       referencia = destinoArchivo1;
       
       try{
            File archivo = new File(referencia);
            Desktop.getDesktop().open(archivo);
       }
       catch(IOException | IllegalArgumentException e){
            Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
            if ( desktop != null && desktop.isSupported(Desktop.Action.BROWSE) ) {
                try {
                    url = new URI(referencia);
                    desktop.browse(url);
                } catch ( IOException | URISyntaxException ex ) {
                    JOptionPane.showMessageDialog(null, "ERROR ABRIR COTIZACIÓN. " + ex.getMessage());
                }
            }    
            
       }        
    }//GEN-LAST:event_bot_verdocumetoActionPerformed

    private void cmb_moneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_moneda1ActionPerformed
        if (evt.getModifiers() != 0){
            if (!cmb_moneda1.getSelectedItem().equals("Seleccione...")){
                lbl_moneda1.setText(cmb_moneda1.getSelectedItem().toString().substring(5, cmb_moneda1.getSelectedItem().toString().length()));
            }
            else{
                lbl_moneda1.setText("");
            }
        }
    }//GEN-LAST:event_cmb_moneda1ActionPerformed

    private void bot_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_crearActionPerformed
       frm_proveedor frm = new frm_proveedor(1);
       frm.setVisible(true);
    }//GEN-LAST:event_bot_crearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_detalleact_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_detalleact_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_detalleact_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_detalleact_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_detalleact_cotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_crear;
    private javax.swing.JButton bot_verdocumeto;
    private javax.swing.JCheckBox chk_flete1;
    private javax.swing.JCheckBox chk_recomendacion1;
    private javax.swing.JComboBox<String> cmb_condicionpago1;
    private javax.swing.JComboBox<String> cmb_moneda1;
    private javax.swing.JComboBox<String> cmb_monedacosto1;
    private javax.swing.JComboBox<String> cmb_plazoentrega1;
    private javax.swing.JComboBox<String> cmb_tipotransporte1;
    private com.toedter.calendar.JDateChooser date_cotizar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_adjuntar1;
    private javax.swing.JLabel lbl_cantidad1;
    private javax.swing.JLabel lbl_cantidadautorizada;
    private javax.swing.JLabel lbl_cantidaddias1;
    private javax.swing.JLabel lbl_condicionpago1;
    private javax.swing.JLabel lbl_costoflete1;
    private javax.swing.JLabel lbl_descantidad;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_desidmaterial;
    private javax.swing.JLabel lbl_desmaterial;
    private javax.swing.JLabel lbl_diasflete1;
    private javax.swing.JLabel lbl_diasplazoentrega1;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_fechacotizacion1;
    private javax.swing.JLabel lbl_idmaterial;
    private javax.swing.JLabel lbl_idsolicitud;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_moneda1;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_plazoentrega1;
    private javax.swing.JLabel lbl_preciounitario1;
    private javax.swing.JLabel lbl_proveedor1;
    private javax.swing.JLabel lbl_tipotransporte1;
    private javax.swing.JLabel lbl_total1;
    private javax.swing.JLabel lbl_und1;
    private javax.swing.JPanel panel_alternativa1;
    private javax.swing.JTextField spin_cantidad1;
    private javax.swing.JTextField txt_costoflete1;
    protected static javax.swing.JTextField txt_descripcionprov1;
    private javax.swing.JTextField txt_diasflete1;
    private javax.swing.JTextField txt_diasplazo1;
    private javax.swing.JTextField txt_idcotizacion;
    protected static javax.swing.JTextField txt_idproveedor;
    private javax.swing.JTextField txt_preciounitario1;
    protected static javax.swing.JTextField txt_rif1;
    private javax.swing.JTextField txt_total1;
    // End of variables declaration//GEN-END:variables
}
