/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import controlador.ctrl_entrada;
import controlador.ctrl_salida;
import formatos_pdf.pdf_recepcion;
import formatos_pdf.pdf_salida;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class frm_detallemovimientosalida extends javax.swing.JFrame {

    /**
     * Creates new form frm_detallemovimientoentrada
     */
    
    public frm_detallemovimientosalida() {
        initComponents();
        this.setTitle("SISTIMACA - HISTORIAL DE SALIDAS DE MATERIAL");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setLocationRelativeTo(null);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("SISTIMACA - DETALLES ENTRADA DE MATERIAL");
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_documento = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detallematerial = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_verdocumento = new javax.swing.JButton();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_nrodocumento = new javax.swing.JTextField();
        txt_nromaterial = new javax.swing.JTextField();
        txt_descripcionmaterial = new javax.swing.JTextField();
        lbl_codigo1 = new javax.swing.JLabel();
        lbl_codigo2 = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        date_desde = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_documento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_documento.setText("NRO DE DOCUMENTO");
        getContentPane().add(lbl_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codigo.setText("FECHA HASTA");
        getContentPane().add(lbl_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        table_detallematerial.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_detallematerial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DOCUMENTO", "NRO MATERIAL", "DESCRIPCIÓN", "POSICIÓN", "CANTIDAD", "UMB", "FECHA DE DESPACHO", "PROYECTO", "ALMACÉN", "UBICACIÓN", "DESTINO", "COD. MOV", "justificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detallematerial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_detallematerialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_detallematerial);
        if (table_detallematerial.getColumnModel().getColumnCount() > 0) {
            table_detallematerial.getColumnModel().getColumn(0).setMinWidth(80);
            table_detallematerial.getColumnModel().getColumn(0).setPreferredWidth(80);
            table_detallematerial.getColumnModel().getColumn(0).setMaxWidth(80);
            table_detallematerial.getColumnModel().getColumn(1).setMinWidth(100);
            table_detallematerial.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_detallematerial.getColumnModel().getColumn(1).setMaxWidth(100);
            table_detallematerial.getColumnModel().getColumn(2).setMinWidth(200);
            table_detallematerial.getColumnModel().getColumn(2).setPreferredWidth(200);
            table_detallematerial.getColumnModel().getColumn(2).setMaxWidth(200);
            table_detallematerial.getColumnModel().getColumn(3).setMinWidth(80);
            table_detallematerial.getColumnModel().getColumn(3).setPreferredWidth(80);
            table_detallematerial.getColumnModel().getColumn(3).setMaxWidth(80);
            table_detallematerial.getColumnModel().getColumn(5).setMinWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setMaxWidth(50);
            table_detallematerial.getColumnModel().getColumn(7).setMinWidth(200);
            table_detallematerial.getColumnModel().getColumn(7).setPreferredWidth(200);
            table_detallematerial.getColumnModel().getColumn(7).setMaxWidth(200);
            table_detallematerial.getColumnModel().getColumn(12).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(12).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(12).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1320, 490));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("DETALLE SALIDAS DE MATERIAL");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 260, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1200, 10, 110, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(790, 10, 240, 17);

        lbl_nombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(790, 30, 240, 17);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1070, 10, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 60));

        bot_verdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_verdocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        bot_verdocumento.setText("VER DOCUMENTO");
        bot_verdocumento.setEnabled(false);
        bot_verdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_verdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, -1, -1));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        txt_nrodocumento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nrodocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nrodocumentoKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nrodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, -1));

        txt_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 160, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 160, -1));

        lbl_codigo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codigo1.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbl_codigo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codigo2.setText("FECHA DESDE");
        getContentPane().add(lbl_codigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        date_hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_hastaPropertyChange(evt);
            }
        });
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 130, -1));

        date_desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_desdePropertyChange(evt);
            }
        });
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                 
 /*           ctrl_salida salida  = new ctrl_salida(
                    0, 
                    0, 
                    0,//NUMERO DE MATERIAL
                    "", //descripcion material
                    0,//CEDULA 
                    "",//NOMBRES 
                    0,//ID ALMACEN
                    "",//DESCRIPCION ALMACEN
                    0,//ID UBICACION
                    "",//DESCRIPCION UBICACION
                    "",//FECHA SALIDA
                    0,//ID PROYECTO
                    3,//CLASE DE MOVIMIENTO
                    0, //documento 
                    0,//CANTIDAD A DESPACHAR
                    "",//DESTINO 
                    "", //justificacion
                    true //STATUS
                           
            ); 

                
             salida.consultar_salida_material_almacen("","",table_detallematerial);*/
    }//GEN-LAST:event_formWindowOpened

    private void bot_verdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdocumentoActionPerformed
        Integer fila;
        Integer documento;
        
        fila = table_detallematerial.getSelectedRow();
        
        documento = Integer.parseInt(table_detallematerial.getValueAt(fila, 0).toString());
        
        try {
            pdf_salida.dato("\\\\192.168.0.3\\dist\\Documentos_SisTimaca",documento,"");
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(frm_entradaexpress.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_entradaexpress.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bot_verdocumentoActionPerformed

    private void table_detallematerialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detallematerialMouseClicked
       bot_verdocumento.setEnabled(true);
    }//GEN-LAST:event_table_detallematerialMouseClicked

    private void txt_nromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialKeyReleased
        String fechadesde;
        String fechahasta;

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            if((txt_nromaterial.getText().trim().length() > 7) && (!txt_nromaterial.getText().trim().equals(""))){
                    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
                    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);

                    ctrl_salida salida  = new ctrl_salida(
                            0, 
                            0, 
                            Integer.parseInt(txt_nromaterial.getText().trim()),//NUMERO DE MATERIAL
                            "", //descripcion material
                            0,//CEDULA 
                            "",//NOMBRES 
                            0,//ID ALMACEN
                            "",//DESCRIPCION ALMACEN
                            0,//ID UBICACION
                            "",//DESCRIPCION UBICACION
                            "",//FECHA SALIDA
                            0,//ID PROYECTO
                            3,//CLASE DE MOVIMIENTO
                            0, //documento 
                            0,//CANTIDAD A DESPACHAR
                            "",//DESTINO 
                            "", //justificacion
                            true //STATUS

                    ); 


                     salida.consultar_salida_material_almacen(fechadesde,fechahasta,table_detallematerial);

               
            }

        }
        else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA", JOptionPane.ERROR_MESSAGE,null);
                txt_nromaterial.setText("");
               
        }     
         bot_verdocumento.setEnabled(false);
    }//GEN-LAST:event_txt_nromaterialKeyReleased

    private void txt_nrodocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nrodocumentoKeyReleased
        String fechadesde;
        String fechahasta;
        
         if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
       
             if((txt_nrodocumento.getText().trim().length() > 7) && (!txt_nrodocumento.getText().trim().equals(""))){
                    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
                    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);

                    ctrl_salida salida  = new ctrl_salida(
                            0, 
                            0, 
                            Integer.parseInt(txt_nromaterial.getText().trim()),//NUMERO DE MATERIAL
                            "", //descripcion material
                            0,//CEDULA 
                            "",//NOMBRES 
                            0,//ID ALMACEN
                            "",//DESCRIPCION ALMACEN
                            0,//ID UBICACION
                            "",//DESCRIPCION UBICACION
                            "",//FECHA SALIDA
                            0,//ID PROYECTO
                            3,//CLASE DE MOVIMIENTO
                            Integer.parseInt(txt_nrodocumento.getText().trim()), //documento 
                            0,//CANTIDAD A DESPACHAR
                            "",//DESTINO 
                            "", //justificacion
                            true //STATUS

                    ); 

                    salida.consultar_salida_material_almacen(fechadesde,fechahasta,table_detallematerial);
             }
            
       }
        else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA", JOptionPane.ERROR_MESSAGE,null);
                txt_nrodocumento.setText("");
        }        
                bot_verdocumento.setEnabled(false);
    }//GEN-LAST:event_txt_nrodocumentoKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
        String fechadesde;
        String fechahasta;
        
                    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
                    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);

                     ctrl_salida salida  = new ctrl_salida(
                            0, 
                            0, 
                            0,//NUMERO DE MATERIAL
                            txt_descripcionmaterial.getText().trim(), //descripcion material
                            0,//CEDULA 
                            "",//NOMBRES 
                            0,//ID ALMACEN
                            "",//DESCRIPCION ALMACEN
                            0,//ID UBICACION
                            "",//DESCRIPCION UBICACION
                            "",//FECHA SALIDA
                            0,//ID PROYECTO
                            3,//CLASE DE MOVIMIENTO
                            0, //documento 
                            0,//CANTIDAD A DESPACHAR
                            "",//DESTINO 
                            "", //justificacion
                            true //STATUS

                    ); 

                    salida.consultar_salida_material_almacen(fechadesde,fechahasta,table_detallematerial);
                
                bot_verdocumento.setEnabled(false);

    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void date_desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_desdePropertyChange
        String fechadesde;
        String fechahasta;
        Integer nromaterial;
        Integer nrodocumento;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
        
          
            try{
                 nromaterial = Integer.parseInt(txt_nromaterial.getText().trim());
            }
            catch(NumberFormatException ex){
                nromaterial = 0;
            }
 
            try{
                 nrodocumento = Integer.parseInt(txt_nrodocumento.getText().trim());
            }
            catch(NumberFormatException ex){
                nrodocumento = 0;
            }           
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                      ctrl_salida salida  = new ctrl_salida(
                            0, 
                            0, 
                            nromaterial,//NUMERO DE MATERIAL
                            txt_descripcionmaterial.getText().trim(), //descripcion material
                            0,//CEDULA 
                            "",//NOMBRES 
                            0,//ID ALMACEN
                            "",//DESCRIPCION ALMACEN
                            0,//ID UBICACION
                            "",//DESCRIPCION UBICACION
                            "",//FECHA SALIDA
                            0,//ID PROYECTO
                            3,//CLASE DE MOVIMIENTO
                            nrodocumento, //documento 
                            0,//CANTIDAD A DESPACHAR
                            "",//DESTINO 
                            "", //justificacion
                            true //STATUS

                    ); 

                    salida.consultar_salida_material_almacen(fechadesde,fechahasta,table_detallematerial);
                                
                
            }

             bot_verdocumento.setEnabled(false);
    }//GEN-LAST:event_date_desdePropertyChange

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_detallemovimientosalida frm = new frm_detallemovimientosalida();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void date_hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_hastaPropertyChange
        String fechadesde;
        String fechahasta;
        Integer nromaterial;
        Integer nrodocumento;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
        
            try{
                 nromaterial = Integer.parseInt(txt_nromaterial.getText().trim());
            }
            catch(NumberFormatException ex){
                nromaterial = 0;
            }
 
            try{
                 nrodocumento = Integer.parseInt(txt_nrodocumento.getText().trim());
            }
            catch(NumberFormatException ex){
                nrodocumento = 0;
            }
             
            
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                      ctrl_salida salida  = new ctrl_salida(
                            0, 
                            0, 
                            nromaterial,//NUMERO DE MATERIAL
                            txt_descripcionmaterial.getText().trim(), //descripcion material
                            0,//CEDULA 
                            "",//NOMBRES 
                            0,//ID ALMACEN
                            "",//DESCRIPCION ALMACEN
                            0,//ID UBICACION
                            "",//DESCRIPCION UBICACION
                            "",//FECHA SALIDA
                            0,//ID PROYECTO
                            3,//CLASE DE MOVIMIENTO
                            nrodocumento, //documento 
                            0,//CANTIDAD A DESPACHAR
                            "",//DESTINO 
                            "", //justificacion
                            true //STATUS

                    ); 

                    salida.consultar_salida_material_almacen(fechadesde,fechahasta,table_detallematerial);
                                
                
            }

  
             bot_verdocumento.setEnabled(false);
    }//GEN-LAST:event_date_hastaPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientosalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientosalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientosalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientosalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_detallemovimientosalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_verdocumento;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_codigo1;
    private javax.swing.JLabel lbl_codigo2;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_documento;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable table_detallematerial;
    private javax.swing.JTextField txt_descripcionmaterial;
    private javax.swing.JTextField txt_nrodocumento;
    private javax.swing.JTextField txt_nromaterial;
    // End of variables declaration//GEN-END:variables
}
