/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



import controlador.ctrl_area;

import controlador.ctrl_comun;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import model.class_area;
import javax.swing.UIManager;


/**
 *
 * @author ruben
 */
public class frm_area extends javax.swing.JFrame {

    /**
     * Creates new form frm_centrocosto
     */
    public frm_area() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - EMPRESA");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setExtendedState(MAXIMIZED_BOTH);

        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        table_area = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        radio_creararea = new javax.swing.JRadioButton();
        lbl_area = new javax.swing.JLabel();
        txt_idarea = new javax.swing.JTextField();
        lbl_desarea = new javax.swing.JLabel();
        txt_area = new javax.swing.JTextField();
        bot_crear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radio_actualizararea = new javax.swing.JRadioButton();
        lbl_desnuevoarea = new javax.swing.JLabel();
        lbl_nuevaarea = new javax.swing.JLabel();
        txt_nuevaarea = new javax.swing.JTextField();
        cmb_area = new javax.swing.JComboBox();
        lbl_nuevoidarea1 = new javax.swing.JLabel();
        txt_nuevoidarea = new javax.swing.JTextField();
        bot_actualizar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_area.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIPCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_area);
        if (table_area.getColumnModel().getColumnCount() > 0) {
            table_area.getColumnModel().getColumn(0).setMinWidth(100);
            table_area.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_area.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 520, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_creararea.setBackground(new java.awt.Color(255, 255, 255));
        radio_creararea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radio_creararea.setSelected(true);
        radio_creararea.setText("CREAR ÁREAS");
        radio_creararea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_crearareaActionPerformed(evt);
            }
        });
        jPanel1.add(radio_creararea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_area.setBackground(new java.awt.Color(240, 255, 255));
        lbl_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_area.setText("ID ÁREA");
        jPanel1.add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        txt_idarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_area, org.jdesktop.beansbinding.ObjectProperty.create(), txt_idarea, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_idarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idareaKeyReleased(evt);
            }
        });
        jPanel1.add(txt_idarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));

        lbl_desarea.setBackground(new java.awt.Color(240, 255, 255));
        lbl_desarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_desarea.setText("DESCRIPCIÓN ÁREA");
        jPanel1.add(lbl_desarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txt_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JTextField(), org.jdesktop.beansbinding.ObjectProperty.create(), txt_area, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_areaKeyPressed(evt);
            }
        });
        jPanel1.add(txt_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, -1));

        bot_crear.setBackground(new java.awt.Color(240, 255, 255));
        bot_crear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        bot_crear.setText("CREAR");
        bot_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_crearActionPerformed(evt);
            }
        });
        jPanel1.add(bot_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 770, 180));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_actualizararea.setBackground(new java.awt.Color(255, 255, 255));
        radio_actualizararea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radio_actualizararea.setText("ACTUALIZAR ÁREA");
        radio_actualizararea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_actualizarareaActionPerformed(evt);
            }
        });
        jPanel2.add(radio_actualizararea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lbl_desnuevoarea.setBackground(new java.awt.Color(240, 255, 255));
        lbl_desnuevoarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_desnuevoarea.setText("ÁREA");
        jPanel2.add(lbl_desnuevoarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_nuevaarea.setBackground(new java.awt.Color(240, 255, 255));
        lbl_nuevaarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nuevaarea.setText("NUEVA DESCRIPCION ÁREA");
        jPanel2.add(lbl_nuevaarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txt_nuevaarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nuevaarea.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JTextField(), org.jdesktop.beansbinding.ObjectProperty.create(), txt_nuevaarea, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_nuevaarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nuevaareaActionPerformed(evt);
            }
        });
        txt_nuevaarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nuevaareaKeyPressed(evt);
            }
        });
        jPanel2.add(txt_nuevaarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, -1));

        cmb_area.setBackground(new java.awt.Color(240, 255, 255));
        cmb_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_area.setEnabled(false);
        cmb_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_areaActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, -1));

        lbl_nuevoidarea1.setBackground(new java.awt.Color(240, 255, 255));
        lbl_nuevoidarea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nuevoidarea1.setText("NUEVO ID ÁREA");
        jPanel2.add(lbl_nuevoidarea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txt_nuevoidarea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nuevoidarea.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_nuevaarea, org.jdesktop.beansbinding.ObjectProperty.create(), txt_nuevoidarea, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_nuevoidarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nuevoidareaKeyReleased(evt);
            }
        });
        jPanel2.add(txt_nuevoidarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, -1));

        bot_actualizar.setBackground(new java.awt.Color(240, 255, 255));
        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 170, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 770, 200));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("ADMINISTRACIÓN ÁREAS");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 200, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 30);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 100, 30);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(920, 10, 180, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(922, 30, 180, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_crearActionPerformed
      class_area modelo_area;
      ctrl_comun control;
        
        if(!txt_idarea.getText().trim().equals("") && !txt_area.getText().trim().equals("") ) {
               
                ctrl_area area = new ctrl_area(Integer.parseInt(txt_idarea.getText()),txt_area.getText(),1,0);
                               
                modelo_area = area.actualizar_area();
                
                if (modelo_area.isStatus()){
                    
                   area.consulta_area(table_area);
                         
                   control = new ctrl_comun(2); 
                   cmb_area =  control.cargar_combo(cmb_area,txt_area.getText().toUpperCase().trim());
                   
                }
                
        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        } 
           
    }//GEN-LAST:event_bot_crearActionPerformed

    private void radio_crearareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_crearareaActionPerformed
        txt_idarea.setEnabled(true);
        txt_area.setEnabled(true);
        bot_crear.setEnabled(true);
        cmb_area.setEnabled(false);
        txt_nuevaarea.setEnabled(false);
        
        bot_actualizar.setEnabled(false);
        radio_actualizararea.setSelected(false);
        jPanel2.setBackground(new Color(250,250,250));
        jPanel1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_radio_crearareaActionPerformed

    private void radio_actualizarareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_actualizarareaActionPerformed
        txt_idarea.setText("");
        txt_idarea.setEnabled(false);
        txt_area.setText("");
        txt_area.setEnabled(false);
        bot_crear.setEnabled(false);
        cmb_area.setEnabled(true);
        txt_nuevaarea.setEnabled(true);
        txt_nuevoidarea.setEnabled(true);
        txt_nuevoidarea.setText("");
        
        bot_actualizar.setEnabled(true);
        radio_creararea.setSelected(false);
        jPanel1.setBackground(new Color(250,250,250));
        jPanel2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_radio_actualizarareaActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
       
        class_area modelo_area= null; 
        ctrl_comun control;
        boolean resp = true;
       
        
        if(!txt_nuevaarea.getText().equals("") && !cmb_area.getSelectedItem().equals("Seleccione...")  ) {

           
            
            /*if (!txt_cedularesponsablenuevo.getText().equals(cmb_area.getSelectedItem().toString().substring(0,3).trim())){
                
                ctrl_area area = new ctrl_area(Integer.parseInt(txt_cedularesponsablenuevo.getText()),"",0,0);
                
                modelo_area = area.buscaridarea();
                
                resp =  modelo_area.isStatus();
            }
            
            if (resp){*/
                
                ctrl_area area = new ctrl_area(Integer.parseInt(txt_nuevoidarea.getText()),txt_nuevaarea.getText(),0,Integer.parseInt(cmb_area.getSelectedItem().toString().substring(0,3).trim()));
                
                modelo_area = area.actualizar_area_detalle();

                if (modelo_area.isStatus()){
                    
                    area.consulta_area(table_area);
                                                    
                    control = new ctrl_comun(2); 
                    cmb_area =  control.cargar_combo(cmb_area,txt_area.getText().toUpperCase().trim());
                    
                    txt_nuevaarea.setText("");
                    
                    
                                   
                }
            //}
        }
        else{

            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
      
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_area area = new ctrl_area(0,"",0,0);
        area.consulta_area(table_area);
         
        ctrl_comun control = new ctrl_comun(2);
        cmb_area =  control.cargar_combo(cmb_area,"Seleccione...");
        
        txt_idarea.requestFocusInWindow();
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_areaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_areaKeyPressed
        if (evt.getKeyCode()==10){
            bot_crear.doClick();
        }
        
        if (evt.getKeyCode() == 27){
         
            bot_reiniciar.doClick();
                    
        }
    }//GEN-LAST:event_txt_areaKeyPressed

    private void txt_nuevaareaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nuevaareaKeyPressed
       if (evt.getKeyCode()==10){
            bot_actualizar.doClick();
        }
        
        if (evt.getKeyCode() == 27){
         
            bot_reiniciar.doClick();
                    
        }
    }//GEN-LAST:event_txt_nuevaareaKeyPressed

    private void cmb_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_areaActionPerformed
       
       if(evt.getModifiers() != 0){
            if (cmb_area.getSelectedItem().equals("Seleccione...")){
                txt_nuevaarea.setText("");
            }
            else{
                txt_nuevoidarea.setText(cmb_area.getSelectedItem().toString().substring(0,3).trim());
                txt_nuevaarea.setText(cmb_area.getSelectedItem().toString().substring(5,cmb_area.getSelectedItem().toString().length()).trim());
                
            }
        }
        
    }//GEN-LAST:event_cmb_areaActionPerformed

    private void txt_nuevaareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nuevaareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nuevaareaActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
       frm_area frm = new frm_area();
       frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void txt_idareaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idareaKeyReleased
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_idarea.setText("");
             }   
        }
    }//GEN-LAST:event_txt_idareaKeyReleased

    private void txt_nuevoidareaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nuevoidareaKeyReleased
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nuevoidarea.setText("");
             }   
        }
    }//GEN-LAST:event_txt_nuevoidareaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_area().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_crear;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox cmb_area;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_desarea;
    private javax.swing.JLabel lbl_desnuevoarea;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nuevaarea;
    private javax.swing.JLabel lbl_nuevoidarea1;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JRadioButton radio_actualizararea;
    private javax.swing.JRadioButton radio_creararea;
    private javax.swing.JTable table_area;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_idarea;
    private javax.swing.JTextField txt_nuevaarea;
    private javax.swing.JTextField txt_nuevoidarea;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
