/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_material;
import controlador.ctrl_umb;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.class_material;
import model.class_umb;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
/**
 *
 * @author ruben
 */
public class frm_material extends javax.swing.JFrame {

  
     private File fichero = null;
    public frm_material() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - MATERIAL");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        txt_ruta = new javax.swing.JTextField();
        panel_infogeneralmaterial = new javax.swing.JPanel();
        lbl_numeromaterial = new javax.swing.JLabel();
        lbl_codmaterialalterno = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        txt_numeromaterial = new javax.swing.JTextField();
        txt_codmaterialalterno = new javax.swing.JTextField();
        lbl_infogeneralmaterial = new javax.swing.JLabel();
        lbl_desmaterial1 = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        txt_desmaterial = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        lbl_clasematerial = new javax.swing.JLabel();
        cmb_clasematerial = new javax.swing.JComboBox();
        lbl_grupomaterial = new javax.swing.JLabel();
        cmb_grupoarticulo = new javax.swing.JComboBox();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        bot_buscarfoto = new javax.swing.JButton();
        lbl_grupomaterial1 = new javax.swing.JLabel();
        lbl_codigomaestromaterial = new javax.swing.JLabel();
        panel_infostockmaterial = new javax.swing.JPanel();
        lbl_stockinicialmaterial = new javax.swing.JLabel();
        lbl_stockminimomaterial = new javax.swing.JLabel();
        lbl_stockpedidomaterial = new javax.swing.JLabel();
        lbl_stockmaximo = new javax.swing.JLabel();
        lbl_unidadmedidamaterial = new javax.swing.JLabel();
        txt_stockinicialmaterial = new javax.swing.JTextField();
        txt_stockminimomaterial = new javax.swing.JTextField();
        txt_stockpedidomaterial = new javax.swing.JTextField();
        cmb_unidadmedidamaterial = new javax.swing.JComboBox();
        txt_stockmaximo = new javax.swing.JTextField();
        lbl_infostockmaterial = new javax.swing.JLabel();
        panel_observaciones = new javax.swing.JPanel();
        lbl_observaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_observaciones = new javax.swing.JTextArea();
        panel_usomaterial = new javax.swing.JPanel();
        lbl_usomaterial = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_usomaterial = new javax.swing.JTextArea();
        bot_agregarinventario = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_infogeneralmaterial.setBackground(new java.awt.Color(255, 255, 255));
        panel_infogeneralmaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_infogeneralmaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_numeromaterial.setText("NÚMERO DE MATERIAL");
        panel_infogeneralmaterial.add(lbl_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_codmaterialalterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codmaterialalterno.setText("CÓDIGO MATERIAL ALTERNO");
        panel_infogeneralmaterial.add(lbl_codmaterialalterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lbl_modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_modelo.setText("MODELO");
        panel_infogeneralmaterial.add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txt_modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_stockinicialmaterial, org.jdesktop.beansbinding.ObjectProperty.create(), txt_modelo, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_modeloKeyReleased(evt);
            }
        });
        panel_infogeneralmaterial.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 210, 30));

        txt_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_codmaterialalterno, org.jdesktop.beansbinding.ObjectProperty.create(), txt_numeromaterial, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_numeromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_numeromaterialKeyPressed(evt);
            }
        });
        panel_infogeneralmaterial.add(txt_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 210, 30));

        txt_codmaterialalterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_desmaterial, org.jdesktop.beansbinding.ObjectProperty.create(), txt_codmaterialalterno, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_codmaterialalterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codmaterialalternoKeyReleased(evt);
            }
        });
        panel_infogeneralmaterial.add(txt_codmaterialalterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 210, 30));

        lbl_infogeneralmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_infogeneralmaterial.setForeground(new java.awt.Color(0, 138, 218));
        lbl_infogeneralmaterial.setText("INFORMACIÓN GENERAL / CLASIFICACIÓN MATERIAL");
        panel_infogeneralmaterial.add(lbl_infogeneralmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lbl_desmaterial1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_desmaterial1.setText("DESCRIPCIÓN MATERIAL");
        panel_infogeneralmaterial.add(lbl_desmaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lbl_marca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_marca.setText("MARCA");
        panel_infogeneralmaterial.add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txt_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_marca, org.jdesktop.beansbinding.ObjectProperty.create(), txt_desmaterial, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_desmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_desmaterialKeyReleased(evt);
            }
        });
        panel_infogeneralmaterial.add(txt_desmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 300, 30));

        txt_marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_modelo, org.jdesktop.beansbinding.ObjectProperty.create(), txt_marca, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_marcaKeyReleased(evt);
            }
        });
        panel_infogeneralmaterial.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, 30));

        lbl_clasematerial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_clasematerial.setText("CLASE MATERIAL");
        panel_infogeneralmaterial.add(lbl_clasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cmb_clasematerial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_clasematerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_clasematerialActionPerformed(evt);
            }
        });
        panel_infogeneralmaterial.add(cmb_clasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 190, 30));

        lbl_grupomaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_grupomaterial.setText("CÓDIGO MAESTRO DEL MATERIAL");
        panel_infogeneralmaterial.add(lbl_grupomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        cmb_grupoarticulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_grupoarticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_grupoarticuloActionPerformed(evt);
            }
        });
        panel_infogeneralmaterial.add(cmb_grupoarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 570, 30));

        panel_foto.setBackground(new java.awt.Color(255, 255, 255));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 138, 218));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        panel_infogeneralmaterial.add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 210, 230));

        bot_buscarfoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_buscarfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscarfoto.setText("BUSCAR FOTO");
        bot_buscarfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarfotoActionPerformed(evt);
            }
        });
        panel_infogeneralmaterial.add(bot_buscarfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 160, 40));
        complemento.DisableBorderButton(bot_buscarfoto);

        lbl_grupomaterial1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_grupomaterial1.setText("GRUPO DE ARTÍCULO");
        panel_infogeneralmaterial.add(lbl_grupomaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        lbl_codigomaestromaterial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_codigomaestromaterial.setForeground(new java.awt.Color(255, 0, 0));
        panel_infogeneralmaterial.add(lbl_codigomaestromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        getContentPane().add(panel_infogeneralmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1060, 330));

        panel_infostockmaterial.setBackground(new java.awt.Color(255, 255, 255));
        panel_infostockmaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_infostockmaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_stockinicialmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_stockinicialmaterial.setText("STOCK INICIAL");
        panel_infostockmaterial.add(lbl_stockinicialmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        lbl_stockminimomaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_stockminimomaterial.setText("STOCK MÍNIMO");
        panel_infostockmaterial.add(lbl_stockminimomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        lbl_stockpedidomaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_stockpedidomaterial.setText("PUNTO DE PEDIDO");
        panel_infostockmaterial.add(lbl_stockpedidomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        lbl_stockmaximo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_stockmaximo.setText("STOCK MÁXIMO");
        panel_infostockmaterial.add(lbl_stockmaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        lbl_unidadmedidamaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_unidadmedidamaterial.setText("UNIDAD DE MEDIDA BASE (UMB)");
        panel_infostockmaterial.add(lbl_unidadmedidamaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        txt_stockinicialmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_stockpedidomaterial, org.jdesktop.beansbinding.ObjectProperty.create(), txt_stockinicialmaterial, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_stockinicialmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_stockinicialmaterialKeyPressed(evt);
            }
        });
        panel_infostockmaterial.add(txt_stockinicialmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 30));

        txt_stockminimomaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_stockminimomaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_stockminimomaterialKeyPressed(evt);
            }
        });
        panel_infostockmaterial.add(txt_stockminimomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 90, 30));

        txt_stockpedidomaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_stockmaximo, org.jdesktop.beansbinding.ObjectProperty.create(), txt_stockpedidomaterial, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_stockpedidomaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_stockpedidomaterialKeyPressed(evt);
            }
        });
        panel_infostockmaterial.add(txt_stockpedidomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 30));

        cmb_unidadmedidamaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_unidadmedidamaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_unidadmedidamaterialActionPerformed(evt);
            }
        });
        panel_infostockmaterial.add(cmb_unidadmedidamaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 150, 30));

        txt_stockmaximo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_stockminimomaterial, org.jdesktop.beansbinding.ObjectProperty.create(), txt_stockmaximo, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_stockmaximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_stockmaximoKeyPressed(evt);
            }
        });
        panel_infostockmaterial.add(txt_stockmaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 30));

        lbl_infostockmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_infostockmaterial.setForeground(new java.awt.Color(0, 138, 218));
        lbl_infostockmaterial.setText("INFORMACIÓN STOCK");
        panel_infostockmaterial.add(lbl_infostockmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        getContentPane().add(panel_infostockmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 480, 250));

        panel_observaciones.setBackground(new java.awt.Color(255, 255, 255));
        panel_observaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_observaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_observaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_observaciones.setForeground(new java.awt.Color(0, 138, 218));
        lbl_observaciones.setText("OBSERVACIONES");
        panel_observaciones.add(lbl_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        area_observaciones.setColumns(20);
        area_observaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_observaciones.setLineWrap(true);
        area_observaciones.setRows(5);
        area_observaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                area_observacionesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(area_observaciones);

        panel_observaciones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 530, -1));

        getContentPane().add(panel_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 560, 120));

        panel_usomaterial.setBackground(new java.awt.Color(255, 255, 255));
        panel_usomaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_usomaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_usomaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usomaterial.setForeground(new java.awt.Color(0, 138, 218));
        lbl_usomaterial.setText("USO MATERIAL");
        panel_usomaterial.add(lbl_usomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        area_usomaterial.setColumns(20);
        area_usomaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_usomaterial.setLineWrap(true);
        area_usomaterial.setRows(5);
        area_usomaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                area_usomaterialKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(area_usomaterial);

        panel_usomaterial.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 530, 90));

        getContentPane().add(panel_usomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 560, 130));

        bot_agregarinventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_agregarinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        bot_agregarinventario.setText("AGREGAR AL MAESTRO");
        bot_agregarinventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bot_agregarinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregarinventarioActionPerformed(evt);
            }
        });
        getContentPane().add(bot_agregarinventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, -1, 40));
        complemento.DisableBorderButton(bot_agregarinventario);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("CREAR MATERIAL");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(270, 10, 150, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1113, 20, 130, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 110, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(870, 10, 230, 17);

        lbl_nombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(872, 30, 230, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         
        
        ctrl_comun control = new ctrl_comun(9);
        cmb_clasematerial =  control.cargar_combo(cmb_clasematerial,"Seleccione...");
        
        control = new ctrl_comun(10);
        cmb_grupoarticulo =  control.cargar_combo(cmb_grupoarticulo,"Seleccione...");
        
        control = new ctrl_comun(13);
        cmb_unidadmedidamaterial =  control.cargar_combo(cmb_unidadmedidamaterial,"Seleccione...");
        
        ctrl_material material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);
        
         try {
             class_material modelo_material = material.consultar_numeromaterial();
             txt_numeromaterial.setText(modelo_material.getNumero_material().toString());
         } catch (SQLException ex) {
       
         }
        
        
        
        txt_numeromaterial.requestFocusInWindow();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void bot_buscarfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarfotoActionPerformed

        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.jpg", "jpg");
        file.setFileFilter(filtro);

        int seleccion = file.showOpenDialog(this);
        //Si el usuario, pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            //Seleccionamos el fichero
            lbl_foto.setIcon(null);

            fichero = file.getSelectedFile();
            //Ecribe la ruta del fichero seleccionado en el campo de texto
            txt_ruta.setText(fichero.getAbsolutePath());
            ImageIcon icon = new ImageIcon(fichero.toString());
            //System.out.println(fichero.getName());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(),lbl_foto.getHeight(), Image.SCALE_DEFAULT));
            lbl_foto.setIcon(icono);
        }
    }//GEN-LAST:event_bot_buscarfotoActionPerformed

    private void bot_agregarinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregarinventarioActionPerformed
        class_material modelo_material;
        ctrl_comun control;
        String image_string = null;

        if (!txt_ruta.getText().equals("")) {
            try {
                // TODO add your handling code here:
                BufferedImage img = ImageIO.read(new File(fichero.toString()));
                image_string = funciones.encodeToString(img);
                //guardar_imagen(image_string, fichero.getName());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"ERROR EN FOTO");
            }

        }

        if(!txt_numeromaterial.getText().equals("") && !txt_codmaterialalterno.getText().equals("") && !txt_desmaterial.getText().equals("") && !txt_marca.getText().equals("") && !txt_modelo.getText().equals("")
            && !txt_stockinicialmaterial.getText().equals("") && !txt_stockminimomaterial.getText().equals("") && !txt_stockpedidomaterial.getText().equals("") && !txt_stockmaximo.getText().equals("") && !cmb_unidadmedidamaterial.getSelectedItem().equals("Seleccione...")
            && !cmb_clasematerial.getSelectedItem().equals("Seleccione...") && !cmb_grupoarticulo.getSelectedItem().equals("Seleccione...")
            && !area_observaciones.getText().equals("") && !area_usomaterial.getText().equals("") ) {

            ctrl_material material = new ctrl_material(
                0,
                Integer.parseInt(txt_numeromaterial.getText().trim().toUpperCase()),
                txt_codmaterialalterno.getText().trim().toUpperCase(),
                image_string,
                txt_desmaterial.getText().trim().toUpperCase(),
                txt_marca.getText().trim().toUpperCase(),
                txt_modelo.getText().trim().toUpperCase(),
                Integer.parseInt(cmb_unidadmedidamaterial.getSelectedItem().toString().substring(0,3).trim()),
                cmb_unidadmedidamaterial.getSelectedItem().toString().substring(5, cmb_unidadmedidamaterial.getSelectedItem().toString().length()),
                Integer.parseInt(txt_stockinicialmaterial.getText().trim()),
                0,
                0,
                Integer.parseInt(txt_stockminimomaterial.getText().trim()),
                Integer.parseInt(txt_stockpedidomaterial.getText().trim()),
                Integer.parseInt(txt_stockmaximo.getText().trim()),
                0.0,
                0.0,
                funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2),
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                frm_principalM1.lbl_nombres.getText().trim(),
                0,
                0,
                area_observaciones.getText().trim(),
                area_usomaterial.getText().trim(),
                Integer.parseInt(cmb_clasematerial.getSelectedItem().toString().substring(0,3).trim()),
                cmb_clasematerial.getSelectedItem().toString().substring(5,cmb_clasematerial.getSelectedItem().toString().length()).trim(),
                Integer.parseInt(cmb_grupoarticulo.getSelectedItem().toString().substring(0,3).trim()),
                cmb_grupoarticulo.getSelectedItem().toString().substring(5,cmb_grupoarticulo.getSelectedItem().toString().length()).trim(),
                1,
                "VEB",
                "SIN UBICACION",
                1,
                "CENTRAL",
                1,
                "TIMACA",
                1,
                "STOCK NUEVO",
                true

            );

            modelo_material = material.actualizar_material();

            if (modelo_material.isStatus()){

            }

        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        }
    }//GEN-LAST:event_bot_agregarinventarioActionPerformed

    private void cmb_unidadmedidamaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_unidadmedidamaterialActionPerformed
        class_umb modelo_umb;
        
        if (evt.getModifiers() != 0){
            ctrl_umb umb = new ctrl_umb(Integer.parseInt(cmb_unidadmedidamaterial.getSelectedItem().toString().substring(0,3).trim()),"","");
            modelo_umb = umb.buscardescripcion();
        }
        
    }//GEN-LAST:event_cmb_unidadmedidamaterialActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_material frm = new frm_material();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void txt_numeromaterialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeromaterialKeyPressed
                        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
           if(txt_numeromaterial.getText().trim().length() > 7){
               txt_numeromaterial.setText(txt_numeromaterial.getText().trim().substring(0, 7));
           }
        
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numeromaterial.setText("");
                lbl_codigomaestromaterial.setText("");
             }   
        }
    }//GEN-LAST:event_txt_numeromaterialKeyPressed

    private void txt_stockinicialmaterialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stockinicialmaterialKeyPressed
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_stockinicialmaterial.setText("");
             }   
        }
    }//GEN-LAST:event_txt_stockinicialmaterialKeyPressed

    private void txt_stockpedidomaterialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stockpedidomaterialKeyPressed
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_stockpedidomaterial.setText("");
             }   
        }
    }//GEN-LAST:event_txt_stockpedidomaterialKeyPressed

    private void txt_stockmaximoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stockmaximoKeyPressed
            if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_stockmaximo.setText("");
             }   
        }
    }//GEN-LAST:event_txt_stockmaximoKeyPressed

    private void txt_stockminimomaterialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stockminimomaterialKeyPressed
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_stockminimomaterial.setText("");
             }   
        }
    }//GEN-LAST:event_txt_stockminimomaterialKeyPressed

    private void cmb_clasematerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_clasematerialActionPerformed
            if (evt.getModifiers() != 0){
        
                if(!cmb_clasematerial.getSelectedItem().equals("Seleccione...") && !cmb_grupoarticulo.getSelectedItem().equals("Seleccione...")){
                    lbl_codigomaestromaterial.setText(cmb_clasematerial.getSelectedItem().toString().substring(6,8).trim() + "-" + txt_numeromaterial.getText().trim() + "-" + cmb_grupoarticulo.getSelectedItem().toString().substring(0,3));
                }
            }    
    }//GEN-LAST:event_cmb_clasematerialActionPerformed

    private void cmb_grupoarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_grupoarticuloActionPerformed
            if (evt.getModifiers() != 0){
        
                if(!cmb_clasematerial.getSelectedItem().equals("Seleccione...") && !cmb_grupoarticulo.getSelectedItem().equals("Seleccione...")){
                    lbl_codigomaestromaterial.setText(cmb_clasematerial.getSelectedItem().toString().substring(6,8) + "-" + txt_numeromaterial.getText().trim() + "-" + cmb_grupoarticulo.getSelectedItem().toString().substring(0,3));
                }
            }    

    }//GEN-LAST:event_cmb_grupoarticuloActionPerformed

    private void txt_desmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_desmaterialKeyReleased
         if(txt_desmaterial.getText().trim().length() > 39){
               txt_desmaterial.setText(txt_desmaterial.getText().trim().substring(0, 39));
         }
    }//GEN-LAST:event_txt_desmaterialKeyReleased

    private void txt_codmaterialalternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codmaterialalternoKeyReleased
        if(txt_codmaterialalterno.getText().trim().length() > 10){
               txt_codmaterialalterno.setText(txt_codmaterialalterno.getText().trim().substring(0, 10));
         }
    }//GEN-LAST:event_txt_codmaterialalternoKeyReleased

    private void txt_marcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_marcaKeyReleased
         if(txt_marca.getText().trim().length() > 20){
               txt_marca.setText(txt_marca.getText().trim().substring(0, 20));
         }
    }//GEN-LAST:event_txt_marcaKeyReleased

    private void txt_modeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modeloKeyReleased
        if(txt_modelo.getText().trim().length() > 20){
               txt_modelo.setText(txt_modelo.getText().trim().substring(0, 20));
         }
    }//GEN-LAST:event_txt_modeloKeyReleased

    private void area_observacionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_area_observacionesKeyReleased
        if(area_observaciones.getText().trim().length() > 60){
               area_observaciones.setText(area_observaciones.getText().trim().substring(0, 60));
         }
    }//GEN-LAST:event_area_observacionesKeyReleased

    private void area_usomaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_area_usomaterialKeyReleased
         if(area_usomaterial.getText().trim().length() > 60){
               area_usomaterial.setText(area_usomaterial.getText().trim().substring(0, 60));
         }
    }//GEN-LAST:event_area_usomaterialKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_material().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_observaciones;
    private javax.swing.JTextArea area_usomaterial;
    private javax.swing.JButton bot_agregarinventario;
    private javax.swing.JButton bot_buscarfoto;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox cmb_clasematerial;
    private javax.swing.JComboBox cmb_grupoarticulo;
    private javax.swing.JComboBox cmb_unidadmedidamaterial;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_clasematerial;
    private javax.swing.JLabel lbl_codigomaestromaterial;
    private javax.swing.JLabel lbl_codmaterialalterno;
    private javax.swing.JLabel lbl_desmaterial1;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_grupomaterial;
    private javax.swing.JLabel lbl_grupomaterial1;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_infogeneralmaterial;
    private javax.swing.JLabel lbl_infostockmaterial;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_numeromaterial;
    private javax.swing.JLabel lbl_observaciones;
    private javax.swing.JLabel lbl_stockinicialmaterial;
    private javax.swing.JLabel lbl_stockmaximo;
    private javax.swing.JLabel lbl_stockminimomaterial;
    private javax.swing.JLabel lbl_stockpedidomaterial;
    private javax.swing.JLabel lbl_unidadmedidamaterial;
    private javax.swing.JLabel lbl_usomaterial;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JPanel panel_infogeneralmaterial;
    private javax.swing.JPanel panel_infostockmaterial;
    private javax.swing.JPanel panel_observaciones;
    private javax.swing.JPanel panel_usomaterial;
    private javax.swing.JTextField txt_codmaterialalterno;
    private javax.swing.JTextField txt_desmaterial;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_numeromaterial;
    private javax.swing.JTextField txt_ruta;
    private javax.swing.JTextField txt_stockinicialmaterial;
    private javax.swing.JTextField txt_stockmaximo;
    private javax.swing.JTextField txt_stockminimomaterial;
    private javax.swing.JTextField txt_stockpedidomaterial;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
