/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_proyecto;
import java.awt.Color;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ruben
 */
public class frm_buscarproyecto extends javax.swing.JFrame {

    /**
     * Creates new form frm_buscarproyecto
     */
    private Integer interfaz;
    public frm_buscarproyecto(Integer interfaz) {
        initComponents();
         this.setTitle("SISTIMACA - BUSCAR PROYECTO");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setLocationRelativeTo(null);
        this.interfaz = interfaz;
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
 // Instanciamos nuestro modelo de datos, por ejemplo, DefaultTableModel
       // y lo metemos en el JTable
        DefaultTableModel modelotabla = (DefaultTableModel) table_proyecto.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        table_proyecto.setRowSorter(elQueOrdena);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_proyecto = new javax.swing.ButtonGroup();
        bot_seleccionar = new javax.swing.JButton();
        radio_idproyecto = new javax.swing.JRadioButton();
        radio_descripcionproyecto = new javax.swing.JRadioButton();
        txt_idproyecto = new javax.swing.JTextField();
        txt_descripcionproyecto = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_proyecto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bot_seleccionar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccionar.png"))); // NOI18N
        bot_seleccionar.setText("Seleccionar");
        bot_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_seleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        radio_idproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_idproyecto.setSelected(true);
        radio_idproyecto.setText("ID PROYECTO");
        radio_idproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_idproyectoActionPerformed(evt);
            }
        });
        getContentPane().add(radio_idproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        radio_descripcionproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_descripcionproyecto.setText("DESCRIPCIÓN");
        radio_descripcionproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_descripcionproyectoActionPerformed(evt);
            }
        });
        getContentPane().add(radio_descripcionproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txt_idproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_idproyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idproyectoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_idproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, -1));

        txt_descripcionproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionproyecto.setEnabled(false);
        txt_descripcionproyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descripcionproyectoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_descripcionproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("BÚSQUEDA DE PROYECTO");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(290, 20, 220, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 270, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1070, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        table_proyecto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_proyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIPCIÓN", "DESDE", "HASTA", "CÉDULA RESPONSABLE", "RESPONSABLE", "TIPO ORDEN", "NRO ORDEN", "CLIENTE", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_proyecto);
        if (table_proyecto.getColumnModel().getColumnCount() > 0) {
            table_proyecto.getColumnModel().getColumn(9).setMinWidth(0);
            table_proyecto.getColumnModel().getColumn(9).setPreferredWidth(0);
            table_proyecto.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1180, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_idproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_idproyectoActionPerformed
        txt_descripcionproyecto.setText("");
        txt_descripcionproyecto.setEnabled(false);
        
        txt_idproyecto.setText("");
        txt_idproyecto.setEnabled(true);
        
    }//GEN-LAST:event_radio_idproyectoActionPerformed

    private void radio_descripcionproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_descripcionproyectoActionPerformed
        txt_descripcionproyecto.setText("");
        txt_descripcionproyecto.setEnabled(true);
        
        txt_idproyecto.setText("");
        txt_idproyecto.setEnabled(false);
    }//GEN-LAST:event_radio_descripcionproyectoActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_seleccionarActionPerformed
        Integer fila;
        
        fila = table_proyecto.getSelectedRow();
        
        switch (this.interfaz){
           case 1: 
                   frm_proyecto.txt_idproyectoact.setText(table_proyecto.getValueAt(fila,0).toString());
                   frm_proyecto.txt_descripcionproyectoact.setText(table_proyecto.getValueAt(fila,1).toString());
                   frm_proyecto.txt_nuevoidproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
                   frm_proyecto.txt_nuevaproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
                   frm_proyecto.date_nuevodesde.setDate(Date.valueOf(funciones.fecha_bd_usuario(table_proyecto.getValueAt(fila,2).toString(),2)));
                   frm_proyecto.date_nuevohasta.setDate(Date.valueOf(funciones.fecha_bd_usuario(table_proyecto.getValueAt(fila,3).toString(),2)));
                   frm_proyecto.cmb_tipoordennuevo.setSelectedItem(table_proyecto.getValueAt(fila,6).toString());
                   frm_proyecto.txt_nuevoorden.setText(table_proyecto.getValueAt(fila,7).toString());
                   frm_proyecto.txt_nuevocliente.setText(table_proyecto.getValueAt(fila,8).toString());
                   frm_proyecto.txt_cedularesponsablenuevo.setText(table_proyecto.getValueAt(fila,4).toString());
                   frm_proyecto.txt_nombreresponsablenuevo.setText(table_proyecto.getValueAt(fila,5).toString());
                   frm_proyecto.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
                   
                   frm_proyecto.txt_nuevoidproyecto.setEnabled(true);
                   frm_proyecto.txt_nuevaproyecto.setEnabled(true);
                   frm_proyecto.date_nuevodesde.setEnabled(true);
                   frm_proyecto.date_nuevohasta.setEnabled(true);
                   frm_proyecto.cmb_tipoordennuevo.setEnabled(true);
                   frm_proyecto.txt_nuevoorden.setEnabled(true);
                   frm_proyecto.txt_nuevocliente.setEnabled(true);
                   frm_proyecto.txt_cedularesponsablenuevo.setEnabled(true); 
                   frm_proyecto.txt_nombreresponsablenuevo.setEnabled(true);
                   frm_proyecto.bot_buscarrespact.setEnabled(true);
                   frm_proyecto.bot_actualizar.setEnabled(true);
                    this.dispose(); 
               break;            
           case 2:
               frm_solicitud.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_solicitud.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_solicitud.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               this.dispose(); 
               break;
           case 3:
               frm_reserva.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_reserva.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_reserva.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               
               this.dispose(); 
               break; 
           case 4:
               frm_salidaexpress.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_salidaexpress.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_salidaexpress.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               
               this.dispose(); 
               break; 
           case 5:
               frm_reporteentradamaterial2.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_reporteentradamaterial2.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_reporteentradamaterial2.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               
               this.dispose(); 
               break;     
          case 6:
               frm_reporte_ordendecompra.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_reporte_ordendecompra.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_reporte_ordendecompra.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               
               this.dispose(); 
               break; 
         case 7:
               frm_entradaexpress.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_entradaexpress.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_entradaexpress.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               
               this.dispose(); 
               break;          
        case 8:
               frm_consultarsolicitud.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_consultarsolicitud.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_consultarsolicitud.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               frm_consultarsolicitud.consultar_solicitud_proyecto();
               
               this.dispose(); 
               break;         
        case 9:
               frm_consultarreserva.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_consultarreserva.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_consultarreserva.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               frm_consultarreserva.consultar_reserva_proyecto();
               
               this.dispose(); 
               break; 
        case 10:
               frm_actualizarreserva.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_actualizarreserva.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_actualizarreserva.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               frm_actualizarreserva.actualizar_consultar_reserva();
               
               this.dispose(); 
               break;        
        case 11:
               frm_actualizarsolicitud.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_actualizarsolicitud.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_actualizarsolicitud.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               frm_actualizarsolicitud.actualizar_consultar_solicitud();
               
               this.dispose(); 
               break; 
        case 12:
               frm_anularreserva.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_anularreserva.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_anularreserva.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               frm_anularreserva.anular_consultar_reserva();
               
               this.dispose(); 
               break;
               
        case 13:
               frm_anularsolicitud.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_anularsolicitud.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_anularsolicitud.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               frm_anularsolicitud.anular_consultar_solicitud();
               
               this.dispose(); 
               break;  
        case 14:
               frm_reportesalidamaterial.txt_idproyecto.setText(table_proyecto.getValueAt(fila,0).toString());
               frm_reportesalidamaterial.txt_descripcionproyecto.setText(table_proyecto.getValueAt(fila,1).toString());
               frm_reportesalidamaterial.txt_id.setText(table_proyecto.getValueAt(fila,9).toString());
               
               this.dispose(); 
               break;            
       }
    }//GEN-LAST:event_bot_seleccionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       ctrl_proyecto proyecto = new ctrl_proyecto(0,"","","","",0,"","","",0);
       proyecto.consulta_proyecto(table_proyecto);
    }//GEN-LAST:event_formWindowOpened

    private void txt_idproyectoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idproyectoKeyPressed
       ctrl_proyecto proyecto = new ctrl_proyecto(0,txt_idproyecto.getText().trim(),"","","",0,"","","",0);
       proyecto.consulta_proyecto_detalle(table_proyecto);
    }//GEN-LAST:event_txt_idproyectoKeyPressed

    private void txt_descripcionproyectoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionproyectoKeyPressed
       ctrl_proyecto proyecto = new ctrl_proyecto(0,"",txt_descripcionproyecto.getText().trim(),"","",0,"","","",0);
       proyecto.consulta_proyecto_detalle_descripcion(table_proyecto);
    }//GEN-LAST:event_txt_descripcionproyectoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_buscarproyecto(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_seleccionar;
    private javax.swing.ButtonGroup group_proyecto;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JRadioButton radio_descripcionproyecto;
    private javax.swing.JRadioButton radio_idproyecto;
    private javax.swing.JTable table_proyecto;
    private javax.swing.JTextField txt_descripcionproyecto;
    private javax.swing.JTextField txt_idproyecto;
    // End of variables declaration//GEN-END:variables
}
