/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_solicitud;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static view.frm_solicitud.lbl_usuario;

/**
 *
 * @author ruben
 */
public class frm_anularprestamo extends javax.swing.JFrame {

    /**
     * Creates new form frm_consultarsolicitud
     */
    public frm_anularprestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - ANULAR PRÉSTAMOS DE MATERIAL");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());  
        
        DefaultTableModel modelotabla = (DefaultTableModel) table_prestamo.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        table_prestamo.setRowSorter(elQueOrdena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_solicitud = new javax.swing.ButtonGroup();
        lbl_nrosolicitud = new javax.swing.JLabel();
        txt_nrosolicitud = new javax.swing.JTextField();
        lbl_proyecto = new javax.swing.JLabel();
        cmb_proyecto = new javax.swing.JComboBox<>();
        lbl_area = new javax.swing.JLabel();
        cmb_tiposolicitud = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoaprobarsolicitud = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        date_desde = new com.toedter.calendar.JDateChooser();
        lbl_fechadesde = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prestamo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txt_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nrosolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nrosolicitudKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 90, -1));

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        getContentPane().add(lbl_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        cmb_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proyectoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 270, -1));

        lbl_area.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_area.setText("ÁREA");
        getContentPane().add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, -1, -1));

        cmb_tiposolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_tiposolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tiposolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tiposolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 240, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoaprobarsolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoaprobarsolicitud.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoaprobarsolicitud.setText("ANULAR PRÉSTAMO DE MATERIAL");
        jPanel7.add(lbl_encabezadoaprobarsolicitud);
        lbl_encabezadoaprobarsolicitud.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FECHA HASTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        date_hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_hastaPropertyChange(evt);
            }
        });
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        date_desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_desdePropertyChange(evt);
            }
        });
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, -1));

        lbl_fechadesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechadesde.setText("FECHA DESDE");
        getContentPane().add(lbl_fechadesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        table_prestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        table_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_prestamo", "id_entrada", "NRO MATERIAL", "DESCRIPCIÓN", "CANTIDAD PRESTADA", "UMB", "PROYECTO", "NOMBRE SOLICITANTE", "FECHA DESDE", "FECHA HASTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_prestamo);
        if (table_prestamo.getColumnModel().getColumnCount() > 0) {
            table_prestamo.getColumnModel().getColumn(0).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(2).setMinWidth(120);
            table_prestamo.getColumnModel().getColumn(2).setPreferredWidth(120);
            table_prestamo.getColumnModel().getColumn(2).setMaxWidth(120);
            table_prestamo.getColumnModel().getColumn(3).setMinWidth(300);
            table_prestamo.getColumnModel().getColumn(3).setPreferredWidth(300);
            table_prestamo.getColumnModel().getColumn(3).setMaxWidth(300);
            table_prestamo.getColumnModel().getColumn(5).setMinWidth(50);
            table_prestamo.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_prestamo.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1390, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_anularprestamo frm = new frm_anularprestamo();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_comun control = new ctrl_comun(7);
        cmb_proyecto =  control.cargar_combo(cmb_proyecto,"Seleccione...");
        control = new ctrl_comun(11);
        cmb_tiposolicitud =  control.cargar_combo(cmb_tiposolicitud,"Seleccione...");
        
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_activa(table_prestamo,0,"","",1,0);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_nrosolicitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nrosolicitudKeyReleased
        Integer opcion = 1;
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            
            ctrl_solicitud solicitud = new ctrl_solicitud(
                
                Integer.parseInt(txt_nrosolicitud.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  

            solicitud.consultar_solicitudes_activa(table_prestamo,1,"","",opcion,0);

        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nrosolicitud.setText("");
                
             }   
        }     
    }//GEN-LAST:event_txt_nrosolicitudKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
           Integer opcion = 1;
           
            ctrl_solicitud solicitud = new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  
       
            solicitud.consultar_solicitudes_activa(table_prestamo,2,"","",opcion,0);

         
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void cmb_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proyectoActionPerformed
        
        Integer opcion = 1;
        
        if(evt.getModifiers() != 0){
            
            if(!cmb_proyecto.getSelectedItem().equals("Seleccione...")){

                ctrl_solicitud solicitud =  new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim()),
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""        
             );
                

             solicitud.consultar_solicitudes_activa(table_prestamo,3,"","",opcion,0);   
            }    
        }
            
    }//GEN-LAST:event_cmb_proyectoActionPerformed

    private void date_hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_hastaPropertyChange
        String fechadesde;
        String fechahasta;
        Integer opcion = 1;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
                ctrl_solicitud solicitud=null;

                solicitud = new ctrl_solicitud(
                
                    0,
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    0,
                    "",
                    0,
                    0, //numero de material
                    "",             // descripcion de material     
                    0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,    
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );  
 
                solicitud.consultar_solicitudes_activa(table_prestamo,5,fechadesde,fechahasta,opcion,0);   
            }
        
    }//GEN-LAST:event_date_hastaPropertyChange

    private void date_desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_desdePropertyChange
        String fechadesde;
        String fechahasta;
        Integer opcion = 1;
        
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
                ctrl_solicitud solicitud=null;

                solicitud = new ctrl_solicitud(
                
                    0,
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    0,
                    "",
                    0,
                    0, //numero de material
                    "",             // descripcion de material     
                    0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,    
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );  


                solicitud.consultar_solicitudes_activa(table_prestamo,5,fechadesde,fechahasta,opcion,0);   
            }
    }//GEN-LAST:event_date_desdePropertyChange

    private void cmb_tiposolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tiposolicitudActionPerformed
        Integer opcion = 1;

        if(evt.getModifiers() != 0){

            if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){

                ctrl_solicitud solicitud =  new ctrl_solicitud(

                    0,
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim()),
                    "",
                    0,
                    0, //numero de material
                    "",             // descripcion de material
                    0,
                    "",
                    0,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );


                solicitud.consultar_solicitudes_activa(table_prestamo,4,"","",opcion,0);
            }
        }
    }//GEN-LAST:event_cmb_tiposolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_anularprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_anularprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_anularprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_anularprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_anularprestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox<String> cmb_proyecto;
    private javax.swing.JComboBox<String> cmb_tiposolicitud;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.ButtonGroup group_solicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_encabezadoaprobarsolicitud;
    private javax.swing.JLabel lbl_fechadesde;
    private javax.swing.JLabel lbl_imagentimaca2;
    protected static javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_proyecto;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable table_prestamo;
    private javax.swing.JTextField txt_descripcionmaterial;
    private javax.swing.JTextField txt_nrosolicitud;
    // End of variables declaration//GEN-END:variables
}
