/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import com.sun.org.apache.xpath.internal.operations.And;

import controlador.ctrl_cotizacion;
import controlador.ctrl_proveedor;
import java.awt.Color;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import static view.frm_entrada.table_posicioncompra;
import static view.frm_proveedor.table_clasematerial;


/**
 *
 * @author ruben
 */
public class frm_buscarproveedor extends javax.swing.JFrame {

    /**
     * Creates new form frm_proveedor
     */
    //private final Integer  id_frame;
    private Integer interfaz; 
    public frm_buscarproveedor(Integer interfaz) {
        initComponents();
        this.setTitle("SISTIMACA - BUSCAR PROVEEDOR");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setLocationRelativeTo(null);
        this.interfaz = interfaz;
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_material = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_proveedor = new javax.swing.JTable();
        radio_rif = new javax.swing.JRadioButton();
        radio_descripcion = new javax.swing.JRadioButton();
        txt_nombreproveedor = new javax.swing.JTextField();
        txt_rif = new javax.swing.JTextField();
        bot_seleccionar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_proveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RIF", "NOMBRE", "DIRECCION", "CIUDAD", "ESTADO", "PAIS", "CODIGO POSTAL", "TIPO", "PERSONA CONTACTO", "TELEFONO 1", "TELEFONO 2", "E-MAIL", "BANCO1", "NRO CUENTA1", "TIPO CUENTA1", "BANCO2", "NRO CUENTA2", "TIPO CUENTA2", "BANCO3", "NRO CUENTA3", "TIPO CUENTA3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_proveedorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_proveedor);
        if (table_proveedor.getColumnModel().getColumnCount() > 0) {
            table_proveedor.getColumnModel().getColumn(0).setMinWidth(0);
            table_proveedor.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_proveedor.getColumnModel().getColumn(0).setMaxWidth(0);
            table_proveedor.getColumnModel().getColumn(5).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(5).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(5).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(6).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(6).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(6).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(7).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(7).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(7).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(13).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(13).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(13).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(14).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(14).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(14).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(15).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(15).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(15).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(16).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(16).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(16).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(17).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(17).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(17).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(18).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(18).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(18).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(19).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(19).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(19).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(20).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(20).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(20).setMaxWidth(1);
            table_proveedor.getColumnModel().getColumn(21).setMinWidth(1);
            table_proveedor.getColumnModel().getColumn(21).setPreferredWidth(1);
            table_proveedor.getColumnModel().getColumn(21).setMaxWidth(1);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 1320, 250));

        group_material.add(radio_rif);
        radio_rif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_rif.setSelected(true);
        radio_rif.setText("RIF DE PROVEEDOR");
        radio_rif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_rifActionPerformed(evt);
            }
        });
        getContentPane().add(radio_rif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        group_material.add(radio_descripcion);
        radio_descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_descripcion.setText("NOMBRE PROVEEDOR");
        radio_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(radio_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        txt_nombreproveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombreproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreproveedorKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nombreproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 30));

        txt_rif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_rif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rifActionPerformed(evt);
            }
        });
        txt_rif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rifKeyReleased(evt);
            }
        });
        getContentPane().add(txt_rif, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 30));

        bot_seleccionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_seleccionar.setText("SELECCIONAR");
        bot_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_seleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));
        complemento.DisableBorderButton(bot_seleccionar);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("BÚSQUEDA DE PROVEEDORES");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(290, 20, 220, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 270, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txt_rif.requestFocusInWindow();
        txt_nombreproveedor.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void txt_rifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rifKeyReleased
      
       ctrl_proveedor proveedor;
       DefaultTableModel modelotabla = (DefaultTableModel) table_proveedor.getModel();
       
        if (radio_rif.isSelected() && !txt_rif.getText().trim().equals("") ){
            
            proveedor = new ctrl_proveedor(
                0,//id_proveedor
                txt_rif.getText().trim(), //rif
                "", //nombre
                "", //direccion
                "", //ciudad 
                "", //estado
                "", //pais
                "", //codigopostal
                "", //tipo 
                "", //persona contacto
                "", //telefono 1
                "", //telefono 2
                "", //correo electronico
                "", //banco 1 
                "", //nrocuenta 1 
                "", //tipo cuenta 1
                "", //banco 2 
                "", //nrocuenta 2 
                "", //tipo cuenta 2
                "", //banco 3 
                "", //nrocuenta 3 
                "", //tipo cuenta 3
                0, //clase material     
                0, //grupo material 
                false     
            );
        
           try {
               proveedor.buscar_proveedor_detalle(table_proveedor);
           } catch (SQLException ex) {
               Logger.getLogger(frm_buscarproveedor.class.getName()).log(Level.SEVERE, null, ex);
           }
        
            
            
        }
        else{
                modelotabla.setRowCount(0);
        }


        
    }//GEN-LAST:event_txt_rifKeyReleased

    private void radio_rifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_rifActionPerformed
        DefaultTableModel modelotabla = (DefaultTableModel) table_proveedor.getModel();
        modelotabla.setRowCount(0);
        txt_rif.setEnabled(true);
        txt_rif.setText("");
        txt_nombreproveedor.setText("");
        txt_nombreproveedor.setEnabled(false);
        txt_rif.requestFocusInWindow();
    }//GEN-LAST:event_radio_rifActionPerformed

    private void radio_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_descripcionActionPerformed
        DefaultTableModel modelotabla = (DefaultTableModel) table_proveedor.getModel();
        modelotabla.setRowCount(0);
        txt_nombreproveedor.setEnabled(true);
        txt_rif.setText("");
        txt_nombreproveedor.setText("");
        txt_rif.setEnabled(false);
        txt_nombreproveedor.requestFocusInWindow();
    }//GEN-LAST:event_radio_descripcionActionPerformed

    private void txt_nombreproveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreproveedorKeyReleased
     
           ctrl_proveedor proveedor;
       DefaultTableModel modelotabla = (DefaultTableModel) table_proveedor.getModel();
       
       
        if (radio_descripcion.isSelected() && !txt_nombreproveedor.getText().trim().equals("")){
            
            proveedor = new ctrl_proveedor(
                0,//id_proveedor
                "", //rif
                txt_nombreproveedor.getText().trim(), //nombre
                "", //direccion
                "", //ciudad 
                "", //estado
                "", //pais
                "", //codigopostal
                "", //tipo 
                "", //persona contacto
                "", //telefono 1
                "", //telefono 2
                "", //correo electronico
                "", //banco 1 
                "", //nrocuenta 1 
                "", //tipo cuenta 1
                "", //banco 2 
                "", //nrocuenta 2 
                "", //tipo cuenta 2
                "", //banco 3 
                "", //nrocuenta 3 
                "", //tipo cuenta 3
                0, //clase material     
                0, //grupo material 
                false    
            );
        
            proveedor.buscar_proveedor_detalle_descripcion(table_proveedor);
        
            
            
        }
        else{
                modelotabla.setRowCount(0);
        }

    }//GEN-LAST:event_txt_nombreproveedorKeyReleased

    private void bot_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_seleccionarActionPerformed
         DefaultTableModel modelotabla = (DefaultTableModel) table_proveedor.getModel();
         Integer fila;
         fila = table_proveedor.getSelectedRow();
         Integer i = 0;
         
         switch (this.interfaz){
             case 1: frm_alternativa.txt_idproveedor1.setText(table_proveedor.getValueAt(fila, 0).toString());
                     frm_alternativa.txt_rif1.setText(table_proveedor.getValueAt(fila, 1).toString());
                     frm_alternativa.txt_descripcionprov1.setText(table_proveedor.getValueAt(fila, 2).toString());           
         
                     break;
                     
             case 2: frm_alternativa.txt_idproveedor2.setText(table_proveedor.getValueAt(fila, 0).toString());
                     frm_alternativa.txt_rif2.setText(table_proveedor.getValueAt(fila, 1).toString());
                     frm_alternativa.txt_descripcionprov2.setText(table_proveedor.getValueAt(fila, 2).toString());           
         
                     break;        
                     
            case 3:  frm_alternativa.txt_idproveedor3.setText(table_proveedor.getValueAt(fila, 0).toString());
                     frm_alternativa.txt_rif3.setText(table_proveedor.getValueAt(fila, 1).toString());
                     frm_alternativa.txt_descripcionprov3.setText(table_proveedor.getValueAt(fila, 2).toString());           
                     
                     break;
                     
            case 4: 
                    frm_proveedor.txt_proveedor.setText(table_proveedor.getValueAt(fila, 0).toString());
                    frm_proveedor.txt_rif.setText(table_proveedor.getValueAt(fila, 1).toString());
                    frm_proveedor.txt_nombre.setText(table_proveedor.getValueAt(fila, 2).toString());
                    frm_proveedor.area_direccion.setText(table_proveedor.getValueAt(fila, 3).toString());
                    frm_proveedor.txt_ciudad.setText(table_proveedor.getValueAt(fila, 4).toString());
                    frm_proveedor.txt_estado.setText(table_proveedor.getValueAt(fila, 5).toString());
                    frm_proveedor.txt_pais.setText(table_proveedor.getValueAt(fila, 6).toString());
                    frm_proveedor.txt_codigopostal.setText(table_proveedor.getValueAt(fila, 7).toString());    
                    frm_proveedor.cmb_tipo.setSelectedItem(table_proveedor.getValueAt(fila, 8).toString());
                    frm_proveedor.txt_personacontacto.setText(table_proveedor.getValueAt(fila, 9).toString());    
                    frm_proveedor.txt_telefono1.setText(table_proveedor.getValueAt(fila, 10).toString());    
                    frm_proveedor.txt_telefono2.setText(table_proveedor.getValueAt(fila, 11).toString());    
                    frm_proveedor.txt_correoelectronico.setText(table_proveedor.getValueAt(fila, 12).toString());
                    frm_proveedor.txt_banco1.setText(table_proveedor.getValueAt(fila, 13).toString());
                    frm_proveedor.txt_nrocuenta1.setText(table_proveedor.getValueAt(fila, 14).toString());
                    frm_proveedor.cmb_tipocuenta1.setSelectedItem(table_proveedor.getValueAt(fila, 15).toString());
                    frm_proveedor.txt_banco2.setText(table_proveedor.getValueAt(fila, 16).toString());
                    frm_proveedor.txt_nrocuenta2.setText(table_proveedor.getValueAt(fila, 17).toString());
                    frm_proveedor.cmb_tipocuenta2.setSelectedItem(table_proveedor.getValueAt(fila, 18).toString());
                    frm_proveedor.txt_banco3.setText(table_proveedor.getValueAt(fila, 19).toString());
                    frm_proveedor.txt_nrocuenta3.setText(table_proveedor.getValueAt(fila, 20).toString());
                    frm_proveedor.cmb_tipocuenta3.setSelectedItem(table_proveedor.getValueAt(fila, 21).toString());                

                    ctrl_proveedor proveedor = new ctrl_proveedor(
                        Integer.parseInt(frm_proveedor.txt_proveedor.getText().trim()),//id_proveedor
                        "", //rif
                        "", //nombre
                        "", //direccion
                        "", //ciudad 
                        "", //estado
                        "", //pais
                        "", //codigopostal
                        "", //tipo 
                        "", //persona contacto
                        "", //telefono 1
                        "", //telefono 2
                        "", //correo electronico
                        "", //banco 1 
                        "", //nrocuenta 1 
                        "", //tipo cuenta 1
                        "", //banco 2 
                        "", //nrocuenta 2 
                        "", //tipo cuenta 2
                        "", //banco 3 
                        "", //nrocuenta 3 
                        "", //tipo cuenta 3
                        0, //clase material     
                        0, //grupo material 
                        false       
                    );
                    
                    for(i=0;i<frm_proveedor.table_clasematerial.getRowCount();i++){
                        frm_proveedor.table_clasematerial.setValueAt(false,i,1);
                    }
                
                    for(i=0;i<frm_proveedor.table_grupoarticulo.getRowCount();i++){
                        frm_proveedor.table_grupoarticulo.setValueAt(false,i,0);
                    }
                             
                    try {
                        proveedor.consultar_clasematerial_proveedor(frm_proveedor.table_clasematerial);
                         proveedor.consultar_grupomaterial_proveedor(frm_proveedor.table_grupoarticulo);
                        frm_proveedor.bot_actualizarproveedor.setEnabled(true);
                        frm_proveedor.bot_anularproveedor.setEnabled(true);
                    } catch (SQLException ex) {
                    }
         
                                       
                     break; 
                     
             case 5:          
                
                frm_entrada.txt_idproveedor.setText(table_proveedor.getValueAt(fila, 1).toString());
               
                ctrl_cotizacion cotizacion = new ctrl_cotizacion(
                   0, 
                   0, 
                   table_proveedor.getValueAt(fila, 1).toString(), 
                   "", 
                   0, 
                   0, 
                   0, 
                   0, 
                   0, 
                   0,
                   0.0, 
                   0.0, 
                   "", 
                   "", //tipo plazo entrega
                    0, //dias plazoentrega
                   "", //condicion de pago
                   "", //tipotransporte
                    0, //diasflete
                    0.0, //costoflete
                    0, //codigomonedaflete
                   "", //fotocotizacion
                    "", //justificacion
                    "", //observacion     
                   false, 
                   false, 
                   "", 
                   false, 
                   "", 
                   false, 
                   0,
                   "",     
                   true
                );                  
            
                try {
                    cotizacion.consultar_ordendecompraproveedor_detalle_entrada(frm_entrada.table_posicioncompra);
                    
                } catch (SQLException | ArrayIndexOutOfBoundsException ex) {}
    
                break;      
                    
           
         }
         
         this.dispose();
        
    }//GEN-LAST:event_bot_seleccionarActionPerformed

    private void txt_rifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rifActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void table_proveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_proveedorMousePressed
        //bot_seleccionar.doClick();
    }//GEN-LAST:event_table_proveedorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_buscarproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_buscarproveedor(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_seleccionar;
    private javax.swing.ButtonGroup group_material;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JRadioButton radio_descripcion;
    private javax.swing.JRadioButton radio_rif;
    private javax.swing.JTable table_proveedor;
    private javax.swing.JTextField txt_nombreproveedor;
    private javax.swing.JTextField txt_rif;
    // End of variables declaration//GEN-END:variables
}
