/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_grupomaterial;
import controlador.ctrl_moneda;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;
import model.class_grupomaterial;
import model.class_moneda;
import javax.swing.UIManager;
import javax.swing.ImageIcon;


/**
 *
 * @author ruben
 */
public class frm_moneda extends javax.swing.JFrame {

    /**
     * Creates new form frm_servicio
     */
    public frm_moneda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - MONEDA");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        radio_servicio = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_moneda = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        radio_crearmoneda = new javax.swing.JRadioButton();
        lbl_demoneda = new javax.swing.JLabel();
        txt_moneda = new javax.swing.JTextField();
        bot_crear = new javax.swing.JButton();
        lbl_codmoneda = new javax.swing.JLabel();
        txt_codmoneda = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radio_actualizarmoneda = new javax.swing.JRadioButton();
        lbl_desnuevomoneda = new javax.swing.JLabel();
        lbl_nuevamoneda = new javax.swing.JLabel();
        cmb_moneda = new javax.swing.JComboBox();
        txt_nuevamoneda = new javax.swing.JTextField();
        bot_actualizar = new javax.swing.JButton();
        lbl_nuevacodmoneda = new javax.swing.JLabel();
        txt_nuevacodmoneda = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        table_moneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_moneda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIPCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_moneda);
        if (table_moneda.getColumnModel().getColumnCount() > 0) {
            table_moneda.getColumnModel().getColumn(0).setMinWidth(100);
            table_moneda.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_moneda.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 320, 140));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_crearmoneda.setBackground(new java.awt.Color(245, 245, 245));
        radio_servicio.add(radio_crearmoneda);
        radio_crearmoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radio_crearmoneda.setSelected(true);
        radio_crearmoneda.setText("CREAR MONEDA");
        radio_crearmoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_crearmonedaActionPerformed(evt);
            }
        });
        jPanel1.add(radio_crearmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_demoneda.setBackground(new java.awt.Color(240, 255, 255));
        lbl_demoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_demoneda.setText("DESCRIPCIÓN MONEDA");
        jPanel1.add(lbl_demoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        txt_moneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 300, -1));

        bot_crear.setBackground(new java.awt.Color(255, 255, 255));
        bot_crear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        bot_crear.setText("CREAR");
        bot_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_crearActionPerformed(evt);
            }
        });
        jPanel1.add(bot_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 150, 30));

        lbl_codmoneda.setBackground(new java.awt.Color(240, 255, 255));
        lbl_codmoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codmoneda.setText("CÓDIGO MONEDA");
        jPanel1.add(lbl_codmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_codmoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_moneda, org.jdesktop.beansbinding.ObjectProperty.create(), txt_codmoneda, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        jPanel1.add(txt_codmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 880, 120));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_actualizarmoneda.setBackground(new java.awt.Color(245, 245, 245));
        radio_servicio.add(radio_actualizarmoneda);
        radio_actualizarmoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radio_actualizarmoneda.setText("ACTUALIZAR MONEDA");
        radio_actualizarmoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_actualizarmonedaActionPerformed(evt);
            }
        });
        jPanel2.add(radio_actualizarmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_desnuevomoneda.setBackground(new java.awt.Color(240, 255, 255));
        lbl_desnuevomoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_desnuevomoneda.setText("MONEDA");
        jPanel2.add(lbl_desnuevomoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbl_nuevamoneda.setBackground(new java.awt.Color(240, 255, 255));
        lbl_nuevamoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nuevamoneda.setText("NUEVA DESCRIPCIÓN MONEDA");
        jPanel2.add(lbl_nuevamoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        cmb_moneda.setBackground(new java.awt.Color(240, 255, 255));
        cmb_moneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_moneda.setEnabled(false);
        cmb_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_monedaActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, -1));

        txt_nuevamoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nuevamoneda.setEnabled(false);
        txt_nuevamoneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nuevamonedaKeyPressed(evt);
            }
        });
        jPanel2.add(txt_nuevamoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 300, -1));

        bot_actualizar.setBackground(new java.awt.Color(255, 255, 255));
        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 150, 30));

        lbl_nuevacodmoneda.setBackground(new java.awt.Color(240, 255, 255));
        lbl_nuevacodmoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nuevacodmoneda.setText("NUEVO CÓDIGO MONEDA");
        jPanel2.add(lbl_nuevacodmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        txt_nuevacodmoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nuevacodmoneda.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txt_nuevamoneda, org.jdesktop.beansbinding.ObjectProperty.create(), txt_nuevacodmoneda, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txt_nuevacodmoneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nuevacodmonedaKeyPressed(evt);
            }
        });
        jPanel2.add(txt_nuevacodmoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 880, 120));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("ADMINISTRACIÓN MONEDA");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 210, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1113, 20, 130, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 100, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(910, 10, 190, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(912, 30, 190, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_crearActionPerformed
      class_moneda modelo_moneda;
      ctrl_comun control;
        
        if(!txt_moneda.getText().equals("") && !txt_codmoneda.getText().equals("") ) {
                
                ctrl_moneda moneda = new ctrl_moneda(0,txt_codmoneda.getText().toUpperCase().trim(),txt_moneda.getText().toUpperCase().trim());
                               
                modelo_moneda = moneda.actualizar_moneda();
                
                if (modelo_moneda.isStatus()){
                    
                   moneda.consulta_moneda(table_moneda);
                         
                   control = new ctrl_comun(6); 
                   cmb_moneda =  control.cargar_combo(cmb_moneda,txt_codmoneda.getText().toUpperCase().trim());
                   
                }
                
        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        } 
    }//GEN-LAST:event_bot_crearActionPerformed

    private void radio_crearmonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_crearmonedaActionPerformed
        txt_moneda.setEnabled(true);
        txt_codmoneda.setEnabled(true);
        bot_crear.setEnabled(true);
        cmb_moneda.setEnabled(false);
        txt_nuevamoneda.setEnabled(false);
        txt_nuevacodmoneda.setEnabled(false);
        bot_actualizar.setEnabled(false);
        radio_actualizarmoneda.setSelected(false);
        jPanel2.setBackground(new Color(250,250,250));
        jPanel1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_radio_crearmonedaActionPerformed

    private void radio_actualizarmonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_actualizarmonedaActionPerformed
        txt_moneda.setText("");
        txt_moneda.setEnabled(false);
        txt_codmoneda.setText("");
        txt_codmoneda.setEnabled(false);
        bot_crear.setEnabled(false);
        cmb_moneda.setEnabled(true);
        txt_nuevamoneda.setEnabled(true);
        txt_nuevacodmoneda.setEnabled(true);
        bot_actualizar.setEnabled(true);
        radio_crearmoneda.setSelected(false);
        jPanel1.setBackground(new Color(250,250,250));
        jPanel2.setBackground(new Color(255,255,255));
            
    }//GEN-LAST:event_radio_actualizarmonedaActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        class_moneda modelo_moneda= null; 
        ctrl_comun control;
        boolean resp = true;
       
        
        if(!txt_nuevamoneda.getText().equals("") && !txt_nuevacodmoneda.getText().equals("") && !cmb_moneda.getSelectedItem().equals("Seleccione...")  ) {

           
            
            if (!txt_nuevacodmoneda.getText().equals(cmb_moneda.getSelectedItem().toString().substring(5,cmb_moneda.getSelectedItem().toString().length()).trim())){
                
                ctrl_moneda moneda = new ctrl_moneda(Integer.parseInt(cmb_moneda.getSelectedItem().toString().substring(0,3).trim()),txt_nuevacodmoneda.getText(),txt_nuevamoneda.getText().trim().toUpperCase());
                
                modelo_moneda = moneda.actualizar_moneda_detalle();
                
                resp =  modelo_moneda.isStatus();
                
                if (resp){ 
                    moneda.consulta_moneda(table_moneda);
                    
                    control = new ctrl_comun(6); 
                    cmb_moneda =  control.cargar_combo(cmb_moneda,txt_nuevamoneda.getText().toUpperCase().trim());
                    
                    txt_nuevamoneda.setText("");
                    
                }
                
            }
            
        }
        else{

            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        ctrl_moneda moneda = new ctrl_moneda(0,"","");
        moneda.consulta_moneda(table_moneda);
         
        ctrl_comun control = new ctrl_comun(6);
        cmb_moneda =  control.cargar_combo(cmb_moneda,"Seleccione...");
        
        txt_codmoneda.requestFocusInWindow();
       
    }//GEN-LAST:event_formWindowOpened

    private void txt_nuevamonedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nuevamonedaKeyPressed
       if (evt.getKeyCode()==10){
            bot_actualizar.doClick();
        }
        
        if (evt.getKeyCode() == 27){
         
            bot_reiniciar.doClick();
                    
        }
    }//GEN-LAST:event_txt_nuevamonedaKeyPressed

    private void cmb_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_monedaActionPerformed
        
        if(evt.getModifiers() != 0){
            if (cmb_moneda.getSelectedItem().equals("Seleccione...")){
                txt_nuevacodmoneda.setText("");
            }
            else{
                txt_nuevacodmoneda.setText(cmb_moneda.getSelectedItem().toString().substring(5,cmb_moneda.getSelectedItem().toString().length()).trim());
            }
        }
        
    }//GEN-LAST:event_cmb_monedaActionPerformed

    private void txt_nuevacodmonedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nuevacodmonedaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nuevacodmonedaKeyPressed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_moneda frm = new frm_moneda();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_moneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_crear;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox cmb_moneda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_codmoneda;
    private javax.swing.JLabel lbl_demoneda;
    private javax.swing.JLabel lbl_desnuevomoneda;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nuevacodmoneda;
    private javax.swing.JLabel lbl_nuevamoneda;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JRadioButton radio_actualizarmoneda;
    private javax.swing.JRadioButton radio_crearmoneda;
    private javax.swing.ButtonGroup radio_servicio;
    private javax.swing.JTable table_moneda;
    private javax.swing.JTextField txt_codmoneda;
    private javax.swing.JTextField txt_moneda;
    private javax.swing.JTextField txt_nuevacodmoneda;
    private javax.swing.JTextField txt_nuevamoneda;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
