/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_cotizacion;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.class_cotizacion;



/**
 *
 * @author ruben
 */
public class frm_alternativapart extends javax.swing.JFrame {

    /**
     * Creates new form frm_alternativa
     */
   
     
    private String origenArchivo;
    private String destinoArchivo1="";
    private String destinoArchivo2="";
    private String destinoArchivo3="";
    private File archivo;
            
    public frm_alternativapart(String id_solicitud,String posicion,String id_material,String des_material,Object cantidad,String umb ) {
        initComponents();
        this.setTitle("SISTIMACA - ALTERNATIVAS");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setLocationRelativeTo(null);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
        lbl_idsolicitud.setText(id_solicitud);
        lbl_desidmaterial.setText(id_material);
        lbl_desmaterial.setText(des_material);
        lbl_descantidad.setText(cantidad.toString());
        spin_cantidad1.setValue(cantidad);
        spin_cantidad2.setValue(cantidad);
        spin_cantidad3.setValue(cantidad);
        lbl_und1.setText(umb);
        lbl_und2.setText(umb);
        lbl_und3.setText(umb);
        txt_posicion.setText(posicion);
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_posicion = new javax.swing.JTextField();
        txt_alternativa1 = new javax.swing.JTextField();
        txt_alternativa2 = new javax.swing.JTextField();
        txt_alternativa3 = new javax.swing.JTextField();
        bot_guardar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        panel_alternativa1 = new javax.swing.JPanel();
        chk_alternativa1 = new javax.swing.JCheckBox();
        lbl_preciounitario1 = new javax.swing.JLabel();
        txt_total1 = new javax.swing.JTextField();
        spin_cantidad1 = new javax.swing.JSpinner();
        lbl_total1 = new javax.swing.JLabel();
        lbl_cantidad1 = new javax.swing.JLabel();
        txt_preciounitario1 = new javax.swing.JTextField();
        chk_recomendacion1 = new javax.swing.JCheckBox();
        cmb_moneda1 = new javax.swing.JComboBox<>();
        lbl_und1 = new javax.swing.JLabel();
        date_cotizar1 = new com.toedter.calendar.JDateChooser();
        lbl_fechacotizacion1 = new javax.swing.JLabel();
        lbl_referencia = new javax.swing.JLabel();
        lbl_moneda1 = new javax.swing.JLabel();
        lbl_referencia1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_observaciones1 = new javax.swing.JTextArea();
        bot_buscar1 = new javax.swing.JButton();
        bot_guardar1 = new javax.swing.JButton();
        lbl_guardar1 = new javax.swing.JLabel();
        panel_alternativa2 = new javax.swing.JPanel();
        chk_alternativa2 = new javax.swing.JCheckBox();
        lbl_preciounitario2 = new javax.swing.JLabel();
        txt_total2 = new javax.swing.JTextField();
        spin_cantidad2 = new javax.swing.JSpinner();
        lbl_total2 = new javax.swing.JLabel();
        lbl_cantidad2 = new javax.swing.JLabel();
        txt_preciounitario2 = new javax.swing.JTextField();
        chk_recomendacion2 = new javax.swing.JCheckBox();
        cmb_moneda2 = new javax.swing.JComboBox<>();
        lbl_und2 = new javax.swing.JLabel();
        date_cotizar2 = new com.toedter.calendar.JDateChooser();
        lbl_fechacotizacion2 = new javax.swing.JLabel();
        lbl_moneda2 = new javax.swing.JLabel();
        lbl_referencia3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_observaciones2 = new javax.swing.JTextArea();
        bot_guardar2 = new javax.swing.JButton();
        lbl_referencia6 = new javax.swing.JLabel();
        bot_buscar2 = new javax.swing.JButton();
        lbl_guardar2 = new javax.swing.JLabel();
        panel_alternativa3 = new javax.swing.JPanel();
        chk_alternativa3 = new javax.swing.JCheckBox();
        lbl_preciounitario3 = new javax.swing.JLabel();
        txt_total3 = new javax.swing.JTextField();
        spin_cantidad3 = new javax.swing.JSpinner();
        lbl_total3 = new javax.swing.JLabel();
        lbl_cantidad3 = new javax.swing.JLabel();
        txt_preciounitario3 = new javax.swing.JTextField();
        chk_recomendacion3 = new javax.swing.JCheckBox();
        cmb_moneda3 = new javax.swing.JComboBox<>();
        lbl_und3 = new javax.swing.JLabel();
        date_cotizar3 = new com.toedter.calendar.JDateChooser();
        lbl_fechacotizacion3 = new javax.swing.JLabel();
        lbl_moneda3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_observaciones3 = new javax.swing.JTextArea();
        lbl_referencia5 = new javax.swing.JLabel();
        bot_buscar3 = new javax.swing.JButton();
        lbl_referencia7 = new javax.swing.JLabel();
        bot_guardar3 = new javax.swing.JButton();
        lbl_guardar3 = new javax.swing.JLabel();
        lbl_idmaterial = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_cantidadautorizada = new javax.swing.JLabel();
        lbl_nrosolicitud = new javax.swing.JLabel();
        lbl_desidmaterial = new javax.swing.JLabel();
        lbl_desmaterial = new javax.swing.JLabel();
        lbl_descantidad = new javax.swing.JLabel();
        lbl_idsolicitud = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        area_justificacion1 = new javax.swing.JTextArea();

        txt_alternativa1.setText("false");

        txt_alternativa2.setText("false");

        txt_alternativa3.setText("false");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bot_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/databasesave.png"))); // NOI18N
        bot_guardar.setText("GUARDAR");
        bot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 140, 30));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("ALTERNATIVAS PARTICULARES");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(260, 10, 250, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.setToolTipText("");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1260, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(1000, 10, 240, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(1000, 30, 240, 17);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 60));

        panel_alternativa1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_alternativa1.setEnabled(false);
        panel_alternativa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk_alternativa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_alternativa1.setSelected(true);
        chk_alternativa1.setText("ALTERNATIVA 1");
        chk_alternativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_alternativa1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(chk_alternativa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_preciounitario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_preciounitario1.setText("PRECIO UNITARIO");
        panel_alternativa1.add(lbl_preciounitario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txt_total1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_total1.setEnabled(false);
        panel_alternativa1.add(txt_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        spin_cantidad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidad1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_cantidad1StateChanged(evt);
            }
        });
        panel_alternativa1.add(spin_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, -1));

        lbl_total1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total1.setText("TOTAL");
        panel_alternativa1.add(lbl_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_cantidad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad1.setText("CANTIDAD A COTIZAR");
        panel_alternativa1.add(lbl_cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_preciounitario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_preciounitario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_preciounitario1KeyReleased(evt);
            }
        });
        panel_alternativa1.add(txt_preciounitario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 150, -1));

        chk_recomendacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_recomendacion1.setText("RECOMENDACIÓN COMPRADOR");
        panel_alternativa1.add(chk_recomendacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        cmb_moneda1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_moneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_moneda1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(cmb_moneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, -1));

        lbl_und1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_und1.setText("jLabel13");
        panel_alternativa1.add(lbl_und1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));
        panel_alternativa1.add(date_cotizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        lbl_fechacotizacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechacotizacion1.setText("FECHA COTIZACIÓN");
        panel_alternativa1.add(lbl_fechacotizacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lbl_referencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_referencia.setText("OBSERVACIONES");
        panel_alternativa1.add(lbl_referencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lbl_moneda1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_moneda1.setText("jLabel13");
        panel_alternativa1.add(lbl_moneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        lbl_referencia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_referencia1.setText("ADJUNTAR DOCUMENTO");
        panel_alternativa1.add(lbl_referencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        area_observaciones1.setColumns(20);
        area_observaciones1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        area_observaciones1.setLineWrap(true);
        area_observaciones1.setRows(5);
        jScrollPane1.setViewportView(area_observaciones1);

        panel_alternativa1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, -1));

        bot_buscar1.setText("Buscar");
        bot_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscar1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(bot_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        bot_guardar1.setText("Guardar");
        bot_guardar1.setEnabled(false);
        bot_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardar1ActionPerformed(evt);
            }
        });
        panel_alternativa1.add(bot_guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        lbl_guardar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_guardar1.setForeground(new java.awt.Color(255, 0, 0));
        lbl_guardar1.setText("Sin Adjunto");
        panel_alternativa1.add(lbl_guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        getContentPane().add(panel_alternativa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 400, 360));

        panel_alternativa2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_alternativa2.setEnabled(false);
        panel_alternativa2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk_alternativa2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_alternativa2.setText("ALTERNATIVA 2");
        chk_alternativa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_alternativa2ActionPerformed(evt);
            }
        });
        panel_alternativa2.add(chk_alternativa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_preciounitario2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_preciounitario2.setText("PRECIO UNITARIO");
        panel_alternativa2.add(lbl_preciounitario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txt_total2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_total2.setEnabled(false);
        panel_alternativa2.add(txt_total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        spin_cantidad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidad2.setEnabled(false);
        spin_cantidad2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_cantidad2StateChanged(evt);
            }
        });
        panel_alternativa2.add(spin_cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, -1));

        lbl_total2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total2.setText("TOTAL");
        panel_alternativa2.add(lbl_total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_cantidad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad2.setText("CANTIDAD A COTIZAR");
        panel_alternativa2.add(lbl_cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_preciounitario2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_preciounitario2.setEnabled(false);
        txt_preciounitario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_preciounitario2KeyReleased(evt);
            }
        });
        panel_alternativa2.add(txt_preciounitario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 150, -1));

        chk_recomendacion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_recomendacion2.setText("RECOMENDACIÓN COMPRADOR");
        chk_recomendacion2.setEnabled(false);
        panel_alternativa2.add(chk_recomendacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        cmb_moneda2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_moneda2.setEnabled(false);
        cmb_moneda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_moneda2ActionPerformed(evt);
            }
        });
        panel_alternativa2.add(cmb_moneda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, -1));

        lbl_und2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_und2.setText("jLabel13");
        panel_alternativa2.add(lbl_und2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        date_cotizar2.setEnabled(false);
        panel_alternativa2.add(date_cotizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        lbl_fechacotizacion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechacotizacion2.setText("FECHA COTIZACIÓN");
        panel_alternativa2.add(lbl_fechacotizacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lbl_moneda2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_moneda2.setText("jLabel13");
        panel_alternativa2.add(lbl_moneda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        lbl_referencia3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_referencia3.setText("OBSERVACIONES");
        panel_alternativa2.add(lbl_referencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        area_observaciones2.setColumns(20);
        area_observaciones2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        area_observaciones2.setLineWrap(true);
        area_observaciones2.setRows(5);
        area_observaciones2.setEnabled(false);
        jScrollPane2.setViewportView(area_observaciones2);

        panel_alternativa2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, -1));

        bot_guardar2.setText("Guardar");
        bot_guardar2.setEnabled(false);
        bot_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardar2ActionPerformed(evt);
            }
        });
        panel_alternativa2.add(bot_guardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        lbl_referencia6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_referencia6.setText("ADJUNTAR DOCUMENTO");
        panel_alternativa2.add(lbl_referencia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        bot_buscar2.setText("Buscar");
        bot_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscar2ActionPerformed(evt);
            }
        });
        panel_alternativa2.add(bot_buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lbl_guardar2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_guardar2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_guardar2.setText("Sin Adjunto");
        panel_alternativa2.add(lbl_guardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        getContentPane().add(panel_alternativa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 400, 360));

        panel_alternativa3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_alternativa3.setEnabled(false);
        panel_alternativa3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk_alternativa3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_alternativa3.setText("ALTERNATIVA 3");
        chk_alternativa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_alternativa3ActionPerformed(evt);
            }
        });
        panel_alternativa3.add(chk_alternativa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_preciounitario3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_preciounitario3.setText("PRECIO UNITARIO");
        panel_alternativa3.add(lbl_preciounitario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txt_total3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_total3.setEnabled(false);
        panel_alternativa3.add(txt_total3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        spin_cantidad3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidad3.setEnabled(false);
        spin_cantidad3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_cantidad3StateChanged(evt);
            }
        });
        panel_alternativa3.add(spin_cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, -1));

        lbl_total3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total3.setText("TOTAL");
        panel_alternativa3.add(lbl_total3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_cantidad3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad3.setText("CANTIDAD A COTIZAR");
        panel_alternativa3.add(lbl_cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_preciounitario3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_preciounitario3.setEnabled(false);
        txt_preciounitario3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_preciounitario3KeyReleased(evt);
            }
        });
        panel_alternativa3.add(txt_preciounitario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 160, -1));

        chk_recomendacion3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_recomendacion3.setText("RECOMENDACIÓN COMPRADOR");
        chk_recomendacion3.setEnabled(false);
        panel_alternativa3.add(chk_recomendacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        cmb_moneda3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_moneda3.setEnabled(false);
        cmb_moneda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_moneda3ActionPerformed(evt);
            }
        });
        panel_alternativa3.add(cmb_moneda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 70, -1));

        lbl_und3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_und3.setText("jLabel13");
        panel_alternativa3.add(lbl_und3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        date_cotizar3.setEnabled(false);
        panel_alternativa3.add(date_cotizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        lbl_fechacotizacion3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechacotizacion3.setText("FECHA COTIZACIÓN");
        panel_alternativa3.add(lbl_fechacotizacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lbl_moneda3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_moneda3.setText("jLabel13");
        panel_alternativa3.add(lbl_moneda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        area_observaciones3.setColumns(20);
        area_observaciones3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        area_observaciones3.setLineWrap(true);
        area_observaciones3.setRows(5);
        area_observaciones3.setEnabled(false);
        jScrollPane3.setViewportView(area_observaciones3);

        panel_alternativa3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, -1));

        lbl_referencia5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_referencia5.setText("OBSERVACIONES");
        panel_alternativa3.add(lbl_referencia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        bot_buscar3.setText("Buscar");
        bot_buscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscar3ActionPerformed(evt);
            }
        });
        panel_alternativa3.add(bot_buscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lbl_referencia7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_referencia7.setText("ADJUNTAR DOCUMENTO");
        panel_alternativa3.add(lbl_referencia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        bot_guardar3.setText("Guardar");
        bot_guardar3.setEnabled(false);
        bot_guardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardar3ActionPerformed(evt);
            }
        });
        panel_alternativa3.add(bot_guardar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        lbl_guardar3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_guardar3.setForeground(new java.awt.Color(255, 0, 0));
        lbl_guardar3.setText("Sin Adjunto");
        panel_alternativa3.add(lbl_guardar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        getContentPane().add(panel_alternativa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, 400, 360));

        lbl_idmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idmaterial.setText("ID MATERIAL");
        getContentPane().add(lbl_idmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcion.setText("DESCRIPCIÓN MATERIAL");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        lbl_cantidadautorizada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadautorizada.setText("CANTIDAD AUTORIZADA");
        getContentPane().add(lbl_cantidadautorizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("DOCUMENTO SOLICITUD");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lbl_desidmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desidmaterial.setText("jLabel1");
        getContentPane().add(lbl_desidmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        lbl_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desmaterial.setText("jLabel1");
        getContentPane().add(lbl_desmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        lbl_descantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descantidad.setText("jLabel1");
        getContentPane().add(lbl_descantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        lbl_idsolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idsolicitud.setText("jLabel1");
        getContentPane().add(lbl_idsolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("JUSTIFICACIÓN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        area_justificacion1.setColumns(20);
        area_justificacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_justificacion1.setLineWrap(true);
        area_justificacion1.setRows(5);
        area_justificacion1.setEnabled(false);
        jScrollPane6.setViewportView(area_justificacion1);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Integer fila;
        
        fila =  frm_cotizacion.table_posicionsolicitud.getSelectedRow();
        ctrl_comun control = new ctrl_comun(6);
        cmb_moneda1 =  control.cargar_combo(cmb_moneda1,"Seleccione...");
        lbl_moneda1.setText("");
        
        cmb_moneda2 =  control.cargar_combo(cmb_moneda2,"Seleccione...");
        lbl_moneda2.setText("");
        
        cmb_moneda3 =  control.cargar_combo(cmb_moneda3,"Seleccione...");
        lbl_moneda3.setText("");
        
        area_justificacion1.setText(frm_cotizacion.table_posicionsolicitud.getValueAt(fila,13).toString());
       
        
    }//GEN-LAST:event_formWindowOpened

    private void bot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardarActionPerformed
       
        String fecha_cotizacion;
        String fecha_carga_compras;
        ctrl_cotizacion cotizacion = null;
        class_cotizacion modelo_cotizacion = null;
        Boolean errorguardar = false;
        Boolean guardar = true;
      
        fecha_carga_compras = funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2);
        
        if(chk_alternativa1.isSelected()){
            
           /* if (destinoArchivo1.trim().equals("")) {
                  JOptionPane.showMessageDialog(null,"FALTA ADJUNTAR DOCUMENTO DE COTIZACIÓN ALTERNATIVA 1");
                  errorguardar = true;
            }*/
           
            
             fecha_cotizacion = funciones.fecha_convertir_date(date_cotizar1, 1);
            
            if (!txt_preciounitario1.getText().trim().equals("") &&
                !fecha_cotizacion.equals("") &&
                !cmb_moneda1.getSelectedItem().equals("Seleccione...") ){
           }
           else{
                JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS ALTERNATIVA 1");
                errorguardar = true;
           }
        }

        if(chk_alternativa2.isSelected()){
            
            /*if (destinoArchivo2.trim().equals("")) {
                  JOptionPane.showMessageDialog(null,"FALTA ADJUNTAR DOCUMENTO DE COTIZACIÓN ALTERNATIVA 2");
                  errorguardar = true;
            }*/
           
            
             fecha_cotizacion = funciones.fecha_convertir_date(date_cotizar2, 1);
            
            if (!txt_preciounitario2.getText().trim().equals("") &&
                !fecha_cotizacion.equals("") &&
                !cmb_moneda2.getSelectedItem().equals("Seleccione...")){
               
            }
           else{
                JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS ALTERNATIVA 2");
                errorguardar = true;
           }
        }
        
     
       if(chk_alternativa3.isSelected()){
            
            /*if (destinoArchivo3.trim().equals("")) {
                  JOptionPane.showMessageDialog(null,"FALTA ADJUNTAR DOCUMENTO DE COTIZACIÓN ALTERNATIVA 3");
                  errorguardar = true;
            }*/

            
            fecha_cotizacion = funciones.fecha_convertir_date(date_cotizar3, 1);
            
            if (!txt_preciounitario3.getText().trim().equals("") &&
                !fecha_cotizacion.equals("") &&
                !cmb_moneda3.getSelectedItem().equals("Seleccione...")){
       
            }
           else{
               JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS ALTERNATIVA 3");
               errorguardar = true;
           }
        }

        
        if (errorguardar.equals(false)){
           
            if (chk_alternativa1.isSelected()){
                fecha_cotizacion = funciones.fecha_convertir_date(date_cotizar1, 1);
                cotizacion = new ctrl_cotizacion(
                   0, 
                   8, 
                   "", 
                   "", 
                   Integer.parseInt(lbl_idsolicitud.getText()), 
                   Integer.parseInt(lbl_desidmaterial.getText()), 
                   Integer.parseInt(txt_posicion.getText()), 
                   Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()), 
                   Integer.parseInt(cmb_moneda1.getSelectedItem().toString().substring(0,3).trim()), 
                   Integer.parseInt(spin_cantidad1.getValue().toString()),
                   Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario1.getText().trim(),false)), 
                   Double.parseDouble(funciones.separadormilesflotante(txt_total1.getText().trim(),false)), 
                   fecha_cotizacion, 
                   "", //tipo plazo entrega
                   0, //dias plazoentrega
                   "", //condicion de pago
                   "", //tipotransporte
                   0, //diasflete
                   0.0, //costoflete
                   1, //codigomonedaflete
                   destinoArchivo1, //fotocotizacion //referencia
                   area_justificacion1.getText().trim(), //justificacion
                   area_observaciones1.getText().trim(), //observacion    
                   chk_recomendacion1.isSelected(), 
                   false, 
                   "", 
                   false, 
                   "", 
                   false, 
                   0,
                   fecha_carga_compras,     
                   true
                );       
                    
           
                modelo_cotizacion = cotizacion.crear_posicion();
                txt_alternativa1.setText(modelo_cotizacion.getStatus().toString());
                if (!modelo_cotizacion.isStatus()){
                    guardar = false;
                }   
                
                       
            }
            if(chk_alternativa2.isSelected()){
               fecha_cotizacion = funciones.fecha_convertir_date(date_cotizar2, 1);
               cotizacion = new ctrl_cotizacion(
                   0, 
                   8, 
                   "", 
                   "", 
                   Integer.parseInt(lbl_idsolicitud.getText()), 
                   Integer.parseInt(lbl_desidmaterial.getText()), 
                   Integer.parseInt(txt_posicion.getText()), 
                   Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()), 
                   Integer.parseInt(cmb_moneda2.getSelectedItem().toString().substring(0,3).trim()), 
                   Integer.parseInt(spin_cantidad2.getValue().toString()),
                   Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario2.getText().trim(),false)), 
                   Double.parseDouble(funciones.separadormilesflotante(txt_total2.getText().trim(),false)), 
                   fecha_cotizacion, 
                   "", //tipo plazo entrega
                   0, //dias plazoentrega
                   "", //condicion de pago
                   "", //tipotransporte
                   0, //diasflete
                   0.0, //costoflete
                   1, //codigomonedaflete
                   destinoArchivo2, //fotocotizacion //referencia
                   area_justificacion1.getText().trim(), //justificacion
                   area_observaciones2.getText().trim(), //observacion    
                   chk_recomendacion2.isSelected(), 
                   false, 
                   "", 
                   false, 
                   "", 
                   false, 
                   0,
                   fecha_carga_compras,     
                   true
                );       
                    
           
                modelo_cotizacion = cotizacion.crear_posicion();
                txt_alternativa2.setText(modelo_cotizacion.getStatus().toString());
                if (!modelo_cotizacion.isStatus()){
                    guardar = false;
                }     
            }
            
            if(chk_alternativa3.isSelected()){
                fecha_cotizacion = funciones.fecha_convertir_date(date_cotizar3, 1);
                cotizacion = new ctrl_cotizacion(
                   0, 
                   8, 
                   "", 
                   "", 
                   Integer.parseInt(lbl_idsolicitud.getText()), 
                   Integer.parseInt(lbl_desidmaterial.getText()), 
                   Integer.parseInt(txt_posicion.getText()), 
                   Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()), 
                   Integer.parseInt(cmb_moneda3.getSelectedItem().toString().substring(0,3).trim()), 
                   Integer.parseInt(spin_cantidad3.getValue().toString()),
                   Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario3.getText().trim(),false)), 
                   Double.parseDouble(funciones.separadormilesflotante(txt_total3.getText().trim(),false)), 
                   fecha_cotizacion, 
                   "", //tipo plazo entrega
                   0, //dias plazoentrega
                   "", //condicion de pago
                   "", //tipotransporte
                   0, //diasflete
                   0.0, //costoflete
                   1, //codigomonedaflete
                   destinoArchivo3, //fotocotizacion //referencia
                   area_justificacion1.getText().trim(), //justificacion
                   area_observaciones3.getText().trim(), //observacion    
                   chk_recomendacion3.isSelected(), 
                   false, 
                   "", 
                   false, 
                   "", 
                   false, 
                   0,
                   fecha_carga_compras,     
                   true
                );       
                    
           
                modelo_cotizacion = cotizacion.crear_posicion();
                txt_alternativa3.setText(modelo_cotizacion.getStatus().toString());
                if (modelo_cotizacion.isStatus()){
                    guardar = false;
                }                
            }
            if (guardar){
                JOptionPane.showMessageDialog(null, "SOLICITUD " + Integer.parseInt(lbl_idsolicitud.getText()) + " GUARDADA PARA SU APROBACION");
                frm_cotizacion.bot_reiniciar.doClick();
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR EN GUARDAR EN UNA O VARIAS COTIZACIONES DE LA SOLICITUD " + Integer.parseInt(lbl_idsolicitud.getText()));
            }
        }
        
       
       
       
        
    }//GEN-LAST:event_bot_guardarActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void chk_alternativa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_alternativa2ActionPerformed
         if (chk_alternativa2.isSelected()){
            txt_preciounitario2.setEnabled(true);
            cmb_moneda2.setEnabled(true);
            spin_cantidad2.setEnabled(true);
            //txt_total2.setEnabled(true);
            
            chk_recomendacion2.setEnabled(true); 
            
            date_cotizar2.setEnabled(true);
            
            
            area_observaciones2.setEnabled(true);
            
        }
        else{
            txt_preciounitario2.setEnabled(false);
            cmb_moneda2.setEnabled(false);
            spin_cantidad2.setEnabled(false);
            txt_total2.setEnabled(false);
            
            
            date_cotizar2.setEnabled(false);
            
            chk_recomendacion2.setEnabled(false);  
            
            
            area_observaciones2.setEnabled(false);
            
        }    
    }//GEN-LAST:event_chk_alternativa2ActionPerformed

    private void spin_cantidad2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_cantidad2StateChanged
        // TODO add your handling code here:
        String monto = null;

        if (!txt_preciounitario2.getText().trim().equals("")){
            Double valor = Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario2.getText().trim(),false)) * Double.parseDouble(spin_cantidad2.getValue().toString());
            
            monto = String.valueOf(BigDecimal.valueOf(Math.rint((valor)*100)/100));
 
            monto = monto.replace(".",",");
            txt_total2.setText(funciones.separadormilesflotante(monto,true));
        }
    }//GEN-LAST:event_spin_cantidad2StateChanged

    private void txt_preciounitario2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_preciounitario2KeyReleased
       String monto = null;
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10) || (evt.getKeyCode() == 44) ){       
            Double valor = Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario2.getText().trim(),false)) * Double.parseDouble(spin_cantidad2.getValue().toString());
            
            monto = String.valueOf(BigDecimal.valueOf(Math.rint((valor)*100)/100));
 
            monto = monto.replace(".",",");
            
            txt_total2.setText(monto);
            
            txt_preciounitario2.setText(funciones.separadormilesflotante(txt_preciounitario2.getText().trim(),true));
            txt_total2.setText(funciones.separadormilesflotante(txt_total2.getText().trim(),true));
        }
        else{
            
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - ALTERNATIVA PROVEEDORES", JOptionPane.ERROR_MESSAGE,null);
                txt_preciounitario2.setText("");
                txt_total2.setText("");
               
        }  
    }//GEN-LAST:event_txt_preciounitario2KeyReleased

    private void cmb_moneda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_moneda2ActionPerformed
        if (evt.getModifiers() != 0){
            if (!cmb_moneda2.getSelectedItem().equals("Seleccione...")){
                lbl_moneda2.setText(cmb_moneda2.getSelectedItem().toString().substring(5, cmb_moneda2.getSelectedItem().toString().length()));
            }
            else{
                lbl_moneda2.setText("");
            }
        }
    }//GEN-LAST:event_cmb_moneda2ActionPerformed

    private void chk_alternativa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_alternativa3ActionPerformed
       if (chk_alternativa3.isSelected()){
            txt_preciounitario3.setEnabled(true);
            cmb_moneda3.setEnabled(true);
            spin_cantidad3.setEnabled(true);
            //txt_total3.setEnabled(true);
            
                       
            chk_recomendacion3.setEnabled(true); 
            
            date_cotizar3.setEnabled(true);
            
           
            area_observaciones3.setEnabled(true);
            
        }
        else{
            txt_preciounitario3.setEnabled(false);
            cmb_moneda3.setEnabled(false);
            spin_cantidad3.setEnabled(false);
            txt_total3.setEnabled(false);
            
        
            date_cotizar3.setEnabled(false);
            
            chk_recomendacion3.setEnabled(false);  
            
            
            area_observaciones3.setEnabled(false);
            
        }    
    }//GEN-LAST:event_chk_alternativa3ActionPerformed

    private void spin_cantidad3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_cantidad3StateChanged
        // TODO add your handling code here:
        String monto = null;

        if (!txt_preciounitario3.getText().trim().equals("")){
            Double valor = Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario3.getText().trim(),false)) * Double.parseDouble(spin_cantidad3.getValue().toString());
            
            monto = String.valueOf(BigDecimal.valueOf(Math.rint((valor)*100)/100));

            monto = monto.replace(".",",");
            txt_total3.setText(funciones.separadormilesflotante(monto,true));
        }
    }//GEN-LAST:event_spin_cantidad3StateChanged

    private void txt_preciounitario3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_preciounitario3KeyReleased
     String monto = null;
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10) || (evt.getKeyCode() == 44) ){       
            Double valor = Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario3.getText().trim(),false)) * Double.parseDouble(spin_cantidad3.getValue().toString());
            
            monto = String.valueOf(BigDecimal.valueOf(Math.rint((valor)*100)/100));

            monto = monto.replace(".",",");
            
            txt_total3.setText(monto);
            
            txt_preciounitario3.setText(funciones.separadormilesflotante(txt_preciounitario3.getText().trim(),true));
            txt_total3.setText(funciones.separadormilesflotante(txt_total3.getText().trim(),true));
         }
        else{
            
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - ALTERNATIVA PROVEEDORES", JOptionPane.ERROR_MESSAGE,null);
                txt_preciounitario3.setText("");
                txt_total3.setText("");
               
        }  
    }//GEN-LAST:event_txt_preciounitario3KeyReleased

    private void cmb_moneda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_moneda3ActionPerformed
        if (evt.getModifiers() != 0){
            if (!cmb_moneda3.getSelectedItem().equals("Seleccione...")){
                lbl_moneda3.setText(cmb_moneda3.getSelectedItem().toString().substring(5, cmb_moneda3.getSelectedItem().toString().length()));
            }
            else{
                lbl_moneda3.setText("");
            }
        }
    }//GEN-LAST:event_cmb_moneda3ActionPerformed

    private void cmb_moneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_moneda1ActionPerformed
        if (evt.getModifiers() != 0){
            if (!cmb_moneda1.getSelectedItem().equals("Seleccione...")){
                lbl_moneda1.setText(cmb_moneda1.getSelectedItem().toString().substring(5, cmb_moneda1.getSelectedItem().toString().length()));
            }
            else{
                lbl_moneda1.setText("");
            }
        }
    }//GEN-LAST:event_cmb_moneda1ActionPerformed

    private void txt_preciounitario1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_preciounitario1KeyReleased
        String monto = null;

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10) || (evt.getKeyCode() == 44) ){
            Double valor = Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario1.getText().trim(),false)) * Double.parseDouble(spin_cantidad1.getValue().toString());
            
            monto = String.valueOf(BigDecimal.valueOf(Math.rint((valor)*100)/100));

            monto = monto.replace(".",",");
            
            txt_total1.setText(monto);
            
            txt_preciounitario1.setText(funciones.separadormilesflotante(txt_preciounitario1.getText().trim(),true));
            txt_total1.setText(funciones.separadormilesflotante(txt_total1.getText().trim(),true));
          }
        else{

            JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
            txt_preciounitario1.setText("");
            txt_total1.setText("");

        }
    }//GEN-LAST:event_txt_preciounitario1KeyReleased

    private void spin_cantidad1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_cantidad1StateChanged
        // TODO add your handling code here:
        String monto = null;

        if (!txt_preciounitario1.getText().trim().equals("")){
            Double valor = Double.parseDouble(funciones.separadormilesflotante(txt_preciounitario1.getText().trim(),false)) * Double.parseDouble(spin_cantidad1.getValue().toString());
            
            monto = String.valueOf(BigDecimal.valueOf(Math.rint((valor)*100)/100));

             monto = monto.replace(".",",");
            txt_total1.setText(funciones.separadormilesflotante(monto,true));
        }
    }//GEN-LAST:event_spin_cantidad1StateChanged

    private void chk_alternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_alternativa1ActionPerformed

        if (chk_alternativa1.isSelected()){
            txt_preciounitario1.setEnabled(true);
            cmb_moneda1.setEnabled(true);
            spin_cantidad1.setEnabled(true);
            txt_total1.setEnabled(true);

            chk_recomendacion1.setEnabled(true);

            date_cotizar1.setEnabled(true);
           
            area_observaciones1.setEnabled(true);

        }
        else{
            txt_preciounitario1.setEnabled(false);
            cmb_moneda1.setEnabled(false);
            spin_cantidad1.setEnabled(false);
            txt_total1.setEnabled(false);

            date_cotizar1.setEnabled(false);

            chk_recomendacion1.setEnabled(false);
            
            area_observaciones1.setEnabled(false);
        }
    }//GEN-LAST:event_chk_alternativa1ActionPerformed

    private void bot_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardar1ActionPerformed
       
                           
        destinoArchivo1 = "\\\\192.168.0.3\\dist\\Documentos_SisTimaca\\" + archivo.getName();
        //destinoArchivo1 ="C:\\Users\\ruben\\Desktop\\" + archivo.getName();

        if(origenArchivo !=null){
            try {
                Path origenPath =  Paths.get(origenArchivo);
                Path destinoPath = Paths.get(destinoArchivo1);
                //sobreescribir el fichero de destino si existe y lo copia
                Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
                //destinoArchivo1 ="C:\\\\Users\\\\ruben\\\\Desktop\\\\" + archivo.getName();
                destinoArchivo1 = "\\\\\\\\192.168.0.3\\\\dist\\\\Documentos_SisTimaca\\\\" + archivo.getName();
                //JOptionPane.showMessageDialog(null, destinoArchivo1);
                bot_guardar1.setEnabled(false);
                lbl_guardar1.setText("Guardado");
                lbl_guardar1.setForeground(Color.GREEN);
                JOptionPane.showMessageDialog(null, "ARCHIVO " + archivo.getName() + " GUARDADO SATISFACTORIAMENTE");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en Guardar Archivo " + ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error en Guardar Archivo " + ex.getMessage());
            }
        }
      
    }//GEN-LAST:event_bot_guardar1ActionPerformed

    private void bot_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscar1ActionPerformed
 
        JFileChooser file=new JFileChooser();
        file.showOpenDialog(file);
        origenArchivo  =file.getSelectedFile().toString();

        archivo = file.getSelectedFile();
        bot_guardar1.setEnabled(true);
        
    }//GEN-LAST:event_bot_buscar1ActionPerformed

    private void bot_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscar2ActionPerformed
         JFileChooser file=new JFileChooser();
        file.showOpenDialog(file);
        origenArchivo  =file.getSelectedFile().toString();

        archivo = file.getSelectedFile();
        bot_guardar2.setEnabled(true);
    }//GEN-LAST:event_bot_buscar2ActionPerformed

    private void bot_guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardar2ActionPerformed
       destinoArchivo2 = "\\\\192.168.0.3\\dist\\Documentos_SisTimaca\\" + archivo.getName();
       // destinoArchivo2 ="C:\\Users\\ruben\\Desktop\\" + archivo.getName();

        if(origenArchivo !=null){
            try {
                Path origenPath =  Paths.get(origenArchivo);
                Path destinoPath = Paths.get(destinoArchivo2);
                //sobreescribir el fichero de destino si existe y lo copia
                Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
                //destinoArchivo2 ="C:\\\\Users\\\\ruben\\\\Desktop\\\\" + archivo.getName();
                destinoArchivo1 = "\\\\\\\\192.168.0.3\\\\dist\\\\Documentos_SisTimaca\\\\" + archivo.getName();
                bot_guardar2.setEnabled(false);
                lbl_guardar2.setText("Guardado");
                lbl_guardar2.setForeground(Color.GREEN);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en Guardar Archivo " + ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error en Guardar Archivo " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_bot_guardar2ActionPerformed

    private void bot_buscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscar3ActionPerformed
         JFileChooser file=new JFileChooser();
        file.showOpenDialog(file);
        origenArchivo  =file.getSelectedFile().toString();

        archivo = file.getSelectedFile();
        bot_guardar3.setEnabled(true);
    }//GEN-LAST:event_bot_buscar3ActionPerformed

    private void bot_guardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardar3ActionPerformed
       destinoArchivo3 = "\\\\192.168.0.3\\dist\\Documentos_SisTimaca\\" + archivo.getName();
       // destinoArchivo3 ="C:\\Users\\ruben\\Desktop\\" + archivo.getName();

        if(origenArchivo !=null){
            try {
                Path origenPath =  Paths.get(origenArchivo);
                Path destinoPath = Paths.get(destinoArchivo3);
                //sobreescribir el fichero de destino si existe y lo copia
                Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
                //destinoArchivo3 ="C:\\\\Users\\\\ruben\\\\Desktop\\\\" + archivo.getName();
                destinoArchivo3 = "\\\\\\\\192.168.0.3\\\\dist\\\\Documentos_SisTimaca\\\\" + archivo.getName();
                
                bot_guardar3.setEnabled(false);
                lbl_guardar3.setText("Guardado");
                lbl_guardar3.setForeground(Color.GREEN);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en Guardar Archivo " + ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error en Guardar Archivo " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_bot_guardar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_alternativapart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_alternativapart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_alternativapart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_alternativapart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_alternativapart("","","","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_justificacion1;
    private javax.swing.JTextArea area_observaciones1;
    private javax.swing.JTextArea area_observaciones2;
    private javax.swing.JTextArea area_observaciones3;
    private javax.swing.JButton bot_buscar1;
    private javax.swing.JButton bot_buscar2;
    private javax.swing.JButton bot_buscar3;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_guardar;
    private javax.swing.JButton bot_guardar1;
    private javax.swing.JButton bot_guardar2;
    private javax.swing.JButton bot_guardar3;
    private javax.swing.JCheckBox chk_alternativa1;
    private javax.swing.JCheckBox chk_alternativa2;
    private javax.swing.JCheckBox chk_alternativa3;
    private javax.swing.JCheckBox chk_recomendacion1;
    private javax.swing.JCheckBox chk_recomendacion2;
    private javax.swing.JCheckBox chk_recomendacion3;
    private javax.swing.JComboBox<String> cmb_moneda1;
    private javax.swing.JComboBox<String> cmb_moneda2;
    private javax.swing.JComboBox<String> cmb_moneda3;
    private com.toedter.calendar.JDateChooser date_cotizar1;
    private com.toedter.calendar.JDateChooser date_cotizar2;
    private com.toedter.calendar.JDateChooser date_cotizar3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbl_cantidad1;
    private javax.swing.JLabel lbl_cantidad2;
    private javax.swing.JLabel lbl_cantidad3;
    private javax.swing.JLabel lbl_cantidadautorizada;
    private javax.swing.JLabel lbl_descantidad;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_desidmaterial;
    private javax.swing.JLabel lbl_desmaterial;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_fechacotizacion1;
    private javax.swing.JLabel lbl_fechacotizacion2;
    private javax.swing.JLabel lbl_fechacotizacion3;
    private javax.swing.JLabel lbl_guardar1;
    private javax.swing.JLabel lbl_guardar2;
    private javax.swing.JLabel lbl_guardar3;
    private javax.swing.JLabel lbl_idmaterial;
    private javax.swing.JLabel lbl_idsolicitud;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_moneda1;
    private javax.swing.JLabel lbl_moneda2;
    private javax.swing.JLabel lbl_moneda3;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_preciounitario1;
    private javax.swing.JLabel lbl_preciounitario2;
    private javax.swing.JLabel lbl_preciounitario3;
    private javax.swing.JLabel lbl_referencia;
    private javax.swing.JLabel lbl_referencia1;
    private javax.swing.JLabel lbl_referencia3;
    private javax.swing.JLabel lbl_referencia5;
    private javax.swing.JLabel lbl_referencia6;
    private javax.swing.JLabel lbl_referencia7;
    private javax.swing.JLabel lbl_total1;
    private javax.swing.JLabel lbl_total2;
    private javax.swing.JLabel lbl_total3;
    private javax.swing.JLabel lbl_und1;
    private javax.swing.JLabel lbl_und2;
    private javax.swing.JLabel lbl_und3;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_alternativa1;
    private javax.swing.JPanel panel_alternativa2;
    private javax.swing.JPanel panel_alternativa3;
    private javax.swing.JSpinner spin_cantidad1;
    private javax.swing.JSpinner spin_cantidad2;
    private javax.swing.JSpinner spin_cantidad3;
    protected static javax.swing.JTextField txt_alternativa1;
    protected static javax.swing.JTextField txt_alternativa2;
    protected static javax.swing.JTextField txt_alternativa3;
    private javax.swing.JTextField txt_posicion;
    private javax.swing.JTextField txt_preciounitario1;
    private javax.swing.JTextField txt_preciounitario2;
    private javax.swing.JTextField txt_preciounitario3;
    private javax.swing.JTextField txt_total1;
    private javax.swing.JTextField txt_total2;
    private javax.swing.JTextField txt_total3;
    // End of variables declaration//GEN-END:variables
}
