/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import java.awt.Color;
import controlador.ctrl_ordendecompra;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.class_ordendecompra;

/**
 *
 * @author ruben
 */
public class frm_analisisresultado extends javax.swing.JFrame {

    /**
     * Creates new form frm_cotizacion
     */
    public frm_analisisresultado() {
        initComponents();
        this.getContentPane().setBackground(new Color(240,240,240)); 
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_posicion = new javax.swing.JTextField();
        txt_idcompra = new javax.swing.JTextField();
        lbl_nrocotizacion = new javax.swing.JLabel();
        txt_numerosolicitud = new javax.swing.JTextField();
        bot_buscar = new javax.swing.JButton();
        lbl_titulodetallesolicitud = new javax.swing.JLabel();
        bot_agregarposicion = new javax.swing.JButton();
        bot_verdocumento = new javax.swing.JButton();
        lbl_titulocotizacion = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_resumensolicitud = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_resumensolicitud1 = new javax.swing.JTable();
        lbl_titulodetallesolicitud1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        table_resumensolicitud2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        lbl_encabezadoalmacen1 = new javax.swing.JLabel();
        lbl_imagentimaca1 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cancelar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        txt_posicion.setText("0");

        txt_idcompra.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrocotizacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nrocotizacion.setText("NRO DE COTIZACION");
        getContentPane().add(lbl_nrocotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_numerosolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numerosolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numerosolicitudKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numerosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, -1));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscar.setIcon(new ImageIcon("imagenes/icon/buscar.png"));
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));
        complemento.DisableBorderButton(bot_buscar);

        lbl_titulodetallesolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallesolicitud.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallesolicitud.setText("ANALISIS RESULTADOS");
        getContentPane().add(lbl_titulodetallesolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        bot_agregarposicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_agregarposicion.setIcon(new ImageIcon("imagenes/icon/autorizar.png"));
        bot_agregarposicion.setText("AUTORIZAR COTIZACION");
        bot_agregarposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregarposicionActionPerformed(evt);
            }
        });
        getContentPane().add(bot_agregarposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, 40));
        complemento.DisableBorderButton(bot_agregarposicion);

        bot_verdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_verdocumento.setIcon(new ImageIcon("imagenes/icon/documento.png"));
        bot_verdocumento.setText("VER DOCUMENTO");
        bot_verdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_verdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 190, 40));
        complemento.DisableBorderButton(bot_verdocumento);

        lbl_titulocotizacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulocotizacion.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulocotizacion.setText("RESUMEN DE COTIZACIONES POR SOLICITUD");
        getContentPane().add(lbl_titulocotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        table_resumensolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "INDICADOR", "PROVEEDOR", "RIF", "RESULTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_resumensolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_resumensolicitudMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(table_resumensolicitud);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 1270, 120));

        table_resumensolicitud1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID SOLICITUD", "CANTIDAD DE COTIZACIONES", "CEDULA", "NOMBRE", "DESCRIPCION AREA", "PROYECTO", "EMPRESA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_resumensolicitud1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_resumensolicitud1MousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(table_resumensolicitud1);
        if (table_resumensolicitud1.getColumnModel().getColumnCount() > 0) {
            table_resumensolicitud1.getColumnModel().getColumn(4).setHeaderValue("DESCRIPCION AREA");
            table_resumensolicitud1.getColumnModel().getColumn(5).setHeaderValue("PROYECTO");
            table_resumensolicitud1.getColumnModel().getColumn(6).setHeaderValue("EMPRESA");
        }

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1270, 90));

        lbl_titulodetallesolicitud1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallesolicitud1.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallesolicitud1.setText("COTIZACIONES");
        getContentPane().add(lbl_titulodetallesolicitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        table_resumensolicitud2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID COTIZACION", "PROVEEDOR", "RIF", "UBICACION", "TOTAL EN Bs", "COBERTURA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_resumensolicitud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_resumensolicitud2MousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(table_resumensolicitud2);
        if (table_resumensolicitud2.getColumnModel().getColumnCount() > 0) {
            table_resumensolicitud2.getColumnModel().getColumn(4).setHeaderValue("TOTAL EN Bs");
        }

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 1270, 90));

        jPanel6.setBackground(new java.awt.Color(35, 35, 35));
        jPanel6.setLayout(null);

        lbl_encabezadoalmacen1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen1.setText("ANÁLISIS DE RESULTADOS");
        jPanel6.add(lbl_encabezadoalmacen1);
        lbl_encabezadoalmacen1.setBounds(110, 20, 400, 29);

        lbl_imagentimaca1.setIcon(new ImageIcon("imagenes/logo.png"));
        jPanel6.add(lbl_imagentimaca1);
        lbl_imagentimaca1.setBounds(10, 0, 90, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new ImageIcon("imagenes/icon/reiniciar.png"));
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel6.add(bot_reiniciar);
        bot_reiniciar.setBounds(1130, 20, 113, 25);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cancelar.setIcon(new ImageIcon("imagenes/icon/cancelar.png"));
        bot_cancelar.setText("Cancelar");
        bot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cancelarActionPerformed(evt);
            }
        });
        jPanel6.add(bot_cancelar);
        bot_cancelar.setBounds(1250, 20, 91, 25);
        complemento.DisableBorderButton(bot_cancelar);

        lbl_usuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_usuario.setText("USUARIO");
        jPanel6.add(lbl_usuario);
        lbl_usuario.setBounds(1033, 10, 67, 17);

        lbl_nombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel6.add(lbl_nombres);
        lbl_nombres.setBounds(1030, 30, 72, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
       /*ctrl_ordendecompra ordendecompra = null;
       
       if(!txt_numerosolicitud.getText().trim().equals("")){
           ordendecompra = new ctrl_ordendecompra(0,"",Integer.parseInt(txt_numerosolicitud.getText().trim()),0,0,0,0.0,0.0,"","","");
           
           ordendecompra.consultar_solicitud(table_posicionsolicitud);
       }
       */
       
       
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void bot_agregarposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregarposicionActionPerformed
       /*ctrl_ordendecompra ordendecompra = null;
       DefaultTableModel modelotablasolicitud = (DefaultTableModel) table_posicionsolicitud.getModel();
       DefaultTableModel modelotablacotizacion = (DefaultTableModel) table_posicioncotizacion.getModel();
       
       String fecha_cotizacion;
       class_ordendecompra modelo_ordendecompra = null;
       Integer fila;
       
       fila = table_posicionsolicitud.getSelectedRow();
       
       //fecha_cotizacion = funciones.fecha_bd_usuario(date_cotizacion, 2);
      
       
       
        if (!txt_preciounitario.getText().equals("") && !txt_descripcionproveedor.getText().trim().equals("") &&
            !txt_rifproveedor.getText().trim().equals("")
        ){*/
                    
          /* cotizacion = new ctrl_cotizacion(
                   Integer.parseInt(txt_idcompra.getText().trim()), 
                   txt_rifproveedor.getText().trim(), 
                   Integer.parseInt(txt_numerosolicitud.getText().trim()), 
                   Integer.parseInt(txt_posicion.getText().trim()), 
                   Integer.parseInt(table_posicionsolicitud.getValueAt(fila,1).toString()),
                   Integer.parseInt(spin_cantidadcotizada.getValue().toString()), 
                   Double.parseDouble(txt_preciounitario.getText().trim()), 
                   Double.parseDouble(txt_descripcionproveedor.getText().trim()), 
                   fecha_cotizacion
            );*/
           
          /* try {
               modelo_ordendecompra = ordendecompra.crear_posicion(table_posicioncotizacion);
               
           } catch (SQLException ex) {
               Logger.getLogger(frm_solicitud.class.getName()).log(Level.SEVERE, null, ex);
           }
            txt_idcompra.setText(modelo_ordendecompra.getId_compra().toString());
            txt_posicion.setText(modelo_ordendecompra.getPosicion().toString());
        }
        else{
                JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS");
//                modelotabla.setRowCount(0);
        }*/
    }//GEN-LAST:event_bot_agregarposicionActionPerformed

    private void bot_verdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdocumentoActionPerformed
       
        class_ordendecompra modelo_ordendecompra = null;
        ctrl_ordendecompra ordendecompra = null;
        
            ordendecompra = new ctrl_ordendecompra(
                   Integer.parseInt(txt_idcompra.getText().trim()), 
                   "", 
                   0,  
                   0, 
                   0,
                   0, 
                   0.0, 
                   0.0, 
                   "", 
                   "",
                   ""
            );
        
                
                try {
                    ordendecompra.generar_documentoordendecompra();
                } catch (DocumentException | IOException ex) {
                    
                }
        
    }//GEN-LAST:event_bot_verdocumentoActionPerformed

    private void txt_numerosolicitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numerosolicitudKeyReleased
               
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARACTER NO VALIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numerosolicitud.setText("");
             }   
        }            
        
            
    }//GEN-LAST:event_txt_numerosolicitudKeyReleased

    private void table_resumensolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_resumensolicitudMousePressed
        /*ctrl_reserva reserva = null;

        fila_reserva = table_resumensolicitud.getSelectedRow();

        reserva = new ctrl_reserva(

            Integer.parseInt(table_resumensolicitud.getValueAt(fila_reserva, 0).toString()),
            0,
            0,
            "",
            0,
            0, //numero de material
            "",             // descripcion de material
            0,
            "",
            0,
            "",
            0,
            0,
            "", //fecha reserva
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        );

        reserva.consultar_reserva_detalle_autorizada(Integer.parseInt(frm_principal.lbl_nivel.getText()),table_detallereserva);*/

    }//GEN-LAST:event_table_resumensolicitudMousePressed

    private void table_resumensolicitud1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_resumensolicitud1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_resumensolicitud1MousePressed

    private void table_resumensolicitud2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_resumensolicitud2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_resumensolicitud2MousePressed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_analisisresultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_agregarposicion;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cancelar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_verdocumento;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbl_encabezadoalmacen1;
    private javax.swing.JLabel lbl_imagentimaca1;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrocotizacion;
    private javax.swing.JLabel lbl_titulocotizacion;
    private javax.swing.JLabel lbl_titulodetallesolicitud;
    private javax.swing.JLabel lbl_titulodetallesolicitud1;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable table_resumensolicitud;
    private javax.swing.JTable table_resumensolicitud1;
    private javax.swing.JTable table_resumensolicitud2;
    private javax.swing.JTextField txt_idcompra;
    private javax.swing.JTextField txt_numerosolicitud;
    private javax.swing.JTextField txt_posicion;
    // End of variables declaration//GEN-END:variables
}
