/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_cotizacion;
import controlador.ctrl_usuario;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import model.class_cotizacion;
import model.class_usuario;
import static view.frm_aprobarcotizacionprocura.lbl_usuario;

/**
 *
 * @author ruben
 */
public class frm_autorizarcotizacionprocura extends javax.swing.JFrame {

    /**
     * Creates new form frm_aprobarcotizacionprocura
     */
    public frm_autorizarcotizacionprocura(String id_solicitud,String posicion,String id_material,String des_material,Object cantidad,String umb) {
        initComponents();
        this.setTitle("SISTIMACA - AUTORIZAR COTIZACIONES");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setLocationRelativeTo(null);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        lbl_idsolicitud.setText(id_solicitud);
        lbl_desidmaterial.setText(id_material);
        lbl_desmaterial.setText(des_material);
        lbl_descantidad.setText(cantidad.toString());
        txt_posicion.setText(posicion);
        lbl_umb.setText(umb);
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){}
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_posicion = new javax.swing.JTextField();
        lbl_idmaterial = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_cantidadautorizada = new javax.swing.JLabel();
        lbl_nrosolicitud = new javax.swing.JLabel();
        lbl_desidmaterial = new javax.swing.JLabel();
        lbl_desmaterial = new javax.swing.JLabel();
        lbl_descantidad = new javax.swing.JLabel();
        lbl_idsolicitud = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_titulosolicitud = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detalle_cotizacion = new javax.swing.JTable();
        bot_autorizarcotizacion = new javax.swing.JButton();
        bot_vercotizacion = new javax.swing.JButton();
        lbl_umb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_idmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idmaterial.setText("ID MATERIAL");
        getContentPane().add(lbl_idmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("DESCRIPCION MATERIAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lbl_cantidadautorizada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadautorizada.setText("CANTIDAD COTIZADA");
        getContentPane().add(lbl_cantidadautorizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("DOCUMENTO SOLICITUD");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lbl_desidmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desidmaterial.setText("jLabel1");
        getContentPane().add(lbl_desidmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        lbl_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desmaterial.setText("jLabel1");
        getContentPane().add(lbl_desmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        lbl_descantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descantidad.setText("jLabel1");
        getContentPane().add(lbl_descantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        lbl_idsolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idsolicitud.setText("jLabel1");
        getContentPane().add(lbl_idsolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("AUTORIZAR COTIZACIONES");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(260, 10, 250, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 240, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1210, 20, 100, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(580, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(580, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(860, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        lbl_titulosolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulosolicitud.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulosolicitud.setText("ALTERNATIVAS DE PROVEEDORES");
        getContentPane().add(lbl_titulosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        tabla_detalle_cotizacion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tabla_detalle_cotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "RIF", "NOMBRE", "CONTACTO", "CANTIDAD A COTIZAR", "UMB", "PRECIO UNITARIO", "PRECIO TOTAL", "MONEDA", "PLAZO ENTREGA", "CONDICIÓN PAGO", "FECHA COTIZACIÓN", "RECOMENDADO COMPRADOR", "JUSTIFICACIÓN", "archivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_detalle_cotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_detalle_cotizacionMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_detalle_cotizacion);
        if (tabla_detalle_cotizacion.getColumnModel().getColumnCount() > 0) {
            tabla_detalle_cotizacion.getColumnModel().getColumn(0).setMinWidth(0);
            tabla_detalle_cotizacion.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabla_detalle_cotizacion.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla_detalle_cotizacion.getColumnModel().getColumn(14).setMinWidth(0);
            tabla_detalle_cotizacion.getColumnModel().getColumn(14).setPreferredWidth(0);
            tabla_detalle_cotizacion.getColumnModel().getColumn(14).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1300, 230));

        bot_autorizarcotizacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_autorizarcotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autorizar.png"))); // NOI18N
        bot_autorizarcotizacion.setText("AUTORIZAR COTIZACIÓN");
        bot_autorizarcotizacion.setEnabled(false);
        bot_autorizarcotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_autorizarcotizacionActionPerformed(evt);
            }
        });
        getContentPane().add(bot_autorizarcotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 270, 40));
        complemento.DisableBorderButton(bot_autorizarcotizacion);

        bot_vercotizacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_vercotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        bot_vercotizacion.setText("VER COTIZACIÓN");
        bot_vercotizacion.setEnabled(false);
        bot_vercotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_vercotizacionActionPerformed(evt);
            }
        });
        getContentPane().add(bot_vercotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 270, 40));
        complemento.DisableBorderButton(bot_autorizarcotizacion);

        lbl_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb.setText("jLabel1");
        getContentPane().add(lbl_umb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_autorizarcotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_autorizarcotizacionActionPerformed
        ctrl_cotizacion cotizacion = null;
       
        String fecha_cotizacion;
        class_cotizacion modelo_cotizacion = null;
        Integer filacotizacion;
        Integer respuesta;
        String firma;
        class_usuario modelo_usuario;
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();

        
        ctrl_usuario usuario = new ctrl_usuario(
                      Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                       "", 
                       "", 
                       "", 
                       "", 
                       0, 
                       "",
                       0,
                       "",
                       0,
                       true,
                       ""
            );

            modelo_usuario = usuario.buscar_usuario();

        respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR AUTORIZAR UNA COTIZACION, DESEA CONTINUAR?");
        
            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
       
                                filacotizacion = tabla_detalle_cotizacion.getSelectedRow();

                                fecha_cotizacion = funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2);

                                cotizacion = new ctrl_cotizacion(
                                        Integer.parseInt(tabla_detalle_cotizacion.getValueAt(filacotizacion,0).toString()), 
                                        0, 
                                        tabla_detalle_cotizacion.getValueAt(filacotizacion,1).toString(),
                                        "", 
                                        Integer.parseInt(lbl_idsolicitud.getText()), 
                                        0, 
                                        Integer.parseInt(txt_posicion.getText()), 
                                        0, 
                                        0, 
                                        0,
                                        0.0, 
                                        0.0, 
                                        "", 
                                        "", //tipo plazo entrega
                                        0, //dias plazoentrega
                                        "", //condicion de pago
                                        "", //tipotransporte
                                        0, //diasflete
                                        0.0, //costoflete
                                        0, //codigomonedaflete
                                        "", //fotocotizacion
                                        "", //justificacion
                                        "", //observacion     
                                        false, 
                                        false, 
                                        "", 
                                        true, 
                                        fecha_cotizacion, 
                                        false, 
                                        0,
                                        "",     
                                        true
                                    );   
                            try {
                                if(cotizacion.autorizar_cotizacion_posicion()){
                                    JOptionPane.showMessageDialog(null, "AUTORIZADO COTIZACION PARA ORDEN DE COMPRA " + tabla_detalle_cotizacion.getValueAt(filacotizacion, 1).toString() + " " + tabla_detalle_cotizacion.getValueAt(filacotizacion, 2).toString() + " SOLICITUD NRO " + lbl_idsolicitud.getText() );  
                                    
                                    //ANULAR COTIZACIONES Y SOLICITUDES RELACIONADAS
                                    
                                     respuesta = JOptionPane.showConfirmDialog(null,"AUTORIZA ANULAR LAS OTRAS COTIZACIONES DE LA SOLICITUD NRO " + lbl_idsolicitud.getText());
        
                                     if (respuesta == 0){
                                        if(cotizacion.anular_cotizacion_solicitud_posicion()){
                                            JOptionPane.showMessageDialog(null, "ANULADO LAS COTIZACIONES NO AUTORIZADAS DE LA SOLICITUD NRO " + lbl_idsolicitud.getText() );  
                                        }
                                     }
                                                                     
                                    
                                    frm_autorizarcotizacion.bot_reiniciar.doClick();
                                    this.dispose();
                                }
                            } catch (SQLException ex) {

                            }
                        }
                        else{

                            JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                    }                          
    
                }
                
    }//GEN-LAST:event_bot_autorizarcotizacionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       ctrl_cotizacion cotizacion = null;
        Integer fila_solicitud;

               cotizacion = new ctrl_cotizacion(
                   0, 
                   0, 
                   "", 
                   "", 
                   Integer.parseInt(lbl_idsolicitud.getText()), 
                   0, 
                   Integer.parseInt(txt_posicion.getText()), 
                   Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()), 
                   0, 
                   0,
                   0.0, 
                   0.0, 
                   "", 
                   "", //tipo plazo entrega
                    0, //dias plazoentrega
                   "", //condicion de pago
                   "", //tipotransporte
                    0, //diasflete
                    0.0, //costoflete
                    0, //codigomonedaflete
                   "", //fotocotizacion
                    "", //justificacion
                    "", //observacion    
                   false, 
                   false, 
                   "", 
                   false, 
                   "", 
                   false, 
                   0,
                   "",     
                   true
                );   

        try {
            cotizacion.consultar_cotizacion_detalle_porautorizar_2(Integer.parseInt(frm_principalM1.lbl_nivel.getText()),tabla_detalle_cotizacion);
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void tabla_detalle_cotizacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_detalle_cotizacionMousePressed
       Integer fila;
       
       fila = tabla_detalle_cotizacion.getSelectedRow();
        bot_autorizarcotizacion.setEnabled(true);
       
       if(!tabla_detalle_cotizacion.getValueAt(fila, 14).toString().trim().equals("")){
           bot_vercotizacion.setEnabled(true);
       }
       else{
           bot_vercotizacion.setEnabled(false);
       }
    }//GEN-LAST:event_tabla_detalle_cotizacionMousePressed

    private void bot_vercotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_vercotizacionActionPerformed
       Integer fila;
       String referencia;
       fila = tabla_detalle_cotizacion.getSelectedRow();
       URI url;
       referencia = tabla_detalle_cotizacion.getValueAt(fila, 14).toString().trim();
       
       try{
            File archivo = new File(referencia);
            Desktop.getDesktop().open(archivo);
       }
       catch(IOException | IllegalArgumentException e){
            Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
            if ( desktop != null && desktop.isSupported(Desktop.Action.BROWSE) ) {
                try {
                    url = new URI(referencia);
                    desktop.browse(url);
                } catch ( IOException | URISyntaxException ex ) {
                    JOptionPane.showMessageDialog(null, "ERROR ABRIR COTIZACIÓN. " + ex.getMessage());
                }
            }    
            
       }
    }//GEN-LAST:event_bot_vercotizacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_autorizarcotizacionprocura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_autorizarcotizacionprocura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_autorizarcotizacionprocura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_autorizarcotizacionprocura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_autorizarcotizacionprocura("","","","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_autorizarcotizacion;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_vercotizacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cantidadautorizada;
    private javax.swing.JLabel lbl_descantidad;
    private javax.swing.JLabel lbl_desidmaterial;
    private javax.swing.JLabel lbl_desmaterial;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_idmaterial;
    private javax.swing.JLabel lbl_idsolicitud;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_titulosolicitud;
    private javax.swing.JLabel lbl_umb;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable tabla_detalle_cotizacion;
    private javax.swing.JTextField txt_posicion;
    // End of variables declaration//GEN-END:variables
}
