/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_material;
import controlador.ctrl_solicitud;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.class_material;

/**
 *
 * @author ruben
 */
public class frm_actualizarmaterial extends javax.swing.JFrame {

    /**
     * Creates new form frm_actualizarmaterial
     */
    private File fichero = null;
    private String Imagen = null;
    public frm_actualizarmaterial() {
        initComponents();
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - ACTUALIZAR MATERIAL");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallematerial.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        table_detallematerial.setRowSorter(elQueOrdena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ruta = new javax.swing.JTextField();
        lbl_nromaterial = new javax.swing.JLabel();
        txt_nromaterial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detallematerial = new javax.swing.JTable();
        lbl_clasematerial = new javax.swing.JLabel();
        lbl_stockmaximo = new javax.swing.JLabel();
        txt_stockminimo = new javax.swing.JTextField();
        txt_stockmaximo = new javax.swing.JTextField();
        txt_stockpedido = new javax.swing.JTextField();
        lbl_stockminimo = new javax.swing.JLabel();
        cmb_clasematerial = new javax.swing.JComboBox<>();
        lbl_stockpedido = new javax.swing.JLabel();
        lbl_grupoarticulo = new javax.swing.JLabel();
        cmb_grupoarticulo = new javax.swing.JComboBox<>();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        lbl_clasematerialbusqueda = new javax.swing.JLabel();
        lbl_grupomaterialbusqueda = new javax.swing.JLabel();
        cmb_grupoarticulobusqueda = new javax.swing.JComboBox<>();
        cmb_clasematerialbusqueda = new javax.swing.JComboBox<>();
        bot_actualizarfoto = new javax.swing.JButton();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        bot_actualizar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_descripcion = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        lbl_grupomaterial = new javax.swing.JLabel();
        lbl_codigomaestromaterial = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        lbl_modelo = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        lbl_modelo1 = new javax.swing.JLabel();
        cmb_umb = new javax.swing.JComboBox<>();
        lbl_usomaterial = new javax.swing.JLabel();
        txt_usomaterial = new javax.swing.JTextField();
        lbl_observaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_observaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nromaterial.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txt_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, -1));

        table_detallematerial.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_detallematerial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "NRO MATERIAL", "DESCRIPCIÓN", "MARCA", "MODELO", "UMB", "CLASE ART", "GRUPO ART", "STOCK DISPONIBLE", "STOCK MÍNIMO", "STOCK MÁXIMO", "STOCK PEDIDO", "campo1", "campo2", "USO", "OBSERVACIONES", "id_grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detallematerial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_detallematerialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_detallematerial);
        if (table_detallematerial.getColumnModel().getColumnCount() > 0) {
            table_detallematerial.getColumnModel().getColumn(0).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(0).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(4).setMinWidth(100);
            table_detallematerial.getColumnModel().getColumn(4).setPreferredWidth(100);
            table_detallematerial.getColumnModel().getColumn(4).setMaxWidth(100);
            table_detallematerial.getColumnModel().getColumn(5).setMinWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setMaxWidth(50);
            table_detallematerial.getColumnModel().getColumn(9).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(9).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(9).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(12).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(12).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(12).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(13).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(13).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(13).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(15).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(15).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(15).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(16).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(16).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(16).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1350, 250));

        lbl_clasematerial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_clasematerial.setText("CLASE MATERIAL");
        getContentPane().add(lbl_clasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, 20));

        lbl_stockmaximo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_stockmaximo.setText("STOCK MÁXIMO");
        getContentPane().add(lbl_stockmaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        txt_stockminimo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_stockminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 60, 20));

        txt_stockmaximo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_stockmaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 60, 20));

        txt_stockpedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_stockpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 60, 20));

        lbl_stockminimo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_stockminimo.setText("STOCK MÍNIMO");
        getContentPane().add(lbl_stockminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 20));

        cmb_clasematerial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_clasematerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_clasematerialActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_clasematerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 350, 20));

        lbl_stockpedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_stockpedido.setText("PUNTO DE PEDIDO");
        getContentPane().add(lbl_stockpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 20));

        lbl_grupoarticulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_grupoarticulo.setText("GRUPO ARTÍCULO");
        getContentPane().add(lbl_grupoarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, 20));

        cmb_grupoarticulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_grupoarticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_grupoarticuloActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_grupoarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 350, 20));

        panel_foto.setBackground(new java.awt.Color(255, 255, 255));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        getContentPane().add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 320, 220));

        lbl_clasematerialbusqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_clasematerialbusqueda.setText("CLASE MATERIAL");
        getContentPane().add(lbl_clasematerialbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        lbl_grupomaterialbusqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_grupomaterialbusqueda.setText("GRUPO ARTÍCULO");
        getContentPane().add(lbl_grupomaterialbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        cmb_grupoarticulobusqueda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_grupoarticulobusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_grupoarticulobusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_grupoarticulobusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 410, -1));

        cmb_clasematerialbusqueda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_clasematerialbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_clasematerialbusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_clasematerialbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 180, -1));

        bot_actualizarfoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_actualizarfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        bot_actualizarfoto.setText("Actualizar Foto");
        bot_actualizarfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarfotoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizarfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, -1, -1));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 240, -1));

        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR MATERIAL");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 240, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("ACTUALIZAR MATERIAL");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1113, 20, 130, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 110, 30);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(860, 10, 240, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(862, 30, 240, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcion.setText("DESCRIPCIÓN");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, 20));

        txt_descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 510, 20));

        lbl_grupomaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_grupomaterial.setText("CÓDIGO MAESTRO DEL MATERIAL");
        getContentPane().add(lbl_grupomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, -1));

        lbl_codigomaestromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codigomaestromaterial.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_codigomaestromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 230, 20));

        lbl_marca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_marca.setText("MARCA");
        getContentPane().add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 20));

        txt_marca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, 20));

        lbl_modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_modelo.setText("UMB");
        getContentPane().add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, 20));

        txt_modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 160, 20));

        lbl_modelo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_modelo1.setText("MODELO");
        getContentPane().add(lbl_modelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, 20));

        cmb_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(cmb_umb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 120, -1));

        lbl_usomaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usomaterial.setText("USO MATERIAL");
        getContentPane().add(lbl_usomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, 20));

        txt_usomaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_usomaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 370, 20));

        lbl_observaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_observaciones.setText("OBSERVACIONES");
        getContentPane().add(lbl_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 20));

        area_observaciones.setColumns(20);
        area_observaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_observaciones.setLineWrap(true);
        area_observaciones.setRows(5);
        jScrollPane2.setViewportView(area_observaciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_detallematerialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detallematerialMouseClicked
        Integer fila;
        ctrl_material material;
        BufferedImage img;

        fila = table_detallematerial.getSelectedRow();

        txt_stockminimo.setText(table_detallematerial.getValueAt(fila,9).toString());
        txt_stockmaximo.setText(table_detallematerial.getValueAt(fila,10).toString());
        txt_stockpedido.setText(table_detallematerial.getValueAt(fila,11).toString());
        txt_descripcion.setText(table_detallematerial.getValueAt(fila,2).toString());
        txt_marca.setText(table_detallematerial.getValueAt(fila,3).toString());
        txt_modelo.setText(table_detallematerial.getValueAt(fila,4).toString());
        txt_usomaterial.setText(table_detallematerial.getValueAt(fila,14).toString());
        area_observaciones.setText(table_detallematerial.getValueAt(fila,15).toString());
        
        ctrl_comun control = new ctrl_comun(9);
        cmb_clasematerial =  control.cargar_combo(cmb_clasematerial,table_detallematerial.getValueAt(fila,6).toString().trim().toUpperCase());
        
        control = new ctrl_comun(10);
        cmb_grupoarticulo =  control.cargar_combo(cmb_grupoarticulo,table_detallematerial.getValueAt(fila,7).toString().trim().toUpperCase());

        control = new ctrl_comun(13);
        cmb_umb =  control.cargar_combo(cmb_umb,table_detallematerial.getValueAt(fila,5).toString().trim().toUpperCase());

        
        lbl_codigomaestromaterial.setText(cmb_clasematerial.getSelectedItem().toString().substring(6,8) + "-" + table_detallematerial.getValueAt(fila,1).toString() + "-" + cmb_grupoarticulo.getSelectedItem().toString().substring(0,3));
           
        
        ctrl_solicitud solicitud = new ctrl_solicitud(

            0,
            0,
            0,
            "",
            0,
            "",
            0,
            Integer.parseInt(table_detallematerial.getValueAt(fila,1).toString()), //numero de material
            "",             // descripcion de material
            0,
            "",
            0,
            "",
            0,
            0,
            0,
            0,
            0,    
            "", //fecha solicitud
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""    
        );

        try{
            
            lbl_foto.setIcon(null);
            Imagen = solicitud.consultar_foto();
            img = funciones.decodeToImage(Imagen);
            
            ImageIcon icon = new ImageIcon(img);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(frm_actualizarmaterial.lbl_foto.getWidth(), frm_actualizarmaterial.lbl_foto.getHeight(), Image.SCALE_DEFAULT));
            
            lbl_foto.setIcon(icono);

        }
        catch(NullPointerException ex){ System.out.println(ex.getMessage()); }
        
        bot_actualizar.setEnabled(true);
    }//GEN-LAST:event_table_detallematerialMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_material material = null;
        class_material modelo_material = null;

        material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

        material.consultar_material_maestro_general(table_detallematerial);
        
        ctrl_comun control = new ctrl_comun(9);
        cmb_clasematerialbusqueda =  control.cargar_combo(cmb_clasematerialbusqueda,"Seleccione...");
        
        control = new ctrl_comun(10);
        cmb_grupoarticulobusqueda =  control.cargar_combo(cmb_grupoarticulobusqueda,"Seleccione...");
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void bot_actualizarfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarfotoActionPerformed

        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.jpg", "jpg");
        file.setFileFilter(filtro);

        int seleccion = file.showOpenDialog(this);
        //Si el usuario, pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            //Seleccionamos el fichero
            lbl_foto.setIcon(null);
            fichero = file.getSelectedFile();
            //Ecribe la ruta del fichero seleccionado en el campo de texto
            txt_ruta.setText(fichero.getAbsolutePath());
            ImageIcon icon = new ImageIcon(fichero.toString());
            //System.out.println(fichero.getName());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(),lbl_foto.getHeight(), Image.SCALE_DEFAULT));
            
            lbl_foto.setIcon(icono);
        }
    }//GEN-LAST:event_bot_actualizarfotoActionPerformed

    private void txt_nromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialKeyReleased
        ctrl_material material;
       DefaultTableModel modelotabla = (DefaultTableModel) table_detallematerial.getModel();
       
        if (!txt_nromaterial.getText().trim().equals("")){
            
        
            material = new ctrl_material(0,Integer.parseInt(txt_nromaterial.getText().trim()),"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_detalle(table_detallematerial);
        
        }
        else{
            material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_general(table_detallematerial);
        }
        
        
        txt_stockmaximo.setText("");
        txt_stockminimo.setText("");
        txt_stockpedido.setText("");
        txt_marca.setText("");
        txt_descripcion.setText("");
        cmb_clasematerial.setSelectedItem("Seleccione...");  
        cmb_grupoarticulo.setSelectedItem("Seleccione...");  
        txt_modelo.setText("");
        lbl_foto.setIcon(null);
        bot_actualizar.setEnabled(false);
        lbl_codigomaestromaterial.setEnabled(true);
    }//GEN-LAST:event_txt_nromaterialKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
       ctrl_material material;
       DefaultTableModel modelotabla = (DefaultTableModel) table_detallematerial.getModel();
       
        if (!txt_descripcionmaterial.getText().trim().equals("")){
            
        
            material = new ctrl_material(0,0,"","",txt_descripcionmaterial.getText().trim(),"","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_detalle_descripcion(table_detallematerial);
        
        }
        else{
            material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_general(table_detallematerial);
 
        }
        
        txt_stockmaximo.setText("");
        txt_stockminimo.setText("");
        txt_stockpedido.setText("");
        txt_marca.setText("");
        txt_descripcion.setText("");
        cmb_clasematerial.setSelectedItem("Seleccione...");  
        cmb_grupoarticulo.setSelectedItem("Seleccione...");  
        txt_modelo.setText("");
        lbl_foto.setIcon(null);
        bot_actualizar.setEnabled(false);
        lbl_codigomaestromaterial.setEnabled(true);
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void cmb_clasematerialbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_clasematerialbusquedaActionPerformed
        if(evt.getModifiers()!= 0){
            if (!cmb_clasematerialbusqueda.getSelectedItem().equals("Seleccione...")){
                ctrl_material material  = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",Integer.parseInt(cmb_clasematerialbusqueda.getSelectedItem().toString().substring(0,3).trim()),"",0,"", 0,"","",0,"",0,"", 0,"",true);

                material.consultar_material_maestro_detalle_clasematerial(table_detallematerial);
                
                cmb_grupoarticulobusqueda.setSelectedItem("Seleccione...");
            }
        }
        txt_stockmaximo.setText("");
        txt_stockminimo.setText("");
        txt_stockpedido.setText("");
        txt_marca.setText("");
        txt_descripcion.setText("");
        cmb_clasematerial.setSelectedItem("Seleccione...");  
        cmb_grupoarticulo.setSelectedItem("Seleccione...");  
        txt_modelo.setText("");
        lbl_foto.setIcon(null);
        bot_actualizar.setEnabled(false);
        lbl_codigomaestromaterial.setEnabled(true);
    }//GEN-LAST:event_cmb_clasematerialbusquedaActionPerformed

    private void cmb_grupoarticulobusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_grupoarticulobusquedaActionPerformed
        if(evt.getModifiers()!= 0){
            if (!cmb_grupoarticulobusqueda.getSelectedItem().equals("Seleccione...")){
                ctrl_material material  = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",Integer.parseInt(cmb_grupoarticulobusqueda.getSelectedItem().toString().substring(0,3).trim()),"", 0,"","",0,"",0,"", 0,"",true);

                material.consultar_material_maestro_detalle_grupoarticulo(table_detallematerial);
                
                cmb_clasematerialbusqueda.setSelectedItem("Seleccione...");
                
            }
        }
        
        txt_stockmaximo.setText("");
        txt_stockminimo.setText("");
        txt_stockpedido.setText("");
        txt_marca.setText("");
        txt_descripcion.setText("");
        cmb_clasematerial.setSelectedItem("Seleccione...");  
        cmb_grupoarticulo.setSelectedItem("Seleccione...");  
        txt_modelo.setText("");
        lbl_foto.setIcon(null);
        bot_actualizar.setEnabled(false);
        lbl_codigomaestromaterial.setEnabled(true);
    }//GEN-LAST:event_cmb_grupoarticulobusquedaActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
       frm_actualizarmaterial frm = new frm_actualizarmaterial();
       frm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        class_material modelo_material;
        ctrl_comun control;
        String image_string = null;
        Integer fila;
    
        if (!txt_ruta.getText().equals("")) {
            try {
                // TODO add your handling code here:
                   BufferedImage img = ImageIO.read(new File(fichero.toString()));
                   image_string = funciones.encodeToString(img);
               
                //guardar_imagen(image_string, fichero.getName());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"ERROR EN FOTO");
            }

        }
        else{
            image_string = Imagen;
        }
    
    try{
        fila = table_detallematerial.getSelectedRow();
        
        if(!txt_stockminimo.getText().equals("") && !txt_stockmaximo.getText().equals("") && !txt_stockpedido.getText().equals("") && 
            !cmb_clasematerial.getSelectedItem().equals("Seleccione...") && !cmb_grupoarticulo.getSelectedItem().equals("Seleccione...")) {

            ctrl_material material = new ctrl_material(
                Integer.parseInt(table_detallematerial.getValueAt(fila, 0).toString()),
                Integer.parseInt(table_detallematerial.getValueAt(fila, 1).toString()),
                "",//codigo altermo
                image_string, //foto
                txt_descripcion.getText().trim(), //descripcion
                txt_marca.getText().trim(), //marca
                txt_modelo.getText().trim(),//modelo
                Integer.parseInt(cmb_umb.getSelectedItem().toString().substring(0,3).trim()), //unidad de medida
                "",//descripcion unidad de medida
                0,
                0,
                0,
                Integer.parseInt(txt_stockminimo.getText().trim()),
                Integer.parseInt(txt_stockpedido.getText().trim()),
                Integer.parseInt(txt_stockmaximo.getText().trim()),
                0.0,
                0.0,
                funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2),
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                frm_principalM1.lbl_nombres.getText().trim(),
                0,
                0,
                area_observaciones.getText().trim(),
                txt_usomaterial.getText().trim(),
                Integer.parseInt(cmb_clasematerial.getSelectedItem().toString().substring(0,3).trim()),
                cmb_clasematerial.getSelectedItem().toString().substring(5,cmb_clasematerial.getSelectedItem().toString().length()).trim(),
                Integer.parseInt(cmb_grupoarticulo.getSelectedItem().toString().substring(0,3).trim()),
                cmb_grupoarticulo.getSelectedItem().toString().substring(5,cmb_grupoarticulo.getSelectedItem().toString().length()).trim(),
                1,
                "VEB",
                "SIN UBICACION",
                1,
                "CENTRAL",
                1,
                "TIMACA",
                1,
                "STOCK NUEVO",
                true

            );

            modelo_material = material.actualizar_material_detalle();

            if (modelo_material.isStatus()){
                JOptionPane.showMessageDialog(null,"SE ACTUALIZO EL MATERIAL " + Integer.parseInt(table_detallematerial.getValueAt(fila, 1).toString()) + " SATISFACTORIAMENTE" );
                bot_reiniciar.doClick();
            }

        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        }
    }
    catch(IndexOutOfBoundsException ex){
        JOptionPane.showMessageDialog(null,"SELECCIONAR ELEMENTO DE LA TABLA PARA ACTUALIZAR");
    }    
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void cmb_clasematerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_clasematerialActionPerformed
            try{
                if (evt.getModifiers() != 0){
        
                    if(!cmb_clasematerial.getSelectedItem().equals("Seleccione...") && !cmb_grupoarticulo.getSelectedItem().equals("Seleccione...")){
                        lbl_codigomaestromaterial.setText(cmb_clasematerial.getSelectedItem().toString().substring(6,8) + "-" + table_detallematerial.getValueAt(table_detallematerial.getSelectedRow(), 1).toString() + "-" + cmb_grupoarticulo.getSelectedItem().toString().substring(0,3));
                    }
                }
            }
            catch(NullPointerException ex){
                
            }
    }//GEN-LAST:event_cmb_clasematerialActionPerformed

    private void cmb_grupoarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_grupoarticuloActionPerformed
            try{
                if (evt.getModifiers() != 0){
        
                    if(!cmb_clasematerial.getSelectedItem().equals("Seleccione...") && !cmb_grupoarticulo.getSelectedItem().equals("Seleccione...")){
                        lbl_codigomaestromaterial.setText(cmb_clasematerial.getSelectedItem().toString().substring(6,8) + "-" + table_detallematerial.getValueAt(table_detallematerial.getSelectedRow(), 1).toString() + "-" + cmb_grupoarticulo.getSelectedItem().toString().substring(0,3));
                    }
                }
            }    
            catch(NullPointerException ex){
                
            }    
    }//GEN-LAST:event_cmb_grupoarticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_actualizarmaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_observaciones;
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_actualizarfoto;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox<String> cmb_clasematerial;
    private javax.swing.JComboBox<String> cmb_clasematerialbusqueda;
    private javax.swing.JComboBox<String> cmb_grupoarticulo;
    private javax.swing.JComboBox<String> cmb_grupoarticulobusqueda;
    private javax.swing.JComboBox<String> cmb_umb;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_clasematerial;
    private javax.swing.JLabel lbl_clasematerialbusqueda;
    private javax.swing.JLabel lbl_codigomaestromaterial;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_grupoarticulo;
    private javax.swing.JLabel lbl_grupomaterial;
    private javax.swing.JLabel lbl_grupomaterialbusqueda;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_modelo1;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nromaterial;
    private javax.swing.JLabel lbl_observaciones;
    private javax.swing.JLabel lbl_stockmaximo;
    private javax.swing.JLabel lbl_stockminimo;
    private javax.swing.JLabel lbl_stockpedido;
    private javax.swing.JLabel lbl_usomaterial;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JTable table_detallematerial;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_descripcionmaterial;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nromaterial;
    private javax.swing.JTextField txt_ruta;
    private javax.swing.JTextField txt_stockmaximo;
    private javax.swing.JTextField txt_stockminimo;
    private javax.swing.JTextField txt_stockpedido;
    private javax.swing.JTextField txt_usomaterial;
    // End of variables declaration//GEN-END:variables
}
