/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import RenderTable.RenderTablaMaestroMaterial;
import controlador.ctrl_material;
import controlador.ctrl_usuario;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.class_material;
import model.class_usuario;


/**
 *
 * @author ruben
 */
public class frm_anularmaterial extends javax.swing.JFrame {

    /**
     * Creates new form frm_maestromaterial
     */
    public frm_anularmaterial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - SUPRIMIR MATERIAL");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);

        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
       // Instanciamos nuestro modelo de datos, por ejemplo, DefaultTableModel
       // y lo metemos en el JTable
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallematerial.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        table_detallematerial.setRowSorter(elQueOrdena);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        group_material = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detallematerial = new javax.swing.JTable();
        txt_nromaterial = new javax.swing.JTextField();
        txt_descripcionmaterial = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bot_anularmaterial = new javax.swing.JButton();
        radio_nromaterial = new javax.swing.JRadioButton();
        radio_descripcion = new javax.swing.JRadioButton();

        panel_foto.setBackground(new java.awt.Color(255, 255, 255));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_detallematerial.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_detallematerial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "NRO MATERIAL", "DESCRIPCIÓN", "MARCA", "MODELO", "UMB", "CLASE DE MATERIAL", "GRUPO DE MATERIAL", "STOCK DISPONIBLE", "STOCK MÍNIMO", "STOCK MÁXIMO", "STOCK PEDIDO", "CANTIDAD ENTRANTE", "CANTIDAD SALIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detallematerial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_detallematerialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_detallematerial);
        if (table_detallematerial.getColumnModel().getColumnCount() > 0) {
            table_detallematerial.getColumnModel().getColumn(0).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(0).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(1).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(1).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(1).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(3).setMinWidth(70);
            table_detallematerial.getColumnModel().getColumn(3).setPreferredWidth(70);
            table_detallematerial.getColumnModel().getColumn(3).setMaxWidth(70);
            table_detallematerial.getColumnModel().getColumn(4).setMinWidth(70);
            table_detallematerial.getColumnModel().getColumn(4).setPreferredWidth(70);
            table_detallematerial.getColumnModel().getColumn(4).setMaxWidth(70);
            table_detallematerial.getColumnModel().getColumn(5).setMinWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setMaxWidth(50);
            table_detallematerial.getColumnModel().getColumn(7).setMinWidth(120);
            table_detallematerial.getColumnModel().getColumn(7).setPreferredWidth(120);
            table_detallematerial.getColumnModel().getColumn(7).setMaxWidth(120);
            table_detallematerial.getColumnModel().getColumn(9).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(9).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(9).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setMaxWidth(90);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1360, 310));

        txt_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 100, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descripcionmaterial.setEnabled(false);
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 300, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("SUPRIMIR MATERIAL");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 180, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 220, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1130, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1260, 20, 100, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(850, 10, 250, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(852, 30, 250, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        bot_anularmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_anularmaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        bot_anularmaterial.setText("SUPRIMIR MATERIAL");
        bot_anularmaterial.setEnabled(false);
        bot_anularmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_anularmaterialActionPerformed(evt);
            }
        });
        getContentPane().add(bot_anularmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 200, 30));

        group_material.add(radio_nromaterial);
        radio_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_nromaterial.setSelected(true);
        radio_nromaterial.setText("NÚMERO DE MATERIAL");
        radio_nromaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_nromaterialActionPerformed(evt);
            }
        });
        getContentPane().add(radio_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        group_material.add(radio_descripcion);
        radio_descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_descripcion.setText("DESCRIPCIÓN MATERIAL");
        radio_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(radio_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_material material = null;
        class_material modelo_material = null;

        material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

        material.consultar_material_maestro_general_2(table_detallematerial);
        
        table_detallematerial.setDefaultRenderer(Object.class, new RenderTablaMaestroMaterial());
        
     
          
    }//GEN-LAST:event_formWindowOpened

    private void table_detallematerialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detallematerialMouseClicked
       bot_anularmaterial.setEnabled(true);
    }//GEN-LAST:event_table_detallematerialMouseClicked

    private void txt_nromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialKeyReleased
        ctrl_material material;
        
        if (!txt_nromaterial.getText().trim().equals("")){

            material = new ctrl_material(0,Integer.parseInt(txt_nromaterial.getText().trim()),"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_detalle(table_detallematerial);

        }
        else{
            material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_general(table_detallematerial);
        }
        bot_anularmaterial.setEnabled(false);
    }//GEN-LAST:event_txt_nromaterialKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
        ctrl_material material;
 
        if (!txt_descripcionmaterial.getText().trim().equals("")){

            material = new ctrl_material(0,0,"","",txt_descripcionmaterial.getText().trim(),"","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_detalle_descripcion(table_detallematerial);

        }
        else{
            material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_general(table_detallematerial);
 
        }
        bot_anularmaterial.setEnabled(false);
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_anularmaterial frm = new frm_anularmaterial();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_anularmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_anularmaterialActionPerformed
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
        int i=0;
        boolean anulado= false;
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
        
        
        Integer fila;
        
        ctrl_usuario usuario = new ctrl_usuario(
                      Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                       "", 
                       "", 
                       "", 
                       "", 
                       0, 
                       "",
                       0,
                       "",
                       0,
                       true,
                       ""
            );

            modelo_usuario = usuario.buscar_usuario();
            
            respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR SUPRIMIR UN MATERIAL DEL MAESTRO, DESEA CONTINUAR?");
        
            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                     if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
            
        
                            try{
                                fila = table_detallematerial.getSelectedRow();
                                ctrl_material material = new ctrl_material(Integer.parseInt(table_detallematerial.getValueAt(fila, 0).toString()),0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);
                                
                                try {
                                    if(material.suprimir_material_maestro()){
                                        JOptionPane.showMessageDialog(null, "MATERIAL BORRADO SATISFACTORIAMENTE DE LA BASE DE DATOS ");
                                        bot_reiniciar.doClick();
                                        
                                    }
                                    else{
                                        JOptionPane.showMessageDialog(null, "SN RESULTADOS. EL MATERIAL TIENE ASOCIADO ALGUNA TRANSACCION(SOLICITUD, RESERVA, PRÉSTAMO)");
                                        bot_reiniciar.doClick();
                                    }
                                } catch (SQLException ex) {
                                    
                                }
                                  
                            }
                            catch(IndexOutOfBoundsException ex){
                                JOptionPane.showMessageDialog(null, "SELECCIONE UN MATERIAL DE LA TABLA");
                            }
                     
                        }
                        else{   

                            JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        } 
                }
                else{
                    JOptionPane.showMessageDialog(null, "CANCELADA TRANSACCIÓN");
                }
            }    
    }//GEN-LAST:event_bot_anularmaterialActionPerformed

    private void radio_nromaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_nromaterialActionPerformed
        txt_nromaterial.setEnabled(true);
        txt_nromaterial.setText("");
        
        txt_descripcionmaterial.setText("");
        txt_descripcionmaterial.setEnabled(false);
        
        
        
    }//GEN-LAST:event_radio_nromaterialActionPerformed

    private void radio_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_descripcionActionPerformed
        txt_descripcionmaterial.setEnabled(true);
        txt_descripcionmaterial.setText("");
        
        txt_nromaterial.setText("");
        txt_nromaterial.setEnabled(false);
    }//GEN-LAST:event_radio_descripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_anularmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_anularmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_anularmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_anularmaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_anularmaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_anularmaterial;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.ButtonGroup group_material;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JRadioButton radio_descripcion;
    private javax.swing.JRadioButton radio_nromaterial;
    protected static javax.swing.JTable table_detallematerial;
    private javax.swing.JTextField txt_descripcionmaterial;
    private javax.swing.JTextField txt_nromaterial;
    // End of variables declaration//GEN-END:variables
}
