/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import controlador.ctrl_material;
import formatos_pdf.pdf_salida;
import formatos_pdf.pdf_solicitud;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.class_material;
import static view.frm_maestromaterial.table_detallematerial;

/**
 *
 * @author ruben
 */
public class frm_detallemovimientoordencompra extends javax.swing.JFrame {

    /**
     * Creates new form frm_detallemovimientoentrada
     */
    
    public frm_detallemovimientoordencompra() {
        initComponents();
        this.setTitle("SISTIMACA - STOCK EN CURSO");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setLocationRelativeTo(null);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_descodigo = new javax.swing.JLabel();
        lbl_material = new javax.swing.JLabel();
        lbl_desmaterial = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detallematerial = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_cerrar = new javax.swing.JButton();
        bot_verdocumento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_descodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_descodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 120, 20));

        lbl_material.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_material.setText("DESCRIPCIÓN MATERIAL");
        getContentPane().add(lbl_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        lbl_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_desmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 690, 20));

        lbl_codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_codigo.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        table_detallematerial.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_detallematerial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DOCUMENTO", "NRO MATERIAL", "DESCRIPCIÓN", "POSICIÓN", "UMB", "PROYECTO", "EMPRESA", "CANTIDAD SOLICITADA", "CANTIDAD APROBADA", "CANTIDAD AUTORIZADA", "ORDEN DE COMPRA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detallematerial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_detallematerialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_detallematerial);
        if (table_detallematerial.getColumnModel().getColumnCount() > 0) {
            table_detallematerial.getColumnModel().getColumn(0).setMinWidth(80);
            table_detallematerial.getColumnModel().getColumn(0).setPreferredWidth(80);
            table_detallematerial.getColumnModel().getColumn(0).setMaxWidth(80);
            table_detallematerial.getColumnModel().getColumn(1).setMinWidth(100);
            table_detallematerial.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_detallematerial.getColumnModel().getColumn(1).setMaxWidth(100);
            table_detallematerial.getColumnModel().getColumn(2).setMinWidth(300);
            table_detallematerial.getColumnModel().getColumn(2).setPreferredWidth(300);
            table_detallematerial.getColumnModel().getColumn(2).setMaxWidth(300);
            table_detallematerial.getColumnModel().getColumn(3).setMinWidth(80);
            table_detallematerial.getColumnModel().getColumn(3).setPreferredWidth(80);
            table_detallematerial.getColumnModel().getColumn(3).setMaxWidth(80);
            table_detallematerial.getColumnModel().getColumn(4).setMinWidth(50);
            table_detallematerial.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_detallematerial.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1220, 260));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("DETALLE STOCK EN CURSO");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 250, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1080, 20, 110, 29);
        complemento.DisableBorderButton(bot_cerrar);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 60));

        bot_verdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_verdocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        bot_verdocumento.setText("VER DOCUMENTO");
        bot_verdocumento.setEnabled(false);
        bot_verdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_verdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Integer fila;
        
        ctrl_material material = null;
        class_material modelo_material = null;
        
        fila = frm_maestromaterial.table_stockcurso.getSelectedRow();
        
        lbl_descodigo.setText(frm_maestromaterial.table_stockcurso.getValueAt(fila, 1).toString());
        lbl_desmaterial.setText(frm_maestromaterial.table_stockcurso.getValueAt(fila, 2).toString());
        
        material = new ctrl_material(0,Integer.parseInt(lbl_descodigo.getText()),"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

        material.consultar_material_maestro_detalle_stockcurso(table_detallematerial);
    }//GEN-LAST:event_formWindowOpened

    private void bot_verdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdocumentoActionPerformed
        Integer fila;
        Integer documento;
        
        fila = table_detallematerial.getSelectedRow();
        
        documento = Integer.parseInt(table_detallematerial.getValueAt(fila, 0).toString());
        
        try {
            pdf_solicitud.dato("\\\\192.168.0.3\\dist\\Documentos_SisTimaca",documento,"Salida","FALSE");
        } catch (DocumentException | IOException | SQLException ex) {
            
        }
    }//GEN-LAST:event_bot_verdocumentoActionPerformed

    private void table_detallematerialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detallematerialMouseClicked
        bot_verdocumento.setEnabled(true);
    }//GEN-LAST:event_table_detallematerialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientoordencompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientoordencompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientoordencompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_detallemovimientoordencompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_detallemovimientoordencompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_verdocumento;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_descodigo;
    private javax.swing.JLabel lbl_desmaterial;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_material;
    private javax.swing.JTable table_detallematerial;
    // End of variables declaration//GEN-END:variables
}
