/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_entrada;
import controlador.ctrl_material;
import controlador.ctrl_prestamo;
import controlador.ctrl_solicitud;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.class_material;
import static view.frm_prestamo.lbl_desumb;
import static view.frm_reporteentradamaterial.cmb_almacen;
import static view.frm_reporteentradamaterial.cmb_proyecto;

/**
 *
 * @author ruben
 */
public class frm_actualizarprestamo extends javax.swing.JFrame {

   private File fichero;
   
    public frm_actualizarprestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - ACTUALIZAR PRÉSTAMO DE MATERIAL");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_devolucion = new javax.swing.ButtonGroup();
        group_dano = new javax.swing.ButtonGroup();
        txt_rutadano = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prestamo = new javax.swing.JTable();
        lbl_nromaterial = new javax.swing.JLabel();
        txt_numeromaterial = new javax.swing.JTextField();
        bot_buscar = new javax.swing.JButton();
        lbl_diasmora = new javax.swing.JLabel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        lbl_numeromaterial = new javax.swing.JLabel();
        lbl_diasentregamaterial = new javax.swing.JLabel();
        lbl_desdescripcionmaterial = new javax.swing.JLabel();
        lbl_desnromaterial = new javax.swing.JLabel();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        bot_actualizarprestamo = new javax.swing.JButton();
        date_hasta = new com.toedter.calendar.JDateChooser();
        date_desde = new com.toedter.calendar.JDateChooser();
        lbl_diasentregamaterial1 = new javax.swing.JLabel();
        txt_solicitante = new javax.swing.JTextField();
        chk_indefinido = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("ACTUALIZAR PRÉSTAMO");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(270, 10, 190, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 280, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1140, 20, 113, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1280, 20, 91, 25);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 60));

        table_prestamo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_prestamo", "id_entrada", "NRO DOCUMENTO", "NRO MATERIAL", "DESCRIPCIÓN", "POSICIÓN", "CANTIDAD PRESTADA", "UMB", "PROYECTO", "AREA", "NOMBRE SOLICITANTE", "FECHA DESDE", "FECHA HASTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prestamoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prestamo);
        if (table_prestamo.getColumnModel().getColumnCount() > 0) {
            table_prestamo.getColumnModel().getColumn(0).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(4).setMinWidth(300);
            table_prestamo.getColumnModel().getColumn(4).setPreferredWidth(300);
            table_prestamo.getColumnModel().getColumn(4).setMaxWidth(300);
            table_prestamo.getColumnModel().getColumn(5).setMinWidth(80);
            table_prestamo.getColumnModel().getColumn(5).setPreferredWidth(80);
            table_prestamo.getColumnModel().getColumn(5).setMaxWidth(80);
            table_prestamo.getColumnModel().getColumn(7).setMinWidth(50);
            table_prestamo.getColumnModel().getColumn(7).setPreferredWidth(50);
            table_prestamo.getColumnModel().getColumn(7).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1390, 280));

        lbl_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nromaterial.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_numeromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));
        complemento.DisableBorderButton(bot_buscar);

        lbl_diasmora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasmora.setText("FECHA HASTA");
        getContentPane().add(lbl_diasmora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        lbl_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_numeromaterial.setText("NÚMERO DE MATERIAL");
        getContentPane().add(lbl_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        lbl_diasentregamaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasentregamaterial.setText("NOMBRE SOLICITANTE");
        getContentPane().add(lbl_diasentregamaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        lbl_desdescripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_desdescripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 310, 20));

        lbl_desnromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_desnromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 170, 20));

        panel_foto.setBackground(new java.awt.Color(253, 253, 253));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );

        getContentPane().add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 210, 200));

        bot_actualizarprestamo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_actualizarprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilizar.png"))); // NOI18N
        bot_actualizarprestamo.setText("ACTUALIZAR PRÉSTAMO");
        bot_actualizarprestamo.setEnabled(false);
        bot_actualizarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarprestamoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizarprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, -1, -1));

        date_hasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 120, -1));

        date_desde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 120, -1));

        lbl_diasentregamaterial1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasentregamaterial1.setText("FECHA DESDE");
        getContentPane().add(lbl_diasentregamaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        txt_solicitante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_solicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 200, -1));

        chk_indefinido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_indefinido.setText("Permanente");
        chk_indefinido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_indefinidoActionPerformed(evt);
            }
        });
        getContentPane().add(chk_indefinido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_actualizarprestamo frm = new frm_actualizarprestamo();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void txt_numeromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeromaterialKeyReleased
        class_material modelo_material;
        BufferedImage img;

         bot_actualizarprestamo.setEnabled(false);
         
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){
            if(txt_numeromaterial.getText().length() > 7){

                ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    Integer.parseInt(txt_numeromaterial.getText().trim()), //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

            prestamo.consultar_prestamos(table_prestamo,"","",1);

            }    
        }
        else{
            if (evt.getKeyCode() == 27){

                bot_reiniciar.doClick();

            }
            else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numeromaterial.setText("");
                
            }
        }
    }//GEN-LAST:event_txt_numeromaterialKeyReleased

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
        frm_buscarmaterial frm = new frm_buscarmaterial(10);
        frm.setVisible(true);
         bot_actualizarprestamo.setEnabled(false);
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
               
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    0, //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

        prestamo.consultar_prestamos(table_prestamo,"","",1);
    }//GEN-LAST:event_formWindowOpened

    private void table_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prestamoMouseClicked
        Integer fila;
        BufferedImage img;
         
        fila = table_prestamo.getSelectedRow();
        
        lbl_desnromaterial.setText(table_prestamo.getValueAt(fila, 3).toString());
        lbl_desdescripcionmaterial.setText(table_prestamo.getValueAt(fila, 4).toString());
        date_desde.setDate(Date.valueOf(funciones.fecha_bd_usuario(table_prestamo.getValueAt(fila, 11).toString(),2)));
        date_hasta.setDate(Date.valueOf(funciones.fecha_bd_usuario(table_prestamo.getValueAt(fila, 12).toString(),2)));
        txt_solicitante.setText(table_prestamo.getValueAt(fila, 10).toString());
        
         bot_actualizarprestamo.setEnabled(true);
         
        ctrl_solicitud solicitud = new ctrl_solicitud(
                
                        0,
                        0,
                        0,
                        "",
                        0,
                        "",
                        0,
                        Integer.parseInt(lbl_desnromaterial.getText().trim()), //numero de material
                        "",             // descripcion de material     
                        0,
                        "",
                        0,
                        "",
                        0,    
                        0,
                        0,
                        0,
                        0,     
                        "", //fecha solicitud
                        "",
                        "",
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""     
                );  
                     
                   try{  
                     img = funciones.decodeToImage(solicitud.consultar_foto());
                     lbl_foto.setIcon(null);
                     ImageIcon icon = new ImageIcon(img);
                     Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                     
                     lbl_foto.setIcon(icono);
                    
                   }  
                   catch(NullPointerException ex){  }
                   
       
    }//GEN-LAST:event_table_prestamoMouseClicked

    private void bot_actualizarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarprestamoActionPerformed
        Integer fila;
        String fecha_desde;
        String fecha_hasta;
        
        fila = table_prestamo.getSelectedRow();
        
        fecha_desde = funciones.fecha_convertir_date(date_desde, 1);
        fecha_hasta = funciones.fecha_convertir_date(date_hasta, 1);
        
        if (chk_indefinido.isSelected()){
            fecha_hasta = "9999-09-09";
        }        
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    Integer.parseInt(table_prestamo.getValueAt(fila, 0).toString()), //id_prestamo 
                    0, //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    txt_solicitante.getText().trim(), // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    fecha_desde, //fecha_desde, 
                    fecha_hasta, //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

        if(prestamo.actualizar_prestamo(table_prestamo)){
            JOptionPane.showMessageDialog(null,"SE ACTUALIZÓ SATISFACTORIAMENTE EL PRÉSTAMO");
            bot_reiniciar.doClick();
        }
        else{
           JOptionPane.showMessageDialog(null,"NO ACTUALIZÓ EL PRÉSTAMO");
        }
    }//GEN-LAST:event_bot_actualizarprestamoActionPerformed

    private void chk_indefinidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_indefinidoActionPerformed
        if(!chk_indefinido.isSelected()){
            
            date_hasta.setEnabled(true);
            date_hasta.setDate(null);
        }
        else{
            date_hasta.setDate(null);
            date_hasta.setEnabled(false);
        }
    }//GEN-LAST:event_chk_indefinidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_actualizarprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_actualizarprestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizarprestamo;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JCheckBox chk_indefinido;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.ButtonGroup group_dano;
    private javax.swing.ButtonGroup group_devolucion;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_desdescripcionmaterial;
    private javax.swing.JLabel lbl_desnromaterial;
    private javax.swing.JLabel lbl_diasentregamaterial;
    private javax.swing.JLabel lbl_diasentregamaterial1;
    private javax.swing.JLabel lbl_diasmora;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nromaterial;
    private javax.swing.JLabel lbl_numeromaterial;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    protected static javax.swing.JTable table_prestamo;
    protected static javax.swing.JTextField txt_numeromaterial;
    private javax.swing.JTextField txt_rutadano;
    private javax.swing.JTextField txt_solicitante;
    // End of variables declaration//GEN-END:variables
}
