/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_solicitud;
import formatos_excel.reporte_solicitud;
import java.awt.Color;
import java.awt.Desktop;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import jxl.write.WriteException;

/**
 *
 * @author ruben
 */
public class frm_consultarsolicitud extends javax.swing.JFrame {

    /**
     * Creates new form frm_consultarsolicitud
     */
    public frm_consultarsolicitud() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - CONSULTAR SOLICITUDES A COMPRAS");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());  
        
        DefaultTableModel modelotabla = (DefaultTableModel) tabla_resumensolicitud.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        tabla_resumensolicitud.setRowSorter(elQueOrdena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_solicitud = new javax.swing.ButtonGroup();
        txt_id = new javax.swing.JTextField();
        lbl_nrosolicitud = new javax.swing.JLabel();
        txt_nrosolicitud = new javax.swing.JTextField();
        lbl_proyecto = new javax.swing.JLabel();
        lbl_tiposolicitud = new javax.swing.JLabel();
        cmb_tiposolicitud = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_resumensolicitud = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoaprobarsolicitud = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        date_desde = new com.toedter.calendar.JDateChooser();
        lbl_fechadesde = new javax.swing.JLabel();
        radio_pendiente = new javax.swing.JRadioButton();
        radio_conformada = new javax.swing.JRadioButton();
        radio_anulada = new javax.swing.JRadioButton();
        bot_excel = new javax.swing.JButton();
        radio_aprobada = new javax.swing.JRadioButton();
        radio_autorizada = new javax.swing.JRadioButton();
        bot_buscarreporte = new javax.swing.JButton();
        txt_idproyecto = new javax.swing.JTextField();
        txt_descripcionproyecto = new javax.swing.JTextField();

        txt_id.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("NRO SOLICITUD");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nrosolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nrosolicitudActionPerformed(evt);
            }
        });
        txt_nrosolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nrosolicitudKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        getContentPane().add(lbl_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        lbl_tiposolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_tiposolicitud.setText("TIPO DE SOLICITUD");
        getContentPane().add(lbl_tiposolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, -1, -1));

        cmb_tiposolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_tiposolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tiposolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tiposolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 240, -1));

        tabla_resumensolicitud.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tabla_resumensolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_area", "id_proyecto", "id_tiposolicitud", "", "NRO DE SOLICITUD", "POS", "NRO DE MATERIAL", "MATERIAL SOLICITADO", "UMB", "FECHA REQ", "GRUPO ART", "CANT SOLIC.", "PROYECTO", "EMPRESA", "TIPO SOLICITUD", "FECHA SOLICITUD", "aprob_solicitud", "fecha_aprobacion", "cantidad_aprobada", "autori_solicitud", "fecha_autorizacion", "cantidad_autorizada", "conformacion_solicitud", "fecha_conformacion", "cantidad_conformada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_resumensolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_resumensolicitudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_resumensolicitud);
        if (tabla_resumensolicitud.getColumnModel().getColumnCount() > 0) {
            tabla_resumensolicitud.getColumnModel().getColumn(0).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(1).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(1).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(1).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(2).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(2).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(2).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(3).setMinWidth(1);
            tabla_resumensolicitud.getColumnModel().getColumn(3).setPreferredWidth(1);
            tabla_resumensolicitud.getColumnModel().getColumn(3).setMaxWidth(1);
            tabla_resumensolicitud.getColumnModel().getColumn(5).setMinWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(5).setPreferredWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(5).setMaxWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(7).setMinWidth(200);
            tabla_resumensolicitud.getColumnModel().getColumn(7).setPreferredWidth(200);
            tabla_resumensolicitud.getColumnModel().getColumn(7).setMaxWidth(200);
            tabla_resumensolicitud.getColumnModel().getColumn(8).setMinWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(8).setPreferredWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(8).setMaxWidth(40);
            tabla_resumensolicitud.getColumnModel().getColumn(11).setMinWidth(80);
            tabla_resumensolicitud.getColumnModel().getColumn(11).setPreferredWidth(80);
            tabla_resumensolicitud.getColumnModel().getColumn(11).setMaxWidth(80);
            tabla_resumensolicitud.getColumnModel().getColumn(16).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(16).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(16).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(17).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(17).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(17).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(18).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(18).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(18).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(19).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(19).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(19).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(20).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(20).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(20).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(21).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(21).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(21).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(22).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(22).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(22).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(23).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(23).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(23).setMaxWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(24).setMinWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(24).setPreferredWidth(0);
            tabla_resumensolicitud.getColumnModel().getColumn(24).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1310, 530));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoaprobarsolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoaprobarsolicitud.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoaprobarsolicitud.setText("CONSULTAR SOLICITUD");
        jPanel7.add(lbl_encabezadoaprobarsolicitud);
        lbl_encabezadoaprobarsolicitud.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FECHA HASTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        date_hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_hastaPropertyChange(evt);
            }
        });
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        date_desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_desdePropertyChange(evt);
            }
        });
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));

        lbl_fechadesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechadesde.setText("FECHA DESDE");
        getContentPane().add(lbl_fechadesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        group_solicitud.add(radio_pendiente);
        radio_pendiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_pendiente.setText("PENDIENTE");
        radio_pendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pendienteActionPerformed(evt);
            }
        });
        getContentPane().add(radio_pendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        group_solicitud.add(radio_conformada);
        radio_conformada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_conformada.setText("CONFORMADAS");
        radio_conformada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_conformadaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_conformada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        group_solicitud.add(radio_anulada);
        radio_anulada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_anulada.setText("ANULADAS");
        radio_anulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_anuladaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_anulada, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, -1, -1));

        bot_excel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
        bot_excel.setText("EXPORTAR EXCEL");
        bot_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_excelActionPerformed(evt);
            }
        });
        getContentPane().add(bot_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, -1, -1));

        group_solicitud.add(radio_aprobada);
        radio_aprobada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_aprobada.setText("APROBADAS");
        radio_aprobada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_aprobadaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_aprobada, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        group_solicitud.add(radio_autorizada);
        radio_autorizada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_autorizada.setText("AUTORIZADAS");
        radio_autorizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_autorizadaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_autorizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        bot_buscarreporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_buscarreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscarreporte.setText("Buscar");
        bot_buscarreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarreporteActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscarreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        txt_idproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_idproyecto.setEnabled(false);
        getContentPane().add(txt_idproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 70, -1));

        txt_descripcionproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionproyecto.setEnabled(false);
        getContentPane().add(txt_descripcionproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 230, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_consultarsolicitud frm = new frm_consultarsolicitud();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        ctrl_comun control = new ctrl_comun(11);
        cmb_tiposolicitud =  control.cargar_combo(cmb_tiposolicitud,"Seleccione...");
        
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,5,"","",Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
                
        //solicitud.consultar_solicitudes_activa(tabla_resumensolicitud,0,"","",1,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
       
        
    }//GEN-LAST:event_formWindowOpened

    private void txt_nrosolicitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nrosolicitudKeyReleased
        Integer opcion = 5;
        
        
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            
            ctrl_solicitud solicitud = new ctrl_solicitud(
                
                Integer.parseInt(txt_nrosolicitud.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  

            radio_pendiente.setSelected(false);
            radio_conformada.setSelected(false);
            radio_aprobada.setSelected(false);
            radio_autorizada.setSelected(false);
              
            solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,opcion,"","",Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
                    
            //solicitud.consultar_solicitudes_activa(tabla_resumensolicitud,1,"","",opcion,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));

        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nrosolicitud.setText("");
                
             }   
        }     
    }//GEN-LAST:event_txt_nrosolicitudKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
        Integer opcion = 5;

        Integer proyecto;
        Integer tiposolicitud;
        Integer nrosolicitud;
    
       
        
        proyecto = Integer.parseInt(txt_id.getText().trim());
       
        if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
            tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
        }
        else{
            tiposolicitud = 0;
        }

        if (!txt_nrosolicitud.getText().trim().equals("")){
            nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
        }
        else{
            nrosolicitud = 0;
        }   
        
        String fechadesde = funciones.fecha_convertir_date(date_desde, 1);
        String fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
           
            ctrl_solicitud solicitud = new ctrl_solicitud(
                
               nrosolicitud,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                tiposolicitud,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),// descripcion de material     
                0,
                "",
                proyecto,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  
                 if(radio_pendiente.isSelected()){
                    opcion = 0;
                }
                
                if(radio_conformada.isSelected()){
                    opcion = 1;
                }
                
                if(radio_aprobada.isSelected()){
                    opcion = 2;
                }     
                
                if (radio_autorizada.isSelected()){
                    opcion = 3;
                }
                
                if(radio_anulada.isSelected()){
                    opcion = 4;
                }
                
            solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,opcion,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
                
            //solicitud.consultar_solicitudes_activa(tabla_resumensolicitud,2,"","",opcion,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));

         
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void cmb_tiposolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tiposolicitudActionPerformed
        Integer opcion = 5;
        String fechadesde = funciones.fecha_convertir_date(date_desde, 1);
        String fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
        Integer proyecto;
        Integer nrosolicitud;
  
        if(evt.getModifiers() != 0){
            
            if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
   
                
                proyecto = Integer.parseInt(txt_id.getText().trim());
               
                if (!txt_nrosolicitud.getText().trim().equals("")){
                    nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
                }
                else{
                    nrosolicitud = 0;
                } 
                
                ctrl_solicitud solicitud =  new ctrl_solicitud(
                
                nrosolicitud,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim()),
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                proyecto,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""        
             );
                
                if(radio_pendiente.isSelected()){
                    opcion = 0;
                }
                
                if(radio_conformada.isSelected()){
                    opcion = 1;
                }
                
                if(radio_aprobada.isSelected()){
                    opcion = 2;
                }     
                
                if (radio_autorizada.isSelected()){
                    opcion = 3;
                }
                
                if(radio_anulada.isSelected()){
                    opcion = 4;
                }
               
            solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,opcion,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
                               
             //solicitud.consultar_solicitudes_activa(tabla_resumensolicitud,4,"","",opcion,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim())); 
            }  
        }    
    }//GEN-LAST:event_cmb_tiposolicitudActionPerformed

    private void date_hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_hastaPropertyChange
        String fechadesde;
        String fechahasta;
        Integer opcion = 5;
        
        Integer proyecto;
        Integer tiposolicitud;
        Integer nrosolicitud;
    
        fechadesde = funciones.fecha_convertir_date(date_desde, 1);
        fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
     try{   
       
        proyecto = Integer.parseInt(txt_id.getText().trim());
       
        if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
            tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
        }
        else{
            tiposolicitud = 0;
        }

        if (!txt_nrosolicitud.getText().trim().equals("")){
            nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
        }
        else{
            nrosolicitud = 0;
        }              
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
                ctrl_solicitud solicitud=null;

                solicitud = new ctrl_solicitud(
                
                    nrosolicitud,
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    tiposolicitud,
                    "",
                    0,
                    0, //numero de material
                    "",             // descripcion de material     
                    0,
                    "",
                    proyecto,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,    
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );  
                
                
                if(radio_pendiente.isSelected()){
                    opcion = 0;
                }
                
                if(radio_conformada.isSelected()){
                    opcion = 1;
                }
                
                if(radio_aprobada.isSelected()){
                    opcion = 2;
                }     
                
                if (radio_autorizada.isSelected()){
                    opcion = 3;
                }
                
                if(radio_anulada.isSelected()){
                    opcion = 4;
                }
                
                solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,opcion,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
                
               // solicitud.consultar_solicitudes_activa(tabla_resumensolicitud,5,fechadesde,fechahasta,opcion,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim())); 
            }
     }
     catch(NullPointerException ex){
         
     }
    }//GEN-LAST:event_date_hastaPropertyChange

    private void date_desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_desdePropertyChange
         String fechadesde;
        String fechahasta;
        Integer opcion = 5;
        
        Integer proyecto;
        Integer tiposolicitud;
        Integer nrosolicitud;
    
        fechadesde = funciones.fecha_convertir_date(date_desde, 1);
        fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
     
     try{   
        
       
        proyecto = Integer.parseInt(txt_id.getText().trim());
        

        if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
            tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
        }
        else{
            tiposolicitud = 0;
        }

        if (!txt_nrosolicitud.getText().trim().equals("")){
            nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
        }
        else{
            nrosolicitud = 0;
        }              
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                
                ctrl_solicitud solicitud=null;

                solicitud = new ctrl_solicitud(
                
                    nrosolicitud,
                    Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                    Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                    frm_principalM1.lbl_desarea.getText().trim(),
                    tiposolicitud,
                    "",
                    0,
                    0, //numero de material
                    "",             // descripcion de material     
                    0,
                    "",
                    proyecto,
                    "",
                    0,
                    0,
                    0,
                    0,
                    0,    
                    "", //fecha solicitud
                    "",
                    "",
                    false,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""    
                );  
                
                
                if(radio_pendiente.isSelected()){
                    opcion = 0;
                }
                
                if(radio_conformada.isSelected()){
                    opcion = 1;
                }
                
                if(radio_aprobada.isSelected()){
                    opcion = 2;
                }     
                
                if (radio_autorizada.isSelected()){
                    opcion = 3;
                }
                
                if(radio_anulada.isSelected()){
                    opcion = 4;
                }
                
                solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,opcion,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
                
               // solicitud.consultar_solicitudes_activa(tabla_resumensolicitud,5,fechadesde,fechahasta,opcion,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim())); 
            }
     }
     catch(NullPointerException ex){
         
     }
    }//GEN-LAST:event_date_desdePropertyChange

    private void tabla_resumensolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_resumensolicitudMouseClicked
        frm_consultadetallesolicitud frm = new frm_consultadetallesolicitud();
        frm.setVisible(true);
    }//GEN-LAST:event_tabla_resumensolicitudMouseClicked

    private void radio_pendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pendienteActionPerformed
    String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer tiposolicitud;
    Integer nrosolicitud;
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
   
    proyecto = Integer.parseInt(txt_id.getText().trim());
   
    
    if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
        tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        tiposolicitud = 0;
    }

    if (!txt_nrosolicitud.getText().trim().equals("")){
        nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
    }
    else{
        nrosolicitud = 0;
    }    
    
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                nrosolicitud,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                tiposolicitud,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),// descripcion de material     
                0,
                "",
                proyecto,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,0,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
    }//GEN-LAST:event_radio_pendienteActionPerformed

    private void radio_conformadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_conformadaActionPerformed
    String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer tiposolicitud;
    Integer nrosolicitud;
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
    proyecto = Integer.parseInt(txt_id.getText().trim());
        
    if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
        tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        tiposolicitud = 0;
    }

    if (!txt_nrosolicitud.getText().trim().equals("")){
        nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
    }
    else{
        nrosolicitud = 0;
    }    
    
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                nrosolicitud,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                tiposolicitud,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),// descripcion de material     
                0,
                "",
                proyecto,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,1,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
    }//GEN-LAST:event_radio_conformadaActionPerformed

    private void radio_anuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_anuladaActionPerformed
   String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer tiposolicitud;
    Integer nrosolicitud;
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
    proyecto = Integer.parseInt(txt_id.getText().trim());
        
    if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
        tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        tiposolicitud = 0;
    }

    if (!txt_nrosolicitud.getText().trim().equals("")){
        nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
    }
    else{
        nrosolicitud = 0;
    }    
    
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                nrosolicitud,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                tiposolicitud,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),// descripcion de material     
                0,
                "",
                proyecto,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,4,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
    }//GEN-LAST:event_radio_anuladaActionPerformed

    private void radio_aprobadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_aprobadaActionPerformed
    String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer tiposolicitud;
    Integer nrosolicitud;
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
    proyecto = Integer.parseInt(txt_id.getText().trim());
    
    
    if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
        tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        tiposolicitud = 0;
    }

    if (!txt_nrosolicitud.getText().trim().equals("")){
        nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
    }
    else{
        nrosolicitud = 0;
    }    
    
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                nrosolicitud,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                tiposolicitud,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),// descripcion de material     
                0,
                "",
                proyecto,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,2,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));

    }//GEN-LAST:event_radio_aprobadaActionPerformed

    private void radio_autorizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_autorizadaActionPerformed
    String fechadesde;
    String fechahasta;
    Integer proyecto;
    Integer tiposolicitud;
    Integer nrosolicitud;
    
    fechadesde = funciones.fecha_convertir_date(date_desde, 1);
    fechahasta = funciones.fecha_convertir_date(date_hasta, 1);      
        
   
    proyecto = Integer.parseInt(txt_id.getText().trim());
        
    if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
        tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
    }
    else{
        tiposolicitud = 0;
    }

    if (!txt_nrosolicitud.getText().trim().equals("")){
        nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
    }
    else{
        nrosolicitud = 0;
    }    
    
        ctrl_solicitud solicitud=null;

        solicitud = new ctrl_solicitud(
                
                nrosolicitud,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                tiposolicitud,
                "",
                0,
                0, //numero de material
                txt_descripcionmaterial.getText().trim(),// descripcion de material     
                0,
                "",
                proyecto,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,3,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
    }//GEN-LAST:event_radio_autorizadaActionPerformed

    private void bot_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_excelActionPerformed
        String nombre_archivo;
        String fecha_desde;
        String fecha_hasta;
        Integer numero = (int) (Math.random() * 10000000) + 1;
        nombre_archivo = "\\\\192.168.0.3\\dist\\Documentos_SisTimaca\\Solicitudes" + numero +".xls";
        //nombre_archivo = "C:\\Users\\ruben\\Desktop\\Solicitudes.xls";

        
        
    if (tabla_resumensolicitud.getRowCount()>0){                     
        reporte_solicitud ex = new reporte_solicitud(new File(nombre_archivo), "DATOS DE SOLICITUD DE MATERIAL", tabla_resumensolicitud);
           
        try {
            if(ex.excel_export_reporte()){

                File archivo_abrir = new File(nombre_archivo);
                Desktop.getDesktop().open(archivo_abrir);
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR EN EXPORTAR ARCHIVO EXCEL");
            }
        } catch (WriteException | IOException ex1) {
            JOptionPane.showMessageDialog(null, "ERROR ABRIR ARCHIVO " + ex1.getMessage() );
        }
          
    }
    else{
        JOptionPane.showMessageDialog(null, "NO HAY DATOS PARA LA CONSULTA");
    }
    }//GEN-LAST:event_bot_excelActionPerformed

    private void txt_nrosolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nrosolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nrosolicitudActionPerformed

    private void bot_buscarreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarreporteActionPerformed
        frm_buscarproyecto frm = new frm_buscarproyecto(8);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_buscarreporteActionPerformed

    public static void consultar_solicitud_proyecto(){
    
    
        Integer opcion = 5;
        String fechadesde = funciones.fecha_convertir_date(date_desde, 1);
        String fechahasta = funciones.fecha_convertir_date(date_hasta, 1);

        Integer tiposolicitud;
        Integer nrosolicitud;

       
        if(!cmb_tiposolicitud.getSelectedItem().equals("Seleccione...")){
            tiposolicitud = Integer.parseInt(cmb_tiposolicitud.getSelectedItem().toString().substring(0,3).trim());
        }
        else{
            tiposolicitud = 0;
        }

        if (!txt_nrosolicitud.getText().trim().equals("")){
            nrosolicitud = Integer.parseInt(txt_nrosolicitud.getText().trim());
        }
        else{
            nrosolicitud = 0;
        }

        ctrl_solicitud solicitud =  new ctrl_solicitud(

            nrosolicitud,
            Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
            Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
            frm_principalM1.lbl_desarea.getText().trim(),
            tiposolicitud,
            "",
            0,
            0, //numero de material
            "",             // descripcion de material
            0,
            "",
            Integer.parseInt(txt_id.getText().trim()),
            "",
            0,
            0,
            0,
            0,
            0,
            "", //fecha solicitud
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""    
        );

        if(radio_pendiente.isSelected()){
            opcion = 0;
        }

        if(radio_conformada.isSelected()){
            opcion = 1;
        }

        if(radio_aprobada.isSelected()){
            opcion = 2;
        }

        if (radio_autorizada.isSelected()){
            opcion = 3;
        }

        if(radio_anulada.isSelected()){
            opcion = 4;
        }

        solicitud.consultar_solicitudes_fase(tabla_resumensolicitud,opcion,fechadesde,fechahasta,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));

        // solicitud.consultar_solicitudes_activa(tabla_resumensolicitud,3,"","",opcion,Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));
 
    
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_consultarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_consultarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_consultarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_consultarsolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_consultarsolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_buscarreporte;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_excel;
    private javax.swing.JButton bot_reiniciar;
    public static javax.swing.JComboBox<String> cmb_tiposolicitud;
    public static com.toedter.calendar.JDateChooser date_desde;
    public static com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.ButtonGroup group_solicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_encabezadoaprobarsolicitud;
    private javax.swing.JLabel lbl_fechadesde;
    private javax.swing.JLabel lbl_imagentimaca2;
    protected static javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_proyecto;
    private javax.swing.JLabel lbl_tiposolicitud;
    protected static javax.swing.JLabel lbl_usuario;
    public static javax.swing.JRadioButton radio_anulada;
    public static javax.swing.JRadioButton radio_aprobada;
    public static javax.swing.JRadioButton radio_autorizada;
    public static javax.swing.JRadioButton radio_conformada;
    public static javax.swing.JRadioButton radio_pendiente;
    protected static javax.swing.JTable tabla_resumensolicitud;
    public static javax.swing.JTextField txt_descripcionmaterial;
    protected static javax.swing.JTextField txt_descripcionproyecto;
    public static javax.swing.JTextField txt_id;
    protected static javax.swing.JTextField txt_idproyecto;
    public static javax.swing.JTextField txt_nrosolicitud;
    // End of variables declaration//GEN-END:variables
}
