/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_comun;
import controlador.ctrl_cotizacion;
import java.awt.Color;

import static java.awt.Frame.MAXIMIZED_BOTH;

import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ruben
 */
public class frm_anularcotizacion extends javax.swing.JFrame {

    /**
     * Creates new form frm_cotizacion
     */
    public frm_anularcotizacion() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - ANULAR COTIZACIÓN");
        this.getContentPane().setBackground(new Color(240,240,240));
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        this.setExtendedState(MAXIMIZED_BOTH);
        

        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_estatus = new javax.swing.ButtonGroup();
        lbl_nrosolicitud = new javax.swing.JLabel();
        txt_numerosolicitud = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_posicioncotizacion = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmb_proveedor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbl_nrosolicitud1 = new javax.swing.JLabel();
        txt_numeromaterial = new javax.swing.JTextField();
        lbl_titulodetallesolicitud1 = new javax.swing.JLabel();
        lbl_titulodetallesolicitud = new javax.swing.JLabel();
        radio_sinaprobar = new javax.swing.JRadioButton();
        radio_aprobada = new javax.swing.JRadioButton();
        radio_autorizada = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud.setText("NRO DE SOLICITUD");
        getContentPane().add(lbl_nrosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txt_numerosolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numerosolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numerosolicitudKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numerosolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, -1));

        table_posicioncotizacion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_posicioncotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_cotizacion", "NRO SOLICITUD", "POSICIÓN", "NRO MATERIAL", "MATERIAL SOLICITADO", "PROVEEDOR", "CANTIDAD COTIZADA", "UMB", "PRECIO UNITARIO", "MONEDA", "TOTAL", "PLAZO DE ENTREGA(días)", "CONDICIÓN PAGO", "title14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20", "Title 21", "Title 22", "Title 23", "Title 24", "Title 25", "Title 26", "Title 27", "Title 28", "Title 29", "Title 30", "Title 31", "Title 32", "Title 33", "Title 34", "Title 35"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_posicioncotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_posicioncotizacionMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table_posicioncotizacion);
        if (table_posicioncotizacion.getColumnModel().getColumnCount() > 0) {
            table_posicioncotizacion.getColumnModel().getColumn(0).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(0).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(13).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(13).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(13).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(14).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(14).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(14).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(15).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(15).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(15).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(16).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(16).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(16).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(17).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(17).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(17).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(18).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(18).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(18).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(19).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(19).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(19).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(20).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(20).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(20).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(21).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(21).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(21).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(22).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(22).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(22).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(23).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(23).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(23).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(24).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(24).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(24).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(25).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(25).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(25).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(26).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(26).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(26).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(27).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(27).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(27).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(28).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(28).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(28).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(29).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(29).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(29).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(30).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(30).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(30).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(31).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(31).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(31).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(32).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(32).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(32).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(33).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(33).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(33).setMaxWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(34).setMinWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(34).setPreferredWidth(0);
            table_posicioncotizacion.getColumnModel().getColumn(34).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1330, 320));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("ANULAR COTIZACIÓN");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(280, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(840, 10, 260, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(842, 30, 260, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        cmb_proveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proveedorActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 280, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PROVEEDOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        lbl_nrosolicitud1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nrosolicitud1.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nrosolicitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txt_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numeromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, -1));

        lbl_titulodetallesolicitud1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallesolicitud1.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallesolicitud1.setText("DETALLES COTIZACIÓN");
        getContentPane().add(lbl_titulodetallesolicitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        lbl_titulodetallesolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallesolicitud.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallesolicitud.setText("ESTATUS COTIZACIÓN");
        getContentPane().add(lbl_titulodetallesolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        group_estatus.add(radio_sinaprobar);
        radio_sinaprobar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_sinaprobar.setSelected(true);
        radio_sinaprobar.setText("SIN APROBAR");
        radio_sinaprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_sinaprobarActionPerformed(evt);
            }
        });
        getContentPane().add(radio_sinaprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        group_estatus.add(radio_aprobada);
        radio_aprobada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_aprobada.setText("APROBADAS");
        radio_aprobada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_aprobadaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_aprobada, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        group_estatus.add(radio_autorizada);
        radio_autorizada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_autorizada.setText("AUTORIZADAS");
        radio_autorizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_autorizadaActionPerformed(evt);
            }
        });
        getContentPane().add(radio_autorizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_posicioncotizacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_posicioncotizacionMousePressed
       
        frm_detalleanular_cotizacion frm = new frm_detalleanular_cotizacion();
        frm.setVisible(true);
        
    }//GEN-LAST:event_table_posicioncotizacionMousePressed

    private void txt_numerosolicitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numerosolicitudKeyReleased
        Integer opcion = 0;
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
                ctrl_cotizacion cotizacion = new ctrl_cotizacion(
                          0, 
                          0, 
                          "", 
                          "", 
                          Integer.parseInt(txt_numerosolicitud.getText().trim()), 
                          0, 
                          0, 
                          0, 
                          0, 
                          0,
                          0.0, 
                          0.0, 
                          "", 
                          "", //tipo plazo entrega
                           0, //dias plazoentrega
                          "", //condicion de pago
                          "", //tipotransporte
                           0, //diasflete
                           0.0, //costoflete
                           0, //codigomonedaflete
                          "", //fotocotizacion
                           "", //justificacion
                           "", //observacion    
                          false, 
                          false, 
                          "", 
                          false, 
                          "", 
                          false, 
                          0,
                          "",
                          true
                       );   
                    
                    if(radio_sinaprobar.isSelected()){
                        opcion = 0;
                    }

                    if(radio_aprobada.isSelected()){
                        opcion = 1;
                    }

                    if(radio_autorizada.isSelected()){
                        opcion = 2;
                    } 

                           
       

               try {
                   cotizacion.consultar_cotizacion(table_posicioncotizacion,opcion);
               } catch (SQLException ex) {

               }
        
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numerosolicitud.setText("");
             }   
        }            
        
            
    }//GEN-LAST:event_txt_numerosolicitudKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        ctrl_cotizacion cotizacion = new ctrl_cotizacion(
                   0, 
                   0, 
                   "", 
                   "", 
                   0, 
                   0, 
                   0, 
                   0, 
                   0, 
                   0,
                   0.0, 
                   0.0, 
                   "", 
                   "", //tipo plazo entrega
                    0, //dias plazoentrega
                   "", //condicion de pago
                   "", //tipotransporte
                    0, //diasflete
                    0.0, //costoflete
                    0, //codigomonedaflete
                   "", //fotocotizacion
                    "", //justificacion
                    "", //observacion    
                   false, 
                   false, 
                   "", 
                   false, 
                   "", 
                   false, 
                   0,
                   "",
                   true
                );       
                
        try {
            cotizacion.consultar_cotizacion_sin_aprobar(table_posicioncotizacion);
        } catch (SQLException ex) {
            
        }
            
        ctrl_comun ctrl = new ctrl_comun(17);

        cmb_proveedor = ctrl.cargar_combo(cmb_proveedor, "Seleccione...");
            
    }//GEN-LAST:event_formWindowOpened

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_anularcotizacion frm = new frm_anularcotizacion();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void txt_numeromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeromaterialKeyReleased
        Integer opcion = 0;
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
                ctrl_cotizacion cotizacion = new ctrl_cotizacion(
                          0, 
                          0, 
                          "", 
                          "", 
                          0, 
                          Integer.parseInt(txt_numeromaterial.getText().trim()), 
                          0, 
                          0, 
                          0, 
                          0,
                          0.0, 
                          0.0, 
                          "", 
                          "", //tipo plazo entrega
                           0, //dias plazoentrega
                          "", //condicion de pago
                          "", //tipotransporte
                           0, //diasflete
                           0.0, //costoflete
                           0, //codigomonedaflete
                          "", //fotocotizacion
                           "", //justificacion
                           "", //observacion    
                          false, 
                          false, 
                          "", 
                          false, 
                          "", 
                          false, 
                          0,
                          "",
                          true
                       );   
                
                

               try {
                   cotizacion.consultar_cotizacion(table_posicioncotizacion,0);
               } catch (SQLException ex) {

               }
        
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - CONSULTAR COTIZACIÓN", JOptionPane.ERROR_MESSAGE,null);
                txt_numerosolicitud.setText("");
             }   
        }        
    }//GEN-LAST:event_txt_numeromaterialKeyReleased

    private void cmb_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proveedorActionPerformed
        Integer opcion = 0;
        
        if(evt.getModifiers() != 0){
        
            if (!cmb_proveedor.getSelectedItem().equals("Seleccione...")){

                ctrl_cotizacion cotizacion = new ctrl_cotizacion(
                                  0, 
                                  Integer.parseInt(cmb_proveedor.getSelectedItem().toString().substring(0,3).trim()), 
                                  "", 
                                  "", 
                                  0, 
                                  0, 
                                  0, 
                                  0, 
                                  0, 
                                  0,
                                  0.0, 
                                  0.0, 
                                  "", 
                                  "", //tipo plazo entrega
                                   0, //dias plazoentrega
                                  "", //condicion de pago
                                  "", //tipotransporte
                                   0, //diasflete
                                   0.0, //costoflete
                                   0, //codigomonedaflete
                                  "", //fotocotizacion
                                   "", //justificacion
                                   "", //observacion    
                                  false, 
                                  false, 
                                  "", 
                                  false, 
                                  "", 
                                  false, 
                                  0,
                                  "",
                                  true
                               );   

                    if(radio_sinaprobar.isSelected()){
                        opcion = 0;
                    }

                    if(radio_aprobada.isSelected()){
                        opcion = 1;
                    }

                    if(radio_autorizada.isSelected()){
                        opcion = 2;
                    } 

                 

                       try {
                           cotizacion.consultar_cotizacion(table_posicioncotizacion,opcion);
                       } catch (SQLException ex) {

                       }
            }
        }    
    }//GEN-LAST:event_cmb_proveedorActionPerformed

    private void radio_sinaprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_sinaprobarActionPerformed
        Integer proveedor;
        Integer id_solicitud;
        Integer nromaterial;

        if (!cmb_proveedor.getSelectedItem().equals("Seleccione...")){
            proveedor = Integer.parseInt(cmb_proveedor.getSelectedItem().toString().substring(0,3).trim());
        }
        else{
            proveedor = 0;
        }

        if (!txt_numerosolicitud.getText().trim().equals("")){
            id_solicitud = Integer.parseInt(txt_numerosolicitud.getText().trim());
        }
        else{
            id_solicitud = 0;
        }

        if (!txt_numeromaterial.getText().trim().equals("")){
            nromaterial = Integer.parseInt(txt_numeromaterial.getText().trim());
        }
        else{
            nromaterial = 0;
        }

        ctrl_cotizacion cotizacion = new ctrl_cotizacion(
            0,
            proveedor,
            "",
            "",
            id_solicitud,
            nromaterial,
            0,
            0,
            0,
            0,
            0.0,
            0.0,
            "",
            "", //tipo plazo entrega
            0, //dias plazoentrega
            "", //condicion de pago
            "", //tipotransporte
            0, //diasflete
            0.0, //costoflete
            0, //codigomonedaflete
            "", //fotocotizacion
            "", //justificacion
            "", //observacion
            false,
            false,
            "",
            false,
            "",
            false,
            0,
            "",
            true
        );

        try {
            cotizacion.consultar_cotizacion(table_posicioncotizacion,0);
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_radio_sinaprobarActionPerformed

    private void radio_aprobadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_aprobadaActionPerformed
        Integer proveedor;
        Integer id_solicitud;
        Integer nromaterial;

        if (!cmb_proveedor.getSelectedItem().equals("Seleccione...")){
            proveedor = Integer.parseInt(cmb_proveedor.getSelectedItem().toString().substring(0,3).trim());
        }
        else{
            proveedor = 0;
        }

        if (!txt_numerosolicitud.getText().trim().equals("")){
            id_solicitud = Integer.parseInt(txt_numerosolicitud.getText().trim());
        }
        else{
            id_solicitud = 0;
        }

        if (!txt_numeromaterial.getText().trim().equals("")){
            nromaterial = Integer.parseInt(txt_numeromaterial.getText().trim());
        }
        else{
            nromaterial = 0;
        }

        ctrl_cotizacion cotizacion = new ctrl_cotizacion(
            0,
            proveedor,
            "",
            "",
            id_solicitud,
            nromaterial,
            0,
            0,
            0,
            0,
            0.0,
            0.0,
            "",
            "", //tipo plazo entrega
            0, //dias plazoentrega
            "", //condicion de pago
            "", //tipotransporte
            0, //diasflete
            0.0, //costoflete
            0, //codigomonedaflete
            "", //fotocotizacion
            "", //justificacion
            "", //observacion
            false,
            false,
            "",
            false,
            "",
            false,
            0,
            "",
            true
        );

        try {
            cotizacion.consultar_cotizacion(table_posicioncotizacion,1);
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_radio_aprobadaActionPerformed

    private void radio_autorizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_autorizadaActionPerformed
        Integer proveedor;
        Integer id_solicitud;
        Integer nromaterial;

        if (!cmb_proveedor.getSelectedItem().equals("Seleccione...")){
            proveedor = Integer.parseInt(cmb_proveedor.getSelectedItem().toString().substring(0,3).trim());
        }
        else{
            proveedor = 0;
        }

        if (!txt_numerosolicitud.getText().trim().equals("")){
            id_solicitud = Integer.parseInt(txt_numerosolicitud.getText().trim());
        }
        else{
            id_solicitud = 0;
        }

        if (!txt_numeromaterial.getText().trim().equals("")){
            nromaterial = Integer.parseInt(txt_numeromaterial.getText().trim());
        }
        else{
            nromaterial = 0;
        }

        ctrl_cotizacion cotizacion = new ctrl_cotizacion(
            0,
            proveedor,
            "",
            "",
            id_solicitud,
            nromaterial,
            0,
            0,
            0,
            0,
            0.0,
            0.0,
            "",
            "", //tipo plazo entrega
            0, //dias plazoentrega
            "", //condicion de pago
            "", //tipotransporte
            0, //diasflete
            0.0, //costoflete
            0, //codigomonedaflete
            "", //fotocotizacion
            "", //justificacion
            "", //observacion
            false,
            false,
            "",
            false,
            "",
            false,
            0,
            "",
            true
        );

        try {
            cotizacion.consultar_cotizacion(table_posicioncotizacion,2);
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_radio_autorizadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_anularcotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    protected static javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox<String> cmb_proveedor;
    private javax.swing.ButtonGroup group_estatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_nrosolicitud1;
    private javax.swing.JLabel lbl_titulodetallesolicitud;
    private javax.swing.JLabel lbl_titulodetallesolicitud1;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JRadioButton radio_aprobada;
    private javax.swing.JRadioButton radio_autorizada;
    private javax.swing.JRadioButton radio_sinaprobar;
    protected static javax.swing.JTable table_posicioncotizacion;
    private javax.swing.JTextField txt_numeromaterial;
    private javax.swing.JTextField txt_numerosolicitud;
    // End of variables declaration//GEN-END:variables
}
