/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controlador.ctrl_reserva;
import controlador.ctrl_usuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.class_usuario;
import static view.frm_actualizarmaterial.lbl_foto;
import static view.frm_reserva.txt_numeromaterial;

/**
 *
 * @author ruben
 */
public class frm_autorizarreserva extends javax.swing.JFrame {

    private Integer fila_reserva;
    private Integer fila_posicion;
    public frm_autorizarreserva() {
        initComponents();
        this.getContentPane().setBackground(new Color(240,240,240)); 
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){}
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bot_buscar = new javax.swing.JButton();
        txt_numeroreserva = new javax.swing.JTextField();
        lbl_nroreserva = new javax.swing.JLabel();
        lbl_titulodetallereserva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_resumenreserva = new javax.swing.JTable();
        bot_autorizar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_detallereserva = new javax.swing.JTable();
        lbl_titulodetallereserva1 = new javax.swing.JLabel();
        bot_anular = new javax.swing.JButton();
        bot_reversar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_materialsolicitado = new javax.swing.JLabel();
        lbl_umb = new javax.swing.JLabel();
        lbl_numeromaterial = new javax.swing.JLabel();
        lbl_proyecto = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_empresa = new javax.swing.JLabel();
        lbl_fecharequerida = new javax.swing.JLabel();
        lbl_justificacion = new javax.swing.JLabel();
        spin_cantidadautorizada = new javax.swing.JSpinner();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        lbl_desnombre = new javax.swing.JLabel();
        lbl_desempresa = new javax.swing.JLabel();
        lbl_desproyecto = new javax.swing.JLabel();
        lbl_desumb = new javax.swing.JLabel();
        lbl_desfecharequerida = new javax.swing.JLabel();
        lbl_desnumaterial = new javax.swing.JLabel();
        lbl_desmaterial = new javax.swing.JLabel();
        lbl_desjustificacion = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chk_seleccionartodo = new javax.swing.JCheckBox();

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });

        txt_numeroreserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numeroreserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeroreservaKeyReleased(evt);
            }
        });

        lbl_nroreserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nroreserva.setText("NRO DE RESERVA");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulodetallereserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallereserva.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallereserva.setText("RESERVA PENDIENTES POR AUTORIZAR");
        getContentPane().add(lbl_titulodetallereserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        table_resumenreserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID RESERVA", "CEDULA", "NOMBRE", "DESCRIPCION AREA", "PROYECTO", "EMPRESA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_resumenreserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_resumenreservaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_resumenreserva);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1240, 110));

        bot_autorizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_autorizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autorizar.png"))); // NOI18N
        bot_autorizar.setText("AUTORIZAR POSICIÓN");
        bot_autorizar.setEnabled(false);
        bot_autorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_autorizarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_autorizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, 40));
        complemento.DisableBorderButton(bot_autorizar);

        table_detallereserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "POSICIÓN", "NRO MATERIAL", "MATERIAL SOLICITADO", "CANTIDAD APROBADA", "CANTIDAD AUTORIZADA", "UMB", "GRUPO DE ARTÍCULO", "FECHA REQUERIDA", "JUSTIFICACIÓN", "OBSERVACIÓN", "EMPRESA", "CEDULA", "NOMBRE", "DESCRIPCION AREA", "PROYECTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detallereserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_detallereservaMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(table_detallereserva);
        if (table_detallereserva.getColumnModel().getColumnCount() > 0) {
            table_detallereserva.getColumnModel().getColumn(0).setMinWidth(30);
            table_detallereserva.getColumnModel().getColumn(0).setPreferredWidth(30);
            table_detallereserva.getColumnModel().getColumn(0).setMaxWidth(30);
            table_detallereserva.getColumnModel().getColumn(10).setMinWidth(1);
            table_detallereserva.getColumnModel().getColumn(10).setPreferredWidth(1);
            table_detallereserva.getColumnModel().getColumn(10).setMaxWidth(1);
            table_detallereserva.getColumnModel().getColumn(11).setMinWidth(0);
            table_detallereserva.getColumnModel().getColumn(11).setPreferredWidth(0);
            table_detallereserva.getColumnModel().getColumn(11).setMaxWidth(0);
            table_detallereserva.getColumnModel().getColumn(12).setMinWidth(0);
            table_detallereserva.getColumnModel().getColumn(12).setPreferredWidth(0);
            table_detallereserva.getColumnModel().getColumn(12).setMaxWidth(0);
            table_detallereserva.getColumnModel().getColumn(13).setMinWidth(0);
            table_detallereserva.getColumnModel().getColumn(13).setPreferredWidth(0);
            table_detallereserva.getColumnModel().getColumn(13).setMaxWidth(0);
            table_detallereserva.getColumnModel().getColumn(14).setMinWidth(0);
            table_detallereserva.getColumnModel().getColumn(14).setPreferredWidth(0);
            table_detallereserva.getColumnModel().getColumn(14).setMaxWidth(0);
            table_detallereserva.getColumnModel().getColumn(15).setMinWidth(0);
            table_detallereserva.getColumnModel().getColumn(15).setPreferredWidth(0);
            table_detallereserva.getColumnModel().getColumn(15).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 1240, 120));

        lbl_titulodetallereserva1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallereserva1.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallereserva1.setText("DETALLES RESERVA ");
        getContentPane().add(lbl_titulodetallereserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        bot_anular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_anular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        bot_anular.setText("ANULAR POSICIÓN");
        bot_anular.setEnabled(false);
        bot_anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_anularActionPerformed(evt);
            }
        });
        getContentPane().add(bot_anular, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 250, 40));
        complemento.DisableBorderButton(bot_anular);

        bot_reversar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reversar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reverse.png"))); // NOI18N
        bot_reversar.setText("REVERSAR POSICIÓN");
        bot_reversar.setEnabled(false);
        bot_reversar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reversarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_reversar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 250, 40));
        complemento.DisableBorderButton(bot_reversar);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        lbl_cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad.setText("CANTIDAD A AUTORIZAR");
        jPanel1.add(lbl_cantidad);
        lbl_cantidad.setBounds(10, 70, 153, 15);

        lbl_materialsolicitado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_materialsolicitado.setText("MATERIAL SOLICITADO");
        jPanel1.add(lbl_materialsolicitado);
        lbl_materialsolicitado.setBounds(10, 40, 144, 15);

        lbl_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb.setText("UNIDAD DE MEDIDA BÁSICA");
        jPanel1.add(lbl_umb);
        lbl_umb.setBounds(10, 100, 180, 15);

        lbl_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_numeromaterial.setText("NÚMERO MATERIAL");
        jPanel1.add(lbl_numeromaterial);
        lbl_numeromaterial.setBounds(10, 10, 120, 15);

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        jPanel1.add(lbl_proyecto);
        lbl_proyecto.setBounds(10, 160, 64, 15);

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombre.setText("NOMBRE SOLICITANTE");
        jPanel1.add(lbl_nombre);
        lbl_nombre.setBounds(10, 130, 150, 15);

        lbl_empresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empresa.setText("EMPRESA");
        jPanel1.add(lbl_empresa);
        lbl_empresa.setBounds(10, 190, 59, 15);

        lbl_fecharequerida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fecharequerida.setText("FECHA REQUERIDA");
        jPanel1.add(lbl_fecharequerida);
        lbl_fecharequerida.setBounds(10, 220, 115, 15);

        lbl_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_justificacion.setText("JUSTIFICACIÓN");
        jPanel1.add(lbl_justificacion);
        lbl_justificacion.setBounds(10, 250, 92, 15);

        spin_cantidadautorizada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidadautorizada.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spin_cantidadautorizada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_cantidadautorizadaStateChanged(evt);
            }
        });
        jPanel1.add(spin_cantidadautorizada);
        spin_cantidadautorizada.setBounds(190, 70, 60, 20);

        panel_foto.setBackground(new java.awt.Color(245, 245, 245));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 138, 218));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        jPanel1.add(panel_foto);
        panel_foto.setBounds(788, 13, 310, 250);

        lbl_desnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desnombre);
        lbl_desnombre.setBounds(190, 130, 380, 20);

        lbl_desempresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desempresa);
        lbl_desempresa.setBounds(190, 190, 300, 20);

        lbl_desproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desproyecto);
        lbl_desproyecto.setBounds(190, 160, 460, 20);

        lbl_desumb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desumb);
        lbl_desumb.setBounds(190, 100, 210, 20);

        lbl_desfecharequerida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desfecharequerida);
        lbl_desfecharequerida.setBounds(190, 220, 190, 20);

        lbl_desnumaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desnumaterial);
        lbl_desnumaterial.setBounds(190, 10, 570, 20);

        lbl_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desmaterial);
        lbl_desmaterial.setBounds(190, 40, 590, 20);

        lbl_desjustificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desjustificacion);
        lbl_desjustificacion.setBounds(190, 250, 590, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 1240, 280));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("AUTORIZAR RESERVA");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(290, 20, 200, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 240, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1130, 20, 113, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(800, 10, 300, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(802, 30, 300, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        chk_seleccionartodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_seleccionartodo.setText("Seleccionar Todo");
        chk_seleccionartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_seleccionartodoActionPerformed(evt);
            }
        });
        getContentPane().add(chk_seleccionartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_numeroreservaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroreservaKeyReleased

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){
        }
        else{
            if (evt.getKeyCode() == 27){

                bot_reiniciar.doClick();

            }
            else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numeroreserva.setText("");
            }
        }

    }//GEN-LAST:event_txt_numeroreservaKeyReleased

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
       /* ctrl_reserva reserva = null;

        if(!txt_numeroreserva.getText().trim().equals("")){
            reserva = new ctrl_reserva(

                Integer.parseInt(txt_numeroreserva.getText().trim()),
                0,
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material
                0,
                "",
                0,
                "",
                0,
                0,
                "", //fecha reserva
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );

            reserva.consultar_reserva_detalle(table_resumenreserva);
        }*/

    }//GEN-LAST:event_bot_buscarActionPerformed

    private void table_resumenreservaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_resumenreservaMousePressed
        ctrl_reserva reserva = null;
        
        
        
        fila_reserva = table_resumenreserva.getSelectedRow();

        
            reserva = new ctrl_reserva(

                Integer.parseInt(table_resumenreserva.getValueAt(fila_reserva, 0).toString()),
                0,
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha reserva
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );

            reserva.consultar_reserva_detalle_autorizada(Integer.parseInt(frm_principalM1.lbl_nivel.getText()),table_detallereserva);
        
        
      
    }//GEN-LAST:event_table_resumenreservaMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_reserva reserva=null;
        
        reserva = new ctrl_reserva(

            0,
            Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
            Integer.parseInt(frm_principalM1.lbl_area.getText()),
            "",
            0,
            0, //numero de material
            "",             // descripcion de material
            0,
            "",
            0,
            "",
            0,
            0,
            0,
            0,
            0,    
            "", //fecha reserva
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""    
        ); 
        
        reserva.consultar_reserva_por_autorizar(Integer.parseInt(frm_principalM1.lbl_nivel.getText()),table_resumenreserva);
        
    }//GEN-LAST:event_formWindowOpened

    private void table_detallereservaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detallereservaMousePressed
        Integer fila;
        BufferedImage img;
        
        fila_posicion  = table_detallereserva.getSelectedRow();
        
        lbl_desempresa.setText(table_detallereserva.getValueAt(fila_posicion, 11).toString());
        lbl_desnombre.setText(table_detallereserva.getValueAt(fila_posicion, 13).toString());
        lbl_desproyecto.setText(table_detallereserva.getValueAt(fila_posicion, 15).toString());
        lbl_desnumaterial.setText(table_detallereserva.getValueAt(fila_posicion, 2).toString());
        
        lbl_desmaterial.setText(table_detallereserva.getValueAt(fila_posicion, 3).toString());
        lbl_desumb.setText(table_detallereserva.getValueAt(fila_posicion, 6).toString());
        
        spin_cantidadautorizada.setValue(table_detallereserva.getValueAt(fila_posicion, 4));
        
        lbl_desfecharequerida.setText(table_detallereserva.getValueAt(fila_posicion, 8).toString());
        
        lbl_desjustificacion.setText(table_detallereserva.getValueAt(fila_posicion, 9).toString());
        
        if (table_detallereserva.getValueAt(fila_posicion, 0).equals(false)){
            table_detallereserva.setValueAt(true, fila_posicion, 0);
        }
        else{
            table_detallereserva.setValueAt(false, fila_posicion, 0);
        }
        
        
        ctrl_reserva reserva = new ctrl_reserva(
                                0,
                                0,
                                0,
                                "",
                                0,
                                Integer.parseInt(table_detallereserva.getValueAt(fila_posicion, 2).toString()), //numero de material
                                "",             // descripcion de material     
                                0,
                                "",
                                0,
                                "",
                                0,    
                                0,
                                0,
                                0,
                                0,
                                "", //fecha reserva
                                "",
                                "",
                                false,
                                "",
                                "",
                                "",
                                "",
                                "",
                                "",
                                "",
                                "",
                                ""
                        );  
        
        try{
            img = funciones.decodeToImage(reserva.consultar_foto());
            lbl_foto.setIcon(null);
            ImageIcon icon = new ImageIcon(img);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(),lbl_foto.getHeight(), Image.SCALE_DEFAULT));
            
            lbl_foto.setIcon(icono);
        }
        catch(NullPointerException ex){}
        
        bot_autorizar.setEnabled(true);
                        
        bot_anular.setEnabled(true);
        
        bot_reversar.setEnabled(true);
        
        
    }//GEN-LAST:event_table_detallereservaMousePressed

    private void bot_autorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_autorizarActionPerformed
        
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
         int i=0;
        boolean autorizado= false;
        Integer nroreserva=0;
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallereserva.getModel();
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
       
        
        ctrl_usuario usuario = new ctrl_usuario(
                      Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                       "", 
                       "", 
                       "", 
                       "", 
                       0, 
                       "",
                       0,
                       "",
                       0,
                       true,
                       ""
            );

            modelo_usuario = usuario.buscar_usuario();
            
            respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR AUTORIZAR UNA POSICION, DESEA CONTINUAR?");
        
            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
                    
                            while(i < table_detallereserva.getRowCount()){

                              if(table_detallereserva.getValueAt(i, 0).equals(true)){ 
                                fila_posicion = i;


                                ctrl_reserva reserva = new ctrl_reserva(

                                    Integer.parseInt(table_resumenreserva.getValueAt(fila_reserva, 0).toString()),
                                    Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                                    0,
                                    "",
                                    0,
                                    Integer.parseInt(table_detallereserva.getValueAt(fila_posicion, 2).toString()), //numero de material
                                    "",             // descripcion de material     
                                    0,
                                    "",
                                    0,
                                    "",
                                    Integer.parseInt(table_detallereserva.getValueAt(fila_posicion, 1).toString()),
                                    0,
                                    0,
                                    Integer.parseInt(table_detallereserva.getValueAt(fila_posicion, 5).toString()),
                                    0,    
                                    "", //fecha reserva
                                    "",
                                    lbl_desjustificacion.getText().trim().toUpperCase() + " AUTORIZADO POR " + frm_principalM1.lbl_nombres.getText(),
                                    false,
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    ""    
                                );  


                            if(reserva.autorizar_reserva_posicion(Integer.parseInt(frm_principalM1.lbl_nivel.getText()))){
                                 autorizado = true; 

                                 nroreserva = Integer.parseInt(table_resumenreserva.getValueAt(fila_reserva, 0).toString());

                                 //reserva.consultar_reserva_por_autorizar(Integer.parseInt(frm_principalM1.lbl_nivel.getText()),table_resumenreserva);
                            }
                           }  

                          i++;
                          }   
                    }
                    else{

                        JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                }                      
                        
            }
            if (autorizado==true){
                    i--;
                    if (i>0){
                       JOptionPane.showMessageDialog(null, "AUTORIZADO POSICIONES DE LA RESERVA " + nroreserva); 
                    }
                    else{
                       JOptionPane.showMessageDialog(null, "AUTORIZADO POSICION DE LA RESERVA" + nroreserva); 
                    }
                    
                      bot_reiniciar.doClick();
           }
                bot_autorizar.setEnabled(false);
            
    }//GEN-LAST:event_bot_autorizarActionPerformed

    private void bot_anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_anularActionPerformed
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
        int i = 0;
        boolean anulado= false;
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallereserva.getModel();
        Integer nroreserva=0;
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
        
        ctrl_usuario usuario = new ctrl_usuario(
                      Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                       "", 
                       "", 
                       "", 
                       "", 
                       0, 
                       "",
                       0,
                       "",
                       0,
                       true,
                       ""
            );

            modelo_usuario = usuario.buscar_usuario();
            
            respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR ANULAR UNA POSICION, DESEA CONTINUAR?");
        
            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
            
                                while(i < table_detallereserva.getRowCount()){

                                    if(table_detallereserva.getValueAt(i, 0).equals(true)){ 
                                        fila_posicion = i;                


                                        ctrl_reserva reserva = new ctrl_reserva(

                                            Integer.parseInt(table_resumenreserva.getValueAt(fila_reserva, 0).toString()),
                                            Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                                            0,
                                            "",
                                            0,
                                            0, //numero de material
                                            "",             // descripcion de material     
                                            0,
                                            "",
                                            0,
                                            "",
                                            Integer.parseInt(table_detallereserva.getValueAt(fila_posicion, 1).toString()),
                                            0,
                                            0,
                                            0,
                                            0,    
                                            "", //fecha reserva
                                            "",
                                            lbl_desjustificacion.getText().trim().toUpperCase() + " ANULADO POR " + frm_principalM1.lbl_nombres.getText(),
                                            false,
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            ""    
                                        );  


                                        if(reserva.autorizar_reserva_posicion_anular(Integer.parseInt(frm_principalM1.lbl_nivel.getText()))){
                                           anulado =true;
                                           nroreserva = Integer.parseInt(table_resumenreserva.getValueAt(fila_reserva, 0).toString());

                                        }

                                        if (anulado==true){
                                            i--;
                                            if (i>0){
                                                JOptionPane.showMessageDialog(null, "ANULADO POSICIONES DE LA RESERVA " + nroreserva); 
                                            }
                                            else{
                                                JOptionPane.showMessageDialog(null, "ANULADO POSICION DE LA RESERVA" + nroreserva); 
                                            }

                                            bot_reiniciar.doClick();
                                        }    
                                    }
                                     i++;
                                }    
                        }
                        else{

                            JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        }
                }
                 else{
                     JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                 }                          
    
            }
            
                modelotabla.setRowCount(0);
                bot_anular.setEnabled(false);
    }//GEN-LAST:event_bot_anularActionPerformed

    private void bot_reversarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reversarActionPerformed
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
        int i = 0;
        boolean reversar = false;
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallereserva.getModel();
        Integer nroreserva=0;
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
        
        ctrl_usuario usuario = new ctrl_usuario(
                      Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                       "", 
                       "", 
                       "", 
                       "", 
                       0, 
                       "",
                       0,
                       "",
                       0,
                       true,
                       ""
            );

            modelo_usuario = usuario.buscar_usuario();
            
            respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR REVERSAR POSICION(ES), DESEA CONTINUAR?");
        
            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
               
                                while(i < table_detallereserva.getRowCount()){

                                    if(table_detallereserva.getValueAt(i, 0).equals(true)){ 
                                        fila_posicion = i;                


                                        ctrl_reserva reserva = new ctrl_reserva(

                                            Integer.parseInt(table_resumenreserva.getValueAt(fila_reserva, 0).toString()),
                                            Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                                            0,
                                            "",
                                            0,
                                            0, //numero de material
                                            "",             // descripcion de material     
                                            0,
                                            "",
                                            0,
                                            "",
                                            Integer.parseInt(table_detallereserva.getValueAt(fila_posicion, 1).toString()),
                                            0,
                                            0,
                                            0,
                                            0,    
                                            "", //fecha reserva
                                            "",
                                            lbl_desjustificacion.getText().trim().toUpperCase() + " REVERSADO POR " + frm_principalM1.lbl_nombres.getText(),
                                            false,
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            "",
                                            ""     
                                        );  


                                        if(reserva.reversar_reserva_posicion()){
                                           reversar = true;
                                           nroreserva = Integer.parseInt(table_resumenreserva.getValueAt(fila_reserva, 0).toString());
                                            reserva.consultar_reserva_por_autorizar(Integer.parseInt(frm_principalM1.lbl_nivel.getText()),table_detallereserva);
                                        }

                                    if (reversar==true){
                                        i--;
                                        if (i>0){
                                            JOptionPane.showMessageDialog(null, "REVERSADO POSICIONES DE LA RESERVA " + nroreserva); 
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(null, "REVERSADO POSICION DE LA RESERVA" + nroreserva); 
                                        }
                                        bot_reiniciar.doClick();
                                    }    
                                  }
                                  i++;
                                }   
                        }
                        else{
                           JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                    }                          
    
                }
            
                modelotabla.setRowCount(0);
                bot_anular.setEnabled(false);
    }//GEN-LAST:event_bot_reversarActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_autorizarreserva frm = new frm_autorizarreserva();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void chk_seleccionartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_seleccionartodoActionPerformed
        int i;
        i = 0;
        boolean seleccionar;
        if (chk_seleccionartodo.isSelected()){
            seleccionar = true;
            bot_autorizar.setEnabled(true);
        }
        else{
            seleccionar = false;
            bot_autorizar.setEnabled(false);
        }
        
        while(i < table_detallereserva.getRowCount()){
            table_detallereserva.setValueAt(seleccionar,i, 0);
            i++;
        }    
    }//GEN-LAST:event_chk_seleccionartodoActionPerformed

    private void spin_cantidadautorizadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_cantidadautorizadaStateChanged
        fila_posicion  = table_detallereserva.getSelectedRow();
        
        
        try{
           table_detallereserva.setValueAt(spin_cantidadautorizada.getValue(), fila_posicion, 5);
        }
        catch(NullPointerException ex){
            
        }
    }//GEN-LAST:event_spin_cantidadautorizadaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_autorizarreserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_anular;
    private javax.swing.JButton bot_autorizar;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_reversar;
    private javax.swing.JCheckBox chk_seleccionartodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_desempresa;
    private javax.swing.JLabel lbl_desfecharequerida;
    private javax.swing.JLabel lbl_desjustificacion;
    private javax.swing.JLabel lbl_desmaterial;
    private javax.swing.JLabel lbl_desnombre;
    private javax.swing.JLabel lbl_desnumaterial;
    private javax.swing.JLabel lbl_desproyecto;
    private javax.swing.JLabel lbl_desumb;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_fecharequerida;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_justificacion;
    private javax.swing.JLabel lbl_materialsolicitado;
    private javax.swing.JLabel lbl_nombre;
    protected static javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nroreserva;
    private javax.swing.JLabel lbl_numeromaterial;
    private javax.swing.JLabel lbl_proyecto;
    private javax.swing.JLabel lbl_titulodetallereserva;
    private javax.swing.JLabel lbl_titulodetallereserva1;
    private javax.swing.JLabel lbl_umb;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JSpinner spin_cantidadautorizada;
    private javax.swing.JTable table_detallereserva;
    private javax.swing.JTable table_resumenreserva;
    private javax.swing.JTextField txt_numeroreserva;
    // End of variables declaration//GEN-END:variables
}
