/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import controlador.ctrl_entrada;
import controlador.ctrl_reserva;
import controlador.ctrl_salida;
import formatos_pdf.pdf_salida;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//q import model.class_entrada;
//q import model.class_ordendecompra;
//q import model.class_salida;
import javax.swing.UIManager;
import model.class_salida;

/**
 *
 * @author ruben
 */
public class frm_salida extends javax.swing.JFrame {

    /**
     * Creates new form frm_salida
     * 
     */
    public frm_salida() {
        initComponents();
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - SALIDA DE MATERIAL");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_posicion = new javax.swing.JTextField();
        txt_iddocumento = new javax.swing.JTextField();
        bot_borrarposicion = new javax.swing.JButton();
        lbl_nroreserva = new javax.swing.JLabel();
        txt_numeroreserva = new javax.swing.JTextField();
        lbl_titulodetallereserva = new javax.swing.JLabel();
        lbl_titulodetalleoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_reserva = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_almacen = new javax.swing.JLabel();
        cmb_almacen = new javax.swing.JComboBox<>();
        lbl_ubicacion = new javax.swing.JLabel();
        cmb_ubicacion = new javax.swing.JComboBox<>();
        lbl_proyecto = new javax.swing.JLabel();
        lbl_destino = new javax.swing.JLabel();
        txt_destino = new javax.swing.JTextField();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        lbl_numeromaterial = new javax.swing.JLabel();
        lbl_cantidadreservada = new javax.swing.JLabel();
        lbl_nombresolicitante = new javax.swing.JLabel();
        spin_cantidadegresada = new javax.swing.JSpinner();
        lbl_cantidadegresada = new javax.swing.JLabel();
        lbl_fechasalida = new javax.swing.JLabel();
        lbl_numeromaterial1 = new javax.swing.JLabel();
        lbl_desdescripcion = new javax.swing.JLabel();
        lbl_descantidadconformada = new javax.swing.JLabel();
        lbl_desnombresolicitante = new javax.swing.JLabel();
        lbl_desfechasalida = new javax.swing.JLabel();
        lbl_desproyecto = new javax.swing.JLabel();
        lbl_desumb = new javax.swing.JLabel();
        lbl_desnromaterial = new javax.swing.JLabel();
        lbl_umb = new javax.swing.JLabel();
        lbl_desunidad = new javax.swing.JLabel();
        lbl_justificacion = new javax.swing.JLabel();
        txt_stockdisponible = new javax.swing.JTextField();
        lbl_stockdisponible = new javax.swing.JLabel();
        bot_verdisponibilidad = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_justificacion = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bot_agregarposicion = new javax.swing.JButton();
        bot_verdocumento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_posicionsalida = new javax.swing.JTable();

        txt_posicion.setText("0");

        txt_iddocumento.setText("0");

        bot_borrarposicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_borrarposicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        bot_borrarposicion.setText("BORRAR POSICIÓN");
        bot_borrarposicion.setEnabled(false);
        bot_borrarposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_borrarposicionActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nroreserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nroreserva.setText("NRO DE RESERVA");
        getContentPane().add(lbl_nroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_numeroreserva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_numeroreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numeroreservaActionPerformed(evt);
            }
        });
        txt_numeroreserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeroreservaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numeroreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 80, 20));

        lbl_titulodetallereserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallereserva.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallereserva.setText("DETALLES RESERVA APROBADAS");
        getContentPane().add(lbl_titulodetallereserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        lbl_titulodetalleoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetalleoc.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetalleoc.setText("DETALLES DE SALIDA");
        getContentPane().add(lbl_titulodetalleoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        table_reserva.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_reserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO RESERVA", "POSICIÓN", "NRO MATERIAL", "MATERIAL", "CANTIDAD APROBADA", "UMB", "GRUPO DE ARTICULO", "FECHA REQUERIDA", "EMPRESA", "CEDULA", "NOMBRE", "PROYECTO", "id_proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_reservaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_reserva);
        if (table_reserva.getColumnModel().getColumnCount() > 0) {
            table_reserva.getColumnModel().getColumn(0).setMinWidth(80);
            table_reserva.getColumnModel().getColumn(0).setPreferredWidth(80);
            table_reserva.getColumnModel().getColumn(0).setMaxWidth(80);
            table_reserva.getColumnModel().getColumn(1).setMinWidth(70);
            table_reserva.getColumnModel().getColumn(1).setPreferredWidth(70);
            table_reserva.getColumnModel().getColumn(1).setMaxWidth(70);
            table_reserva.getColumnModel().getColumn(2).setMinWidth(100);
            table_reserva.getColumnModel().getColumn(2).setPreferredWidth(100);
            table_reserva.getColumnModel().getColumn(2).setMaxWidth(100);
            table_reserva.getColumnModel().getColumn(3).setMinWidth(300);
            table_reserva.getColumnModel().getColumn(3).setPreferredWidth(300);
            table_reserva.getColumnModel().getColumn(3).setMaxWidth(300);
            table_reserva.getColumnModel().getColumn(4).setMinWidth(150);
            table_reserva.getColumnModel().getColumn(4).setPreferredWidth(150);
            table_reserva.getColumnModel().getColumn(4).setMaxWidth(150);
            table_reserva.getColumnModel().getColumn(5).setMinWidth(50);
            table_reserva.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_reserva.getColumnModel().getColumn(5).setMaxWidth(50);
            table_reserva.getColumnModel().getColumn(6).setMinWidth(0);
            table_reserva.getColumnModel().getColumn(6).setPreferredWidth(0);
            table_reserva.getColumnModel().getColumn(6).setMaxWidth(0);
            table_reserva.getColumnModel().getColumn(7).setMinWidth(120);
            table_reserva.getColumnModel().getColumn(7).setPreferredWidth(120);
            table_reserva.getColumnModel().getColumn(7).setMaxWidth(120);
            table_reserva.getColumnModel().getColumn(8).setMinWidth(120);
            table_reserva.getColumnModel().getColumn(8).setPreferredWidth(120);
            table_reserva.getColumnModel().getColumn(8).setMaxWidth(120);
            table_reserva.getColumnModel().getColumn(9).setMinWidth(0);
            table_reserva.getColumnModel().getColumn(9).setPreferredWidth(0);
            table_reserva.getColumnModel().getColumn(9).setMaxWidth(0);
            table_reserva.getColumnModel().getColumn(10).setMinWidth(150);
            table_reserva.getColumnModel().getColumn(10).setPreferredWidth(150);
            table_reserva.getColumnModel().getColumn(10).setMaxWidth(150);
            table_reserva.getColumnModel().getColumn(11).setMinWidth(180);
            table_reserva.getColumnModel().getColumn(11).setPreferredWidth(180);
            table_reserva.getColumnModel().getColumn(11).setMaxWidth(180);
            table_reserva.getColumnModel().getColumn(12).setMinWidth(0);
            table_reserva.getColumnModel().getColumn(12).setPreferredWidth(0);
            table_reserva.getColumnModel().getColumn(12).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1300, 180));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        lbl_almacen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_almacen.setText("ALMACÉN");
        jPanel1.add(lbl_almacen);
        lbl_almacen.setBounds(590, 50, 59, 15);

        cmb_almacen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_almacenActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_almacen);
        cmb_almacen.setBounds(740, 50, 170, 20);

        lbl_ubicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ubicacion.setText("UBICACIÓN");
        jPanel1.add(lbl_ubicacion);
        lbl_ubicacion.setBounds(590, 80, 80, 20);

        cmb_ubicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ubicacionActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_ubicacion);
        cmb_ubicacion.setBounds(740, 80, 170, 20);

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        jPanel1.add(lbl_proyecto);
        lbl_proyecto.setBounds(10, 190, 64, 15);

        lbl_destino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_destino.setText("DESTINO ");
        jPanel1.add(lbl_destino);
        lbl_destino.setBounds(590, 140, 57, 15);

        txt_destino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txt_destino);
        txt_destino.setBounds(740, 140, 260, 20);

        panel_foto.setBackground(new java.awt.Color(255, 255, 255));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));
        panel_foto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_foto.add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 160));

        jPanel1.add(panel_foto);
        panel_foto.setBounds(1050, 20, 240, 190);

        lbl_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_numeromaterial.setText("DESCRIPCIÓN MATERIAL");
        jPanel1.add(lbl_numeromaterial);
        lbl_numeromaterial.setBounds(10, 40, 160, 15);

        lbl_cantidadreservada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadreservada.setText("CANTIDAD APROBADA");
        jPanel1.add(lbl_cantidadreservada);
        lbl_cantidadreservada.setBounds(10, 70, 160, 15);

        lbl_nombresolicitante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombresolicitante.setText("NOMBRE SOLICITANTE");
        jPanel1.add(lbl_nombresolicitante);
        lbl_nombresolicitante.setBounds(10, 130, 150, 15);

        spin_cantidadegresada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidadegresada.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(spin_cantidadegresada);
        spin_cantidadegresada.setBounds(740, 20, 70, 20);

        lbl_cantidadegresada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadegresada.setText("CANTIDAD A EGRESAR");
        jPanel1.add(lbl_cantidadegresada);
        lbl_cantidadegresada.setBounds(590, 20, 138, 15);

        lbl_fechasalida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechasalida.setText("FECHA DE SALIDA");
        jPanel1.add(lbl_fechasalida);
        lbl_fechasalida.setBounds(10, 160, 110, 15);

        lbl_numeromaterial1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_numeromaterial1.setText("NÚMERO DE MATERIAL");
        jPanel1.add(lbl_numeromaterial1);
        lbl_numeromaterial1.setBounds(10, 10, 140, 15);

        lbl_desdescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desdescripcion);
        lbl_desdescripcion.setBounds(170, 40, 400, 20);

        lbl_descantidadconformada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_descantidadconformada);
        lbl_descantidadconformada.setBounds(180, 70, 60, 20);

        lbl_desnombresolicitante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desnombresolicitante);
        lbl_desnombresolicitante.setBounds(170, 130, 340, 20);

        lbl_desfechasalida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desfechasalida);
        lbl_desfechasalida.setBounds(170, 160, 230, 20);

        lbl_desproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desproyecto);
        lbl_desproyecto.setBounds(170, 190, 370, 20);

        lbl_desumb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desumb);
        lbl_desumb.setBounds(860, 10, 60, 20);

        lbl_desnromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desnromaterial);
        lbl_desnromaterial.setBounds(170, 10, 230, 20);

        lbl_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb.setText("UNIDAD MEDIDA BASE");
        jPanel1.add(lbl_umb);
        lbl_umb.setBounds(10, 100, 160, 15);

        lbl_desunidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desunidad);
        lbl_desunidad.setBounds(170, 100, 60, 20);

        lbl_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_justificacion.setText("JUSTIFICACIÓN");
        jPanel1.add(lbl_justificacion);
        lbl_justificacion.setBounds(590, 180, 100, 15);

        txt_stockdisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_stockdisponible.setEnabled(false);
        jPanel1.add(txt_stockdisponible);
        txt_stockdisponible.setBounds(740, 110, 90, 21);

        lbl_stockdisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_stockdisponible.setText("STOCK DISPONIBLE");
        jPanel1.add(lbl_stockdisponible);
        lbl_stockdisponible.setBounds(590, 110, 130, 20);

        bot_verdisponibilidad.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        bot_verdisponibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccionar.png"))); // NOI18N
        bot_verdisponibilidad.setText("VER DISPONIBILIDAD MATERIAL");
        bot_verdisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdisponibilidadActionPerformed(evt);
            }
        });
        jPanel1.add(bot_verdisponibilidad);
        bot_verdisponibilidad.setBounds(820, 10, 200, 30);
        complemento.DisableBorderButton(bot_verdisponibilidad);

        txt_justificacion.setColumns(20);
        txt_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_justificacion.setLineWrap(true);
        txt_justificacion.setRows(5);
        txt_justificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_justificacionKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txt_justificacion);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(740, 170, 270, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 1300, 230));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("SALIDA DE MATERIAL");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(260, 10, 170, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1113, 20, 130, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.setToolTipText("");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 100, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(870, 10, 230, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(872, 30, 230, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        bot_agregarposicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_agregarposicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilizar.png"))); // NOI18N
        bot_agregarposicion.setText("CONTABILIZAR POSICIÓN");
        bot_agregarposicion.setEnabled(false);
        bot_agregarposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregarposicionActionPerformed(evt);
            }
        });
        getContentPane().add(bot_agregarposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 260, 40));
        complemento.DisableBorderButton(bot_agregarposicion);

        bot_verdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_verdocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        bot_verdocumento.setText("VER DOCUMENTO");
        bot_verdocumento.setEnabled(false);
        bot_verdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_verdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 670, 190, 40));
        complemento.DisableBorderButton(bot_verdocumento);

        table_posicionsalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "POSICIÓN", "NÚMERO DE MATERIAL", "DESCRIPCIÓN DE MATERIAL", "CANTIDAD", "UMB", "FECHA DE SALIDA", "USUARIO", "ALMACEN", "DESTINO", "OBSERVACIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_posicionsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_posicionsalidaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table_posicionsalida);
        if (table_posicionsalida.getColumnModel().getColumnCount() > 0) {
            table_posicionsalida.getColumnModel().getColumn(6).setMinWidth(1);
            table_posicionsalida.getColumnModel().getColumn(6).setPreferredWidth(1);
            table_posicionsalida.getColumnModel().getColumn(6).setMaxWidth(1);
            table_posicionsalida.getColumnModel().getColumn(9).setMinWidth(1);
            table_posicionsalida.getColumnModel().getColumn(9).setPreferredWidth(1);
            table_posicionsalida.getColumnModel().getColumn(9).setMaxWidth(1);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 1300, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_agregarposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregarposicionActionPerformed
        frm_progress frm = new frm_progress(9,Integer.parseInt(spin_cantidadegresada.getValue().toString()));
        frm.setVisible(true);

    }//GEN-LAST:event_bot_agregarposicionActionPerformed

    private void bot_borrarposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_borrarposicionActionPerformed
        class_salida modelo_salida = null;
        ctrl_salida salida = null;
        Integer fila;
        
        fila = table_posicionsalida.getSelectedRow();
        
        table_posicionsalida.getValueAt(fila, 1);
        
                   salida  = new ctrl_salida(
                    Integer.parseInt(txt_iddocumento.getText().trim()), 
                    Integer.parseInt(txt_posicion.getText().trim()), 
                    Integer.parseInt(table_posicionsalida.getValueAt(fila, 1).toString()),                    "", //descripcion material
                    0,
                    "",
                    0,
                    "",
                    0,
                    "",
                    "",
                    Integer.parseInt(table_posicionsalida.getValueAt(fila, 4).toString()),
                    0,
                    3,
                    Integer.parseInt(txt_iddocumento.getText().trim()),
                    "", 
                    "", 
                    true
                           
            ); 
        
        
           modelo_salida = salida.borrar_posicion(table_posicionsalida,table_posicionsalida.getSelectedRow());
        
        if (table_posicionsalida.getRowCount() == 0){
            bot_verdocumento.setEnabled(false);   
        }
        bot_borrarposicion.setEnabled(false);
    }//GEN-LAST:event_bot_borrarposicionActionPerformed

    private void bot_verdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdocumentoActionPerformed
        try {
            pdf_salida.dato("\\\\192.168.0.3\\dist\\Documentos_SisTimaca",Integer.parseInt(txt_iddocumento.getText()),"");
        } catch (DocumentException | IOException | SQLException ex) {
            
        }
    }//GEN-LAST:event_bot_verdocumentoActionPerformed

    private void txt_numeroreservaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroreservaKeyReleased
               
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
               ctrl_reserva reserva = null;
       
                reserva = new ctrl_reserva(
                
                        Integer.parseInt(txt_numeroreserva.getText().trim()),
                        0,
                        0,
                        "",
                        0,
                        0, //numero de material
                        "",             // descripcion de material     
                        0,
                        "",
                        0,
                        "",
                        0,    
                        0,
                        0,
                        0,
                        0,    
                        "", //fecha reserva
                        "",
                        "",
                        false,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""
                );  
                if(!txt_numeroreserva.getText().trim().equals("")){
                    reserva.consultar_reserva_detalle_salida(table_reserva);
                }
                else{
                    reserva.consultar_reserva_conformadas(table_reserva);
                }     
                      
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numeroreserva.setText("");
             }   
        }            
        
            
    }//GEN-LAST:event_txt_numeroreservaKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                                  
             
                
        txt_numeroreserva.requestFocusInWindow();
        
               
        ctrl_reserva reserva=null;
        
        reserva = new ctrl_reserva(

            0,
            Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
            Integer.parseInt(frm_principalM1.lbl_area.getText()),
            "",
            0,
            0, //numero de material
            "",             // descripcion de material
            0,
            "",
            0,
            "",
            0,
            0,
            0,
            0,
            0,    
            "", //fecha reserva
            "",
            "",
            false,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""    
        ); 
        
        reserva.consultar_reserva_conformadas(table_reserva);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void table_reservaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_reservaMousePressed
        Integer fila;
        ctrl_reserva reserva=null;
        BufferedImage img;
        
        
        fila = table_reserva.getSelectedRow();
        
        lbl_desnromaterial.setText(table_reserva.getValueAt(fila,2).toString());
        lbl_desdescripcion.setText(table_reserva.getValueAt(fila,3).toString());
        lbl_descantidadconformada.setText(table_reserva.getValueAt(fila,4).toString()); 
        lbl_desunidad.setText(table_reserva.getValueAt(fila,5).toString()); 
        lbl_desnombresolicitante.setText(table_reserva.getValueAt(fila,8).toString());
        lbl_desfechasalida.setText(funciones.getfechacalendario());
        lbl_desproyecto.setText(table_reserva.getValueAt(fila,11).toString());
        spin_cantidadegresada.setValue(table_reserva.getValueAt(fila, 4));
        
        ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(table_reserva.getValueAt(fila,2).toString()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                      0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                    Integer.parseInt(table_reserva.getValueAt(fila,12).toString()), //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true       
                ); 
             
                cmb_almacen =  entrada.cargarmaterial_almacen(cmb_almacen,"Seleccione...",1);
                bot_agregarposicion.setEnabled(true);
       reserva = new ctrl_reserva(
                
                0,
                0,
                0,
                "",
                0,
                Integer.parseInt(table_reserva.getValueAt(fila,2).toString()), //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,    
                0,
                0,
                0,
                0,
                "", //fecha reserva
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  
        
        
        try{
            img = funciones.decodeToImage(reserva.consultar_foto());
            ImageIcon icon = new ImageIcon(img);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_DEFAULT));
            
            lbl_foto.setIcon(icono);
        }catch(NullPointerException ex){} 
    }//GEN-LAST:event_table_reservaMousePressed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_salida frm = new frm_salida();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_verdisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdisponibilidadActionPerformed
        frm_detalledisponibilidadmaterial frm = new frm_detalledisponibilidadmaterial(1);
        frm.setVisible(true);
        
    }//GEN-LAST:event_bot_verdisponibilidadActionPerformed

    private void txt_numeroreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numeroreservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numeroreservaActionPerformed

    private void cmb_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_almacenActionPerformed
       Integer fila;
       
         fila = table_reserva.getSelectedRow();
        try{  
        
        if (evt.getModifiers() != 0){
           
           if (!cmb_almacen.getSelectedItem().equals("Seleccione...")){
            ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(lbl_desnromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    Integer.parseInt(cmb_almacen.getSelectedItem().toString().substring(0,3).trim()), //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                     0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                      Integer.parseInt(table_reserva.getValueAt(fila,12).toString()), //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", // codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true //status       
            ); 
             
          
            cmb_ubicacion =  entrada.cargarmaterial_almacen(cmb_ubicacion,"Seleccione...",2);
            
           } 
          
       }
      }catch(NullPointerException ex){} 
    }//GEN-LAST:event_cmb_almacenActionPerformed

    private void table_posicionsalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_posicionsalidaMousePressed
         bot_borrarposicion.setEnabled(true);
           }//GEN-LAST:event_table_posicionsalidaMousePressed

    private void cmb_ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ubicacionActionPerformed
        
        Integer fila;
        
        fila = table_reserva.getSelectedRow();

        
        try{  
        
        if (evt.getModifiers() != 0){
           
           if (!cmb_ubicacion.getSelectedItem().equals("Seleccione...")){

               ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(lbl_desnromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    Integer.parseInt(cmb_almacen.getSelectedItem().toString().substring(0,3).trim()), //id_almacen,
                    "", //descripcion_almacen,
                    Integer.parseInt(cmb_ubicacion.getSelectedItem().toString().substring(0,3).trim()),
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                     0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                      Integer.parseInt(table_reserva.getValueAt(fila,12).toString()), //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", // codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true //status       
                ); 
               
                txt_stockdisponible.setText(entrada.consultarmaterial_cantidadubicacion().toString());
           }
        }
      }catch(NullPointerException ex){} 
    }//GEN-LAST:event_cmb_ubicacionActionPerformed

    private void txt_justificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_justificacionKeyReleased
        if(txt_justificacion.getText().trim().length() > 60){
               txt_justificacion.setText(txt_justificacion.getText().trim().substring(0, 60));
         }
    }//GEN-LAST:event_txt_justificacionKeyReleased

    public static void contabilizar_salida(){
                ctrl_salida salida = null;


                String fecha_salida;
                class_salida modelo_salida = null;
                Integer fila;

                fila = table_reserva.getSelectedRow();

                fecha_salida = funciones.fecha_bd_usuario(lbl_desfechasalida.getText(),2);

             try{   
                if (Integer.parseInt(spin_cantidadegresada.getValue().toString()) <= Integer.parseInt(table_reserva.getValueAt(fila, 4).toString())){
                     if(Integer.parseInt(spin_cantidadegresada.getValue().toString()) <= Integer.parseInt(txt_stockdisponible.getText())){


                         if (!fecha_salida.equals("") &&  
                             !cmb_almacen.getSelectedItem().equals("Seleccione") &&
                             !cmb_ubicacion.getSelectedItem().equals("Seleccione") &&
                             !txt_destino.getText().trim().equals("") &&
                             !txt_justificacion.getText().trim().equals("") ){


                            salida  = new ctrl_salida(
                                     0, 
                                     Integer.parseInt(txt_posicion.getText().trim()), 
                                     Integer.parseInt(lbl_desnromaterial.getText()),
                                     "", //descripcion material
                                     Integer.parseInt(table_reserva.getValueAt(fila, 9).toString()),
                                     lbl_desnombresolicitante.getText().trim(),
                                     Integer.parseInt(cmb_almacen.getSelectedItem().toString().substring(0,3).trim()),
                                     cmb_almacen.getSelectedItem().toString().substring(5,cmb_almacen.getSelectedItem().toString().length()).trim(),
                                     Integer.parseInt(cmb_ubicacion.getSelectedItem().toString().substring(0,3).trim()),
                                     cmb_ubicacion.getSelectedItem().toString().substring(5,cmb_ubicacion.getSelectedItem().toString().length()).trim(),
                                     fecha_salida,
                                     Integer.parseInt(table_reserva.getValueAt(fila, 12).toString()),
                                     3,
                                     Integer.parseInt(txt_iddocumento.getText().trim()),    
                                     Integer.parseInt(spin_cantidadegresada.getValue().toString()),
                                     txt_destino.getText().trim(), 
                                     txt_justificacion.getText().trim(), 
                                     true
                                 ); 


                            try {
                                modelo_salida = salida.crear_posicion(table_posicionsalida);
                                bot_agregarposicion.setEnabled(false);
                                bot_verdocumento.setEnabled(true);

                                //ANULAR LA RESERVA-POSICION QUE SE ACABA DE DAR SALIDA
                                salida.Actualizar_estatus_reserva(Integer.parseInt(table_reserva.getValueAt(fila, 0).toString()),  Integer.parseInt(table_reserva.getValueAt(fila, 1).toString()));

                                //REINICIO PARCIAL DEL MODULO DE SALIDA
                                lbl_desnromaterial.setText("");
                                lbl_desdescripcion.setText("");        
                                lbl_descantidadconformada.setText("");
                                lbl_desunidad.setText("");
                                lbl_desnombresolicitante.setText("");
                                lbl_desfechasalida.setText("");
                                lbl_desproyecto.setText("");
                                cmb_almacen.removeAllItems();
                                cmb_ubicacion.removeAllItems();
                                txt_stockdisponible.setText("");
                                txt_destino.setText("");
                                txt_justificacion.setText("");
                                spin_cantidadegresada.setValue(1);
                                lbl_foto.setIcon(null);
                                 ctrl_reserva reserva=null;

                                 reserva = new ctrl_reserva(

                                     0,
                                     Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                                     Integer.parseInt(frm_principalM1.lbl_area.getText()),
                                     "",
                                     0,
                                     0, //numero de material
                                     "",             // descripcion de material
                                     0,
                                     "",
                                     0,
                                     "",
                                     0,
                                     0,
                                     0,
                                     0,
                                     0,    
                                     "", //fecha reserva
                                     "",
                                     "",
                                     false,
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     ""    
                                 ); 

                                reserva.consultar_reserva_conformadas(table_reserva);

                            } catch (SQLException ex) {
                                Logger.getLogger(frm_solicitud.class.getName()).log(Level.SEVERE, null, ex);
                            }
                             txt_iddocumento.setText(modelo_salida.getId_documento().toString());
                             txt_posicion.setText(modelo_salida.getPosicion().toString());
                         }
                         else{
                                 JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS");
                 //                modelotabla.setRowCount(0);
                         }
                     }
                     else{
                         JOptionPane.showMessageDialog(null, "LA CANTIDAD A EGRESAR ES MAYOR A LA CANTIDAD DEL ALMACÉN-UBICACIÓN");
                     }
                }
                else{
                     JOptionPane.showMessageDialog(null, "LA CANTIDAD A EGRESAR ES MAYOR A LA CANTIDAD CONFORMADA");
                }
             }
             catch(NullPointerException ex){
                 JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS");
             }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bot_agregarposicion;
    protected static javax.swing.JButton bot_borrarposicion;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_verdisponibilidad;
    public static javax.swing.JButton bot_verdocumento;
    public static javax.swing.JComboBox<String> cmb_almacen;
    public static javax.swing.JComboBox<String> cmb_ubicacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_almacen;
    private javax.swing.JLabel lbl_cantidadegresada;
    private javax.swing.JLabel lbl_cantidadreservada;
    protected static javax.swing.JLabel lbl_descantidadconformada;
    protected static javax.swing.JLabel lbl_desdescripcion;
    protected static javax.swing.JLabel lbl_desfechasalida;
    protected static javax.swing.JLabel lbl_desnombresolicitante;
    protected static javax.swing.JLabel lbl_desnromaterial;
    protected static javax.swing.JLabel lbl_desproyecto;
    private javax.swing.JLabel lbl_destino;
    private javax.swing.JLabel lbl_desumb;
    protected static javax.swing.JLabel lbl_desunidad;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_fechasalida;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_justificacion;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nombresolicitante;
    private javax.swing.JLabel lbl_nroreserva;
    private javax.swing.JLabel lbl_numeromaterial;
    private javax.swing.JLabel lbl_numeromaterial1;
    private javax.swing.JLabel lbl_proyecto;
    private javax.swing.JLabel lbl_stockdisponible;
    private javax.swing.JLabel lbl_titulodetalleoc;
    private javax.swing.JLabel lbl_titulodetallereserva;
    private javax.swing.JLabel lbl_ubicacion;
    private javax.swing.JLabel lbl_umb;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    public static javax.swing.JSpinner spin_cantidadegresada;
    protected static javax.swing.JTable table_posicionsalida;
    protected static javax.swing.JTable table_reserva;
    public static javax.swing.JTextField txt_destino;
    protected static javax.swing.JTextField txt_iddocumento;
    public static javax.swing.JTextArea txt_justificacion;
    private javax.swing.JTextField txt_numeroreserva;
    protected static javax.swing.JTextField txt_posicion;
    public static javax.swing.JTextField txt_stockdisponible;
    // End of variables declaration//GEN-END:variables
}
