/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import controlador.SendMail;
import controlador.ctrl_comun;
import controlador.ctrl_material;
import controlador.ctrl_reserva;
import formatos_pdf.pdf_reserva;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.class_reserva;
import javax.swing.UIManager;
import model.class_material;


/**
 *
 * @author ruben
 */
public class frm_reserva extends javax.swing.JFrame {

    private Integer actualizar;
    private String message;
 
    public frm_reserva(Integer actualizar) {
        initComponents();
        this.actualizar = actualizar;
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - SOLICITUD DE MATERIALES");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
        this.message = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_material = new javax.swing.ButtonGroup();
        txt_reserva = new javax.swing.JTextField();
        txt_posicion = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        panel_material = new javax.swing.JPanel();
        lbl_fecharequerida = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        bot_buscar = new javax.swing.JButton();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_numeromaterial = new javax.swing.JTextField();
        lbl_numeromaterial = new javax.swing.JLabel();
        lbl_empresa = new javax.swing.JLabel();
        cmb_empresa = new javax.swing.JComboBox();
        lbl_proyecto = new javax.swing.JLabel();
        lbl_cantidadsolicitada = new javax.swing.JLabel();
        spin_cantidad = new javax.swing.JSpinner();
        lbl_justificacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_justificacion = new javax.swing.JTextArea();
        date_requerida = new com.toedter.calendar.JDateChooser();
        lbl_umb = new javax.swing.JLabel();
        txt_idproyecto = new javax.swing.JTextField();
        bot_buscarsalida = new javax.swing.JButton();
        txt_descripcionproyecto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_posicion = new javax.swing.JTable();
        bot_borrarposicion = new javax.swing.JButton();
        bot_verdocumento = new javax.swing.JButton();
        bot_agregarposicion = new javax.swing.JButton();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        txt_reserva.setText("0");

        txt_posicion.setText("0");

        txt_id.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_material.setBackground(new java.awt.Color(255, 255, 255));
        panel_material.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_material.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_fecharequerida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fecharequerida.setText("FECHA REQUERIDA");
        panel_material.add(lbl_fecharequerida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descripcionmaterial.setEnabled(false);
        panel_material.add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 520, 30));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        panel_material.add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 120, 30));
        complemento.DisableBorderButton(bot_buscar);

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN MATERIAL");
        panel_material.add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numeromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeromaterialKeyReleased(evt);
            }
        });
        panel_material.add(txt_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 30));

        lbl_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_numeromaterial.setText("NÚMERO DE MATERIAL");
        panel_material.add(lbl_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_empresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empresa.setText("EMPRESA");
        panel_material.add(lbl_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cmb_empresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel_material.add(cmb_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 30));

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        panel_material.add(lbl_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lbl_cantidadsolicitada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadsolicitada.setText("CANTIDAD A RESERVAR");
        panel_material.add(lbl_cantidadsolicitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 20));

        spin_cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spin_cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        panel_material.add(spin_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 60, 30));

        lbl_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_justificacion.setText("JUSTIFICACIÓN");
        panel_material.add(lbl_justificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        area_justificacion.setColumns(20);
        area_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_justificacion.setLineWrap(true);
        area_justificacion.setRows(5);
        area_justificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                area_justificacionKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(area_justificacion);

        panel_material.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 320, 110));
        panel_material.add(date_requerida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, 30));

        lbl_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(lbl_umb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 70, 20));

        txt_idproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_idproyecto.setEnabled(false);
        panel_material.add(txt_idproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, -1));

        bot_buscarsalida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_buscarsalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscarsalida.setText("Buscar");
        bot_buscarsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarsalidaActionPerformed(evt);
            }
        });
        panel_material.add(bot_buscarsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        txt_descripcionproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcionproyecto.setEnabled(false);
        panel_material.add(txt_descripcionproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 370, -1));

        getContentPane().add(panel_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1080, 370));

        table_posicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_posicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "POSICIÓN", "NRO MATERIAL", "MATERIAL SOLICITADO", "CANTIDAD", "UMB", "GRUPO DE ARTÍCULO", "FECHA REQUERIDA", "JUSTIFICACIÓN", "OBSERVACIÓN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_posicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_posicionMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_posicion);
        if (table_posicion.getColumnModel().getColumnCount() > 0) {
            table_posicion.getColumnModel().getColumn(0).setMinWidth(80);
            table_posicion.getColumnModel().getColumn(0).setPreferredWidth(80);
            table_posicion.getColumnModel().getColumn(0).setMaxWidth(80);
            table_posicion.getColumnModel().getColumn(1).setMinWidth(120);
            table_posicion.getColumnModel().getColumn(1).setPreferredWidth(120);
            table_posicion.getColumnModel().getColumn(1).setMaxWidth(120);
            table_posicion.getColumnModel().getColumn(2).setMinWidth(350);
            table_posicion.getColumnModel().getColumn(2).setPreferredWidth(350);
            table_posicion.getColumnModel().getColumn(2).setMaxWidth(350);
            table_posicion.getColumnModel().getColumn(3).setMinWidth(80);
            table_posicion.getColumnModel().getColumn(3).setPreferredWidth(80);
            table_posicion.getColumnModel().getColumn(3).setMaxWidth(80);
            table_posicion.getColumnModel().getColumn(4).setMinWidth(50);
            table_posicion.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_posicion.getColumnModel().getColumn(4).setMaxWidth(50);
            table_posicion.getColumnModel().getColumn(8).setMinWidth(1);
            table_posicion.getColumnModel().getColumn(8).setPreferredWidth(1);
            table_posicion.getColumnModel().getColumn(8).setMaxWidth(1);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1320, 170));

        bot_borrarposicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_borrarposicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        bot_borrarposicion.setText("BORRAR POSICIÓN");
        bot_borrarposicion.setEnabled(false);
        bot_borrarposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_borrarposicionActionPerformed(evt);
            }
        });
        getContentPane().add(bot_borrarposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, -1, -1));
        complemento.DisableBorderButton(bot_borrarposicion);

        bot_verdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_verdocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        bot_verdocumento.setText("VER DOCUMENTO");
        bot_verdocumento.setEnabled(false);
        bot_verdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_verdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, -1, -1));
        complemento.DisableBorderButton(bot_verdocumento);

        bot_agregarposicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_agregarposicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        bot_agregarposicion.setText("AGREGAR POSICIÓN");
        bot_agregarposicion.setEnabled(false);
        bot_agregarposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregarposicionActionPerformed(evt);
            }
        });
        getContentPane().add(bot_agregarposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, -1));
        complemento.DisableBorderButton(bot_agregarposicion);

        panel_foto.setBackground(new java.awt.Color(255, 255, 255));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fotoLayout.createSequentialGroup()
                .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 210, 180));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("RESERVA DE MATERIALES");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(280, 10, 230, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1130, 20, 113, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_comun control = new ctrl_comun(4);
        cmb_empresa =  control.cargar_combo(cmb_empresa,"Seleccione...");
        
       
    }//GEN-LAST:event_formWindowOpened

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
        frm_buscarmaterial frm = new frm_buscarmaterial(2);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void bot_borrarposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_borrarposicionActionPerformed
        class_reserva modelo_reserva = null;
        ctrl_reserva reserva = null;
        Integer i;
        
                reserva = new ctrl_reserva(
                
                Integer.parseInt(txt_reserva.getText().trim()),
                0,
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,    
                0,
                0,
                0,
                0,        
                "", //fecha reserva
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );  
        
        
        
        modelo_reserva = reserva.borrar_posicion(table_posicion,table_posicion.getSelectedRow());
        
        if (table_posicion.getRowCount() == 0){
            bot_verdocumento.setEnabled(false);
            
        }
        bot_borrarposicion.setEnabled(false);
        
        this.message = "Saludos \n\n" + "A través de este comunicado se informa que creó RESERVA para la evaluación de lo(s) siguiente(s) de material(es):\n";         
        for(i=0 ; i<table_posicion.getRowCount();i++){
            this.message =  this.message +  "\n" + table_posicion.getValueAt(i, 0).toString() + ") " + table_posicion.getValueAt(i, 1).toString() + " - " + table_posicion.getValueAt(i, 2).toString() + " Reserva: " + table_posicion.getValueAt(i, 3).toString() + " " + table_posicion.getValueAt(i, 4).toString() + " Fecha Requerida: " + table_posicion.getValueAt(i, 6).toString() + " Justificación: " + table_posicion.getValueAt(i, 7).toString(); 
        }
        
        
    }//GEN-LAST:event_bot_borrarposicionActionPerformed

    private void bot_agregarposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregarposicionActionPerformed
       ctrl_reserva reserva = null;
       DefaultTableModel modelotabla = (DefaultTableModel) table_posicion.getModel();
       String fecha_requerida;
       String fecha_reserva;
       class_reserva modelo_reserva = null;
       Integer resp;
       Integer i;
       String subject;
       String to="";
       
       
       
       fecha_requerida = funciones.fecha_convertir_date(date_requerida, 1);
       fecha_reserva = funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2);
       
        if (!cmb_empresa.getSelectedItem().equals("Seleccione...") &&
            !txt_id.getText().trim().equals("0")  &&
            !txt_numeromaterial.getText().trim().equals("") && !txt_descripcionmaterial.getText().trim().equals("") &&
            !area_justificacion.getText().trim().equals("")
        ){
           
            
            
            
            reserva = new ctrl_reserva(
                
                Integer.parseInt(txt_reserva.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                Integer.parseInt(txt_numeromaterial.getText().trim()), //numero de material
                txt_descripcionmaterial.getText().trim(),             // descripcion de material     
                Integer.parseInt(cmb_empresa.getSelectedItem().toString().substring(0,3).trim()),
                cmb_empresa.getSelectedItem().toString(),
                Integer.parseInt(txt_id.getText().trim()),
                "",
                Integer.parseInt(txt_posicion.getText().trim()),
                Integer.parseInt(spin_cantidad.getValue().toString()),
                0,
                0,
                0,    
                fecha_reserva, //fecha reserva
                fecha_requerida,
                area_justificacion.getText().trim().toUpperCase(),
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  
           try {
               modelo_reserva = reserva.crear_posicion(table_posicion);
               this.message = "Saludos \n\n" + "A través de este comunicado se informa que creó RESERVA para la evaluación de lo(s) siguiente(s) de material(es):\n";
               for(i=0 ; i<table_posicion.getRowCount();i++){
                    this.message =  this.message +  "\n" + table_posicion.getValueAt(i, 0).toString() + ") " + table_posicion.getValueAt(i, 1).toString() + " - " + table_posicion.getValueAt(i, 2).toString() + " Reserva: " + table_posicion.getValueAt(i, 3).toString() + " " + table_posicion.getValueAt(i, 4).toString() + " Fecha Requerida: " + table_posicion.getValueAt(i, 6).toString() + " Justificación: " + table_posicion.getValueAt(i, 7).toString(); 
               }
               bot_agregarposicion.setEnabled(false);
               bot_verdocumento.setEnabled(true);
               txt_numeromaterial.setText("");
               txt_descripcionmaterial.setText("");
               spin_cantidad.setValue(1);
               date_requerida.setDate(null);
               area_justificacion.setText("");
               lbl_foto.setIcon(null);
               cmb_empresa.setSelectedItem("Seleccione...");
               txt_id.setText("0");
               txt_idproyecto.setText("");
               txt_descripcionproyecto.setText("");        
               
               resp = JOptionPane.showConfirmDialog(null, "DESEA AGREGAR OTRA POSICIÓN A LA RESERVA?");
               
               if(resp.equals(1)){
                    to = reserva.consultar_email_usuariosupervisor(Integer.parseInt(frm_principalM1.lbl_nivel.getText().trim()));    
                    subject = "CREACIÓN RESERVA # " + modelo_reserva.getId_reserva().toString() + " PENDIENTE PARA SU EVALUACIÓN";
                    
                    SendMail.send(to,subject,this.message);
                    
                    
               }
               
           } catch (SQLException ex) {
               Logger.getLogger(frm_reserva.class.getName()).log(Level.SEVERE, null, ex);
           }
            txt_reserva.setText(modelo_reserva.getId_reserva().toString());
            txt_posicion.setText(modelo_reserva.getPosicion().toString());
        }
        else{
                JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS");
                modelotabla.setRowCount(0);
        }
    }//GEN-LAST:event_bot_agregarposicionActionPerformed

    private void bot_verdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdocumentoActionPerformed
        try {
            pdf_reserva.dato("\\\\192.168.0.3\\dist\\Documentos_SisTimaca",Integer.parseInt(txt_reserva.getText()),"");
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(frm_entradaexpress.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_entradaexpress.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bot_verdocumentoActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_reserva frm = new frm_reserva(0);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            
            if(this.actualizar.equals(1)){
                 frm_actualizarreserva.bot_reiniciar.doClick();
             }
            
            this.dispose();
        }      

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void table_posicionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_posicionMousePressed
            bot_borrarposicion.setEnabled(true);
    }//GEN-LAST:event_table_posicionMousePressed

    private void txt_numeromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeromaterialKeyReleased
       if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            
          if (txt_numeromaterial.getText().trim().length() > 7){ 
            ctrl_material material = null;
            class_material modelo_material = null;
        
            material = new ctrl_material(0,Integer.parseInt(txt_numeromaterial.getText().trim()),"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);
        
            modelo_material = material.consultar_descripcionmaterial();
        
            txt_descripcionmaterial.setText(modelo_material.getDescripcion());
            lbl_umb.setText(modelo_material.getDescripcion_medida());
            if (!txt_descripcionmaterial.getText().trim().equals("")){
                bot_agregarposicion.setEnabled(true);
            }
            else{
                bot_agregarposicion.setEnabled(false);
            }
          }  
            
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numeromaterial.setText("");
                txt_descripcionmaterial.setText("");
             }   
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txt_numeromaterialKeyReleased

    private void area_justificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_area_justificacionKeyReleased
        if(area_justificacion.getText().trim().length() > 60){
               area_justificacion.setText(area_justificacion.getText().trim().substring(0, 60));
         }
    }//GEN-LAST:event_area_justificacionKeyReleased

    private void bot_buscarsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarsalidaActionPerformed
        frm_buscarproyecto frm = new frm_buscarproyecto(3);
        frm.setVisible(true);
    }//GEN-LAST:event_bot_buscarsalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_reserva(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_justificacion;
    protected static javax.swing.JButton bot_agregarposicion;
    protected static javax.swing.JButton bot_borrarposicion;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_buscarsalida;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_verdocumento;
    private javax.swing.JComboBox cmb_empresa;
    private com.toedter.calendar.JDateChooser date_requerida;
    private javax.swing.ButtonGroup group_material;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_cantidadsolicitada;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_fecharequerida;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_justificacion;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_numeromaterial;
    private javax.swing.JLabel lbl_proyecto;
    protected static javax.swing.JLabel lbl_umb;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JPanel panel_material;
    private javax.swing.JSpinner spin_cantidad;
    protected static javax.swing.JTable table_posicion;
    protected static javax.swing.JTextField txt_descripcionmaterial;
    protected static javax.swing.JTextField txt_descripcionproyecto;
    protected static javax.swing.JTextField txt_id;
    protected static javax.swing.JTextField txt_idproyecto;
    protected static javax.swing.JTextField txt_numeromaterial;
    protected static javax.swing.JTextField txt_posicion;
    protected static javax.swing.JTextField txt_reserva;
    // End of variables declaration//GEN-END:variables
}
