/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.ctrl_entrada;
import controlador.ctrl_material;
import controlador.ctrl_prestamo;
import controlador.ctrl_solicitud;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.class_material;
import static view.frm_prestamo.lbl_desumb;
import static view.frm_reporteentradamaterial.cmb_almacen;
import static view.frm_reporteentradamaterial.cmb_proyecto;

/**
 *
 * @author ruben
 */
public class frm_seguimientoprestamo extends javax.swing.JFrame {

   private File fichero;
   
    public frm_seguimientoprestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - SEGUIMIENTO DE PRESTAMO DE MATERIAL");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_devolucion = new javax.swing.ButtonGroup();
        group_dano = new javax.swing.ButtonGroup();
        txt_rutadano = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prestamo = new javax.swing.JTable();
        lbl_nromaterial = new javax.swing.JLabel();
        txt_numeromaterial = new javax.swing.JTextField();
        bot_buscar = new javax.swing.JButton();
        lbl_diasmora = new javax.swing.JLabel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        lbl_numeromaterial = new javax.swing.JLabel();
        lbl_diasentregamaterial = new javax.swing.JLabel();
        lbl_desdiasmora = new javax.swing.JLabel();
        lbl_desdiaentrega = new javax.swing.JLabel();
        lbl_desdescripcionmaterial = new javax.swing.JLabel();
        lbl_desnromaterial = new javax.swing.JLabel();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        lbl_registrardano = new javax.swing.JLabel();
        radio_no = new javax.swing.JRadioButton();
        radio_si = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        radio_sidano = new javax.swing.JRadioButton();
        radio_nodano = new javax.swing.JRadioButton();
        panel_evidencia = new javax.swing.JPanel();
        lbl_fotodano = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_dano = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        bot_cargarfoto = new javax.swing.JButton();
        bot_contabilizardevolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("SEGUIMIENTO PRÉSTAMO");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(270, 10, 190, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 280, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1140, 20, 113, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1280, 20, 91, 25);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 60));

        tabla_prestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_prestamo", "id_entrada", "NRO DOCUMENTO", "NRO MATERIAL", "DESCRIPCIÓN", "POSICIÓN", "CANTIDAD PRESTADA", "UMB", "PROYECTO", "ÁREA", "NOMBRE SOLICITANTE", "FECHA DESDE", "FECHA HASTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_prestamoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_prestamo);
        if (tabla_prestamo.getColumnModel().getColumnCount() > 0) {
            tabla_prestamo.getColumnModel().getColumn(0).setMinWidth(0);
            tabla_prestamo.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabla_prestamo.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla_prestamo.getColumnModel().getColumn(1).setMinWidth(0);
            tabla_prestamo.getColumnModel().getColumn(1).setPreferredWidth(0);
            tabla_prestamo.getColumnModel().getColumn(1).setMaxWidth(0);
            tabla_prestamo.getColumnModel().getColumn(4).setMinWidth(300);
            tabla_prestamo.getColumnModel().getColumn(4).setPreferredWidth(300);
            tabla_prestamo.getColumnModel().getColumn(4).setMaxWidth(300);
            tabla_prestamo.getColumnModel().getColumn(7).setMinWidth(50);
            tabla_prestamo.getColumnModel().getColumn(7).setPreferredWidth(50);
            tabla_prestamo.getColumnModel().getColumn(7).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1390, 180));

        lbl_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nromaterial.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_numeromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));
        complemento.DisableBorderButton(bot_buscar);

        lbl_diasmora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasmora.setText("DIAS DE MORA ENTREGA");
        getContentPane().add(lbl_diasmora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN DE MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        lbl_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_numeromaterial.setText("NÚMERO DE MATERIAL");
        getContentPane().add(lbl_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lbl_diasentregamaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_diasentregamaterial.setText("DIA DE ENTREGA DEL MATERIAL");
        getContentPane().add(lbl_diasentregamaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        lbl_desdiasmora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_desdiasmora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 130, 20));

        lbl_desdiaentrega.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_desdiaentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 130, 20));

        lbl_desdescripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_desdescripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 310, 20));

        lbl_desnromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_desnromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, 20));

        panel_foto.setBackground(new java.awt.Color(253, 253, 253));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );

        getContentPane().add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 210, 200));

        lbl_registrardano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_registrardano.setText("REGISTRAR DAÑO ");
        getContentPane().add(lbl_registrardano, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        group_devolucion.add(radio_no);
        radio_no.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_no.setSelected(true);
        radio_no.setText("NO");
        radio_no.setEnabled(false);
        radio_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_noActionPerformed(evt);
            }
        });
        getContentPane().add(radio_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        group_devolucion.add(radio_si);
        radio_si.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_si.setText("SÍ");
        radio_si.setEnabled(false);
        radio_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_siActionPerformed(evt);
            }
        });
        getContentPane().add(radio_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("REGISTRAR DEVOLUCIÓN ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        group_dano.add(radio_sidano);
        radio_sidano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_sidano.setText("SÍ");
        radio_sidano.setEnabled(false);
        radio_sidano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_sidanoActionPerformed(evt);
            }
        });
        getContentPane().add(radio_sidano, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        group_dano.add(radio_nodano);
        radio_nodano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_nodano.setSelected(true);
        radio_nodano.setText("NO");
        radio_nodano.setEnabled(false);
        radio_nodano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_nodanoActionPerformed(evt);
            }
        });
        getContentPane().add(radio_nodano, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        panel_evidencia.setBackground(new java.awt.Color(253, 253, 253));
        panel_evidencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO EVIDENCIA DAÑO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_evidencia.setForeground(new java.awt.Color(0, 0, 255));

        lbl_fotodano.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_evidenciaLayout = new javax.swing.GroupLayout(panel_evidencia);
        panel_evidencia.setLayout(panel_evidenciaLayout);
        panel_evidenciaLayout.setHorizontalGroup(
            panel_evidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_fotodano, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        panel_evidenciaLayout.setVerticalGroup(
            panel_evidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_fotodano, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        getContentPane().add(panel_evidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 250, 190));

        area_dano.setColumns(20);
        area_dano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_dano.setLineWrap(true);
        area_dano.setRows(5);
        area_dano.setEnabled(false);
        jScrollPane2.setViewportView(area_dano);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 380, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("DESCRIPCIÓN DAÑO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        bot_cargarfoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_cargarfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_cargarfoto.setText("CARGAR FOTO");
        bot_cargarfoto.setEnabled(false);
        bot_cargarfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cargarfotoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cargarfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 330, 160, 40));
        complemento.DisableBorderButton(bot_cargarfoto);

        bot_contabilizardevolucion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_contabilizardevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilizar.png"))); // NOI18N
        bot_contabilizardevolucion.setText("CONTABILIZAR MATERIAL");
        bot_contabilizardevolucion.setEnabled(false);
        bot_contabilizardevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_contabilizardevolucionActionPerformed(evt);
            }
        });
        getContentPane().add(bot_contabilizardevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_seguimientoprestamo frm = new frm_seguimientoprestamo();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void txt_numeromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeromaterialKeyReleased
        class_material modelo_material;
        BufferedImage img;

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){

            ctrl_material material = new ctrl_material(
                0,
                Integer.parseInt(txt_numeromaterial.getText().trim().toUpperCase()),
                "",
                "",
                "",
                "",
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,
                0,
                0.0,
                0.0,
                "",
                0,
                "",
                0,
                0,
                "",
                "",
                0,
                "",
                0,
                "",
                0,
                "",
                "",
                0,
                "",
                0,
                "",
                0,
                "",
                true
            );

            modelo_material = material.consultar_material();

            if (modelo_material.isStatus()){

                lbl_desdescripcionmaterial.setText(modelo_material.getDescripcion());
                lbl_desumb.setText(modelo_material.getDescripcion_medida());

                img = funciones.decodeToImage(modelo_material.getFoto_material());

                try{
                    lbl_foto.setIcon(null);
                    ImageIcon icon = new ImageIcon(img);
                    Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                    
                    lbl_foto.setIcon(icono);
                }
                catch(NullPointerException ex){}

                ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0,
                    Integer.parseInt(txt_numeromaterial.getText().trim()), //id_material,
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,
                    0, //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                    0, //id_procedencia
                    "", //descripcion_procedencia
                    0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                    Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim()), //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", //codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true
                );
                cmb_almacen.setEnabled(true);
                cmb_almacen =  entrada.cargarmaterial_almacen(cmb_almacen,"Seleccione...",6);

            }

        }
        else{
            if (evt.getKeyCode() == 27){

                bot_reiniciar.doClick();

            }
            else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numeromaterial.setText("");
                lbl_desdescripcionmaterial.setText("");
            }
        }
    }//GEN-LAST:event_txt_numeromaterialKeyReleased

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
        frm_buscarmaterial frm = new frm_buscarmaterial(10);
        frm.setVisible(true);

    }//GEN-LAST:event_bot_buscarActionPerformed

    private void bot_cargarfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cargarfotoActionPerformed
       
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.jpg", "jpg");
        file.setFileFilter(filtro);

        int seleccion = file.showOpenDialog(this);
        //Si el usuario, pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            //Seleccionamos el fichero
            fichero = file.getSelectedFile();
            //Ecribe la ruta del fichero seleccionado en el campo de texto
            txt_rutadano.setText(fichero.getAbsolutePath());
            ImageIcon icon = new ImageIcon(fichero.toString());
            //System.out.println(fichero.getName());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_fotodano.getWidth(),lbl_fotodano.getHeight(), Image.SCALE_DEFAULT));
            lbl_fotodano.setText(null);
            lbl_fotodano.setIcon(icono);
        }
    }//GEN-LAST:event_bot_cargarfotoActionPerformed

    private void radio_sidanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_sidanoActionPerformed
        
            area_dano.setEnabled(true);
            area_dano.setText("");
            lbl_fotodano.setText(null);
            bot_cargarfoto.setEnabled(true);
       
    }//GEN-LAST:event_radio_sidanoActionPerformed

    private void radio_nodanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_nodanoActionPerformed

            area_dano.setText("");
            area_dano.setEnabled(false);
            lbl_fotodano.setText(null);
            bot_cargarfoto.setEnabled(false);        
            bot_contabilizardevolucion.setEnabled(false);
    }//GEN-LAST:event_radio_nodanoActionPerformed

    private void radio_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_siActionPerformed
        bot_contabilizardevolucion.setEnabled(true);
        area_dano.setText("");
        area_dano.setEnabled(true);
        lbl_fotodano.setText(null);
        bot_cargarfoto.setEnabled(true); 
    }//GEN-LAST:event_radio_siActionPerformed

    private void radio_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_noActionPerformed
         bot_contabilizardevolucion.setEnabled(false);
    }//GEN-LAST:event_radio_noActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    0, //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

        prestamo.consultar_prestamos(tabla_prestamo,"","",1);
    }//GEN-LAST:event_formWindowOpened

    private void tabla_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_prestamoMouseClicked
       Integer fila;
        BufferedImage img;
       
       fila = tabla_prestamo.getSelectedRow();
               
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaInicial;
        Date fechaFinal;
        Integer dias=0;
       try {
           fechaInicial = dateFormat.parse(funciones.fecha_bd_usuario(tabla_prestamo.getValueAt(fila, 12).toString(),2));
           fechaFinal=dateFormat.parse(funciones.fecha_bd_usuario(funciones.getfechacalendario(),2));
           dias=(int) ((fechaFinal.getTime()-fechaInicial.getTime())/86400000);
       } catch (ParseException ex) {
           
       }
        
       lbl_desnromaterial.setText(tabla_prestamo.getValueAt(fila, 3).toString());
       lbl_desdescripcionmaterial.setText(tabla_prestamo.getValueAt(fila, 4).toString());
       lbl_desdiaentrega.setText(tabla_prestamo.getValueAt(fila, 12).toString());
       lbl_desdiasmora.setText(dias.toString());
       radio_si.setEnabled(true);
       radio_no.setEnabled(true);
 
        ctrl_solicitud solicitud = new ctrl_solicitud(

              0,
              0,
              0,
              "",
              0,
              "",
              0,
              Integer.parseInt(tabla_prestamo.getValueAt(fila, 3).toString()), //numero de material
              "",             // descripcion de material     
              0,
              "",
              0,
              "",
              0,    
              0,
              0,
              0,
              0,     
              "", //fecha solicitud
              "",
              "",
              false,
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              ""     
      );  

         try{  
           img = funciones.decodeToImage(solicitud.consultar_foto());
           lbl_foto.setIcon(null);
           ImageIcon icon = new ImageIcon(img);
           Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_DEFAULT));

           lbl_foto.setIcon(icono);

         }  
         catch(NullPointerException ex){  }
       
       
    }//GEN-LAST:event_tabla_prestamoMouseClicked

    private void bot_contabilizardevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_contabilizardevolucionActionPerformed
        Integer fila;
        String image_string = "";
        Integer i;
        String id_prestamo = "";
        String id_entrada = "";
        Boolean primero = true;
        Boolean valido = false;
        
        fila = tabla_prestamo.getSelectedRow();
        
        for(i=0; i<tabla_prestamo.getRowCount()-1;i++){
            if(tabla_prestamo.getValueAt(fila,2).toString().equals(tabla_prestamo.getValueAt(i,2).toString()) && tabla_prestamo.getValueAt(fila,3).toString().equals(tabla_prestamo.getValueAt(i,3).toString())){
                if (primero){
                    id_prestamo = tabla_prestamo.getValueAt(i,0).toString();
                    id_entrada = tabla_prestamo.getValueAt(i,1).toString();
                    primero = false;
                }
                else{
                    id_prestamo += "," + tabla_prestamo.getValueAt(i,0).toString();
                    id_entrada += "," + tabla_prestamo.getValueAt(i,1).toString();
                }
            }
        }
        
        if (radio_sidano.isSelected()){
            if (!txt_rutadano.getText().equals("") && !area_dano.getText().equals("")) {
                try {
                // TODO add your handling code here:
                   BufferedImage img = ImageIO.read(new File(fichero.toString()));
                   image_string = funciones.encodeToString(img);
               
                //guardar_imagen(image_string, fichero.getName());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null,"ERROR EN FOTO");
                }
            }
            else{
               valido = false;
            }
        }    
        else{
            valido = true;
        }
        
        
        if(valido){
        
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    Integer.parseInt(tabla_prestamo.getValueAt(fila,0).toString()), //id_prestamo 
                    0, //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    0, // posicion,
                    0, // cantidad_prestada,
                    0, //nrodocumento
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    radio_sidano.isSelected(), //dano, 
                    image_string, //foto, 
                    area_dano.getText().trim(), //descripciondano
                    Integer.parseInt(tabla_prestamo.getValueAt(fila,1).toString()), //id_entrada
                    true
            );
        
            if(prestamo.actualizarestatusprestamo(id_prestamo,id_entrada)){
                JOptionPane.showMessageDialog(null,"ESTATUS PRÉSTAMO ACTUALIZADO SATISFACTORIAMENTE");
            }
        }    
        else{
            JOptionPane.showMessageDialog(null,"FALTAN DESCRIPCIÓN O LA FOTO DEL DAÑO POR INGRESAR");
        }    
    }//GEN-LAST:event_bot_contabilizardevolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_seguimientoprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_seguimientoprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_seguimientoprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_seguimientoprestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_seguimientoprestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_dano;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cargarfoto;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_contabilizardevolucion;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.ButtonGroup group_dano;
    private javax.swing.ButtonGroup group_devolucion;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_desdescripcionmaterial;
    private javax.swing.JLabel lbl_desdiaentrega;
    private javax.swing.JLabel lbl_desdiasmora;
    private javax.swing.JLabel lbl_desnromaterial;
    private javax.swing.JLabel lbl_diasentregamaterial;
    private javax.swing.JLabel lbl_diasmora;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    protected static javax.swing.JLabel lbl_foto;
    protected static javax.swing.JLabel lbl_fotodano;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nromaterial;
    private javax.swing.JLabel lbl_numeromaterial;
    private javax.swing.JLabel lbl_registrardano;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_evidencia;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JRadioButton radio_no;
    private javax.swing.JRadioButton radio_nodano;
    private javax.swing.JRadioButton radio_si;
    private javax.swing.JRadioButton radio_sidano;
    private javax.swing.JTable tabla_prestamo;
    protected static javax.swing.JTextField txt_numeromaterial;
    private javax.swing.JTextField txt_rutadano;
    // End of variables declaration//GEN-END:variables
}
