/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import RenderTable.RenderTablaMaestroMaterial;
import controlador.ctrl_material;
import formatos_excel.reporte_almacen;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import jxl.write.WriteException;
import model.class_material;


/**
 *
 * @author ruben
 */
public class frm_maestromaterial extends javax.swing.JFrame {

    /**
     * Creates new form frm_maestromaterial
     */
    public frm_maestromaterial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTIMACA - RESUMEN STOCK");
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setExtendedState(MAXIMIZED_BOTH);

        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
        
       // Instanciamos nuestro modelo de datos, por ejemplo, DefaultTableModel
       // y lo metemos en el JTable
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallematerial.getModel();
       
        // Instanciamos el TableRowSorter y lo añadimos al JTable
        TableRowSorter elQueOrdena = new TableRowSorter(modelotabla);
        table_detallematerial.setRowSorter(elQueOrdena);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_codigomaestromaterial = new javax.swing.JTextField();
        lbl_cantidadentrante = new javax.swing.JLabel();
        bot_cantidadreservada = new javax.swing.JButton();
        lbl_cantidadstockencurso = new javax.swing.JLabel();
        bot_stockencurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detallematerial = new javax.swing.JTable();
        lbl_nromaterial = new javax.swing.JLabel();
        txt_nromaterial = new javax.swing.JTextField();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        txt_descripcionmaterial = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_stockcurso = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_reserva = new javax.swing.JTable();
        bot_entrada = new javax.swing.JButton();
        lbl_entradamaterial = new javax.swing.JLabel();
        bot_salida = new javax.swing.JButton();
        bot_excel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cantidadentrante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadentrante.setText("CANTIDAD RESERVADA");
        getContentPane().add(lbl_cantidadentrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        bot_cantidadreservada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cantidadreservada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_cantidadreservada.setText("Ver Detalle");
        bot_cantidadreservada.setEnabled(false);
        bot_cantidadreservada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cantidadreservadaActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cantidadreservada, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, -1, -1));

        lbl_cantidadstockencurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidadstockencurso.setText("STOCK EN CURSO");
        getContentPane().add(lbl_cantidadstockencurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, -1, -1));

        bot_stockencurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_stockencurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_stockencurso.setText("Ver Detalle");
        bot_stockencurso.setEnabled(false);
        bot_stockencurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_stockencursoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_stockencurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, -1, -1));

        table_detallematerial.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_detallematerial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "NRO MATERIAL", "DESCRIPCIÓN", "MARCA", "MODELO", "UMB", "CLASE DE MATERIAL", "GRUPO DE MATERIAL", "STOCK DISPONIBLE", "STOCK MÍNIMO", "STOCK MÁXIMO", "STOCK PEDIDO", "CANTIDAD ENTRANTE", "CANTIDAD SALIENTE", "uso", "observacion", "id_grupomaterial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detallematerial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_detallematerialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_detallematerial);
        if (table_detallematerial.getColumnModel().getColumnCount() > 0) {
            table_detallematerial.getColumnModel().getColumn(0).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(0).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(1).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(1).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(1).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(3).setMinWidth(70);
            table_detallematerial.getColumnModel().getColumn(3).setPreferredWidth(70);
            table_detallematerial.getColumnModel().getColumn(3).setMaxWidth(70);
            table_detallematerial.getColumnModel().getColumn(4).setMinWidth(70);
            table_detallematerial.getColumnModel().getColumn(4).setPreferredWidth(70);
            table_detallematerial.getColumnModel().getColumn(4).setMaxWidth(70);
            table_detallematerial.getColumnModel().getColumn(5).setMinWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_detallematerial.getColumnModel().getColumn(5).setMaxWidth(50);
            table_detallematerial.getColumnModel().getColumn(7).setMinWidth(120);
            table_detallematerial.getColumnModel().getColumn(7).setPreferredWidth(120);
            table_detallematerial.getColumnModel().getColumn(7).setMaxWidth(120);
            table_detallematerial.getColumnModel().getColumn(9).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(9).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(9).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(10).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setMinWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setPreferredWidth(90);
            table_detallematerial.getColumnModel().getColumn(11).setMaxWidth(90);
            table_detallematerial.getColumnModel().getColumn(14).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(14).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(14).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(15).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(15).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(15).setMaxWidth(0);
            table_detallematerial.getColumnModel().getColumn(16).setMinWidth(0);
            table_detallematerial.getColumnModel().getColumn(16).setPreferredWidth(0);
            table_detallematerial.getColumnModel().getColumn(16).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1360, 380));

        lbl_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nromaterial.setText("NÚMERO DE MATERIAL");
        getContentPane().add(lbl_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 100, -1));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN MATERIAL");
        getContentPane().add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txt_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descripcionmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionmaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 300, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("RESUMEN STOCK");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(250, 10, 140, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 220, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1130, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1260, 20, 100, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(850, 10, 250, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(852, 30, 250, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        table_stockcurso.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_stockcurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_material", "NRO DE MATERIAL", "DESCRIPCIÓN", "CANTIDAD", "UMB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_stockcurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stockcursoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_stockcurso);
        if (table_stockcurso.getColumnModel().getColumnCount() > 0) {
            table_stockcurso.getColumnModel().getColumn(0).setMinWidth(0);
            table_stockcurso.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_stockcurso.getColumnModel().getColumn(0).setMaxWidth(0);
            table_stockcurso.getColumnModel().getColumn(1).setMinWidth(120);
            table_stockcurso.getColumnModel().getColumn(1).setPreferredWidth(120);
            table_stockcurso.getColumnModel().getColumn(1).setMaxWidth(120);
            table_stockcurso.getColumnModel().getColumn(3).setMinWidth(80);
            table_stockcurso.getColumnModel().getColumn(3).setPreferredWidth(80);
            table_stockcurso.getColumnModel().getColumn(3).setMaxWidth(80);
            table_stockcurso.getColumnModel().getColumn(4).setMinWidth(50);
            table_stockcurso.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_stockcurso.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 690, 100));

        table_reserva.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_reserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_material", "NRO DE MATERIAL", "DESCRIPCIÓN", "CANTIDAD", "UMB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_reservaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_reserva);
        if (table_reserva.getColumnModel().getColumnCount() > 0) {
            table_reserva.getColumnModel().getColumn(0).setMinWidth(0);
            table_reserva.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_reserva.getColumnModel().getColumn(0).setMaxWidth(0);
            table_reserva.getColumnModel().getColumn(1).setMinWidth(110);
            table_reserva.getColumnModel().getColumn(1).setPreferredWidth(110);
            table_reserva.getColumnModel().getColumn(1).setMaxWidth(110);
            table_reserva.getColumnModel().getColumn(3).setMinWidth(100);
            table_reserva.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_reserva.getColumnModel().getColumn(3).setMaxWidth(100);
            table_reserva.getColumnModel().getColumn(4).setMinWidth(50);
            table_reserva.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_reserva.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 640, 100));

        bot_entrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar.png"))); // NOI18N
        bot_entrada.setText("Ver Historial Entradas");
        bot_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_entradaActionPerformed(evt);
            }
        });
        getContentPane().add(bot_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 200, -1));

        lbl_entradamaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lbl_entradamaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        bot_salida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salidastock.png"))); // NOI18N
        bot_salida.setText("Ver Historial Salida");
        bot_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_salidaActionPerformed(evt);
            }
        });
        getContentPane().add(bot_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, 30));

        bot_excel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bot_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
        bot_excel.setText("EXPORTAR EXCEL");
        bot_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_excelActionPerformed(evt);
            }
        });
        getContentPane().add(bot_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_material material = null;
        class_material modelo_material = null;

        
        material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

        material.consultar_material_maestro_general_2(table_detallematerial);
        
        table_detallematerial.setDefaultRenderer(Object.class, new RenderTablaMaestroMaterial());
        
        material.consultar_material_maestro_resumen_reservaautorizada(table_reserva);
        
        material.consultar_material_maestro_resumen_stockcurso(table_stockcurso);
        
          
    }//GEN-LAST:event_formWindowOpened

    private void table_detallematerialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detallematerialMouseClicked
        Integer posicion;
        
        posicion = table_detallematerial.getSelectedRow();
        txt_codigomaestromaterial.setText(table_detallematerial.getValueAt(posicion, 6).toString().substring(0, 2) + "-" + table_detallematerial.getValueAt(posicion, 1).toString() + "-" + table_detallematerial.getValueAt(posicion, 16).toString());

        frm_detallestock frm = new frm_detallestock();
        frm.setVisible(true);
    }//GEN-LAST:event_table_detallematerialMouseClicked

    private void txt_nromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nromaterialKeyReleased
        ctrl_material material;
        
        if (!txt_nromaterial.getText().trim().equals("")){

            material = new ctrl_material(0,Integer.parseInt(txt_nromaterial.getText().trim()),"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_detalle(table_detallematerial);

        }
        else{
            material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_general_2(table_detallematerial);
        }
    }//GEN-LAST:event_txt_nromaterialKeyReleased

    private void txt_descripcionmaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionmaterialKeyReleased
        ctrl_material material;
 
        if (!txt_descripcionmaterial.getText().trim().equals("")){

            material = new ctrl_material(0,0,"","",txt_descripcionmaterial.getText().trim(),"","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_detalle_descripcion(table_detallematerial);

        }
        else{
            material = new ctrl_material(0,0,"","","","","",0,"",0,0,0,0,0,0,0.0,0.0,"",0,"",0,0,"","",0,"",0,"", 0,"","",0,"",0,"", 0,"",true);

            material.consultar_material_maestro_general_2(table_detallematerial);
 
        }
    }//GEN-LAST:event_txt_descripcionmaterialKeyReleased

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_maestromaterial frm = new frm_maestromaterial();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_cantidadreservadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cantidadreservadaActionPerformed
        frm_detallemovimientoreserva frm = new frm_detallemovimientoreserva();
        frm.setVisible(true);
    }//GEN-LAST:event_bot_cantidadreservadaActionPerformed

    private void bot_stockencursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_stockencursoActionPerformed
        frm_detallemovimientoordencompra frm = new frm_detallemovimientoordencompra();
        frm.setVisible(true);
    }//GEN-LAST:event_bot_stockencursoActionPerformed

    private void table_reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_reservaMouseClicked
        bot_cantidadreservada.setEnabled(true);
    }//GEN-LAST:event_table_reservaMouseClicked

    private void table_stockcursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_stockcursoMouseClicked
       bot_stockencurso.setEnabled(true);
    }//GEN-LAST:event_table_stockcursoMouseClicked

    private void bot_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_entradaActionPerformed
        frm_detallemovimientoentrada frm = new frm_detallemovimientoentrada();
        frm.setVisible(true);
    }//GEN-LAST:event_bot_entradaActionPerformed

    private void bot_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_salidaActionPerformed
        frm_detallemovimientosalida frm = new frm_detallemovimientosalida();
        frm.setVisible(true);
    }//GEN-LAST:event_bot_salidaActionPerformed

    private void bot_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_excelActionPerformed
        String nombre_archivo;
        String fecha_desde;
        String fecha_hasta;
        Integer numero = (int) (Math.random() * 10000000) + 1;
        nombre_archivo = "\\\\192.168.0.3\\dist\\Documentos_SisTimaca\\ResumenStock" + numero +".xls";
        //nombre_archivo = "C:\\Users\\ruben\\Desktop\\ResumenStock.xls";

        if (table_detallematerial.getRowCount()>0){
            reporte_almacen ex = new reporte_almacen(new File(nombre_archivo), "DATOS DE RESUMEN DE STOCK", table_detallematerial);

            try {
                if(ex.excel_export_reporte_resumenstock()){

                    File archivo_abrir = new File(nombre_archivo);
                    Desktop.getDesktop().open(archivo_abrir);
                }
                else{
                    JOptionPane.showMessageDialog(null, "ERROR EN EXPORTAR ARCHIVO EXCEL");
                }
            } catch (WriteException | IOException ex1) {
                JOptionPane.showMessageDialog(null, "ERROR ABRIR ARCHIVO " + ex1.getMessage() );
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "NO HAY DATOS PARA LA CONSULTA");
        }
    }//GEN-LAST:event_bot_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_maestromaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_maestromaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_maestromaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_maestromaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_maestromaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cantidadreservada;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_entrada;
    private javax.swing.JButton bot_excel;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_salida;
    private javax.swing.JButton bot_stockencurso;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_cantidadentrante;
    private javax.swing.JLabel lbl_cantidadstockencurso;
    private javax.swing.JLabel lbl_descripcionmaterial;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_entradamaterial;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nromaterial;
    protected static javax.swing.JLabel lbl_usuario;
    protected static javax.swing.JTable table_detallematerial;
    protected static javax.swing.JTable table_reserva;
    protected static javax.swing.JTable table_stockcurso;
    protected static javax.swing.JTextField txt_codigomaestromaterial;
    private javax.swing.JTextField txt_descripcionmaterial;
    private javax.swing.JTextField txt_nromaterial;
    // End of variables declaration//GEN-END:variables
}
