/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controlador.SendMail;
import controlador.ctrl_solicitud;
import controlador.ctrl_usuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.class_usuario;
import static view.frm_aprobarreserva.lbl_nombres;

/**
 *
 * @author ruben
 */
public class frm_aprobarsolicitud extends javax.swing.JFrame {

    private Integer fila_solicitud;
    private Integer fila_posicion;
    public frm_aprobarsolicitud() {
        initComponents();
        this.getContentPane().setBackground(new Color(240,240,240)); 
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){}
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bot_buscar = new javax.swing.JButton();
        txt_numerosolicitud = new javax.swing.JTextField();
        lbl_nrosolicitud = new javax.swing.JLabel();
        lbl_titulodetallereserva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_resumensolicitud = new javax.swing.JTable();
        bot_aprobar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_detallesolicitud = new javax.swing.JTable();
        lbl_titulodetallereserva1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_materialsolicitado = new javax.swing.JLabel();
        lbl_umb = new javax.swing.JLabel();
        lbl_numeromaterial = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_empresa = new javax.swing.JLabel();
        spin_cantidadaprobar = new javax.swing.JSpinner();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        lbl_proyecto1 = new javax.swing.JLabel();
        lbl_desarea = new javax.swing.JLabel();
        lbl_fecharequerida = new javax.swing.JLabel();
        lbl_empresa1 = new javax.swing.JLabel();
        lbl_desnombre = new javax.swing.JLabel();
        lbl_desempresa = new javax.swing.JLabel();
        lbl_desproyecto = new javax.swing.JLabel();
        lbl_desumb = new javax.swing.JLabel();
        lbl_desnumaterial = new javax.swing.JLabel();
        lbl_justificacion = new javax.swing.JLabel();
        lbl_desmaterial = new javax.swing.JLabel();
        lbl_desfecharequerida = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoaprobarsolicitud = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chk_seleccionartodo = new javax.swing.JCheckBox();
        bot_anular = new javax.swing.JButton();
        bot_revisar = new javax.swing.JButton();

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });

        txt_numerosolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numerosolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numerosolicitudKeyReleased(evt);
            }
        });

        lbl_nrosolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nrosolicitud.setText("NRO DE RESERVA");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulodetallereserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallereserva.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallereserva.setText("SOLICITUDES POR APROBAR");
        getContentPane().add(lbl_titulodetallereserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        table_resumensolicitud.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_resumensolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DOC. SOLICITUD", "CÉDULA", "NOMBRE", "DESCRIPCIÓN ÁREA", "CANTIDAD POSICIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_resumensolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_resumensolicitudMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_resumensolicitud);
        if (table_resumensolicitud.getColumnModel().getColumnCount() > 0) {
            table_resumensolicitud.getColumnModel().getColumn(0).setMinWidth(100);
            table_resumensolicitud.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_resumensolicitud.getColumnModel().getColumn(0).setMaxWidth(100);
            table_resumensolicitud.getColumnModel().getColumn(3).setMinWidth(200);
            table_resumensolicitud.getColumnModel().getColumn(3).setPreferredWidth(200);
            table_resumensolicitud.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 700, 110));

        bot_aprobar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_aprobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autorizar.png"))); // NOI18N
        bot_aprobar.setText("APROBAR POSICION(ES)");
        bot_aprobar.setEnabled(false);
        bot_aprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_aprobarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_aprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, -1, 40));
        complemento.DisableBorderButton(bot_aprobar);

        table_detallesolicitud.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_detallesolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "POSICIÓN", "NRO MATERIAL", "MATERIAL SOLICITADO", "CANTIDAD SOLICITADA", "CANTIDAD APROBADA", "UMB", "GRUPO DE ARTÍCULO", "FECHA REQUERIDA", "JUSTIFICACIÓN", "OBSERVACIÓN", "EMPRESA", "PROYECTO", "TIPO DE SOLICITUD", "CEDULA", "NOMBRE", "DESCRIPCION AREA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detallesolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_detallesolicitudMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(table_detallesolicitud);
        if (table_detallesolicitud.getColumnModel().getColumnCount() > 0) {
            table_detallesolicitud.getColumnModel().getColumn(0).setMinWidth(30);
            table_detallesolicitud.getColumnModel().getColumn(0).setPreferredWidth(30);
            table_detallesolicitud.getColumnModel().getColumn(0).setMaxWidth(30);
            table_detallesolicitud.getColumnModel().getColumn(1).setMinWidth(80);
            table_detallesolicitud.getColumnModel().getColumn(1).setPreferredWidth(80);
            table_detallesolicitud.getColumnModel().getColumn(1).setMaxWidth(80);
            table_detallesolicitud.getColumnModel().getColumn(2).setMinWidth(100);
            table_detallesolicitud.getColumnModel().getColumn(2).setPreferredWidth(100);
            table_detallesolicitud.getColumnModel().getColumn(2).setMaxWidth(100);
            table_detallesolicitud.getColumnModel().getColumn(6).setMinWidth(50);
            table_detallesolicitud.getColumnModel().getColumn(6).setPreferredWidth(50);
            table_detallesolicitud.getColumnModel().getColumn(6).setMaxWidth(50);
            table_detallesolicitud.getColumnModel().getColumn(7).setMinWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(7).setPreferredWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(7).setMaxWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(9).setMinWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(9).setPreferredWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(9).setMaxWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(10).setMinWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(10).setPreferredWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(10).setMaxWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(14).setMinWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(14).setPreferredWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(14).setMaxWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(15).setMinWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(15).setPreferredWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(15).setMaxWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(16).setMinWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(16).setPreferredWidth(0);
            table_detallesolicitud.getColumnModel().getColumn(16).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 1240, 110));

        lbl_titulodetallereserva1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_titulodetallereserva1.setForeground(new java.awt.Color(0, 138, 218));
        lbl_titulodetallereserva1.setText("DETALLES SOLICITUD ");
        getContentPane().add(lbl_titulodetallereserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        lbl_cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad.setText("CANTIDAD A APROBAR");
        jPanel1.add(lbl_cantidad);
        lbl_cantidad.setBounds(10, 70, 142, 15);

        lbl_materialsolicitado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_materialsolicitado.setText("MATERIAL SOLICITADO");
        jPanel1.add(lbl_materialsolicitado);
        lbl_materialsolicitado.setBounds(10, 40, 171, 17);

        lbl_umb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb.setText("UNIDAD DE MEDIDA BASE");
        jPanel1.add(lbl_umb);
        lbl_umb.setBounds(10, 100, 180, 15);

        lbl_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_numeromaterial.setText("NÚMERO MATERIAL");
        jPanel1.add(lbl_numeromaterial);
        lbl_numeromaterial.setBounds(10, 10, 120, 15);

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombre.setText("NOMBRE SOLICITANTE");
        jPanel1.add(lbl_nombre);
        lbl_nombre.setBounds(10, 130, 180, 15);

        lbl_empresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empresa.setText("EMPRESA");
        jPanel1.add(lbl_empresa);
        lbl_empresa.setBounds(10, 190, 68, 17);

        spin_cantidadaprobar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spin_cantidadaprobar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spin_cantidadaprobar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_cantidadaprobarStateChanged(evt);
            }
        });
        jPanel1.add(spin_cantidadaprobar);
        spin_cantidadaprobar.setBounds(190, 70, 80, 24);

        panel_foto.setBackground(new java.awt.Color(245, 245, 245));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 138, 218));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        jPanel1.add(panel_foto);
        panel_foto.setBounds(690, 10, 240, 260);

        lbl_proyecto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto1.setText("PROYECTO");
        jPanel1.add(lbl_proyecto1);
        lbl_proyecto1.setBounds(10, 160, 64, 15);
        jPanel1.add(lbl_desarea);
        lbl_desarea.setBounds(120, 170, 0, 0);

        lbl_fecharequerida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fecharequerida.setText("FECHA REQUERIDA");
        jPanel1.add(lbl_fecharequerida);
        lbl_fecharequerida.setBounds(10, 220, 120, 15);

        lbl_empresa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empresa1.setText("JUSTIFICACIÓN");
        jPanel1.add(lbl_empresa1);
        lbl_empresa1.setBounds(10, 250, 110, 17);

        lbl_desnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desnombre);
        lbl_desnombre.setBounds(190, 130, 420, 20);

        lbl_desempresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desempresa);
        lbl_desempresa.setBounds(190, 190, 390, 20);

        lbl_desproyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desproyecto);
        lbl_desproyecto.setBounds(190, 160, 430, 20);

        lbl_desumb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desumb);
        lbl_desumb.setBounds(190, 100, 80, 20);

        lbl_desnumaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desnumaterial);
        lbl_desnumaterial.setBounds(190, 10, 270, 20);

        lbl_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_justificacion);
        lbl_justificacion.setBounds(190, 250, 500, 20);

        lbl_desmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desmaterial);
        lbl_desmaterial.setBounds(190, 40, 450, 20);

        lbl_desfecharequerida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lbl_desfecharequerida);
        lbl_desfecharequerida.setBounds(190, 220, 170, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 1240, 280));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoaprobarsolicitud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoaprobarsolicitud.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoaprobarsolicitud.setText("APROBAR SOLICITUD");
        jPanel7.add(lbl_encabezadoaprobarsolicitud);
        lbl_encabezadoaprobarsolicitud.setBounds(250, 10, 400, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 230, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1123, 20, 120, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1250, 20, 101, 29);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 60));

        chk_seleccionartodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_seleccionartodo.setText("Seleccionar Todo");
        chk_seleccionartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_seleccionartodoActionPerformed(evt);
            }
        });
        getContentPane().add(chk_seleccionartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        bot_anular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_anular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        bot_anular.setText("ANULAR POSICIÓN");
        bot_anular.setEnabled(false);
        bot_anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_anularActionPerformed(evt);
            }
        });
        getContentPane().add(bot_anular, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 250, 40));
        complemento.DisableBorderButton(bot_anular);

        bot_revisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_revisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reverse.png"))); // NOI18N
        bot_revisar.setText("REVERSAR POSICION");
        bot_revisar.setEnabled(false);
        bot_revisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_revisarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_revisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 660, -1, 40));
        complemento.DisableBorderButton(bot_revisar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_numerosolicitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numerosolicitudKeyReleased

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){
        }
        else{
            if (evt.getKeyCode() == 27){

                bot_reiniciar.doClick();

            }
            else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numerosolicitud.setText("");
            }
        }

    }//GEN-LAST:event_txt_numerosolicitudKeyReleased

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
       /* ctrl_reserva reserva = null;

        if(!txt_numeroreserva.getText().trim().equals("")){
            reserva = new ctrl_reserva(

                Integer.parseInt(txt_numeroreserva.getText().trim()),
                0,
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material
                0,
                "",
                0,
                "",
                0,
                0,
                "", //fecha reserva
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );

            reserva.consultar_reserva_detalle(table_resumenreserva);
        }*/

    }//GEN-LAST:event_bot_buscarActionPerformed

    private void table_resumensolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_resumensolicitudMousePressed
        ctrl_solicitud solicitud = null;
        
        lbl_desnumaterial.setText("");
        lbl_desmaterial.setText("");
        spin_cantidadaprobar.setValue(1);
        lbl_desumb.setText("");
        lbl_desnombre.setText("");
        lbl_desproyecto.setText("");
        lbl_desempresa.setText("");
        lbl_desfecharequerida.setText("");
        lbl_justificacion.setText("");        
        lbl_foto.setIcon(null);
        
        fila_solicitud = table_resumensolicitud.getSelectedRow();

            solicitud = new ctrl_solicitud(
                
                Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString()),
                0,
                0,
                "",
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );          
        
           solicitud.consultar_solicitud_detalle(Integer.parseInt(frm_principalM1.lbl_nivel.getText()),table_detallesolicitud);
        
        
      
    }//GEN-LAST:event_table_resumensolicitudMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_solicitud solicitud=null;

            solicitud = new ctrl_solicitud(
                
                0,
                Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                frm_principalM1.lbl_desarea.getText().trim(),
                0,
                "",
                0,
                0, //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,    
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""    
            );  

        solicitud.consultar_solicitud_por_aprobar(Integer.parseInt(frm_principalM1.lbl_nivel.getText()),table_resumensolicitud);
        
    }//GEN-LAST:event_formWindowOpened

    private void table_detallesolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_detallesolicitudMousePressed
        Integer fila;
        BufferedImage img;
        
        fila_posicion  = table_detallesolicitud.getSelectedRow();
        
        lbl_desempresa.setText(table_detallesolicitud.getValueAt(fila_posicion, 11).toString());
        
        lbl_desnombre.setText(table_detallesolicitud.getValueAt(fila_posicion, 14).toString());
        lbl_desproyecto.setText(table_detallesolicitud.getValueAt(fila_posicion, 12).toString());
        lbl_desnumaterial.setText(table_detallesolicitud.getValueAt(fila_posicion, 2).toString());
        
        //lbl_desarea.setText(table_detallesolicitud.getValueAt(fila_posicion, 15).toString());
        lbl_desmaterial.setText(table_detallesolicitud.getValueAt(fila_posicion, 3).toString());
        lbl_desumb.setText(table_detallesolicitud.getValueAt(fila_posicion, 6).toString());
        
        spin_cantidadaprobar.setValue(table_detallesolicitud.getValueAt(fila_posicion, 5));
        
        lbl_desfecharequerida.setText(table_detallesolicitud.getValueAt(fila_posicion, 8).toString());
        
        lbl_justificacion.setText(table_detallesolicitud.getValueAt(fila_posicion, 9).toString());
        
        if (table_detallesolicitud.getValueAt(fila_posicion, 0).equals(false)){
            table_detallesolicitud.setValueAt(true, fila_posicion, 0);
        }
        else{
            table_detallesolicitud.setValueAt(false, fila_posicion, 0);
        }
        
        ctrl_solicitud solicitud = new ctrl_solicitud(
                
                0,
                0,
                0,
                "",
                0,
                "",
                0,
                Integer.parseInt(table_detallesolicitud.getValueAt(fila_posicion, 2).toString()), //numero de material
                "",             // descripcion de material     
                0,
                "",
                0,
                "",
                0,
                0,
                0,
                0,
                0,
                "", //fecha solicitud
                "",
                "",
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            );    
                
        try{
            img = funciones.decodeToImage(solicitud.consultar_foto());
            lbl_foto.setIcon(null);
            ImageIcon icon = new ImageIcon(img);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(),lbl_foto.getHeight(), Image.SCALE_DEFAULT));
            
            lbl_foto.setIcon(icono);
        }
        catch(NullPointerException ex){}
        
        bot_aprobar.setEnabled(true);
                        
        bot_anular.setEnabled(true);
        
        bot_revisar.setEnabled(true);
        
    }//GEN-LAST:event_table_detallesolicitudMousePressed

    private void bot_aprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_aprobarActionPerformed
        
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
        int i=0;
        boolean aprobado= false;
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallesolicitud.getModel();
        Integer nrosolicitud=0;
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
        String subject;
        String to="";
        String message = "Saludos \n\n" + "A través de este comunicado se informa que su trámite de SOLICITUD A COMPRAS de material se aprobaron lo(s) siguiente(s):\n";
            
        
        ctrl_usuario usuario = new ctrl_usuario(
                      Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
                       "", 
                       "", 
                       "", 
                       "", 
                       0, 
                       "",
                       0,
                       "",
                       0,
                       true,
                       ""
            );

            modelo_usuario = usuario.buscar_usuario();
            
            respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR APROBAR UNA o VARIAS POSICIONES, DESEA CONTINUAR?");
        
            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
            
                            while(i < table_detallesolicitud.getRowCount()){

                               if(table_detallesolicitud.getValueAt(i, 0).equals(true)){ 
                                 fila_posicion = i;

                                 ctrl_solicitud solicitud = new ctrl_solicitud(

                                     Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString()),
                                     Integer.parseInt(frm_principalM1.lbl_cedula.getText().trim()),
                                     Integer.parseInt(frm_principalM1.lbl_area.getText().trim()),
                                     frm_principalM1.lbl_desarea.getText().trim(),
                                     0,
                                     "",
                                     0,
                                     Integer.parseInt(table_detallesolicitud.getValueAt(fila_posicion, 2).toString()), //numero de material
                                     "",             // descripcion de material     
                                     0,
                                     "",
                                     0,
                                     "",
                                     Integer.parseInt(table_detallesolicitud.getValueAt(fila_posicion, 1).toString()),
                                     0,
                                     Integer.parseInt(table_detallesolicitud.getValueAt(fila_posicion, 5).toString()),
                                     0,
                                     0,    
                                     "", //fecha solicitud
                                     "",
                                     table_detallesolicitud.getValueAt(fila_posicion, 9).toString(),
                                     false,
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     "",
                                     ""    
                                 );  

                                if (i==0){    
                                    to = solicitud.consultar_email_usuariosolicitud();    
                                } 
                                
                                 if(solicitud.aprobar_solicitud_posicion(Integer.parseInt(frm_principalM1.lbl_nivel.getText()))){
                        //         
                                   aprobado = true; 

                                   nrosolicitud = Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString());

                                    message = message +  "\n" + table_detallesolicitud.getValueAt(fila_posicion, 2).toString() + " - " + table_detallesolicitud.getValueAt(fila_posicion, 3).toString() + " Solicitado: " + table_detallesolicitud.getValueAt(fila_posicion, 4).toString() + " " + table_detallesolicitud.getValueAt(fila_posicion, 6).toString() + " Aprobado: " + table_detallesolicitud.getValueAt(fila_posicion, 5).toString() + " " + table_detallesolicitud.getValueAt(fila_posicion, 6).toString()  ;
                                          
                                 }
                               }  

                               i++;
                             }   
                        }
                        else{

                            JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        }
                }
                else{
                    JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                }                          
            }
            
            if (aprobado==true){
                i--;
                if (i>0){
                   JOptionPane.showMessageDialog(null, "APROBADO POSICIONES DE LA SOLICITUD " + nrosolicitud); 
                }
                else{
                   JOptionPane.showMessageDialog(null, "APROBADO POSICION DE LA SOLICITUD" + nrosolicitud); 
                }

                subject = "APROBACIÓN NÚMERO SOLICITUD A COMPRAS " + table_resumensolicitud.getValueAt(fila_solicitud, 0).toString();
                   
                message = message + "\n\n Aprobado por: " + lbl_nombres.getText() + "\n\nPara mas detalles en la sección de Notificaciones de SISTIMACA"; 
                if (!to.equals("")){
                    SendMail.send(to,subject, message);
                }

                bot_reiniciar.doClick();
            }
            else{
                JOptionPane.showMessageDialog(null, "SELECCIONAR ALGUNA DE LAS POSICIONES PARA APROBAR"); 
            }
                bot_aprobar.setEnabled(false);
            
    }//GEN-LAST:event_bot_aprobarActionPerformed

    private void bot_revisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_revisarActionPerformed
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
        int i = 0;
        boolean reversado= false;
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallesolicitud.getModel();
        Integer nrosolicitud=0;
        JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
        JLabel jMotivo = new JLabel("MOTIVO REVERSO");
        JTextField motivo = new JTextField();
 
        String subject;
        String to="";
        String message = "Saludos \n\n" + "A través de este comunicado se informa que su trámite de SOLICITUD A COMPRAS de material se reversaron el(los) siguiente(s) material(es):\n";
 
        
        ctrl_usuario usuario = new ctrl_usuario(
            Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
            "",
            "",
            "",
            "",
            0,
            "",
            0,
            "",
            0,
            true,
            ""    
        );

        modelo_usuario = usuario.buscar_usuario();

        respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR REVERSAR POSICION(ES), DESEA CONTINUAR?");

            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password,jMotivo, motivo};
                
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){
  
                            while(i < table_detallesolicitud.getRowCount()){

                                if(table_detallesolicitud.getValueAt(i, 0).equals(true)){ 
                                    fila_posicion = i;                

                                    ctrl_solicitud solicitud = new ctrl_solicitud(

                                        Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString()),
                                        0,
                                        0,
                                        "",
                                        0,
                                        "",
                                        0,
                                        0, //numero de material
                                        "",             // descripcion de material     
                                        0,
                                        "",
                                        0,
                                        "",
                                        Integer.parseInt(table_detallesolicitud.getValueAt(fila_posicion, 1).toString()),
                                        0,
                                        0,
                                        0,
                                        0,    
                                        "", //fecha solicitud
                                        "",
                                        table_detallesolicitud.getValueAt(fila_posicion, 9).toString() + " REVERSADO POR " + frm_principalM1.lbl_nombres.getText(),
                                        false,
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        motivo.getText().trim()
                                    );  

                                    if (i==0){    
                                            to = solicitud.consultar_email_usuariosolicitud();    
                                    } 
                                    
                                    if(solicitud.reversar_solicitud_posicion(2)){
                                        reversado = true;

                                        nrosolicitud = Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString());

                                        message = message +  "\n" + table_detallesolicitud.getValueAt(fila_posicion, 2).toString() + " - " + table_detallesolicitud.getValueAt(fila_posicion, 3).toString() + " Solicitado: " + table_detallesolicitud.getValueAt(fila_posicion, 4).toString() + " " + table_detallesolicitud.getValueAt(fila_posicion, 6).toString();
                                 

                                    }


                                }
                               i++;
                            }    
                        }
                        else{

                            JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                    }
            }    
            if (reversado==true){
                i--;
                if (i>0){
                    JOptionPane.showMessageDialog(null, "REVERSADO POSICIONES DE LA SOLICITUD " + nrosolicitud); 
                }
                else{
                    JOptionPane.showMessageDialog(null, "REVERSADO POSICIÓN DE LA SOLICITUD" + nrosolicitud); 
                }

                subject = "REVERSO NÚMERO SOLICITUD A COMPRAS " + table_detallesolicitud.getValueAt(fila_posicion, 0).toString();

                message = message + "\n\n Reversado por: " + lbl_nombres.getText();
                message = message + "\n\n Motivo: " + motivo.getText();
                message = message + "\n\nPara mas detalles en la sección de Notificaciones de SISTIMACA"; 

                if (!to.equals("")){
                    SendMail.send(to,subject, message);
                }
                
                bot_reiniciar.doClick();    
                
            }    
        
            

            modelotabla.setRowCount(0);
            
            bot_revisar.setEnabled(false);
    }//GEN-LAST:event_bot_revisarActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_aprobarsolicitud frm = new frm_aprobarsolicitud();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void chk_seleccionartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_seleccionartodoActionPerformed
        int i;
        i = 0;
        boolean seleccionar;
        if (chk_seleccionartodo.isSelected()){
            seleccionar = true;
            bot_aprobar.setEnabled(true);
        }
        else{
            seleccionar = false;
            bot_aprobar.setEnabled(false);
        }
        
        while(i < table_detallesolicitud.getRowCount()){
            table_detallesolicitud.setValueAt(seleccionar,i, 0);
            i++;
        }    
    }//GEN-LAST:event_chk_seleccionartodoActionPerformed

    
    private void spin_cantidadaprobarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_cantidadaprobarStateChanged
        fila_posicion  = table_detallesolicitud.getSelectedRow();
        
        
        try{
           table_detallesolicitud.setValueAt(spin_cantidadaprobar.getValue(), fila_posicion, 5);
        }
        catch(NullPointerException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_spin_cantidadaprobarStateChanged

    private void bot_anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_anularActionPerformed
        class_usuario modelo_usuario;
        int respuesta;
        String firma;
        int i = 0;
        boolean anulado= false;
        DefaultTableModel modelotabla = (DefaultTableModel) table_detallesolicitud.getModel();
          JLabel jPassword = new JLabel("INTRODUZCA SU FIRMA DIGITAL");
        JTextField password = new JPasswordField();
           JLabel jMotivo = new JLabel("MOTIVO ANULACIÓN");
        JTextField motivo = new JTextField();
        String subject;
        String to="";
        String message = "Saludos \n\n" + "A través de este comunicado se informa que su trámite de SOLICITUD A COMPRAS se anularon el(los) siguiente(s) material(es):\n";
 
        
        ctrl_usuario usuario = new ctrl_usuario(
            Integer.parseInt(frm_principalM1.lbl_cedula.getText()),
            "",
            "",
            "",
            "",
            0,
            "",
            0,
            "",
            0,
            true,
            ""
        );

        modelo_usuario = usuario.buscar_usuario();

        respuesta = JOptionPane.showConfirmDialog(null,"ESTA POR ANULAR POSICIÓN(ES), DESEA CONTINUAR?");

            if (respuesta == 0){
                 
                Object[] ob = {jPassword, password,jMotivo,motivo};
               
                respuesta = JOptionPane.showConfirmDialog(null, ob, "VALIDACIÓN DE FIRMA DIGITAL", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == 0){
              
                        if(modelo_usuario.getFirmadigital().equals(password.getText().trim())){

                            while(i < table_detallesolicitud.getRowCount()){

                                if(table_detallesolicitud.getValueAt(i, 0).equals(true)){ 
                                    fila_posicion = i;                

                                    ctrl_solicitud solicitud = new ctrl_solicitud(

                                        Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString()),
                                        0,
                                        0,
                                        "",
                                        0,
                                        "",
                                        0,
                                        0, //numero de material
                                        "",             // descripcion de material     
                                        0,
                                        "",
                                        0,
                                        "",
                                        Integer.parseInt(table_detallesolicitud.getValueAt(fila_posicion, 1).toString()),
                                        0,
                                        0,
                                        0,
                                        0,    
                                        "", //fecha solicitud
                                        "",
                                       table_detallesolicitud.getValueAt(fila_posicion, 9).toString().trim().toUpperCase() + " ANULADO POR " + frm_principalM1.lbl_nombres.getText(),
                                        false,
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        "",
                                        motivo.getText().trim()
                                    );  

                                    if (i==0){    
                                            to = solicitud.consultar_email_usuariosolicitud();    
                                    } 
                                    
                                    if(solicitud.anular_solicitud_posicion()){
                                        anulado = true;
                                        
                                        message = message +  "\n" + table_detallesolicitud.getValueAt(fila_posicion, 2).toString() + " - " + table_detallesolicitud.getValueAt(fila_posicion, 3).toString() + " Solicitado: " + table_detallesolicitud.getValueAt(fila_posicion, 4).toString() + " " + table_detallesolicitud.getValueAt(fila_posicion, 6).toString();
                                 
                                      
                                    }

                                    
                                }
                               i++; 
                            }
                            
                            if (anulado==true){
                                i--;
                                if (i>0){
                                    JOptionPane.showMessageDialog(null, "ANULADO POSICIONES DE LA SOLICITUD " + Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString())); 
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "ANULADO POSICION DE LA SOLICITUD" + Integer.parseInt(table_resumensolicitud.getValueAt(fila_solicitud, 0).toString())); 
                                }
                                
                                subject = "ANULACIÓN NÚMERO SOLICITUD A COMPRAS " + table_resumensolicitud.getValueAt(fila_solicitud, 0).toString();
                       
                                message = message + "\n\n Anulado por: " + lbl_nombres.getText();
                                message = message + "\n\n Motivo: " + motivo.getText();
                                message = message + "\n\nPara mas detalles en la sección de Notificaciones de SISTIMACA"; 
                                if (!to.equals("")){
                                    SendMail.send(to,subject, message);
                                }
                                
                                
                            }    
                                             
                        }
                        else{

                            JOptionPane.showMessageDialog(null, "FIRMA DIGITAL ERRADA. VUELVA A INTENTAR");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "CANCELADO TRANSACCIÓN");
                    }                          
                        
                }

            bot_anular.setEnabled(false);
    }//GEN-LAST:event_bot_anularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_aprobarsolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_anular;
    private javax.swing.JButton bot_aprobar;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_revisar;
    private javax.swing.JCheckBox chk_seleccionartodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_desarea;
    private javax.swing.JLabel lbl_desempresa;
    private javax.swing.JLabel lbl_desfecharequerida;
    private javax.swing.JLabel lbl_desmaterial;
    private javax.swing.JLabel lbl_desnombre;
    private javax.swing.JLabel lbl_desnumaterial;
    private javax.swing.JLabel lbl_desproyecto;
    private javax.swing.JLabel lbl_desumb;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_empresa1;
    private javax.swing.JLabel lbl_encabezadoaprobarsolicitud;
    private javax.swing.JLabel lbl_fecharequerida;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_justificacion;
    private javax.swing.JLabel lbl_materialsolicitado;
    private javax.swing.JLabel lbl_nombre;
    protected static javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nrosolicitud;
    private javax.swing.JLabel lbl_numeromaterial;
    private javax.swing.JLabel lbl_proyecto1;
    private javax.swing.JLabel lbl_titulodetallereserva;
    private javax.swing.JLabel lbl_titulodetallereserva1;
    private javax.swing.JLabel lbl_umb;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JSpinner spin_cantidadaprobar;
    private javax.swing.JTable table_detallesolicitud;
    private javax.swing.JTable table_resumensolicitud;
    private javax.swing.JTextField txt_numerosolicitud;
    // End of variables declaration//GEN-END:variables
}
