/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import controlador.ctrl_comun;
import controlador.ctrl_entrada;
import controlador.ctrl_material;
import controlador.ctrl_prestamo;
import controlador.ctrl_solicitud;
import formatos_pdf.pdf_prestamo;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.class_material;
import model.class_prestamo;

/**
 *
 * @author ruben
 */
public class frm_prestamo extends javax.swing.JFrame {

    /**
     * Creates new form frm_prestamo
     */
    public frm_prestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(245,245,245));
        this.setTitle("SISTIMACA - PRESTAMO DE MATERIAL");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.setIconImage(new ImageIcon(funciones.logoempresa()).getImage());
        
        
        // Cargar Look And Feel (Marcos Windows )
        try{
         UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        }
        catch(Exception e){} 
        
        lbl_usuario.setText(frm_principalM1.lbl_usuario.getText().trim());
        lbl_nombres.setText(frm_principalM1.lbl_nombres.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idprestamo = new javax.swing.JTextField();
        txt_iddocumento = new javax.swing.JTextField();
        txt_posicion = new javax.swing.JTextField();
        txt_numeromaterial = new javax.swing.JTextField();
        javax.swing.JPanel panel_material = new javax.swing.JPanel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_desdescripcionmaterial = new javax.swing.JLabel();
        panel_foto = new javax.swing.JPanel();
        lbl_foto = new javax.swing.JLabel();
        lbl_descripcionmaterial = new javax.swing.JLabel();
        lbl_desumb = new javax.swing.JLabel();
        lbl_empresa = new javax.swing.JLabel();
        cmb_empresa = new javax.swing.JComboBox<>();
        lbl_area = new javax.swing.JLabel();
        cmb_area = new javax.swing.JComboBox<>();
        lbl_almacen = new javax.swing.JLabel();
        cmb_almacen = new javax.swing.JComboBox<>();
        lbl_cantidad = new javax.swing.JLabel();
        spin_cantidad = new javax.swing.JSpinner();
        lbl_fechadesde = new javax.swing.JLabel();
        date_desde = new com.toedter.calendar.JDateChooser();
        lbl_fechahasta1 = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        lbl_nombre = new javax.swing.JLabel();
        lbl_justificacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_justificacion = new javax.swing.JTextArea();
        txt_nombresolicitante = new javax.swing.JTextField();
        lbl_proyecto = new javax.swing.JLabel();
        cmb_proyecto = new javax.swing.JComboBox<>();
        lbl_ubicacion = new javax.swing.JLabel();
        cmb_ubicacion = new javax.swing.JComboBox<>();
        bot_verdisponibilidad = new javax.swing.JButton();
        chk_indefinido = new javax.swing.JCheckBox();
        lbl_umb1 = new javax.swing.JLabel();
        lbl_umb2 = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        lbl_umb4 = new javax.swing.JLabel();
        lbl_nromaterial = new javax.swing.JLabel();
        bot_buscar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_encabezadoalmacen2 = new javax.swing.JLabel();
        lbl_imagentimaca2 = new javax.swing.JLabel();
        bot_reiniciar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bot_agregar = new javax.swing.JButton();
        bot_verdocumento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_prestamo = new javax.swing.JTable();
        bot_borrar = new javax.swing.JButton();

        txt_idprestamo.setText("0");
        txt_idprestamo.setToolTipText("");

        txt_iddocumento.setText("0");

        txt_posicion.setText("1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(600, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_numeromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_numeromaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeromaterialKeyReleased(evt);
            }
        });
        getContentPane().add(txt_numeromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 20));

        panel_material.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_material.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 140, 20));

        lbl_desdescripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(lbl_desdescripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 360, 20));

        panel_foto.setBackground(new java.awt.Color(253, 253, 253));
        panel_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO REFERENCIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_foto.setForeground(new java.awt.Color(0, 0, 255));

        lbl_foto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        panel_material.add(panel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 280, 310));

        lbl_descripcionmaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_descripcionmaterial.setText("DESCRIPCIÓN MATERIAL");
        panel_material.add(lbl_descripcionmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_desumb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(lbl_desumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 70, 20));

        lbl_empresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empresa.setText("EMPRESA");
        panel_material.add(lbl_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        cmb_empresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(cmb_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 200, 20));

        lbl_area.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_area.setText("ÁREA");
        panel_material.add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cmb_area.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(cmb_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 250, 20));

        lbl_almacen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_almacen.setText("ALMACÉN");
        panel_material.add(lbl_almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cmb_almacen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_almacen.setEnabled(false);
        cmb_almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_almacenActionPerformed(evt);
            }
        });
        panel_material.add(cmb_almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, 20));

        lbl_cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cantidad.setText("CANTIDAD A PRESTAR");
        panel_material.add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        spin_cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spin_cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        panel_material.add(spin_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 50, 20));

        lbl_fechadesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechadesde.setText("FECHA DESDE");
        panel_material.add(lbl_fechadesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        panel_material.add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 150, -1));

        lbl_fechahasta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fechahasta1.setText("FECHA HASTA");
        panel_material.add(lbl_fechahasta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        panel_material.add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 150, -1));

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombre.setText("NOMBRE SOLICITANTE");
        panel_material.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        lbl_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_justificacion.setText("JUSTIFICACIÓN");
        panel_material.add(lbl_justificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        area_justificacion.setColumns(20);
        area_justificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_justificacion.setLineWrap(true);
        area_justificacion.setRows(5);
        area_justificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                area_justificacionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(area_justificacion);

        panel_material.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 280, -1));

        txt_nombresolicitante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(txt_nombresolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 150, -1));

        lbl_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proyecto.setText("PROYECTO");
        panel_material.add(lbl_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cmb_proyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_proyectoActionPerformed(evt);
            }
        });
        panel_material.add(cmb_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 250, 20));

        lbl_ubicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ubicacion.setText("UBICACIÓN");
        panel_material.add(lbl_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        cmb_ubicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_ubicacion.setEnabled(false);
        cmb_ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ubicacionActionPerformed(evt);
            }
        });
        panel_material.add(cmb_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 150, 20));

        bot_verdisponibilidad.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        bot_verdisponibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccionar.png"))); // NOI18N
        bot_verdisponibilidad.setText("VER DISPONIBILIDAD MATERIAL");
        bot_verdisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdisponibilidadActionPerformed(evt);
            }
        });
        panel_material.add(bot_verdisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 30));
        complemento.DisableBorderButton(bot_verdisponibilidad);

        chk_indefinido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chk_indefinido.setText("Permanente");
        chk_indefinido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_indefinidoActionPerformed(evt);
            }
        });
        panel_material.add(chk_indefinido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        lbl_umb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb1.setText("UNIDAD DE MEDIDA BASE");
        panel_material.add(lbl_umb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_umb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb2.setText("MARCA");
        panel_material.add(lbl_umb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panel_material.add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 20));

        lbl_umb4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_umb4.setText("MODELO");
        panel_material.add(lbl_umb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        getContentPane().add(panel_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1300, 390));

        lbl_nromaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nromaterial.setText("NRO DE MATERIAL");
        getContentPane().add(lbl_nromaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 30));
        complemento.DisableBorderButton(bot_buscar);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        lbl_encabezadoalmacen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_encabezadoalmacen2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezadoalmacen2.setText("CREAR PRÉSTAMO");
        jPanel7.add(lbl_encabezadoalmacen2);
        lbl_encabezadoalmacen2.setBounds(270, 10, 190, 29);

        lbl_imagentimaca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIMACA.png"))); // NOI18N
        jPanel7.add(lbl_imagentimaca2);
        lbl_imagentimaca2.setBounds(10, 0, 280, 60);

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reiniciar.png"))); // NOI18N
        bot_reiniciar.setText("Reiniciar");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_reiniciar);
        bot_reiniciar.setBounds(1140, 20, 113, 33);
        complemento.DisableBorderButton(bot_reiniciar);

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bot_cerrar.setText("Cerrar");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(bot_cerrar);
        bot_cerrar.setBounds(1280, 20, 91, 25);
        complemento.DisableBorderButton(bot_cerrar);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("USUARIO");
        jPanel7.add(lbl_usuario);
        lbl_usuario.setBounds(830, 10, 270, 17);

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombres.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel7.add(lbl_nombres);
        lbl_nombres.setBounds(832, 30, 270, 17);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jPanel3);
        jPanel3.setBounds(1110, 10, 1, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 60));

        bot_agregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        bot_agregar.setText("AGREGAR POSICIÓN");
        bot_agregar.setEnabled(false);
        bot_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, -1, -1));
        complemento.DisableBorderButton(bot_agregar);

        bot_verdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_verdocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        bot_verdocumento.setText("VER DOCUMENTO");
        bot_verdocumento.setEnabled(false);
        bot_verdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_verdocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(bot_verdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, -1, -1));
        complemento.DisableBorderButton(bot_verdocumento);

        table_prestamo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_prestamo", "nro_documento", "POSICIÓN", "NRO MATERIAL", "DESCRIPCIÓN", "CANTIDAD", "UMB", "PROYECTO", "FECHA DESDE", "FECHA HASTA", "NOMBRE SOLICITANTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prestamoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_prestamo);
        if (table_prestamo.getColumnModel().getColumnCount() > 0) {
            table_prestamo.getColumnModel().getColumn(0).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(0).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMinWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setPreferredWidth(0);
            table_prestamo.getColumnModel().getColumn(1).setMaxWidth(0);
            table_prestamo.getColumnModel().getColumn(2).setMinWidth(80);
            table_prestamo.getColumnModel().getColumn(2).setPreferredWidth(80);
            table_prestamo.getColumnModel().getColumn(2).setMaxWidth(80);
            table_prestamo.getColumnModel().getColumn(3).setMinWidth(100);
            table_prestamo.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_prestamo.getColumnModel().getColumn(3).setMaxWidth(100);
            table_prestamo.getColumnModel().getColumn(5).setMinWidth(90);
            table_prestamo.getColumnModel().getColumn(5).setPreferredWidth(90);
            table_prestamo.getColumnModel().getColumn(5).setMaxWidth(90);
            table_prestamo.getColumnModel().getColumn(6).setMinWidth(50);
            table_prestamo.getColumnModel().getColumn(6).setPreferredWidth(50);
            table_prestamo.getColumnModel().getColumn(6).setMaxWidth(50);
            table_prestamo.getColumnModel().getColumn(8).setMinWidth(100);
            table_prestamo.getColumnModel().getColumn(8).setPreferredWidth(100);
            table_prestamo.getColumnModel().getColumn(8).setMaxWidth(100);
            table_prestamo.getColumnModel().getColumn(9).setMinWidth(100);
            table_prestamo.getColumnModel().getColumn(9).setPreferredWidth(100);
            table_prestamo.getColumnModel().getColumn(9).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1300, 100));

        bot_borrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bot_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        bot_borrar.setText("BORRAR POSICIÓN");
        bot_borrar.setEnabled(false);
        bot_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, -1, -1));
        complemento.DisableBorderButton(bot_verdocumento);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrl_comun control = new ctrl_comun(1);
        cmb_almacen =  control.cargar_combo(cmb_almacen,"Seleccione...");
        
        control = new ctrl_comun(4);
        cmb_empresa =  control.cargar_combo(cmb_empresa,"Seleccione...");
        
        control = new ctrl_comun(2);
        cmb_area =  control.cargar_combo(cmb_area,"Seleccione...");
        
               
        txt_numeromaterial.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void cmb_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_almacenActionPerformed
       Integer fila;
              
        try{  
        
        if (evt.getModifiers() != 0){
           
           if (!cmb_almacen.getSelectedItem().equals("Seleccione...")){
            ctrl_entrada entrada  = new ctrl_entrada(
                    0, //id_entrada,
                    0, 
                    Integer.parseInt(txt_numeromaterial.getText().trim()), //id_material, 
                    "", //descripcionmaterial
                    0, //idvaloracion
                    "", //descripcionvaloracion
                    1,  //moneda
                    "", // descripcion_moneda,  
                    Integer.parseInt(cmb_almacen.getSelectedItem().toString().substring(0,3).trim()), //id_almacen,
                    "", //descripcion_almacen,
                    0,
                    "", //ubicacion
                     0, //id_procedencia
                    "", //descripcion_procedencia
                     0, //id_clasedemovimiento
                    "", //descripcion_clasedemovimiento
                    Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim()), //id_proyecto
                    "", //descripcion_proyecto
                    0,
                    "", // codigo alterno
                    0, //iddocumento
                    0,//idcompra
                    0, //nrofactura
                    "", //fecha_entrada,
                    0, //cantidad_ingresada,
                    0.0, //precio_unitario,
                    0.0, //monto,
                    0.0, //flete
                    0.0, //monto
                    "", //observacion
                    true //status       
            ); 
             
            cmb_ubicacion.setEnabled(true);
            cmb_ubicacion =  entrada.cargarmaterial_almacen(cmb_ubicacion,"Seleccione...",7);
            
           } 
          
       }
      }catch(NullPointerException ex){} 
    }//GEN-LAST:event_cmb_almacenActionPerformed

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
        frm_buscarmaterial frm = new frm_buscarmaterial(10);
        frm.setVisible(true);
       
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void bot_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregarActionPerformed
        String fecha_solicitud;
        String fecha_desde;
        String fecha_hasta;
        class_prestamo  modelo_prestamo;
        
        
        fecha_solicitud = funciones.fecha_bd_usuario(funciones.getfechacalendario(), 2);
        fecha_desde = funciones.fecha_convertir_date(date_desde,1);
        fecha_hasta = funciones.fecha_convertir_date(date_hasta,1);        
        
        if (chk_indefinido.isSelected()){
            fecha_hasta = "9999-09-09";
        }
                
        if(!txt_numeromaterial.getText().trim().equals("") &&
           !cmb_empresa.getSelectedItem().equals("Seleccione...") &&
           !cmb_area.getSelectedItem().equals("Seleccione...") &&     
           !cmb_proyecto.getSelectedItem().equals("Seleccione...") &&  
           !cmb_almacen.getSelectedItem().equals("Seleccione...") &&  
           !cmb_ubicacion.getSelectedItem().equals("Seleccione...") &&  
           !fecha_desde.equals("") && 
           !fecha_hasta.equals("") &&
           !txt_nombresolicitante.getText().trim().equals("") &&  
           !area_justificacion.getText().trim().equals("")){
        
            ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    Integer.parseInt(txt_numeromaterial.getText()), //id_material, 
                    lbl_desdescripcionmaterial.getText(), // descripcionmaterial, 
                    Integer.parseInt(cmb_empresa.getSelectedItem().toString().substring(0,3).trim()), // id_empresa, 
                    cmb_empresa.getSelectedItem().toString().substring(5,cmb_empresa.getSelectedItem().toString().length()).trim(), // descripcion_empresa, 
                    Integer.parseInt(cmb_area.getSelectedItem().toString().substring(0,3).trim()), // id_area, 
                    cmb_area.getSelectedItem().toString().substring(5,cmb_area.getSelectedItem().toString().length()).trim(), //descripcion_area
                    txt_nombresolicitante.getText().trim(), // nombre_usuario, 
                    Integer.parseInt(cmb_almacen.getSelectedItem().toString().substring(0,3).trim()), // id_almacen, 
                    cmb_almacen.getSelectedItem().toString().substring(5,cmb_almacen.getSelectedItem().toString().length()).trim(),// descripcionalmacen, 
                    Integer.parseInt(cmb_ubicacion.getSelectedItem().toString().substring(0,3).trim()), // id_proyecto, 
                    cmb_ubicacion.getSelectedItem().toString().substring(5,cmb_ubicacion.getSelectedItem().toString().length()).trim(),// idubicacion, 
                    Integer.parseInt(cmb_proyecto.getSelectedItem().toString().substring(0,3).trim()), // descripcionubicacion, 
                    cmb_proyecto.getSelectedItem().toString().substring(5,cmb_proyecto.getSelectedItem().toString().length()).trim(),// descripcionalmacen,
                    Integer.parseInt(txt_posicion.getText()), // posicion,
                    Integer.parseInt(spin_cantidad.getValue().toString()), // cantidad_prestada,
                    Integer.parseInt(txt_iddocumento.getText()),
                    fecha_solicitud, //fecha_solicitud, 
                    fecha_desde, //fecha_desde, 
                    fecha_hasta, //fecha_hasta, 
                    area_justificacion.getText(), // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

            modelo_prestamo = prestamo.crear_prestamo(table_prestamo);

            if(modelo_prestamo.getStatus()){
                txt_iddocumento.setText(modelo_prestamo.getId_documento().toString());
                txt_posicion.setText(modelo_prestamo.getPosicion().toString());
                txt_numeromaterial.setText("");
                lbl_desdescripcionmaterial.setText("");
                lbl_desumb.setText("");
                cmb_empresa.setSelectedIndex(0);
                cmb_area.setSelectedIndex(0);
                spin_cantidad.setValue(1);
                cmb_proyecto.setSelectedIndex(0);
                cmb_almacen.setSelectedIndex(0);
                cmb_ubicacion.setSelectedIndex(0);
                date_desde.setDate(null);
                date_hasta.setDate(null);
                txt_nombresolicitante.setText("");
                chk_indefinido.setSelected(false);
                area_justificacion.setText("");   
                lbl_foto.setIcon(null);
                bot_agregar.setEnabled(false);
                bot_verdocumento.setEnabled(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS");
        }
        
        
    }//GEN-LAST:event_bot_agregarActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_prestamo frm = new frm_prestamo();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(null, "ESTÁ SEGURO EN SALIR?");
        if (resp.equals(0)){
            this.dispose();
        }    

    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void cmb_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_proyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_proyectoActionPerformed

    private void txt_numeromaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeromaterialKeyReleased
        class_material modelo_material;
        BufferedImage img;

        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
            if(txt_numeromaterial.getText().length() > 7){
                ctrl_material material = new ctrl_material(
                        0,
                        Integer.parseInt(txt_numeromaterial.getText().trim().toUpperCase()),
                        "",
                        "",
                        "",
                        "",
                        "",
                         0,   
                        "",
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0.0,
                        0.0,
                        "",
                        0,
                        "",
                        0,
                        0,
                        "",
                        "",
                        0,
                        "",
                        0,
                        "",
                        0,
                        "",
                        "",
                        0,
                        "",
                        0,
                        "",
                        0,
                        "",
                        true    
                    );

                    modelo_material = material.consultar_material();

                    if (modelo_material.isStatus()){

                        lbl_desdescripcionmaterial.setText(modelo_material.getDescripcion());
                        lbl_desumb.setText(modelo_material.getDescripcion_medida());

                        img = funciones.decodeToImage(modelo_material.getFoto_material());

                        try{

                        lbl_foto.setIcon(null);    
                        ImageIcon icon = new ImageIcon(img);
                        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbl_foto.getWidth(), lbl_foto.getHeight(), Image.SCALE_DEFAULT));
                        
                        lbl_foto.setIcon(icono);
                        }
                        catch(NullPointerException ex){}

                        ctrl_entrada entrada  = new ctrl_entrada(
                                0, //id_entrada,
                                0, 
                                Integer.parseInt(txt_numeromaterial.getText().trim()), //id_material, 
                                "", //descripcionmaterial
                                0, //idvaloracion
                                "", //descripcionvaloracion
                                1,  //moneda
                                "", // descripcion_moneda,  
                                0, //id_almacen,
                                "", //descripcion_almacen,
                                0,
                                "", //ubicacion
                                 0, //id_procedencia
                                "", //descripcion_procedencia
                                  0, //id_clasedemovimiento
                                "", //descripcion_clasedemovimiento
                                0, //id_proyecto
                                "", //descripcion_proyecto
                                0,
                                "", //codigo alterno
                                0, //iddocumento
                                0,//idcompra
                                0, //nrofactura
                                "", //fecha_entrada,
                                0, //cantidad_ingresada,
                                0.0, //precio_unitario,
                                0.0, //monto,
                                0.0, //flete
                                0.0, //monto
                                "", //observacion
                                true       
                            ); 
                            cmb_proyecto =  entrada.cargarmaterial_proyecto(cmb_proyecto,"Seleccione...",1);
                            cmb_almacen.setEnabled(true);
                            cmb_almacen = entrada.cargarmaterial_almacen(cmb_almacen, "Seleccione...", 1);   
                            bot_borrar.setEnabled(false);                
                    }
            }
            else{
               
            }
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_reiniciar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARÁCTER NO VÁLIDO. SOLO NÚMEROS (1..9)", "SISTIMACA - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_numeromaterial.setText("");
                lbl_desdescripcionmaterial.setText("");
             }   
        }  
    }//GEN-LAST:event_txt_numeromaterialKeyReleased

    private void cmb_ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ubicacionActionPerformed
        try{  
        
            if (evt.getModifiers() != 0){

               if (!cmb_ubicacion.getSelectedItem().equals("Seleccione...")){
                   bot_agregar.setEnabled(true);
               }
            }
        }
        catch(NullPointerException ex){ 
            
        }
    }//GEN-LAST:event_cmb_ubicacionActionPerformed

    private void bot_verdisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdisponibilidadActionPerformed
        frm_detalledisponibilidadmaterial frm = new frm_detalledisponibilidadmaterial(3);
        frm.setVisible(true);

    }//GEN-LAST:event_bot_verdisponibilidadActionPerformed

    private void bot_verdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_verdocumentoActionPerformed
        try {
            
            pdf_prestamo.dato("\\\\192.168.0.3\\dist\\Documentos_SisTimaca",Integer.parseInt(txt_iddocumento.getText()),"");
        } catch (DocumentException | IOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROE EN APERTURAR EL ARCHIVO. " + ex.getMessage());
        }
    }//GEN-LAST:event_bot_verdocumentoActionPerformed

    private void chk_indefinidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_indefinidoActionPerformed
        if(!chk_indefinido.isSelected()){
            
            date_hasta.setEnabled(true);
            date_hasta.setDate(null);
        }
        else{
            date_hasta.setDate(null);
            date_hasta.setEnabled(false);
        }
    }//GEN-LAST:event_chk_indefinidoActionPerformed

    private void bot_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_borrarActionPerformed
       Integer posicion;
       class_prestamo modelo_prestamo;
       
       posicion = table_prestamo.getSelectedRow();
       
        ctrl_prestamo prestamo = new ctrl_prestamo(
                    0, //id_prestamo 
                    0, //id_material, 
                    "", // descripcionmaterial, 
                    0, // id_empresa, 
                    "", // descripcion_empresa, 
                    0, // id_area, 
                    "", //descripcion_area
                    "", // nombre_usuario, 
                    0, // id_almacen, 
                    "",// descripcionalmacen, 
                    0, // id_ubicaciom, 
                    "",// descripcionubicacion, 
                    0, // descripcionubicacion, 
                    "",// descripcionalmacen,
                    Integer.parseInt(table_prestamo.getValueAt(posicion,2).toString()), // posicion,
                    0, // cantidad_prestada,
                    Integer.parseInt(table_prestamo.getValueAt(posicion,1).toString()),
                    "", //fecha_solicitud, 
                    "", //fecha_desde, 
                    "", //fecha_hasta, 
                    "", // justificacion, 
                    "", //fecha_recepcion, 
                    false, //dano, 
                    "", //foto, 
                    "", //descripciondano)
                    0, //id_entrada
                    true
            );

            modelo_prestamo = prestamo.borrar_posicion_prestamo(table_prestamo);

            if(modelo_prestamo.getStatus()){
                if (table_prestamo.getRowCount() == 0){
                    bot_verdocumento.setEnabled(false);
                    txt_posicion.setText(modelo_prestamo.getPosicion().toString());
                }
                bot_borrar.setEnabled(false);
            }
    }//GEN-LAST:event_bot_borrarActionPerformed

    private void table_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prestamoMouseClicked
            bot_borrar.setEnabled(true);
            bot_verdocumento.setEnabled(true);
    }//GEN-LAST:event_table_prestamoMouseClicked

    private void area_justificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_area_justificacionKeyReleased
         if(area_justificacion.getText().trim().length() > 60){
               area_justificacion.setText(area_justificacion.getText().trim().substring(0, 60));
         }
    }//GEN-LAST:event_area_justificacionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_justificacion;
    private javax.swing.JButton bot_agregar;
    protected static javax.swing.JButton bot_borrar;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JButton bot_verdisponibilidad;
    private javax.swing.JButton bot_verdocumento;
    private javax.swing.JCheckBox chk_indefinido;
    protected static javax.swing.JComboBox<String> cmb_almacen;
    private javax.swing.JComboBox<String> cmb_area;
    private javax.swing.JComboBox<String> cmb_empresa;
    protected static javax.swing.JComboBox<String> cmb_proyecto;
    private javax.swing.JComboBox<String> cmb_ubicacion;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_almacen;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_descripcionmaterial;
    protected static javax.swing.JLabel lbl_desdescripcionmaterial;
    protected static javax.swing.JLabel lbl_desumb;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_encabezadoalmacen2;
    private javax.swing.JLabel lbl_fechadesde;
    private javax.swing.JLabel lbl_fechahasta1;
    protected static javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_imagentimaca2;
    private javax.swing.JLabel lbl_justificacion;
    protected static javax.swing.JLabel lbl_marca;
    protected static javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nromaterial;
    private javax.swing.JLabel lbl_proyecto;
    private javax.swing.JLabel lbl_ubicacion;
    private javax.swing.JLabel lbl_umb1;
    private javax.swing.JLabel lbl_umb2;
    private javax.swing.JLabel lbl_umb4;
    protected static javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JSpinner spin_cantidad;
    private javax.swing.JTable table_prestamo;
    private javax.swing.JTextField txt_iddocumento;
    private javax.swing.JTextField txt_idprestamo;
    private javax.swing.JTextField txt_nombresolicitante;
    protected static javax.swing.JTextField txt_numeromaterial;
    private javax.swing.JTextField txt_posicion;
    // End of variables declaration//GEN-END:variables
}
